<?php
/********************************************************
	lang/nn_NO/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Bokmerke";
$bmStrings["identities"] = "Tilnamn";
$bmStrings["edit"] = "Brigda";
$bmStrings["name"] = "Namn";
$bmStrings["url"] = "Lenk";
$bmStrings["category"] = "Slag";
$bmStrings["other"] = "Annat-&gt;";
$bmStrings["comments"] = "Merknader";
$bmStrings["add"] = "F&oslash;r upp";
$bmStrings["new"] = "Nyuppf&oslash;ring";
$bmStrings["edit_url"] = "Brigda uppf&oslash;ringi";
$bmStrings["delete"] = "Strjuk";

$bmError[1] = "P&aring;kravd med anten eit namn elder ein lenk";
$bmError[2] = "Denne evna hev no vorte slegen av.";
?>