<?php
/********************************************************
	lang/nn_NO/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Ny gjerd";
$calStr["edit_schedule"] = "Brigda i gjerdi";
$calStr["weekof"] = "Vika som byrja: %d";
$calStr["title"] = "Gjerd:";
$calStr["color"] = "Farge:";
$calStr["colors"] = array("#990000"=>"myrkeraud", "#FF0000"=>"raud", "#000099"=>"djupbl&aring;", "#0000FF"=>"bl&aring;", 
					"#006600"=>"myrkegr&oslash;n", "#00FF00"=>"gr&oslash;n", "#9900FF"=>"lilla", "#00FFFF"=>"turkis",
					"#FF6600"=>"appelsin", "#FFFF00"=>"gul", "#FF00FF"=>"purpur", ""=>"ingen farge");
$calStr["starts"] = "Byrjar den:";
$calStr["ends"] = "Endar den:";
$calStr["from"] = "fr&aring;:";
$calStr["until"] = "og til:";
$calStr["repeat_on"] = "Gjentak p&aring;";
$calStr["of"] = "i kvar";
$calStr["weeks"] = array(1=>"fyrste vika", 2=>"andre vika", 3=>"tridje vika", 4=>"fjorde vika"); 
$calStr["week_blurb"] = "...av kvar m&aring;nad (til endetidspunkt).<br>Minder du vel onnorleis er det gjentaking kvar vika.";
$calStr["monthly"] = "Gjentak m&aring;nadlegt";
$calStr["yearly"] = "Gjentak &aring;rlegt";
$calStr["place"] = "P&aring; staden:";
$calStr["description"] = "Umtala:";
$calStr["add"] = "F&oslash;r inn";
$calStr["update"] = "Set i verk";
$calStr["Delete"] = "Strjuk ut";
$calStr["go"] = "Gakk &aring;t";
$calStr["disabled"] = "Almanakken er ikkje i drift.";

?>