<?php
/********************************************************
	lang/nn_NO/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

 //TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/compose.inc");

$composeHStrings[0] = "Emne";
$composeHStrings[1] = "Fr&aring;";
$composeHStrings[2] = "&Aring;t";
$composeHStrings[3] = "Avrit &aring;t";
$composeHStrings[4] = "L&oslash;yndeavrit &aring;t";
$composeHStrings[5] = "Tidspunkt";


$composeStrings[0] = "Brevark";
$composeStrings[1] = "Send brevet";
$composeStrings[2] = "Lasta upp";
$composeStrings[3] = "Signera";
$composeStrings[4] = "Vedlegg";
$composeStrings[5] = "Adresseboki";
$composeStrings[6] = "L&oslash;yn adresseboki";
$composeStrings[7] = "Braudtekst:";
$composeStrings[8] = "F&oslash;r p&aring;";
$composeStrings[9] = "%d orda %s:\n";
$composeStrings[10] = "--- Upphavlegt brev ---\n";
$composeStrings[11] = "Lat att vindauga";

$composeStrings[12] = "Staving";
$composeStrings[13] = "Retta stavingi";
$composeStrings[14] = "Ingen endringar";
$composeStrings[15] = "Mogelege stavingsmistak";
$composeStrings[16] = "Rettingar";
$composeStrings[17] = "Hoppa yver";
$composeStrings[18] = "Strjuk ut";

$composeStrings["title"] = "Brevark";

$composeErrors[0] = "Emnelina er tom. F&oslash;r helst p&aring; eit emne elder klikk \"".$composeStrings[1]."\" att for &aring; senda.";
$composeErrors[1] = "\"Fr&aring;\"-feltet er tomt.  F&oslash;r inn e-posttilskrifti di.";
$composeErrors[2] = "\"&Aring;t\"-feltet er tomt.  Set inn den tilskrifti som vantar.";
$composeErrors[3] = "Upplastingi var mislukka";
$composeErrors[4] = "Ingen filer mottekne.";
$composeErrors[5] = "Som eit tiltak imot uynskt reklamepost hev du einast h&oslash;ve til &aring; senda &aring;t %1 menneske (%2 ialt for kvar &oslash;kti) kvart %3 sekund.";

$composeErrors[6] = "Ingen stavemistak funne.";
$composeErrors[7] = "Staving er ikkje tilgjengeleg for gjeldande tungem&aring;l.";
$composeErrors[8] = "(%s ordbok nytta)";

?>