<?php
/********************************************************
	lang/nn_NO/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/contacts.inc");

$cStrings[0] = "Adresseboki";
$cStrings[1] = "F&oslash;r upp ny kjenning";
$cStrings[2] = " kjenning";
$cStrings[3] = "Namn";
$cStrings[4] = "E-tilskrift";
$cStrings[5] = "Lenk";
$cStrings[6] = "Gruppa";
$cStrings[7] = "Merknader";
$cStrings[8] = "F&oslash;r upp/brigda kjenningen";
$cStrings[9] = "E-tilskrift";
$cStrings[10] = "Brevark";


// from english
$cStrings["close"] = "Lat att vindauga";
$cStrings["addto"] = "F&oslash;r kjenningar inn i %s";
$cStrings["showgrp"] = "Syn fram %s";
$cStrings["all"] = "Alle";
$cStrings["instructions"] = "F&oslash;r inn ved &aring; klikka p&aring; namni.  Du kan &ograve;g leggja til heile gruppor ved &aring; klikka p&aring; gruppenamn.";
// end from english

$cErrors[0] = "Du hev ikkje skrive upp nokon av kjenningane dine her enno.";


?>