<?php
/********************************************************
	lang/nn_NO/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Brigda";
$ecStrings[1] = "F&oslash;r upp";
$ecStrings[2] = " kjenning";
$ecStrings[3] = "Namn";
$ecStrings[4] = "E-tilskrift";
$ecStrings[5] = "Heimsida";
$ecStrings[6] = "Gruppa";
$ecStrings[7] = "Merknader";
$ecStrings[8] = "Tlf heim";
$ecStrings[9] = "Tlf yrkje";
$ecStrings[10] = "Tlf laus (mobil)";
$ecStrings[11] = "Tilskrift";
$ecStrings[12] = "E-tilskr. onnor";
$ecStrings[13] = "Strjuk ut";
$ecStrings[14] = "Onnor";


$errors[0] = "Ball i databasen: fekk ikkje lagd til kjenningen.";
$errors[1] = "Det er alt ei uppf&oslash;ring med same tilskrifta.";
$errors[2] = "Trykk ";
$errors[3] = "her";
$errors[4] = " s&aring; du kan brigda i den uppf&oslash;ringi istaden.";
$errors[5] = "Anten vart ikkje kjenningen funnen elder s&aring; vart du neitta tilgjenge.";
$errors[6] = "Er du viss p&aring; at du ynskjer &aring; strjuka uppf&oslash;ringi av \"";
$errors[7] = "\"?";

?>