<?php
/********************************************************
	lang/nn_NO/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_folders.inc");

$efStrings[0] = "Brevpermhandtering";
$efStrings[1] = "Stell til ein ny perm";
$efStrings[2] = "Stell til permen: ";
$efStrings[3] = "Stell til";
$efStrings[4] = "&Oslash;ydelegg permen";
$efStrings[5] = "&Oslash;ydelegg";
$efStrings[6] = "D&oslash;yp um permen";
$efStrings[7] = "D&oslash;yp um";
$efStrings[8] = "Permar i n&oslash;yting";
$efStrings[9] = "N&oslash;yt";
$efStrings[10] = "Un&oslash;ytte permar";
$efStrings[11] = "Ikkje n&oslash;yt";


$errors[0] = "Stell til permen: ";
$errors[1] = "Fekk ikkje stellt til permen: ";
$errors[2] = "&Oslash;ydelegg permen: ";
$errors[3] = "Fekk ikkje &oslash;ydelagd permen: ";
$errors[4] = "Den umd&oslash;ypte permen: ";
$errors[5] = "Fekk ikkje d&oslash;ypt um permen: ";
$errors[6] = "Permstudnad er einast tilgjengeleg for IMAP-kontoar.";

?>