<?php 
/********************************************************
	lang/nn_NO/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="N&oslash;ytarnamn";
$loginStrings[1]="Lausnord";
$loginStrings[2]="Serverar";
$loginStrings[3]="Slag";
$loginStrings[4]="Hovud-/rotperm";
$loginStrings[5]="M&aring;lvald";
$loginStrings[6]="Logga inn";

$loginErrors[0]="Ein us&aelig;tande vert";
$loginErrors[1]="Gali: katalogen for \"uploads\" vart ikkje funnen";
$loginErrors[2]="Gali: permen for \"users\" vart ikkje funnen";
$loginErrors[3]="Gali: permen for \"sessions\" vart ikkje funnen";

?>