<?php
/********************************************************
	lang/nn_NO/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainMessages["delete"] = "Kasta %n brev i s&oslash;pli";
$mainMessages["move"] = "Flutte %n brev &aring;t %f";

$mainStrings[0] = "Syner %p av %n";
$mainStrings[1] = " funn.";
$mainStrings[2] = "Fyrre";
$mainStrings[3] = "";
$mainStrings[4] = "Neste";
$mainStrings[5] = "";
$mainStrings[6] = "Emne";
$mainStrings[7] = "&Aring;t";
$mainStrings[8] = "Fr&aring;";
$mainStrings[9] = "Tidspunkt";
$mainStrings[10] = "Kasta";
$mainStrings[11] = "T&oslash;m s&oslash;pli";
$mainStrings[12] = "Flyt";
$mainStrings[13] = "S&oslash;k";
$mainStrings[14] = "Storleik";
$mainStrings[15] = "unamna";
$mainStrings[16] = "Syn fram";
$mainStrings[17] = "Sj&aring; etter post";
$mainStrings[18] = "Kasta alle";
$mainStrings[19] = "Brjot av";
$mainStrings[20] = "Merk dei avkryssa brevi som %b.";
$mainStrings[21] = "opna";
$mainStrings[22] = "uopna";
$mainStrings[23] = "Vel ...";

$mainErrors[0] = "Ingen brev funne i denne permen";
$mainErrors[1] = "Ingen brev i denne permen";
$mainErrors[2] = "Fekk ikkje flutt brevet i s&oslash;pli.";
$mainErrors[3] = "Fekk ikkje merkt av at brevet er kasta i s&oslash;pli.";
$mainErrors[4] = "Fekk ikkje flutt brevi.";
$mainErrors[5] = "Perm til s&oslash;pli ikkje vald.";
$mainErrors[6] = "Fekk ikkje t&oslash;mt s&oslash;pelpermen.";
$mainErrors[7] = "Er det visst at du vil kasta KVART EINASTE brev i %f?";
$mainErrors[8] = "For &aring; f&aring; flutt deim trykkjer du p&aring; pili nedanom kolonneyverskriftene.<br>N&aring;r du er ferdug let du berre att vindauga.";

?>