<?php
/********************************************************
	lang/nn_NO/pref_colors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "F&oslash;r inn ein HTML-fargekode for kvar komponent.";
$pcStrings["0.1"] = "N&oslash;yt ";
$pcStrings["0.2"] = "fargekodekartet";
$pcStrings["0.3"] = " til &aring; finna rette fargekodane.";
$pcStrings["0.4"] = "Val som fylgjer av temaet kan ikkje endrast.";
$pcStrings["1.0"] = "Verktylina";
$pcStrings["2.0"] = "Permyversyn";
$pcStrings["3.0"] = "Hovudfarge";
$pcStrings["3.1"] = "Yverskriftsbakgrunn: ";
$pcStrings["3.2"] = "Yverskriftstekst: ";
$pcStrings["3.3"] = "Myrk bakgrunn: ";
$pcStrings["3.4"] = "Lys tekst: ";
$pcStrings["4.0"] = "Ymist annat";
$pcStrings["4.1"] = "Hermingar: ";
$pcStrings["5.0"] = "Skrifter";
$pcStrings["5.1"] = "Skrifttype";
$pcStrings["5.2"] = "Skriftstorleik: ";
$pcStrings["5.3"] = "Storleiken p&aring; liti skrift: ";
$pcStrings["5.4"] = "Storleik i menyskrifter: ";
$pcStrings["5.5"] = "Storleiken p&aring; skrifti i permyversynet: ";

							
$pcPortions = array( "Bakgrunn: ", "Lenker: ", "Tekst: ", "Utheving: ");

?>
