<?php
/********************************************************
	lang/nn_NO/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "Tilnamn";
$piStrings["edit"] = "Brigda";
$piStrings["name"] = "Namn";
$piStrings["email"] = "E-posttilskrift";
$piStrings["replyto"] = "Svartilskrift";
$piStrings["sig"] = "Signatur";
$piStrings["add"] = "F&oslash;r upp";
$piStrings["new"] = "Nytt tilnamn";
$piStrings["edit_ident"] = "Brigda tilnamnet";
$piStrings["delete"] = "Strjuk ut";

// from english version
$piStrings["setdef"] = "Gjer fyrevalt";
$piStrings["isdef"] = "(Fyrevalt)";
// end from english version

$piError[1] = "Du lyt minsto fylla inn eit namn elder ei e-posttilskrift";

?>
