<?php
/********************************************************
	lang/nn_NO/quota.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/quota.inc");

$quotaStr["label"] = "Skivebruk: ";
$quotaStr["full"] = "%usedKB/%totalKB (%free% ledigt)";
$quotaStr["unknown"] = "ukjend";

?>