<?php
/********************************************************
	lang/nn_NO/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/read_message.inc");
 	 

$rmStrings[0] = "Attende";
$rmStrings[1] = "Svara";
$rmStrings[2] = "Framsending";
$rmStrings[3] = "Ikkje kasta";
$rmStrings[4] = "Kasta";
$rmStrings[5] = "Flyt";
$rmStrings[6] = "Deler";
$rmStrings[7] = "Merk: dette er eit vevbrev. ";
$rmStrings[8] = "Trykk her for &aring; opna brevet.";
$rmStrings[9] = "Kjelda";
$rmStrings[10] = "Storleik";
$rmStrings[11] = "Lat att uopna";
$rmStrings[12] = "Syn brevhovud";
$rmStrings[13] = "Seg fr&aring; um reklamebrev";
$rmStrings[14] = "Svara alle";
$rmStrings[15] = "Du hev svara p&aring; brevet tidlegare";
$rmStrings[16] = "Prenta";

?>