<?php
/********************************************************
	lang/nn_NO/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translation by Leif Halvard Silli <hyperlekken@lenk.no>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/tool.inc");

$toolStrings["folders"] = " Permar";
$toolStrings["inbox"] = "Innkomne";
$toolStrings["compose"] = "Brevark";
$toolStrings["calendar"] = "Almanakk";
$toolStrings["contacts"] = "Adressebok";
$toolStrings["bookmarks"] = "Bokmerke";
$toolStrings["search"] = "S&oslash;k";
$toolStrings["prefs"] = "Val";
$toolStrings["logout"] = "Logga ut";
$toolStrings["go"] = "Sj&aring; i";

?>