<?php
/********************************************************
	lang/eng/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Σελιδοδείκτες";
$bmStrings["identities"] = "Ταυτότητες";
$bmStrings["edit"] = "Επεξεργασία";
$bmStrings["name"] = "Όνομα";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Κατηγορία";
$bmStrings["other"] = "Specify-&gt;";
$bmStrings["comments"] = "Σχόλια";
$bmStrings["add"] = "Προσθήκη";
$bmStrings["new"] = "Νέα Εισαγωγή";
$bmStrings["edit_url"] = "Επεξεργασία Εισαγωγής";
$bmStrings["delete"] = "Διαγραφή";

$bmError[1] = "Χρειάζεται όνομα ή URL";
$bmError[2] = "Αυτό το χαρακτηριστικό είναι απενεργοποιημένο.";
?>