<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Προσθήκη χρονοδιαγράμματος";
$calStr["edit_schedule"] = "Επεξεργασία χρονοδιαγράμματος";
$calStr["weekof"] = "Εβδομάδα του: %d";
$calStr["title"] = "Τίτλος:";
$calStr["color"] = "Χρώμα:";
$calStr["colors"] = array("#990000"=>"Σκούρο Κόκκινο", "#FF0000"=>"Κόκκινο", "#000099"=>"Βαθύ Μπλέ", "#0000FF"=>"Μπλέ", 
					"#006600"=>"Σκούρο Πράσινο", "#00FF00"=>"Πράσινο", "#9900FF"=>"Μώβ", "#00FFFF"=>"Κυανό",
					"#FF6600"=>"Πορτοκαλί", "#FFFF00"=>"Κίτρινο", "#FF00FF"=>"Πορφυρό", ""=>"Χωρίς Χρώμα");
$calStr["starts"] = "Αρχίζει στις:";
$calStr["ends"] = "Τελειώνει στις:";
$calStr["from"] = "απο:";
$calStr["until"] = "έως:";
$calStr["repeat_on"] = "Επανάληψη στις";
$calStr["of"] = "σε κάθε";
$calStr["weeks"] = array(1=>"Πρώτη εβδομάδα", 2=>"σεύτερη εβδομάδα", 3=>"τρίτη εβδομάδα", 4=>"τεταρτη εβδομάδα"); 
$calStr["week_blurb"] = "...κάθε μήνα (εώς το τέλος της ημερομηνίας).<br>Θα επαναληφθεί σε όλες τις εβδομάδες αν δεν επιλεχθεί καμία.";
$calStr["monthly"] = "Μηνιάια επανάληψη";
$calStr["yearly"] = "Ετήσια επανάληψη";
$calStr["place"] = "Τόπος:";
$calStr["description"] = "Περιγραφή:";
$calStr["add"] = "Προσθήκη";
$calStr["update"] = "Ανανέωση";
$calStr["Delete"] = "Διαγραφή";
$calStr["go"] = "Πήγαινε";
$calStr["disabled"] = "Το χαρακτηριστικό -ημερολόγιο- είναι απενεργοποιημένο.";
?>