<?php
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/contacts.inc");

$cStrings[0] = "Επαφές";
$cStrings[1] = "Προσθήκη επαφής";
$cStrings[2] = " Επαφή";
$cStrings[3] = "Όνομα";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Ομάδα";
$cStrings[7] = "Σχόλια";
$cStrings[8] = "Προσθήκη/Επεξεργασία Επαφής";
$cStrings[9] = "Email";
$cStrings[10] = "Σύνθεση";

$cStrings["close"] = "Κλείσιμο παραθύρου";
$cStrings["addto"] = "Προσθήκη επαφών στο %s";
$cStrings["showgrp"] = "Προβολή %s";
$cStrings["all"] = "Όλα";
$cStrings["instructions"] = "Κάντε click στα ονόματα για προσθήκη.  Μπορείτε επίσης να κάνετε click στην ταμπέλα της ομάδας για να προσθέσετε τους πάντες στην ομάδα.";

$cErrors[0] = "Η λίστα επαφών σας είναι άδεια";


?>