<?php
/********************************************************
	lang/eng/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_folders.inc");

$efStrings[0] = "Διαχείρηση Φακέλων";
$efStrings[1] = "Δημιουργία Νέου Φακέλου";
$efStrings[2] = "Δημιουργία Φακέλου: ";
$efStrings[3] = "Δημιουργία";
$efStrings[4] = "Διαγραφή Φακλελου";
$efStrings[5] = "Διαγραφή";
$efStrings[6] = "Μετονομασία Φακέλου";
$efStrings[7] = "Μετονομασία";
$efStrings[8] = "Εγγεγραμμένοι Φάκελοι";
$efStrings[9] = "Εγγραφή";
$efStrings[10] = "Μή εγγεγραμμένοι Φάκελοι";
$efStrings[11] = "Απεγγραφή";


$errors[0] = "Διμηουργήθηκε ο φάκελος: ";
$errors[1] = "Ο Φάκελος δεν μπόρεσε να δημιουργηθεί: ";
$errors[2] = "Διαγράφκε ο φάκελος: ";
$errors[3] = "Δεν μπόρεσε να διαγραφεί ο φάκελος: ";
$errors[4] = "Μετονομάστηκε ο φάκελος: ";
$errors[5] = "Δεν μπόρεσε να μετονομαστεί ο φάκελος: ";
$errors[6] = "Η υποστήριξη φακέλων είναι διαθέσιμη μόνο για λογαριασούς IMAP.";

?>