<?php
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Επεξεργασία";
$ecStrings[1] = "Πρόσθήκη";
$ecStrings[2] = " επαφή";
$ecStrings[3] = "Όνομα";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Ομάδα";
$ecStrings[7] = "Σχόλια";
$ecStrings[8] = "Τηλέφωνο Οικίας";
$ecStrings[9] = "Τηλεφωνο Εργασίας";
$ecStrings[10] = "Κινητό Τηλέφωνο";
$ecStrings[11] = "Διεύθυνση";
$ecStrings[12] = "Δευτ. Email";
$ecStrings[13] = "Διαγραφή";
$ecStrings[14] = "¶λλο";


$errors[0] = "Δεν μπόρεσε να ποσθεθεί η επαφή. Λάθος της βάσης δεδομένων";
$errors[1] = "Υπάρχει ήδη εγγραφή με αυτή τη διεύθυνση.";
$errors[2] = "Click ";
$errors[3] = "εδώ";
$errors[4] = " για να διορθώστετε αυτή την εγγραφή.";
$errors[5] = "Η επαφή δεν βρέθηκε, ή η πρόσβαση απερίφθη.";
$errors[6] = "Είστε σίγουροι οτι θέλετε να σβήστε την εγγραφή \"";
$errors[7] = "\";";

?>