<?php 
/********************************************************
	lang/en/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Χρήστης";
$loginStrings[1]="Κωδικός";
$loginStrings[2]="Διακομιστής";
$loginStrings[3]="Τύπος";
$loginStrings[4]="Rootdir";
$loginStrings[5]="Γλώσσα";
$loginStrings[6]="Είσοδος";

$loginErrors[0]="Unauthorized host";
$loginErrors[1]="Λάθος: ο κατάλογος \"uploads\" δεν βρέθηκε";
$loginErrors[2]="Λάθος: ο κατάλογος \"users\" δεν βρέθηκε";
$loginErrors[3]="Λάθος: ο κατάλογος \"sessions\" δεν βρέθηκε";

?>