<?php
/********************************************************
	lang/eng/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainMessages["delete"] = "Διαγραφή %n μηνύματος(-ων)";
$mainMessages["move"] = "Μετακίνηση %n μηνύματος (-ων) στο %f";

$mainStrings[0] = "Προβολή %p από %n";
$mainStrings[1] = " μηνύματα βρέθηκαν";
$mainStrings[2] = "Προηγούμενο";
$mainStrings[3] = "";
$mainStrings[4] = "Επόμενο";
$mainStrings[5] = "";
$mainStrings[6] = "Θέμα";
$mainStrings[7] = "Πρός";
$mainStrings[8] = "Από";
$mainStrings[9] = "Ημερομηνία";
$mainStrings[10] = "Διαγραφή";
$mainStrings[11] = "¶δειασμα Απορρίτων";
$mainStrings[12] = "Μετακίνηση";
$mainStrings[13] = "Έυρεση";
$mainStrings[14] = "Μέγεθος";
$mainStrings[15] = "χωρίς τίτλο";
$mainStrings[16] = "Προβολή";
$mainStrings[17] = "Έλεγχος νέων";
$mainStrings[18] = "Διαγραφή όλων";
$mainStrings[19] = "Ακύρωση";
$mainStrings[20] = "Μαρκάρισμα ως %b";
$mainStrings[21] = "Διαβασμένα";
$mainStrings[22] = "Αδιάβαστα";
$mainStrings[23] = "Επιλογή...";


$mainErrors[0] = "Δεν βρέθηκαν μηνύματα σε αυτό τον κατάλογο";
$mainErrors[1] = "Κανένα μήνυμα σε αυτό τον κατάλογο";
$mainErrors[2] = "Δεν μπόρεσαν να μετακινηθούν τα μηνύματα στα απορρίματα.";
$mainErrors[3] = "Δεν μπόρεσαν να σημανθούν τα μηνύματα σαν σβησμένα.";
$mainErrors[4] = "Δεν μπόρεσαν να μετακινηθούν τα μηνύματα.";
$mainErrors[5] = "Ο κατάλογος των απορρίτων δεν έχει διευκρινιστεί.";
$mainErrors[6] = "Δεν μπόρεσαν να αδειάσουν τα απορρίματα";
$mainErrors[7] = "Είστε σίγουροι οτι θέλετε να σβήσετε ΟΛΑ τα μηνύματα στο %f ;";
$mainErrors[8] = "Κάντε Click στα βέλη κάτω απο τις στήλες των επικεφαλίδων για να τα μετακινήσετε.<br>Όταν τελειώσετε, απλά κλείτε το παράθυρο.";



?>
