<?php
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "Ταυτότητες";
$piStrings["edit"] = "Επεξεργασία";
$piStrings["name"] = "Ονομα";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "Απάντηση-σε";
$piStrings["sig"] = "Υπογραφή";
$piStrings["add"] = "Προσθήκη";
$piStrings["new"] = "Νέα Ταυτότητα";
$piStrings["edit_ident"] = "Επεξεργασία Ταυτότητας";
$piStrings["delete"] = "Διαγραφή";
$piStrings["setdef"] = "Ορισμός ως προκαθορισμένου";
$piStrings["isdef"] = "(Προκαθορισμένο)";

$piError[1] = "Απαιτείται όνομα ή διεύθυνση";

?>
