<?php
/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "Δώστε ένα κωδικό χρώματος HTML για κάθε στοιχείο.";
$pcStrings["0.1"] = "Χρήση του ";
$pcStrings["0.2"] = "Πίνακα Χρωματικού Κώδικα";
$pcStrings["0.3"] = " για να βρείτε τα τους σωστούς κωδικούς χρωμάτων.";
$pcStrings["0.4"] = "Οι ρυθμίσεις χρωμάτων του θέματος δεν μπορουν να αλλάξουν.";
$pcStrings["1.0"] = "Μπάρα εργασίας";
$pcStrings["2.0"] = "Λίστα Φακέλων";
$pcStrings["3.0"] = "Κύριο";
$pcStrings["3.1"] = "Κεφαλικό φόντο: ";
$pcStrings["3.2"] = "Κεφαλικό κείμενο: ";
$pcStrings["3.3"] = "Σκοτεινό φόντο: ";
$pcStrings["3.4"] = "Ανοικτό κείμενο: ";
$pcStrings["4.0"] = "Υπόλοιπα";
$pcStrings["4.1"] = "Quotes: ";
$pcStrings["5.0"] = "Γραμματοσειρές";
$pcStrings["5.1"] = "Οικογένεια Γραμματοσειράς";
$pcStrings["5.2"] = "Μέγεθος Γραμματοσειράς: ";
$pcStrings["5.3"] = "Μικρό μέγεθος γραμματοσειράς: ";
$pcStrings["5.4"] = "Μέγεθος γραμματοσειράς Μενού: ";
$pcStrings["5.5"] = "Μέγεθος Γραμματοσειράς Λίστας Φακέλων: ";

							
$pcPortions = array( "Φόντο: ", "Συνδέσεις: ", "Κείμενο: ", "Υπογράμιση: ");

?>
