<?php
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/read_message.inc");


$rmStrings[0] = "Ευρετήριο";
$rmStrings[1] = "Απάντηση";
$rmStrings[2] = "Προώθηση";
$rmStrings[3] = "Αναίρεση διαγραφής";
$rmStrings[4] = "Διαγραφή";
$rmStrings[5] = "Μετακίνηση";
$rmStrings[6] = "Τμήματα";
$rmStrings[7] = "Αυτό είναι ένα HTML μήνυμα. ";
$rmStrings[8] = "Πατήστε εδώ για να το διαβάσετε.";
$rmStrings[9] = "Πηγαίος Κώδικας";
$rmStrings[10] = "Μέγεθος";
$rmStrings[11] = "Μή διαβασμένο";
$rmStrings[12] = "Προβολή Κεφαλίδων";
$rmStrings[13] = "Αναφορά spam";
$rmStrings[14] = "Απάντηση σε όλους";
$rmStrings[15] = "Έχετε απαντήσει σε αυτό το μήνυμα";
$rmStrings[16] = "Εκτύπωση";

?>