<?php
/********************************************************
	lang/gb/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/contacts.inc");

$cStrings[0] = "Contacts";
$cStrings[1] = "Add Contact";
$cStrings[2] = " Contact";
$cStrings[3] = "Name";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Group";
$cStrings[7] = "Comments";
$cStrings[8] = "Add/Edit Contact";
$cStrings[9] = "Email";
$cStrings[10] = "Compose";

$cStrings["close"] = "Close Window";
$cStrings["addto"] = "Add contacts to %s";
$cStrings["showgrp"] = "Show %s";
$cStrings["all"] = "All";
$cStrings["instructions"] = "Click on names to add.  You may also click on group labels to add everyone in the group.";

$cErrors[0] = "Contacts list is empty";


?>