<?php
/********************************************************
	lang/gb/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/edit_folders.inc");

$efStrings[0] = "Manage Folders";
$efStrings[1] = "Create new folder";
$efStrings[2] = "Create folder: ";
$efStrings[3] = "Create";
$efStrings[4] = "Delete folder";
$efStrings[5] = "Delete";
$efStrings[6] = "Rename folder";
$efStrings[7] = "Rename";
$efStrings[8] = "Subscribed Folders";
$efStrings[9] = "Subscribe";
$efStrings[10] = "Unsubscribed Folders";
$efStrings[11] = "Unsubscribe";


$errors[0] = "Create folder: ";
$errors[1] = "Could not create folder: ";
$errors[2] = "Deleted folder: ";
$errors[3] = "Could not delete folder: ";
$errors[4] = "Renamed folder: ";
$errors[5] = "Could not rename folder: ";
$errors[6] = "Folder-support is only available for IMAP acounts.";

?>