<?php
/********************************************************
	lang/gb/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	(C)2003 Lovell Fuller <iloha@lovell.info>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/main.inc");

$mainMessages["delete"] = "Delete %n message(s)";
$mainMessages["move"] = "Moved %n message(s) to %f";

$mainStrings[0] = "Showing %p of %n";
$mainStrings[1] = " messages found";
$mainStrings[2] = "Previous";
$mainStrings[3] = "";
$mainStrings[4] = "Next";
$mainStrings[5] = "";
$mainStrings[6] = "Subject";
$mainStrings[7] = "To";
$mainStrings[8] = "From";
$mainStrings[9] = "Date";
$mainStrings[10] = "Delete";
$mainStrings[11] = "Empty Rubbish";
$mainStrings[12] = "Move";
$mainStrings[13] = "Search";
$mainStrings[14] = "Size";
$mainStrings[15] = "untitled";
$mainStrings[16] = "Show";
$mainStrings[17] = "Check New";
$mainStrings[18] = "Delete All";
$mainStrings[19] = "Cancel";
$mainStrings[20] = "Mark as %b";
$mainStrings[21] = "Read";
$mainStrings[22] = "Unread";
$mainStrings[23] = "Select...";


$mainErrors[0] = "No messages found in this folder";
$mainErrors[1] = "No messages in this folder";
$mainErrors[2] = "Couldn't move messages to Rubbish.";
$mainErrors[3] = "Couldn't flag messages as deleted.";
$mainErrors[4] = "Couldn't move messages.";
$mainErrors[5] = "Rubbish folder not specified.";
$mainErrors[6] = "Couldn't empty Rubbish";
$mainErrors[7] = "Are you sure you want to delete ALL messages in %f?";
$mainErrors[8] = "Click on the arrows underneath the column headings to move them.<br>When you're done, simply close the window.";



?>