<?php
/********************************************************
	lang/gb/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/tool.inc");

$toolStrings["folders"] = "Folders";
$toolStrings["inbox"] = "Inbox";
$toolStrings["compose"] = "Compose";
$toolStrings["calendar"] = "Calendar";
$toolStrings["contacts"] = "Contacts";
$toolStrings["bookmarks"] = "Bookmarks";
$toolStrings["search"] = "Search";
$toolStrings["prefs"] = "Options";
$toolStrings["logout"] = "Logout";
$toolStrings["go"] = "Go";

?>