<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Закладки";
$bmStrings["identities"] = "Персональные Данные";
$bmStrings["edit"] = "Редактировать";
$bmStrings["name"] = "Имя";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Категория";
$bmStrings["other"] = "Укажите-&gt;";
$bmStrings["comments"] = "Комментарий";
$bmStrings["add"] = "Добавить";
$bmStrings["new"] = "Новая Запись";
$bmStrings["edit_url"] = "Редактировать запись";
$bmStrings["delete"] = "Удалить";

$bmError[1] = "Введите Имя или URL";
$bmError[2] = "Эта функция отключена.";

?>
