<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Добавить расписание";
$calStr["edit_schedule"] = "Редактировать расписание";
$calStr["weekof"] = "Неделя: %d";
$calStr["title"] = "Заголовок:";
$calStr["color"] = "Цвет:";
$calStr["colors"] = array("#990000"=>"Темно красный", "#FF0000"=>"Красный", "#000099"=>"Темно синий", "#0000FF"=>"Синий", 
					"#006600"=>"Темно зеленный", "#00FF00"=>"Хеленный", "#9900FF"=>"Пурпурный", "#00FFFF"=>"Циан",
					"#FF6600"=>"Оранжевый", "#FFFF00"=>"Жёлтый", "#FF00FF"=>"Магента", ""=>"Без цвета");
$calStr["starts"] = "Начинается:";
$calStr["ends"] = "Заканчивается:";
$calStr["from"] = "с:";
$calStr["until"] = "по:";
$calStr["repeat_on"] = "повторять";
$calStr["of"] = "каждые";
$calStr["weeks"] = array(1=>"первая неделя", 2=>"вторая неделя", 3=>"третья неделя", 4=>"четвертая неделя"); 
$calStr["week_blurb"] = "...каждого месяця (по конечную дату).<br>Будет повторять каждую неделю если ничего не выбрано.";
$calStr["monthly"] = "Повторять ежемесячно";
$calStr["yearly"] = "Повторять каждый год";
$calStr["place"] = "Вставить:";
$calStr["description"] = "Описание:";
$calStr["add"] = "Добавить";
$calStr["update"] = "Овновить";
$calStr["Delete"] = "Удалить";
$calStr["go"] = "Перейти";
$calStr["disabled"] = "Функция Календарь не активна.";

?>