<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/ruw/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "Тема";
$composeHStrings[1] = "От";
$composeHStrings[2] = "Кому";
$composeHStrings[3] = "Копия";
$composeHStrings[4] = "Слепая копия";
$composeHStrings[5] = "Дата";


$composeStrings[0] = "Создать сообщение";
$composeStrings[1] = "Оттправить сообщение";
$composeStrings[2] = "Загрузить";
$composeStrings[3] = "Присоединить подпись";
$composeStrings[4] = "Вложить файл";
$composeStrings[5] = "Показать контакты";
$composeStrings[6] = "Скрыть контакты";
$composeStrings[7] = "Тело письма:";
$composeStrings[8] = "Добавить";
$composeStrings[9] = "%d, %s вы писали:\n";
$composeStrings[10] = "--- Исходное сообщение ---\n";
$composeStrings[11] = "Закрыть окно";
$composeStrings[12] = "Проверить на ошибки";
$composeStrings[13] = "Исправить ошибки";
$composeStrings[14] = "Без изменений";
$composeStrings[15] = "Возможные ошибки";
$composeStrings[16] = "Изменения языка";
$composeStrings[17] = "игнорировать";
$composeStrings[18] = "стереть";


$composeErrors[0] = "не заполнено поле темы.Пожалуйста введите тему или нажмите \"".$composeStrings[1]."\" еще раз для отсылки сообщения.";
$composeErrors[1] = "Поле \"от\" не заполнено. Пожалуйста введите адрес email.";
$composeErrors[2] = "Поле \"Кому\" не заполнено.  Пожалуйста введите адрес получателя.";
$composeErrors[3] = "Загрузка не удалась";
$composeErrors[4] = "Не принято ни одного файла.";
$composeErrors[5] = "Для предупреждения спама, вы можете посылать сообщения только %1 получателям (%2 всего за сессию) каждые %3 секунд.";
$composeErrors[6] = "Ошибки не найдены.";
$composeErrors[7] = "Проверка на ошибки невозможна для указанного языка.";
$composeErrors[8] = "(использовался %s словарь)";


?>