<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/ruw/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Контакты";
$cStrings[1] = "Добавить контакт";
$cStrings[2] = " Контакт";
$cStrings[3] = "Имя";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Группа";
$cStrings[7] = "Комментарии";
$cStrings[8] = "Добавить/Редактировать контакт";
$cStrings[9] = "Email";
$cStrings[10] = "Создать сообщение";


$cErrors[0] = "Список контактов пуст";


?>