<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
	lang/ruw/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_months[1] = "Январь";
$lang_months[2] = "Февраль";
$lang_months[3] = "Март";
$lang_months[4] = "Апрель";
$lang_months[5] = "Май";
$lang_months[6] = "Июнь";
$lang_months[7] = "Июль";
$lang_months[8] = "Август";
$lang_months[9] = "Сентябрь";
$lang_months[10] = "Октябрь";
$lang_months[11] = "Ноябрь";
$lang_months[12] = "Декабрь";

$lang_datetime["short_mon"][1] = "Янв";
$lang_datetime["short_mon"][2] = "Фев";
$lang_datetime["short_mon"][3] = "Мар";
$lang_datetime["short_mon"][4] = "Апр";
$lang_datetime["short_mon"][5] = "Май";
$lang_datetime["short_mon"][6] = "Июн";
$lang_datetime["short_mon"][7] = "Июл";
$lang_datetime["short_mon"][8] = "Авг";
$lang_datetime["short_mon"][9] = "Сен";
$lang_datetime["short_mon"][10] = "Окт";
$lang_datetime["short_mon"][11] = "Ноя";
$lang_datetime["short_mon"][12] = "Дек";

$lang_datetime["dsow"][0] = "Вос";
$lang_datetime["dsow"][1] = "Пон";
$lang_datetime["dsow"][2] = "Вт";
$lang_datetime["dsow"][3] = "Ср";
$lang_datetime["dsow"][4] = "Чет";
$lang_datetime["dsow"][5] = "Пят";
$lang_datetime["dsow"][6] = "Суб";

$lang_datetime["dsowl"][0] = "Воскресенье";
$lang_datetime["dsowl"][1] = "Понедельник";
$lang_datetime["dsowl"][2] = "Вторник";
$lang_datetime["dsowl"][3] = "Среда";
$lang_datetime["dsowl"][4] = "Четверг";
$lang_datetime["dsowl"][5] = "Пятница";
$lang_datetime["dsowl"][6] = "Суббота";
			
$lang_datetime["dsow_short"] = array("П", "В", "С", "Ч", "П", "С", "В");
$lang_datetime["today"] = "Сегодня %t";		//e.g. "Today 12:02"
$lang_datetime["lastweek"] = "%w %t";		//e.g. "Wed 12:00"
$lang_datetime["thisyear"] = "%m/%d";		//e.g. "2/13"
$lang_datetime["prevyears"] = "%m/%d/%y"; 	//e.g. "1/1/2100"
$lang_datetime["monthyear"] = "%m %y";		//e.g. "January 2002"
$lang_datetime["verbal"] = "%m %d, %y";  	//e.g. "Jan 1, 1900"
$lang_datetime["verbal_short"] = "%m %d";  	//e.g. "Jan 1"
$lang_datetime["hour_system"] = 12;			// 12 or 24
$lang_datetime["ampm"]["am"] = "дп";
$lang_datetime["ampm"]["pm"] = "пп";
$lang_datetime["time_format"] = "%h:%m%a";	// %h=hour, %m=minutes, %a="am:pm"
$lang_datetime["hour_format"] = "%h%a";


?>