<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/ruw/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Редактировать";
$ecStrings[1] = "Добавить";
$ecStrings[2] = " Контакт";
$ecStrings[3] = "Имя";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Группа";
$ecStrings[7] = "Комментарии";
$ecStrings[8] = "Домашний телефон";
$ecStrings[9] = "Рабочий телефон";
$ecStrings[10] = "Мобильный телефон";
$ecStrings[11] = "Адрес";
$ecStrings[12] = "Альтерн. Email";
$ecStrings[13] = "Удалить";
$ecStrings[14] = "Другие";


$errors[0] = "Невозможно добавить контакт:  ошибка базы данных.";
$errors[1] = "Запись с таким адресом уже существует.";
$errors[2] = "Нажмите ";
$errors[3] = "Здесь";
$errors[4] = " редактировать эту запись взамен.";
$errors[5] = "Контакт не найден или запрещен доступ.";
$errors[6] = "Вы уверены, что хотите удалить запись \"";
$errors[7] = "\"?";

?>