<?php 
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Имя пользователя";
$loginStrings[1]="Пароль";
$loginStrings[2]="Сервер";
$loginStrings[3]="Тип";
$loginStrings[4]="Корневая директория";
$loginStrings[5]="Язык";
$loginStrings[6]="Войти";

$loginErrors[0]="Неавторизированный хост";
$loginErrors[1]="Ошибка: папка \"uploads\" не найдена";
$loginErrors[2]="Ошибка: папка \"users\" не найдена";
$loginErrors[3]="Ошибка: папка \"sessions\" не найдена";

?>