<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/ruw/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "Введите HTML код цвета для каждого компонента.";
$pcStrings["0.1"] = "Используйте ";
$pcStrings["0.2"] = "таблицу кодов цветов";
$pcStrings["0.3"] = " для определения кода цвета.";
$pcStrings["0.4"] = "Настройки, которые отвергает тема, не могут быть отменены.";
$pcStrings["1.0"] = "Панель инструментов";
$pcStrings["2.0"] = "Список папок";
$pcStrings["3.0"] = "Главная";
$pcStrings["3.1"] = "Фон заголовок: ";
$pcStrings["3.2"] = "Текст заголовка: ";
$pcStrings["3.3"] = "Черный фон: ";
$pcStrings["3.4"] = "Светлый текст: ";
$pcStrings["4.0"] = "Разное";
$pcStrings["4.1"] = "Цитаты: ";
$pcStrings["5.0"] = "Шрифты";
$pcStrings["5.1"] = "Шрифт";
$pcStrings["5.2"] = "Размер шрифта: ";
$pcStrings["5.3"] = "Размер малого шрифта: ";
$pcStrings["5.4"] = "Размер большого шрифта: ";
$pcStrings["5.5"] = "Размер шрифта списка папок: ";

							
$pcPortions = array( "Фон: ", "Ссылки: ", "Текст: ", "Выделенное: ");

?>
