<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "Персональные Данные";
$piStrings["edit"] = "Редактировать";
$piStrings["name"] = "Имя";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "Ответить";
$piStrings["sig"] = "Подпись";
$piStrings["add"] = "Добавить";
$piStrings["new"] = "Новые данные";
$piStrings["edit_ident"] = "Редактировать данные";
$piStrings["delete"] = "Удалить";

$piError[1] = "Введите имя или email";

?>
