<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/ruw/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Назад";
$rmStrings[1] = "Ответить";
$rmStrings[2] = "Переслать";
$rmStrings[3] = "Восстановить";
$rmStrings[4] = "Удалить";
$rmStrings[5] = "Файл";
$rmStrings[6] = "Части";
$rmStrings[7] = "Это HTML сообщение. ";
$rmStrings[8] = "Нажмите здесь для просмотра.";
$rmStrings[9] = "Исходное сообщение";
$rmStrings[10] = "Размер";
$rmStrings[11] = "Пометить как непрочтенное";
$rmStrings[12] = "Показать заголовок";
$rmStrings[13] = "Сообщить о спаме";
$rmStrings[14] = "Ответить всем";
$rmStrings[15] = "Вы отвечали на ето письмо";
$rmStrings[16] = "Печать";


?>