<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/ruw/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "Неверный критерий поиска:  Неверное поле";
$searchErrors["empty"] = "Неверный критерий поиска:  Пустая строка поиска";
$searchErrors["date"] = "Неверный критерий поиска:  Не указана дата";

?>