<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/ruw/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$toolStrings["folders"] = "Папки";
$toolStrings["inbox"] = "Входящие";
$toolStrings["compose"] = "Создать";
$toolStrings["calendar"] = "Календарь";
$toolStrings["contacts"] = "Контакты";
$toolStrings["bookmarks"] = "Закладки";
$toolStrings["search"] = "Поиск";
$toolStrings["prefs"] = "Настройки";
$toolStrings["logout"] = "Выход";
$toolStrings["go"] = "Перейти";

?>