<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Lag oppgave";
$calStr["edit_schedule"] = "Regiger oppgave";
$calStr["weekof"] = "Uke: %d";
$calStr["title"] = "Tittel:";
$calStr["color"] = "Farge:";
$calStr["colors"] = array("#990000"=>"Mørkerød", "#FF0000"=>"Rød", "#000099"=>"Dypblå", "#0000FF"=>"Blå", 
					"#006600"=>"Mørkegrønn", "#00FF00"=>"Grønn", "#9900FF"=>"Lilla", "#00FFFF"=>"Cyan",
					"#FF6600"=>"Oransje", "#FFFF00"=>"Gul", "#FF00FF"=>"Magenta", ""=>"Ingen farge");
$calStr["starts"] = "Starter:";
$calStr["ends"] = "Slutter:";
$calStr["from"] = "fra:";
$calStr["until"] = "til:";
$calStr["repeat_on"] = "Gjenta";
$calStr["of"] = "hver";
$calStr["weeks"] = array(1=>"første uke", 2=>"andre uke", 3=>"tredje uke", 4=>"fjerde uke"); 
$calStr["week_blurb"] = "...hver måned (til sluttdato).<br>Gjentas alle uker hvis ingen spesielle er valgt.";
$calStr["monthly"] = "Gjenta månedlig";
$calStr["yearly"] = "Gjenta årlig";
$calStr["place"] = "Sted:";
$calStr["description"] = "Beskrivelse:";
$calStr["add"] = "Legg til";
$calStr["update"] = "Oppdater";
$calStr["Delete"] = "Slett";
$calStr["go"] = "Utfør";
$calStr["disabled"] = "Kalenderen er utilgjengelig.";
?>