<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/no/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

      Translated by Tor Olsen <tor@monet.no>
********************************************************/

$composeHStrings[0] = "Emne";
$composeHStrings[1] = "Fra";
$composeHStrings[2] = "Til";
$composeHStrings[3] = "CC";
$composeHStrings[4] = "BCC";
$composeHStrings[5] = "Dato";


$composeStrings[0] = "Skriv Melding";
$composeStrings[1] = "Send Melding";
$composeStrings[2] = "Last Opp";
$composeStrings[3] = "Legg til signatur";
$composeStrings[4] = "Vedlegg";
$composeStrings[5] = "Vis kontakter";
$composeStrings[6] = "Skjul kontakter";
$composeStrings[7] = "Melding:";
$composeStrings[8] = "Legg til";
$composeStrings[9] = "På %d, %s skrev:\n";
$composeStrings[10] = "--- Original Melding ---\n";
$composeStrings[11] = "Lukk Vindu";


$composeErrors[0] = "Emne feltet er tomt. Skriv inn et emne eller klikk \"".$composeStrings[1]."\" igjen for å sende.";
$composeErrors[1] = "\"fra\" feltet er tomt.  Skriv inn e-post adressen din.";
$composeErrors[2] = "\"Til\" feltet er tomt.  Skriv inn mottakers adresse.";
$composeErrors[3] = "Feil under opplasting";
$composeErrors[4] = "Ingen filer mottatt.";
$composeErrors[5] = "For å motvirke spam kan du bare sende til to %1 people (%2 totalt per session) hvert %3 sekund.";

?>