<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/no/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Tor Olsen <tor@monet.no>
********************************************************/

$ecStrings[0] = "Rediger";
$ecStrings[1] = "Legg til";
$ecStrings[2] = " Kontakt";
$ecStrings[3] = "Navn";
$ecStrings[4] = "E-post";
$ecStrings[5] = "URL";
$ecStrings[6] = "Gruppe";
$ecStrings[7] = "Kommentarer";
$ecStrings[8] = "Telefon hjemme";
$ecStrings[9] = "Telefon jobb";
$ecStrings[10] = "Mobil";
$ecStrings[11] = "Adresse";
$ecStrings[12] = "Alt. E-post";
$ecStrings[13] = "Slett";
$ecStrings[14] = "Andre";


$errors[0] = "Kunne ikke legge til kontakt:  database feil.";
$errors[1] = "En kontakt med den adressen finnes allerede.";
$errors[2] = "Klikk ";
$errors[3] = "her";
$errors[4] = " for å redigere den kontakten.";
$errors[5] = "Kontakten ikke funnet, eller nektet tilgang.";
$errors[6] = "Er du sikker på du vil ta bort posten for \"";
$errors[7] = "\"?";

?>