<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/no/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Tor Olsen <tor@monet.no>
********************************************************/
//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_folders.inc");

$efStrings[0] = "Håndtere mapper";
$efStrings[1] = "Lag ny mappe";
$efStrings[2] = "Lag mappe: ";
$efStrings[3] = "Lag";
$efStrings[4] = "Slett mappe";
$efStrings[5] = "Slett";
$efStrings[6] = "Døp om mappe";
$efStrings[7] = "Døp om";
$efStrings[8] = "Abonnerte mapper";
$efStrings[9] = "Abonner";
$efStrings[10] = "Uab. mapper";
$efStrings[11] = "Si opp";


$errors[0] = "Lag mappe: ";
$errors[1] = "Kunne ikke lage ny mappe: ";
$errors[2] = "Slett mappe: ";
$errors[3] = "Kunne ikke slette mappe: ";
$errors[4] = "Døp om mappe: ";
$errors[5] = "Kunne ikke gi mappen nytt navn: ";
$errors[6] = "Mappestøtte er bare tilgjengelig for IMAP kontoer.";

?>