<?php
/********************************************************
	lang/eng/filters.inc
	(C)2001-2004 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html
         Translated by: Tor Olsen <tor@monet.no>


********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/filters.inc");

$fltr["filter"] = "Filter";
$fltr["conditions"] = "Betingelser";
$fltr["actions"] = "Handlinger";
$fltr["auto"] = "Utføres automatisk på innboks";
$fltr["deletemsg"] = "Slett melding";
$fltr["&"] = "og";
$fltr["|"] = "eller";
$fltr["^"] = "begynner med";
$fltr["<"] = "inneholder";
$fltr["$"] = "slutter med";
$fltr["="] = "gjør";
$fltr["!"] = "gjør ikke";
$fltr["field"] = "Felt";
$fltr["condition"] = "Betingelse";
$fltr["action"] = "Handling";
$fltr["name"] = "Navn";
$fltr["sort_order"] = "Prioritet";
$fltr["edit"] = "rediger";
$fltr["add"] = "Legg til Filter";
$fltr["edit_filter"] = "Rediger Filter";
$fltr["delete"] = "Slett";
$fltr["filters"] = "Filtre";
$fltr["new"] = "Nytt Filter";
$fltr["status"] = "Status";
$fltr["stat_en"] = "aktiv";
$fltr["stat_dis"] = "inaktiv";
$fltr["is_active"] = "filteret er aktivt";
$fltr["other"] = "Annet";
$fltr["move"] = "Flytt til";
$fltr["copy"] = "Kopier til";
$fltr["do_nothing"] = "Gjør ingenting";
$fltr["add_cond"] = "Legg til betingelse";
$fltr["remove_cond"] = "Fjern betingelse";
$fltr["condition_str"] = "%b %c %t";

$f_hlp["priority"] = "(Høyere prioritet kjøres først.)";

$f_err["no_name"] = "Velg et navn for denne filter regelen\n";
$f_err["no_act"] = "Velg en eller flere handlinger for denne regelen\n";
$f_err["no_cond"] = "Velg en eller flere betingelser for denne regelen\n";
$f_err["inv_param"] = "Ugyldige parametre for valgte handling\n";
$f_err["inv_sort"] = "Sorteringsrekkefølgen må være numerisk\n";

?>
