<?php 
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Brukernavn";
$loginStrings[1]="Passord";
$loginStrings[2]="Server";
$loginStrings[3]="Type";
$loginStrings[4]="Rotkatalog";
$loginStrings[5]="Språk";
$loginStrings[6]="Logg inn";

$loginErrors[0]="Uautorisert host";
$loginErrors[1]="Error: \"uploads\" directory not found";
$loginErrors[2]="Error: \"users\" directory not found";
$loginErrors[3]="Error: \"sessions\" directory not found";

?>