<?php
include("../lang/eng/quota.inc"); // <-- do not delete
/********************************************************
	lang/eng/quota.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$quotaStr["label"] = "Diskbruk: ";
$quotaStr["full"] = "%usedKB/%totalKB (%free% free)";
$quotaStr["unknown"] = "ukjent";

?>