<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/no/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by: Tor Olsen <tor@monet.no>
********************************************************/

$rmStrings[0] = "Tilbake";
$rmStrings[1] = "Svar";
$rmStrings[2] = "Videresend";
$rmStrings[3] = "Gjenopprett";
$rmStrings[4] = "Slett";
$rmStrings[5] = "Fil";
$rmStrings[6] = "Deler";
$rmStrings[7] = "Dette er en HTML melding. ";
$rmStrings[8] = "Kilkk her for å lese den.";
$rmStrings[9] = "Kilde";
$rmStrings[10] = "Størrelse";
$rmStrings[11] = "Merk uleste";
$rmStrings[12] = "Vis meldingshode";
$rmStrings[13] = "Rapporter spam";
$rmStrings[14] = "Svar alle";

?>