<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/no/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by: Tor Olsen <tor@monet.no>
********************************************************/

$searchErrors["field"] = "Ugyldig søkekriterium:  Ugyldig felt";
$searchErrors["empty"] = "Ugyldig søkekriterium:  Tom søkestreng";
$searchErrors["date"] = "Ugyldig søkekriterium:  Dato ikke spesifisert";

?>