<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/no/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by: Tor Olsen <tor@monet.no>
********************************************************/

$toolStrings["folders"] = "Mapper";
$toolStrings["inbox"] = "Innboks";
$toolStrings["compose"] = "Skriv";
$toolStrings["calendar"] = "Kalender";
$toolStrings["contacts"] = "Kontakter";
$toolStrings["bookmarks"] = "Bokmerker";
$toolStrings["search"] = "Søk";
$toolStrings["prefs"] = "Preferanser";
$toolStrings["logout"] = "Logg ut";
$toolStrings["go"] = "Gå";

?>