<?php
/********************************************************
	lang/eng/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "цесЧЪ";
$bmStrings["identities"] = "хцэЧЪ";
$bmStrings["edit"] = "лэб";
$bmStrings["name"] = "ЧсХгу";
$bmStrings["url"] = "кфцЧф Чсуцок";
$bmStrings["category"] = "ЧснЦЩ";
$bmStrings["other"] = "ЭЯЯ-&gt;";
$bmStrings["comments"] = "усЧЭйЧЪ";
$bmStrings["add"] = "Ужн";
$bmStrings["new"] = "цесЩ ЬЯэЯЩ";
$bmStrings["edit_url"] = "лэб ЧсцесЩ";
$bmStrings["delete"] = "ЧугЭ ЧсцесЩ";

$bmError[1] = "ЧсХгу Уц кфцЧф Чсуцок жбцбэЧф.";
$bmError[2] = "хах ЧсЮЯуЩ лэб удлсЩ.";
?>