<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "ÃÖİ ãæÚÏÇ";
$calStr["edit_schedule"] = "ÛíÑ ãæÚÏÇ";
$calStr["weekof"] = "ÃÓÈæÚ ãä: %d";
$calStr["title"] = "ÇáÚäæÇä:";
$calStr["color"] = "Çááæä:";
$calStr["colors"] = array("#990000"=>"ÃÍãÑ ÛÇãŞ", "#FF0000"=>"ÃÍãÑ", "#000099"=>"ÃÒÑŞ ÛÇãŞ", "#0000FF"=>"ÃÒÑŞ", 
					"#006600"=>"ÃÎÖÑ ÛÇãŞ", "#00FF00"=>"ÃÎÖÑ", "#9900FF"=>"ÃÑÌæÇäí", "#00FFFF"=>"ÃÒÑŞ ÓãÇæí",
					"#FF6600"=>"ÈÑÊŞÇáí", "#FFFF00"=>"ÃÕİÑ", "#FF00FF"=>"ÃÍæÑ ÃÑÌæÇäí", ""=>"áÇ áæä");
$calStr["starts"] = "ÊÇÑíÎ ÇáÈÏÁ:";
$calStr["ends"] = "ÊÇÑíÎ ÇáÅäÊåÇÁ:";
$calStr["from"] = "ãä:";
$calStr["until"] = "ÍÊì:";
$calStr["repeat_on"] = "ßÑÑ";
$calStr["of"] = "ßá";
$calStr["weeks"] = array(1=>"ÇáÃÓÈæÚ ÇáÃæá", 2=>"ÇáÃÓÈæÚ ÇáÊÇäí", 3=>"ÇáÃÓÈæÚ ÇáËÇáË", 4=>"ÇáÃÓÈæÚ ÇáÑÇÈÚ"); 
$calStr["week_blurb"] = "...ãä ßá ÔåÑ (ÍÊì ÊÇÑíÎ ÇáÅäÊåÇÁ).<br>ÓíÊßÑÑ ßá ÃÓÈæÚ Åä áã íÊã ÊÍÏíÏ ÇáÃÓÇÈíÚ.";
$calStr["monthly"] = "ßÑÑ ÔåÑíÇ";
$calStr["yearly"] = "ßÑÑ ÓäæíÇ";
$calStr["place"] = "ÇáãßÇä:";
$calStr["description"] = "ãáÇÍÙÇÊ:";
$calStr["add"] = "ÃÖİ";
$calStr["update"] = "ÍÏË";
$calStr["Delete"] = "ÇãÓÍ";
$calStr["go"] = "ÇĞåÈ Åáì";
$calStr["disabled"] = "ÎÏãÉ ÇáãİßÑÉ ÛíÑ ãÔÛáÉ.";
?>