<?php
/********************************************************
	lang/eng/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/compose.inc");

$composeHStrings[0] = "ÇáãæÖæÚ";
$composeHStrings[1] = "ãä";
$composeHStrings[2] = "Åáì";
$composeHStrings[3] = "äÓÎÉ";
$composeHStrings[4] = "äÓÎÉ ãÎÈÃÉ";
$composeHStrings[5] = "ÇáÊÇÑíÎ";


$composeStrings[0] = "ÑÓÇáÉ ÌÏíÏÉ";
$composeStrings[1] = "ÇÈÚÊ ÇáÑÓÇáÉ";
$composeStrings[2] = "Íãá Úáì ÇáÎÇÏã";
$composeStrings[3] = "ÃÖÝ ÇáÊæÞíÚ";
$composeStrings[4] = "ÃáÍÞ ãáÝÇ";
$composeStrings[5] = "ÚäÇæíä";
$composeStrings[6] = "ÃÎÝ ÇáÚäÇæíä";
$composeStrings[7] = "äÕ ÇáÑÓÇáÉ:";
$composeStrings[8] = "ÃÖÝ";
$composeStrings[9] = "Ýí %d, %s ßÊÈ:\n";
$composeStrings[10] = "--- ÇáÑÓÇáÉ ÇáÃÕáíÉ ---\n";
$composeStrings[11] = "ÃÛáÞ ÇáäÇÝÏÉ";

$composeStrings[12] = "ÊÍÞÞ ãä ÇááÛÉ";
$composeStrings[13] = "ÕÍÍ ÇááÛÉ";
$composeStrings[14] = "áÇ ÊÛííÑ";
$composeStrings[15] = "ÃÎØÇÁ áÛæíÉ ãÍÊãáÉ";
$composeStrings[16] = "ÊÛííÑÇÊ áÛæíÉ";
$composeStrings[17] = "ÊÌÇåá";
$composeStrings[18] = "ÇãÓÍ";

$composeStrings["title"] = "ÑÓÇáÉ ÌÏíÏÉ";

$composeErrors[0] = "ÇáãæÖæÚ ÛíÑ ãÍÏÏ. ÇáãÑÌæ ÅÏÎÇá ÇáãæÖæÚ Ãæ ÇäÞÑ \"".$composeStrings[1]."\" ãÑÉ ÊÇäíÉ áÅÑÓÇá ÇáÑÓÇáÉ.";
$composeErrors[1] = "ÇáÍÞá \"ãä\" ÝÇÑÛ. ÇáãÑÌæ ÅÏÎÇá ÚäæÇäß ÇáÈÑíÏí.";
$composeErrors[2] = "ÇáÍÞá \"Çáì\" ÝÇÑÛ. ÇáãÑÌæ ÅÏÎÇá ÚäæÇä ÇáãÑÓá Åáíå.";
$composeErrors[3] = "ÚØÈ Ýí ÇáÊÍãíá";
$composeErrors[4] = "áã ÊÊæÕá ÈÃí ãáÝ.";
$composeErrors[5] = "ááÍãÇíÉ ãä ÇáÓÈÇã¡ íãßäß ÇáÅÑÓÇá Åáì %1 ÔÎÕÇ ÝÞØ (%2 ÅÌãÇáÇ ßá ÏæÑÉ) ßá %3 ÊÇäíÉ.";

$composeErrors[6] = "áÇ äæÌÏ ÃÎØÇÁ áÛæíÉ.";
$composeErrors[7] = "ÇáÊÍÞÞ ãä ÇááÛÉ ÛíÑ ããßä ÍÇáíÇ ÈÇáäÓÈÉ áåÐå ÇááÛÉ.";
$composeErrors[8] = "(%s ãä ÍÌã ÇáÞÇãæÓ ÇááÛæí ãÓÊÚãá)";
?>

