<?php
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/contacts.inc");

$cStrings[0] = "ַבדַׁ׃בזה";
$cStrings[1] = "ֳײÝ דַׁ׃בַ";
$cStrings[2] = " דַׁ׃ב";
$cStrings[3] = "ַבֵ׃ד";
$cStrings[4] = "ַבָׁםֿ ַבֵבßÊׁזהם";
$cStrings[5] = "ַבזםָ";
$cStrings[6] = "ַבדּדזÚֹ";
$cStrings[7] = "דבַֽÙַÊ";
$cStrings[8] = "ֳײÝ / Ûםׁ ַבדַׁ׃ב";
$cStrings[9] = "ַבָׁםֿ ַבֵבßÊׁזהם";
$cStrings[10] = "ßזה ׁ׃ַבֹ";

$cStrings["close"] = "ֳÛבÞ ַבהַÝֹֿ";
$cStrings["addto"] = "ֳײÝ ַבדַׁ׃ב ֵבל %s";
$cStrings["showgrp"] = "ַÚׁײ %s";
$cStrings["all"] = "ַבßב";
$cStrings["instructions"] = "ֳהÞׁ Úבל ַבֳ׃דֱַ בֵײַÝÊוַ. םדßהß ֳםײַ ַבהÞׁ Úבל ַ׃ד ַבדּדזÚֹ בֵײַÝֹ ßב ַבֳÝַֿׁ ׀ַ־בוַ.";

$cErrors[0] = "בֶַֹֽ ַבÚהַזםה ÝַׁÛֹ";

?>