<?php
/********************************************************
	lang/eng/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/dates.inc");

$lang_months[1] = "нд«н—";
$lang_months[2] = "Ё»—«н—";
$lang_months[3] = "г«—”";
$lang_months[4] = "√»—нб";
$lang_months[5] = "г«н";
$lang_months[6] = "нжднж";
$lang_months[7] = "нжбнж“";
$lang_months[8] = "џ‘ ";
$lang_months[9] = "‘ д»—";
$lang_months[10] = "√я ж»—";
$lang_months[11] = "джд»—";
$lang_months[12] = "ѕЌд»—";

$lang_datetime["short_mon"][1] = "нд«н—";
$lang_datetime["short_mon"][2] = "Ё»—«н—";
$lang_datetime["short_mon"][3] = "г«—”";
$lang_datetime["short_mon"][4] = "√»—нб";
$lang_datetime["short_mon"][5] = "г«н";
$lang_datetime["short_mon"][6] = "нжднж";
$lang_datetime["short_mon"][7] = "нжбнж“";
$lang_datetime["short_mon"][8] = "џ‘ ";
$lang_datetime["short_mon"][9] = "‘ д»—";
$lang_datetime["short_mon"][10] = "√я ж»—";
$lang_datetime["short_mon"][11] = "джд»—";
$lang_datetime["short_mon"][12] = "ѕЌд»—";

$lang_datetime["dsow"][0] = "«б√Ќѕ";
$lang_datetime["dsow"][1] = "«б≈Ћднд";
$lang_datetime["dsow"][2] = "«бЋб«Ћ«Ѕ";
$lang_datetime["dsow"][3] = "«б√—»Џ«Ѕ";
$lang_datetime["dsow"][4] = "«бќгн”";
$lang_datetime["dsow"][5] = "«бћгЏ…";
$lang_datetime["dsow"][6] = "«б”» ";

$lang_datetime["dsowl"][0] = "«б√Ќѕ";
$lang_datetime["dsowl"][1] = "«б≈Ћднд";
$lang_datetime["dsowl"][2] = "«бЋб«Ћ«Ѕ";
$lang_datetime["dsowl"][3] = "«б√—»Џ«Ѕ";
$lang_datetime["dsowl"][4] = "«бќгн”";
$lang_datetime["dsowl"][5] = "«бћгЏ…";
$lang_datetime["dsowl"][6] = "«б”» ";
			
$lang_datetime["dsow_short"] = array("S", "M", "T", "W", "T", "F", "S");
$lang_datetime["today"] = "«бнжг %t";		//e.g. "Today 12:02"
$lang_datetime["lastweek"] = "%w %t";		//e.g. "Wed 12:00"
$lang_datetime["thisyear"] = "%m/%d";		//e.g. "2/13"
$lang_datetime["prevyears"] = "%m/%d/%y"; 	//e.g. "1/1/2100"
$lang_datetime["monthyear"] = "%m %y";		//e.g. "January 2002"
$lang_datetime["verbal"] = "%m %d, %y";  	//e.g. "Jan 1, 1900"
$lang_datetime["verbal_short"] = "%m %d";  	//e.g. "Jan 1"
$lang_datetime["hour_system"] = 24;			// 12 or 24
$lang_datetime["ampm"]["am"] = "ё.“";
$lang_datetime["ampm"]["pm"] = "».“";
$lang_datetime["time_format"] = "%h:%m%a";	// %h=hour, %m=minutes, %a="am:pm"
$lang_datetime["hour_format"] = "%h%a";
?>