<?php
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Ûםׁ";
$ecStrings[1] = "ֳײÝ";
$ecStrings[2] = " דַׁ׃ב";
$ecStrings[3] = "ַבֵ׃ד";
$ecStrings[4] = "ַבָׁםֿ ַבֵבßÊׁזהם";
$ecStrings[5] = "ַבזםָ";
$ecStrings[6] = "ַבדּדזÚֹ";
$ecStrings[7] = "דבַֽÙַÊ";
$ecStrings[8] = "וַÊÝ ַבָםÊ";
$ecStrings[9] = "וַÊÝ ַבÚדב";
$ecStrings[10] = "ַבוַÊÝ ַבדֽדזב";
$ecStrings[11] = "Úהזַה ַבָׁםֿ";
$ecStrings[12] = "ָׁםֿ ֵבßÊׁזהם Êַהם";
$ecStrings[13] = "ַד׃ֽ";
$ecStrings[14] = "ֳ־ׁל";


$errors[0] = "בַ םדßה ֵײַÝֹ ַבדַׁ׃ב : Ú״ָ Ýם ÞַÚֹֿ ַבָםַהַÊ.";
$errors[1] = "םזּֿ דַׁ׃ב ֲ־ׁ ָהÝ׃ ַבÚהזַה.";
$errors[2] = "ֳהÞׁ ";
$errors[3] = "והַ";
$errors[4] = " בÊÚֿםב ו׀ו ַבָםַהַÊ.";
$errors[5] = "דַׁ׃ב Ûםׁ דזּזֿ ֳז בם׃ בß ֽÞ ַבֵÊױַב ָÞַÚֹֿ ַבָםַהַÊ.";
$errors[6] = "ֳהÊ דÊֳßֿ דה ד׃ֽ ַבָםַהַÊ ַבדÊÚבÞֹ ָ \"";
$errors[7] = "\"?";

?>