<?php 
/********************************************************
	lang/en/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="ֵ׃ד ַבד׃Ê־ֿד";
$loginStrings[1]="ßבדֹ ַב׃ׁ";
$loginStrings[2]="ַב־ַֿד";
$loginStrings[3]="ַבהזÚ";
$loginStrings[4]="ַבדבÝ ַבּֿׁ";
$loginStrings[5]="ַבבÛֹ";
$loginStrings[6]="ֿ־זב";

$loginErrors[0]="בם׃ בß ַבֽÞ Ýם ַ׃Ê־ַֿד ו׀ַ ַב־ַֿד";
$loginErrors[1]="־״ֳ: ַבדבÝ \"uploads\" Ûםׁ דזּזֿ";
$loginErrors[2]="־״ֳ: ַבדבÝ \"users\" Ûםׁ דזּזֿ";
$loginErrors[3]="־״ֳ: ַבדבÝ \"sessions\" Ûםׁ דזּזֿ";



?>