<?php
/********************************************************
	lang/eng/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainMessages["delete"] = "ãÓÍ %n ÑÓÇáÉ(s)";
$mainMessages["move"] = "äŞá %n ÑÓÇáÉ(s) Çáì %f";

$mainStrings[0] = "ÚÑÖ %p ãä %n";
$mainStrings[1] = " ÑÓÇáÉ æÌÏÊ";
$mainStrings[2] = "ÓÇÈŞ";
$mainStrings[3] = "";
$mainStrings[4] = "ÊÇáí";
$mainStrings[5] = "";
$mainStrings[6] = "ÇáãæÖæÚ";
$mainStrings[7] = "Åáì";
$mainStrings[8] = "ãä";
$mainStrings[9] = "ÇáÊÇÑíÎ";
$mainStrings[10] = "ÇãÓÍ";
$mainStrings[11] = "ÃİÑÛ ÇáÓáÉ";
$mainStrings[12] = "ÃäŞá";
$mainStrings[13] = "ÇÈÍË";
$mainStrings[14] = "ÍÌã";
$mainStrings[15] = "ÈÏæä ÚäæÇä";
$mainStrings[16] = "ÇÚÑÖ";
$mainStrings[17] = "ÇÈÍÊ Úä ÑÓÇÆá ÌÏíÏÉ";
$mainStrings[18] = "ÇãÓÍ Çáßá";
$mainStrings[19] = "ÃáÛ";
$mainStrings[20] = "ÇÚáöã ß %b";
$mainStrings[21] = "ãŞÑæÁ";
$mainStrings[22] = "ÛíÑ ãŞÑæÁ";
$mainStrings[23] = "ÇÎÊíÇÑ...";


$mainErrors[0] = "áÇ ÑÓÇÆá ãæÌæÏÉ İí åĞÇ Çáãáİ";
$mainErrors[1] = "áÇ ÑÓÇÆá İí åĞÇ Çáãáİ";
$mainErrors[2] = "áÇ íãßä äŞá ÇáÑÓÇÆá áÓáÉ ÇáãåãáÇÊ.";
$mainErrors[3] = "áÇ íãßä ÇÚáÇã ÇáÑÓÇáÉ ßããÓæÍÉ.";
$mainErrors[4] = "áÇ íãßä äŞá ÇáÑÓÇáÉ.";
$mainErrors[5] = "ÓáÉ ÇáãåãáÇÊ ÛíÑ ãÍÏÏÉ.";
$mainErrors[6] = "áÇ íãßä ÊİÑíÛ ÓáÉ ÇáãåãáÇÊ";
$mainErrors[7] = "åá ÃäÊ ãÊÃßÏ Ãäß ÊÑíÏ ãÓÍ ßá ÇáÑÓÇÆá ÇáãæÌæÏÉ İí %f?";
$mainErrors[8] = "ÃäŞÑ Úáì ÇáÃÓåã ÊÍÊ ÚäÇæíä ÇáÃÚãÏÉ áäŞáåã.<br>æÈÚÏ ÇáÅäÊåÇÁ ÃÛáŞ ÇáäÇİÏÉ.";



?>