<?php
/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "ÃÏÎá ßæÏ HTML ááæä ßá ÌÒÁ";
$pcStrings["0.1"] = "ÇÓÊÚãá Çá ";
$pcStrings["0.2"] = "ÊÚáíãÇÊ ßæÏÇÊ ÇáÃáæÇä";
$pcStrings["0.3"] = " áÅíÌÇÏ ÇáßæÏÇÊ ÇáÕÍíÍÉ.";
$pcStrings["0.4"] = "ÇáÎíÇÑÇÊ ÛíÑ ÇáÞÇÈáÉ ááÊÛííÑ áÇ íãßä ÊÚÏíáåÇ.";
$pcStrings["1.0"] = "áæÍÉ ÇáÊÍßã";
$pcStrings["2.0"] = "ÞÇÆãÉ ÇáãáÝÇÊ";
$pcStrings["3.0"] = "ÑÆíÓí";
$pcStrings["3.1"] = "áæä ÇáÎáÝíÉ ÇáÚáæí: ";
$pcStrings["3.2"] = "áæä ÇáäÕ ÇáÚáæí: ";
$pcStrings["3.3"] = "ÇáÎáÝíÉ ÇáÛÇãÞÉ: ";
$pcStrings["3.4"] = "ÇáäÕ ÇáÝÇÊÍ: ";
$pcStrings["4.0"] = "ãÊäæÚ";
$pcStrings["4.1"] = "ÇáÇÞÊÈÇÓ: ";
$pcStrings["5.0"] = "ÇáÎØ";
$pcStrings["5.1"] = "äæÚ ÇáÎØ";
$pcStrings["5.2"] = "ÍÌã ÇáÎØ: ";
$pcStrings["5.3"] = "ÍÌã ÇáÎØ ÇáÕÛíÑ: ";
$pcStrings["5.4"] = "ÍÌã ÎØ ÚäÇæíä: ";
$pcStrings["5.5"] = "ÍÌã ÎØ áÇÆÍÉ ÇáãáÝÇÊ: ";

							
$pcPortions = array( "ÎáÝíÉ: ", "æÕáÇÊ: ", "äÕ: ", "äÕ ãÖíÁ: ");

?>
