<?php
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "åæíÇÊ";
$piStrings["edit"] = "ÊÚÏíá";
$piStrings["name"] = "ÇáÅÓã";
$piStrings["email"] = "ÇáÈÑíÏ ÇáÅáßÊÑæäí";
$piStrings["replyto"] = "ÃÌöÈ Åáì";
$piStrings["sig"] = "ÇáÅãÖÇÁ";
$piStrings["add"] = "ÃÖÝ";
$piStrings["new"] = "åæíÉ ÌÏíÏÉ";
$piStrings["edit_ident"] = "ÚÏá ÇáåæíÉ";
$piStrings["delete"] = "ÇãÓÍ ÇáåæíÉ";
$piStrings["setdef"] = "ÇÌÚáåÇ åæíÉ ÇÚÊíÇÏíÉ";
$piStrings["isdef"] = "(ÇÚÊíÇÏíÉ)";

$piError[1] = "ÇáÅÓã Ãæ ÇáÈÑíÏ ÇáÅáßÊÑæäí ÖÑæÑíÇä";

?>
