<?php
/********************************************************
	lang/eng/prefs.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/prefs.inc");

$prefHeaderStrings[0] = "ÎíÇÑÇÊ";
$prefHeaderStrings[1] = "ÚÇãÉ";
$prefHeaderStrings[3] = "åæíÇÊ";
$prefHeaderStrings[2] = "ÚÑÖ";

											
$prefsStrings["0.0"] = "åæíÉ ÇÚÊíÇÏíÉ";
$prefsStrings["0.1"] = "ÇáÅÓã: ";
$prefsStrings["0.2"] = "ÇáÈÑíÏ ÇáÅáßÊÑæäí: ";
$prefsStrings["0.3"] = "ÇáÊÍæá íÔãá \"%s\" ÕİÍÉ.";
$prefsStrings["0.4"] = "ÛíÑ ãÍÏÏ";
$prefsStrings["1.0"] = "ÚÇáãí";
$prefsStrings["1.1"] = "ÇáæÇÌåÉ: ";
$prefsStrings["1.2"] = "äæÚ ÇáÍÑİ: ";
$prefsStrings["1.3"] = "ÇáÊæŞíÊ: ";
$prefsStrings["1.4"] = "ÎíÇÑ ÇáæŞÊ: ";
$prefsStrings["1.5"] = array(12=>"12 ÓÇÚÉ", 24=>"24 ÓÇÚÉ");
$prefsStrings["2.0"] = "ÎíÇÑÇÊ áÇÆÍÉ ÇáÑÓÇÆá";
$prefsStrings["2.1"] = "ÇÚÑÖ Åáì ÛÇíÉ ";
$prefsStrings["2.2"] = " ãæÖæÚ";
$prefsStrings["2.3"] = "ÇÚÑÖ ÇáÍÌã";
$prefsStrings["2.4"] = "ÑÊÈ ÍÓÈ: ";
$prefsStrings["2.5"] = "";
$prefsStrings["2.6"] = "ÇÊÌÇå ÇáÊÑÊíÈ: ";
$prefsStrings["2.7"] = "";
$prefsStrings["2.8"] = "ÇÚÑÖ áÇÆÍÉ ÇáãáİÇÊ";
$prefsStrings["2.9"] = "ÚÑÖ áÇÆÍÉ ÇáãáİÇÊ";
$prefsStrings["2.10"] = "ÇÈÍË Úä ÑÓÇÆá ÌÏíÏÉ ßá %n ÊÇäíÉ";
$prefsStrings["2.11"] = "ÇÚÑÖ áæÍÉ ÇáÊÍßã İí %m";
$prefsStrings["2.12"] = array("b"=>"ÇáÃÓİá", "t"=>"ÇáÃÚáì", "bt"=>"ÃÚáì æ ÃÓİá");
$prefsStrings["2.13"] = "ÃÚÏ ÊÑÊíÈ ÇáÃÚãÏÉ: ";
$prefsStrings["2.14"] = "ÇäŞÑ åäÇ";
$prefsStrings["3.0"] = "ÎíÇÑÇÊ ÇáÍİÖ ÇáÊáŞÇÆí";
$prefsStrings["3.1"] = "ÇÍİÖ ÇáÑÓÇÆá ÇáÕÇÏÑÉ.";
$prefsStrings["3.2"] = "ÇÍİÖ ÇáÑÓÇÆá ÇáÕÇÏÑÉ İí ãáİ: ";
$prefsStrings["3.3"] = "";
$prefsStrings["3.4"] = "ÃİÑÛ ÊáŞÇÆíÇ ÓáÉ ÇáãåãáÇÊ";
$prefsStrings["3.5"] = "ÇäŞá ÇáÑÓÇÆá ÇáããÓæÍÉ Çáì ãáİ: ";
$prefsStrings["3.6"] = "";
$prefsStrings["3.7"] = "Çáãáİ ÇáÌÏÑ: ";
$prefsStrings["3.8"] = "ÂÎÑ";
$prefsStrings["3.9"] = "ÃÎİ ÇáãáİÇÊ ÛíÑ ÇáãÓÌáÉ";
$prefsStrings["3.10"] = "ÇÚÑÖ äÓÈÉ ÇáÅÓÊÎÏã %m";
$prefsStrings["3.11"] = array(""=>"áÇ ÊÙåÑ", "m"=>"İí áÇÆÍÉ ÇáÑÓÇÆá", "f"=>"İí áÇÆÍÉ ÇáãáİÇÊ");
$prefsStrings["4.0"] = "ÎíÇÑÇÊ ÚÑÖ ÇáÑÓÇÆá";
$prefsStrings["4.1"] = "ÇÚÑÖ İí äİÓ ÇáäÇİĞÉ";
$prefsStrings["4.2"] = "áæä ÇáäÕ ÇáãŞÊÈÓ";
$prefsStrings["4.3"] = "ÊÔÛíá åĞÇ ÇáÎíÇÑ ŞÏ íÄÊÑ ÓáÈÇ Úáì ÓÑÚÉ ÇáäÙÇã.";
$prefsStrings["4.4"] = "Íæá ÇáÚäÇæíä Åáì æÕáÇÊ";
$prefsStrings["4.5"] = "ÇÚÑÖ ÇáÑÓÇÆá ãä äæÚ HTML";
$prefsStrings["4.6"] = "ÇÚÑÖ ÇáÕæÑ ÏÇÎá ÇáäÕ";
$prefsStrings["4.7"] = "ÇÚÑÖ æÕáÉ ÇáÅÈÍÇÑ";
$prefsStrings["4.8"] = "áÇ ÊÚáã ÇáÑÓÇáÉ ÚäÏãÇ íÊã İŞØ ÇáãÑæÑ ÈåÇ";
$prefsStrings["5.0"] = "ÅãÖÇÁ";
$prefsStrings["5.1"] = "ÇÚÑÖ ÇáÅãÖÇÁ ÇáÅÚÊíÇÏí";
$prefsStrings["5.2"] = "";
$prefsStrings["6.0"] = "Êßæíä ÑÓÇáÉ";
$prefsStrings["6.1"] = "ÇÚÑÖ ÇáÚäÇæíä";
$prefsStrings["6.2"] = "ÇÚÑÖ ÇáÍŞæá äÓÎÉ / äÓÎÉ ãÎÈÃÉ";
$prefsStrings["6.3"] = "ÃÛáŞ ÈÚÏ ÇáÅÑÓÇá";
$prefsStrings["6.4"] = "ßæä İí äİÓ ÇáäÇİÏÉ";
$prefsStrings["7.0.0"] = "ÎíÇÑÇÊ ÇáŞÑÕ æÇáãáİÇÊ";
$prefsStrings["7.0.1"] = "ÎíÇÑÇÊ äÓÈÉ ÇáÅÓÊÎÏÇã";
$prefsStrings["7.1"] = "ÇÚÑÖ ÚÏÏ ÇáÑÓÇÆá ÛíÑ ÇáãŞÑæÁÉ";
$prefsStrings["7.2"] = "ÊÌÏíÏ áÇÆÍÉ ÇáãáİÇÊ ßá  %n ÊÇäíÉ";

$pref_col_title = "ÃÚÏ ÊÑÊíÈ ÇáÃÚãÏÉ";
$pref_colstr["order"] = "ÇáÊÑÊíÈ";
$pref_colstr["field"] = "ÇáÍŞá";
$pref_col_label['c'] = "ÒÑ ÇÎÊíÇÑ";
$pref_col_label['a'] = "ãáİÇÊ ãÑİŞÉ";
$pref_col_label['m'] = "ÚáÇãÇÊ/ÃæÖÇÚ";

$sort_fields=array("DATE"=>"ÇáÊÇÑíÎ", "SUBJECT"=>"ÇáãæÖæÚ", "SIZE"=>"ÇáÍÌã");
$sort_orders=array("ASC"=>"ÊÕÇÚÏí", "DESC"=>"ÊäÇÒáí");

$prefsButtonStrings = array( 0=> "ÓÌá ÇáÊÛííÑ", 1=>"äİÏ", 2=> "ÃáÛ", 3=> "ÇáæÖÚ ÇáÇÚÊíÇÏí");

$prefs_new_user = "íÈÏæ Ãäß ÊÓÊÚãá ÇáÈÑäÇãÌ áÃæá ãÑÉ... ãÑÍÈÇ !<br>";
$prefs_new_user .= "ÇáãÑÌæ ãÑÇÌÚÉ åĞå ÇáÎíÇÑÇÊ, Êã ÇáÖÛØ Úáì \"äİÏ\"";
?>