<?php
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/read_message.inc");


$rmStrings[0] = "нхбг";
$rmStrings[1] = "бЯ";
$rmStrings[2] = "умбб";
$rmStrings[3] = "Усл ЧсугЭ";
$rmStrings[4] = "ЧугЭ";
$rmStrings[5] = "Уфос Чсь";
$rmStrings[6] = "УЬвЧС";
$rmStrings[7] = "хах ЧсбгЧсЩ ШслЩ HTML. ";
$rmStrings[8] = "Уфоб хфЧ собЧСЪхЧ";
$rmStrings[9] = "убЬк";
$rmStrings[10] = "ЭЬу";
$rmStrings[11] = "лэб уобцС";
$rmStrings[12] = "уксцуЧЪ ЪофэЩ";
$rmStrings[13] = "УШсл кф гШЧу";
$rmStrings[14] = "бЯ ксь Чспс";
$rmStrings[15] = "соЯ бЯЯЪ ксь хах ЧсгЧсЩ";
$rmStrings[16] = "ЧиШк";

?>