<?php
/********************************************************
	lang/eng/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/search_errors.inc");

$searchErrors["field"] = "ЦзМгя гАхмк шМя умМм : Цгои гАхмк шМя умМми";
$searchErrors["empty"] = "ЦзМгя гАхмк шМя умМм : мчА гАхмк щгяш";
$searchErrors["date"] = "ЦзМгя гАхмк шМя умМм : гАялга еонгА гАйгяМн";
?>