<?php
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/tool.inc");

$toolStrings["folders"] = "ใแÝวส";
$toolStrings["inbox"] = "วแศัํฯ วแๆวัฯ";
$toolStrings["compose"] = "ัำวแษ ฬฯํฯษ";
$toolStrings["calendar"] = "ใÝ฿ัษ";
$toolStrings["contacts"] = "ฺไวๆํไ";
$toolStrings["bookmarks"] = "ๆีÜแวส";
$toolStrings["search"] = "ศอห";
$toolStrings["prefs"] = "ฮํวัวส";
$toolStrings["logout"] = "ฮัๆฬ";
$toolStrings["go"] = "ละๅศ";

?>