<?php
/********************************************************
	lang/si/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Oznaèbe";
$bmStrings["identities"] = "Identitete";
$bmStrings["edit"] = "Urejanje";
$bmStrings["name"] = "Ime";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Kategorija";
$bmStrings["other"] = "Drugo ...";
$bmStrings["comments"] = "Komentarji";
$bmStrings["add"] = "Dodajanje";
$bmStrings["new"] = "Nov vnos";
$bmStrings["edit_url"] = "Urejanje vnosa";
$bmStrings["delete"] = "Brisanje";

$bmError[1] = "Zahtevano polje je URL ali Ime";
$bmError[2] = "Ta možnost je bila izkljuèena.";
?>