<?php
/********************************************************
	lang/si/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Dodajanje urnika";
$calStr["edit_schedule"] = "Urejanje urnika";
$calStr["weekof"] = "Teden: %d";
$calStr["title"] = "Naslov:";
$calStr["color"] = "Barva:";
$calStr["colors"] = array("#990000"=>"Temnordeèa", "#FF0000"=>"Rdeèa", "#000099"=>"Temnomodra", "#0000FF"=>"Modra", 
					"#006600"=>"Temnozelena", "#00FF00"=>"Zelena", "#9900FF"=>"Violièna", "#00FFFF"=>"Cyan",
					"#FF6600"=>"Oranžna", "#FFFF00"=>"Rumena", "#FF00FF"=>"Magenta", ""=>"Brez barve");
$calStr["starts"] = "Se zaène ob:";
$calStr["ends"] = "Se konèa ob:";
$calStr["from"] = "od:";
$calStr["until"] = "do:";
$calStr["repeat_on"] = "Ponavljaj";
$calStr["of"] = "vsakih";
$calStr["weeks"] = array(1=>"prvi teden", 2=>"drugi teden", 3=>"tretji teden", 4=>"èetrti teden"); 
$calStr["week_blurb"] = "...vsakega meseca (do konènega datuma).<br>Ponavljalo se bo vsak teden, èe ni nobeden izbran..";
$calStr["monthly"] = "Ponavljaj meseèno";
$calStr["yearly"] = "Ponavljaj letno";
$calStr["place"] = "Mesto:";
$calStr["description"] = "Opis:";
$calStr["add"] = "Dodajanje";
$calStr["update"] = "Obnavljanje";
$calStr["Delete"] = "Izbris";
$calStr["go"] = "Pojdi";
$calStr["disabled"] = "Možnost koledarja je izkljuèena";
?>