<?php
/********************************************************
	lang/si/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/compose.inc");

$composeHStrings[0] = "Tema";
$composeHStrings[1] = "Od";
$composeHStrings[2] = "Za";
$composeHStrings[3] = "CC";
$composeHStrings[4] = "BCC";
$composeHStrings[5] = "Datum";


$composeStrings[0] = "Sestavi sporoèilo";
$composeStrings[1] = "Pošlji sporoèilo";
$composeStrings[2] = "Naloži datoteko";
$composeStrings[3] = "Priloži podpis";
$composeStrings[4] = "Priloži";
$composeStrings[5] = "Stiki";
$composeStrings[6] = "Skrij stike";
$composeStrings[7] = "Besedilo sporoèila:";
$composeStrings[8] = "Dodaj";
$composeStrings[9] = "Dne %d, je %s napisal(a):\n";
$composeStrings[10] = "--- Izvirno sporoèilo ---\n";
$composeStrings[11] = "Zapri okno";

$composeStrings[12] = "Preveri èrkovanje";
$composeStrings[13] = "Popravi èrkovanje";
$composeStrings[14] = "Brez sprememb";
$composeStrings[15] = "Možne napake v èrkovanju";
$composeStrings[16] = "Sprememba èrkovanja";
$composeStrings[17] = "ignoriraj";
$composeStrings[18] = "izbriši";

$composeStrings["title"] = "Sestavljanje sporoèila";

$composeErrors[0] = "Polje Naslov je prazno. Prosim, vpišite temo ali kliknite \"".$composeStrings[1]."\" ponovno, da pošljete sporoèilo.";
$composeErrors[1] = "Polje \"from\" je prazno. Prosim, vpišite svoj naslov elektronske pošte.";
$composeErrors[2] = "Polje \"To\" je prazno. Prosim, vpišite naslovnikov naslov elektronske pošte.";
$composeErrors[3] = "Dodajanje datoteke je spodletelo.";
$composeErrors[4] = "Niè prejetih datotek.";
$composeErrors[5] = "Zaradi zašèite pred spam pošto, le-to lahko pošljete najveè %1 ljudem (%2 skupaj med prijavo) vsakih %3 sekund.";

$composeErrors[6] = "Najdenih ni bilo èrkovnih napak.";
$composeErrors[7] = "Èrkovanje ni na voljo za izbran jezik.";
$composeErrors[8] = "(Uporabljen èrkovalnik je %s)";
?>