<?php
/********************************************************
	lang/si/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/contacts.inc");

$cStrings[0] = "Stiki";
$cStrings[1] = "Dodaj stik";
$cStrings[2] = " Stik";
$cStrings[3] = "Ime";
$cStrings[4] = "E-pošta";
$cStrings[5] = "URL";
$cStrings[6] = "Skupina";
$cStrings[7] = "Komentarji";
$cStrings[8] = "Dodaj/spremeni stik";
$cStrings[9] = "E-pošta";
$cStrings[10] = "Sestavi";

$cStrings["close"] = "Zapri okno";
$cStrings["addto"] = "Dodaj stike v %s";
$cStrings["showgrp"] = "Pokaži %s";
$cStrings["all"] = "Vse";
$cStrings["instructions"] = "Kliknite na imena za dodajanje. Lahko kliknete tudi na ime skupine, da boste dodali vse èlane skupine.";

$cErrors[0] = "Seznam stikov je prazen.";


?>