<?php
/********************************************************
	lang/si/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Spreminjanje";
$ecStrings[1] = "Dodajanje";
$ecStrings[2] = " Stik";
$ecStrings[3] = "Ime";
$ecStrings[4] = "E-pošta";
$ecStrings[5] = "URL";
$ecStrings[6] = "Skupina";
$ecStrings[7] = "Komentarji";
$ecStrings[8] = "Domaèa telefonska številka";
$ecStrings[9] = "Telefonska številka v službi";
$ecStrings[10] = "Telefon";
$ecStrings[11] = "Naslov";
$ecStrings[12] = "Dodatni naslov e-pošte";
$ecStrings[13] = "Brisanje";
$ecStrings[14] = "Drugo...";


$errors[0] = "Couldn't add contact:  database error.";
$errors[1] = "An entry with the address already exists.";
$errors[2] = "Click ";
$errors[3] = "here";
$errors[4] = " to edit that entry instead.";
$errors[5] = "Contact not found, or access denied.";
$errors[6] = "Are you sure you would like to delete entry for \"";
$errors[7] = "\"?";

?>