<?php
/********************************************************
	lang/si/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/edit_folders.inc");

$efStrings[0] = "Urejanje map";
$efStrings[1] = "Ustvarjanje nove mape";
$efStrings[2] = "Ustvarjanje mape: ";
$efStrings[3] = "Ustvarjanje ";
$efStrings[4] = "Brisanje mape";
$efStrings[5] = "Brisanje";
$efStrings[6] = "Preimenovanje mape";
$efStrings[7] = "Preimenovanje";
$efStrings[8] = "Podpisani imeniki";
$efStrings[9] = "Podpiši";
$efStrings[10] = "Nepodpisani imeniki";
$efStrings[11] = "Ne podpiši";


$errors[0] = "Ustvari mapo: ";
$errors[1] = "Ne morem ustvariti mape: ";
$errors[2] = "Izbrisana mapa: ";
$errors[3] = "Ne morem izbrisati mape: ";
$errors[4] = "Imenik preimenovan: ";
$errors[5] = "Imenika ne morem preimenovati: ";
$errors[6] = "Podpora za mape je navoljo samo pri IMAP raèunih.";

?>