<?php 
/********************************************************
	lang/si/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
//include("../lang/eng/login.inc");

$loginStrings[0]="Uporabniško ime";
$loginStrings[1]="Geslo";
$loginStrings[2]="Strežnik";
$loginStrings[3]="Vrsta";
$loginStrings[4]="Zaèetni imenik";
$loginStrings[5]="Jezik";
$loginStrings[6]="Prijava";

$loginErrors[0]="Neznan naslov.";
$loginErrors[1]="Napaka: \"uploads\" imenika ni bilo mogoèe najti";
$loginErrors[2]="Napaka: \"users\" imenika ni bilo mogoèe najti";
$loginErrors[3]="Napaka: \"sessions\" imenika ni bilo mogoèe najti";

?>