<?php
/********************************************************
	lang/si/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainMessages["delete"] = "Izbris %n sporoèil(a)";
$mainMessages["move"] = "Premik %n sporoèil(a) v %f";

$mainStrings[0] = "Prikazujem %p od %n";
$mainStrings[1] = " najdenih sporoèil";
$mainStrings[2] = "Prejšnje";
$mainStrings[3] = "";
$mainStrings[4] = "Naslednje";
$mainStrings[5] = "";
$mainStrings[6] = "Tema";
$mainStrings[7] = "Za";
$mainStrings[8] = "Od";
$mainStrings[9] = "Datum";
$mainStrings[10] = "Brisanje";
$mainStrings[11] = "Praznjenje smeti";
$mainStrings[12] = "Premikanje";
$mainStrings[13] = "Iskanje";
$mainStrings[14] = "Velikost";
$mainStrings[15] = "neznano";
$mainStrings[16] = "Prikaz";
$mainStrings[17] = "Preverjanje novih";
$mainStrings[18] = "Brisanje vseh";
$mainStrings[19] = "Preklic";
$mainStrings[20] = "Oznaèi kot %b";
$mainStrings[21] = "Brano";
$mainStrings[22] = "Neprebrano";
$mainStrings[23] = "Izberite...";


$mainErrors[0] = "V tej mapi ni najdenih sporoèil";
$mainErrors[1] = "V tej mapi ni sporoèil.";
$mainErrors[2] = "Sporoèil ne morem premakniti v koš.";
$mainErrors[3] = "Sporoèil ne morem oznaèiti kot prebranih.";
$mainErrors[4] = "Sporoèil ne morem premakniti.";
$mainErrors[5] = "Mapa za smeti ni izbrana.";
$mainErrors[6] = "Smeti ne morem izprazniti.";
$mainErrors[7] = "Ste preprièani, da želite izbrisati vsa sporoèila iz mape %f?";
$mainErrors[8] = "Kliknite na pušèice pod kolono sporoèil, da jih premaknete.<br>Ko konèate, preprosto zaprite okno.";



?>