<?php
/********************************************************
	lang/si/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "Identitete";
$piStrings["edit"] = "Urejanje";
$piStrings["name"] = "Ime";
$piStrings["email"] = "E-pošta";
$piStrings["replyto"] = "Odgovor za";
$piStrings["sig"] = "Podpis";
$piStrings["add"] = "Dodajanje";
$piStrings["new"] = "Nova identiteta";
$piStrings["edit_ident"] = "Urejanje identitet";
$piStrings["delete"] = "Brisanje";
$piStrings["setdef"] = "Nastavi na privzeto";
$piStrings["isdef"] = "(Privzeto)";

$piError[1] = "Zahtevano ime ali elektronska pošta.";

?>
