<?php
/********************************************************
	lang/si/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "Vpišite HTML kodo barve za vsako komponento.";
$pcStrings["0.1"] = "Uporabi ";
$pcStrings["0.2"] = "Seznam barv";
$pcStrings["0.3"] = " da najdete prave HTML kode za barve.";
$pcStrings["0.4"] = "Nastavitve, ki jih tema spremeni, ne morejo biti ponastavljene.";
$pcStrings["1.0"] = "Orodna vrstica";
$pcStrings["2.0"] = "Seznam map";
$pcStrings["3.0"] = "Glavno";
$pcStrings["3.1"] = "Glava nazaj: ";
$pcStrings["3.2"] = "Vodilno besedilo: ";
$pcStrings["3.3"] = "Temno ozadje: ";
$pcStrings["3.4"] = "Svetlo besedilo: ";
$pcStrings["4.0"] = "Drugo";
$pcStrings["4.1"] = "Citiranja: ";
$pcStrings["5.0"] = "Pisave";
$pcStrings["5.1"] = "Družina pisave";
$pcStrings["5.2"] = "Velikost pisave: ";
$pcStrings["5.3"] = "Majhna velikost pisave: ";
$pcStrings["5.4"] = "Velikost pisave v menijih: ";
$pcStrings["5.5"] = "Velikost pisave seznama map: ";

							
$pcPortions = array( "Ozadje: ", "Povezave: ", "Besedilo: ", "Oznaæbe: ");

?>
