<?php
/********************************************************
	lang/si/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/read_message.inc");


$rmStrings[0] = "Index";
$rmStrings[1] = "Odgovori";
$rmStrings[2] = "Preusmeri";
$rmStrings[3] = "Obnovi";
$rmStrings[4] = "Izbriši";
$rmStrings[5] = "Premakni";
$rmStrings[6] = "Deli";
$rmStrings[7] = "To je HTML sporoèilo. ";
$rmStrings[8] = "Kliknite tukaj, da ga preberete.";
$rmStrings[9] = "Izvor";
$rmStrings[10] = "Velikost";
$rmStrings[11] = "Neprebrano";
$rmStrings[12] = "Prikaži glavo";
$rmStrings[13] = "Sporoèi spam";
$rmStrings[14] = "Odgovori vsem";
$rmStrings[15] = "Odgovorili ste na to sporoèilo";
$rmStrings[16] = "Natisni";

?>