<?php
/********************************************************
	lang/si/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/tool.inc");

$toolStrings["folders"] = "Mape";
$toolStrings["inbox"] = "Prejeto";
$toolStrings["compose"] = "Sestavljanje sporoèila";
$toolStrings["calendar"] = "Koledar";
$toolStrings["contacts"] = "Stiki";
$toolStrings["bookmarks"] = "Zabeležke";
$toolStrings["search"] = "Iskanje";
$toolStrings["prefs"] = "Nastavitve";
$toolStrings["logout"] = "Odjava";
$toolStrings["go"] = "Pojdi";

?>