<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Favoritos";
$bmStrings["identities"] = "Identidades";
$bmStrings["edit"] = "Editar";
$bmStrings["name"] = "Nome";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Categoria";
$bmStrings["other"] = "Especificar-&gt;";
$bmStrings["comments"] = "Comentários";
$bmStrings["add"] = "Adicionar";
$bmStrings["new"] = "Nova entrada";
$bmStrings["edit_url"] = "Editar entrada";
$bmStrings["delete"] = "Apagar";

$bmError[1] = "Nome e URL necessários";
$bmError[2] = "Esta função foi desativada pelo Administrador.";
?>
