<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Adicionar Compromisso";
$calStr["edit_schedule"] = "Editar Compromisso";
$calStr["weekof"] = "Semana de: %d";
$calStr["title"] = "Titulo:";
$calStr["color"] = "Cor:";
$calStr["colors"] = array("#990000"=>"Vermelho escuro", "#FF0000"=>"Vermelho", "#000099"=>"Azul escuro", "#0000FF"=>"Azul", 
					"#006600"=>"Verde escuro", "#00FF00"=>"Verde", "#9900FF"=>"Purpura", "#00FFFF"=>"Ciano",
					"#FF6600"=>"Laranja", "#FFFF00"=>"Amarelo", "#FF00FF"=>"Magenta", ""=>"Sem cor");
$calStr["starts"] = "Começa a:";
$calStr["ends"] = "Acaba a:";
$calStr["from"] = "de:";
$calStr["until"] = "até:";
$calStr["repeat_on"] = "Repetir em";
$calStr["of"] = "de todos";
$calStr["weeks"] = array(1=>"primeira semana", 2=>"segunda semana", 3=>"terceira semana", 4=>"quarta semana"); 
$calStr["week_blurb"] = "...de todos os meses (até à data).<br>Vai-se repetir todas as semanas se nada for selecionado.";
$calStr["monthly"] = "Repetir mensalmente";
$calStr["yearly"] = "Repetir anualmente";
$calStr["place"] = "Local:";
$calStr["description"] = "Descrição:";
$calStr["add"] = "Adicionar";
$calStr["update"] = "Actualizar";
$calStr["Delete"] = "Apagar";
$calStr["go"] = "Ir";
$calStr["disabled"] = "Esta função foi desativada pelo Administrador.";
?>
