<?php

// TRANSLATORS: bla bla :D
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/pt/compose.inc
	(C)2003 Darwings <darwings@lisboa.alface.de || asas@netcabo.pt>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "Assunto";
$composeHStrings[1] = "De";
$composeHStrings[2] = "Para";
$composeHStrings[3] = "CC";
$composeHStrings[4] = "BCC";
$composeHStrings[5] = "Data";


$composeStrings[0] = "Compor Mensagem";
$composeStrings[1] = "Enviar Mensagem";
$composeStrings[2] = "Enviar Ficheiro";
$composeStrings[3] = "Adicionar Assinatura";
$composeStrings[4] = "Adicionar";
$composeStrings[5] = "Mostrar Contactos";
$composeStrings[6] = "Esconder Contactos";
$composeStrings[7] = "Corpo da Mensagem:";
$composeStrings[8] = "Adicionar";
$composeStrings[9] = "Em %d, %s escreveu:\n";
$composeStrings[10] = "--- Mensagem Original ---\n";
$composeStrings[11] = "Fechar Janela";

$composeStrings[12] = "Verificar ortografia";
$composeStrings[13] = "Corrigir";
$composeStrings[14] = "Não alterar";
$composeStrings[15] = "Possiveis erros de ortografia";
$composeStrings[16] = "Ortografia corrigida";
$composeStrings[17] = "Ignorar";
$composeStrings[18] = "Apagar";

$composeStrings["title"] = "Compor Mensagem";

$composeErrors[0] = "O campo \"Assunto\" está vazio. Por favor introduza um Assunto ou carregue em \"".$composeStrings[1]."\" outra vez para enviar.";
$composeErrors[1] = "O campo \"De\" está vaizio. Por favor introduza o seu endereço de email.";
$composeErrors[2] = "O campo \"Para\" está vazio. Por favor especifique o endereço do destinatário.";
$composeErrors[3] = "Falhou o envio do ficheiro";
$composeErrors[4] = "Nenhum ficheiro recebido.";
$composeErrors[5] = "Para prevenir o Spam, voçê apenas pode enviar para %1 pessoa (%2 total por sessão) todos os %3 segundos.";

$composeErrors[6] = "Nenhuns erros de ortografia encontrados.";
$composeErrors[7] = "Correção ortográfica não disponível para a língua selecionada por favor contacte o Administrador.";
$composeErrors[8] = "(Dicionario de %s usado)";
?>