<?php

// TRANSLATORS: Bla Bla :D
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/pt/contacts.inc
	(C)2003 Darwings <darwings@lisboa.alface.de || asas@netcabo.pt>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Contactos";
$cStrings[1] = "Adicionar Contacto";
$cStrings[2] = " Contacto";
$cStrings[3] = "Nome";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Grupo";
$cStrings[7] = "Comentários";
$cStrings[8] = "Adicionar/Editar Contacto";
$cStrings[9] = "Email";
$cStrings[10] = "Compor";

$cStrings["close"] = "Fechar Janela";
$cStrings["addto"] = "Adicionar contactos ao %s";
$cStrings["showgrp"] = "Mostrar %s";
$cStrings["all"] = "Todos";
$cStrings["instructions"] = "Carregar nos nomes para adicionar. Tambem pode carregar na etiqueta do grupo para adicionar todos os membros do mesmo.";

$cErrors[0] = "A lista de contactos está vazia";


?>
