<?php
include("../lang/eng/cp.inc"); // <-- do not delete
/********************************************************
	lang/pt/cp.inc
	(C)2003 Darwings <darwings@lisboa.alface.de || asas@netcabo.pt>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
?>
<B>Tabela de códigos de cor</B>
