<?php

// TRANSLATORS: Vla Bla :D
include("../lang/eng/defaultFolders.inc"); // <-- do not delete
/********************************************************
	lang/pt/defaultFolders.inc
	(C)2003 Darwings <darwings@lisboa.alface.de || asas@netcabo.pt>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

	$sentbox=$my_prefs["sent_box_name"];
	$trashname=$my_prefs["trash_name"];
	$defaults["INBOX"] = "Entrada";
	$defaults[$sentbox] = "Enviado";
	$defaults[$trashname] = "Lixo";

?>