<?php

// TRANSLATORS: Bla Bla :D
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/pt/edit_contact.inc
	(C)2003 Darwings <darwings@lisboa.alface.de || asas@netcabo.pt>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Editar";
$ecStrings[1] = "Adicionar";
$ecStrings[2] = " Contacto";
$ecStrings[3] = "Nome";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Grupo";
$ecStrings[7] = "Comentários";
$ecStrings[8] = "Telefone de Casa";
$ecStrings[9] = "Telefone de Trabalho";
$ecStrings[10] = "Telefone Móvel";
$ecStrings[11] = "Endereço";
$ecStrings[12] = "Email Alternativo";
$ecStrings[13] = "Apagar";
$ecStrings[14] = "Outro";


$errors[0] = "Impossível adicionar contacto:  Erro na base de dados.";
$errors[1] = "Uma entrada com esse endereço já existe.";
$errors[2] = "Carregue ";
$errors[3] = "aqui";
$errors[4] = " para editar essa entrada.";
$errors[5] = "Contacto não encontrado, ou acesso negado.";
$errors[6] = "Têm a certeza que deseja eliminar a entrada de \"";
$errors[7] = "\"?";

?>
