<?php

// TRANSLATORS: Bla Bla :D
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/pt/edit_folders.inc
	(C)2003 Darwings <darwings@lisboa.alface.de || asas@netcabo.pt>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings[0] = "Gerir Pastas";
$efStrings[1] = "Criar nova pasta";
$efStrings[2] = "Criar Pasta: ";
$efStrings[3] = "Criar";
$efStrings[4] = "Apagar Pasta";
$efStrings[5] = "Apagar";
$efStrings[6] = "Renomear Pasta";
$efStrings[7] = "Renomear";
$efStrings[8] = "Pastas Subscritas";
$efStrings[9] = "Subscrever";
$efStrings[10] = "Dessubscrever Pasta";
$efStrings[11] = "Dessubscrever";


$errors[0] = "Criar Pasta: ";
$errors[1] = "Impossível criar a pasta: ";
$errors[2] = "Pasta apagada: ";
$errors[3] = "Impossível apagar a pasta: ";
$errors[4] = "Pasta renomeada: ";
$errors[5] = "Impossível renomear a pasta: ";
$errors[6] = "Suporte de pastas apenas disponível para contas IMAP.";

?>
