<?php
/********************************************************
        lang/en/login.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Utilizador";
$loginStrings[1]="Password";
$loginStrings[2]="Servidor";
$loginStrings[3]="Tipo";
$loginStrings[4]="Directoria Raiz";
$loginStrings[5]="Língua";
$loginStrings[6]="Ligar";

$loginErrors[0]="Accesso não autorizado";
$loginErrors[1]="Erro: Directoria \"uploads\" não encontrada";
$loginErrors[2]="Erro: Directoria \"users\" não encontrada";
$loginErrors[3]="Erro: Directoria \"sessions\" não encontrada";

?>