<?php

// TRANSLATORS: Bla Bla :D
include("../lang/eng/main.inc"); // <-- do not delete
/********************************************************
	lang/pt/main.inc
	(C)2003 Darwings <darwings@lisboa.alface.de || asas@netcabo.pt>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$mainMessages["delete"] = "Apagada(s) %n mensagem(ns)";
$mainMessages["move"] = "Movida(s) %n mensagem(ns) para %f";


$mainStrings[0] = "Mostrando %p de %n";
$mainStrings[1] = " meensagens encontradas";
$mainStrings[2] = "Anteriores";
$mainStrings[3] = "";
$mainStrings[4] = "Próximas";
$mainStrings[5] = "";
$mainStrings[6] = "Assunto";
$mainStrings[7] = "Para";
$mainStrings[8] = "De";
$mainStrings[9] = "Data";
$mainStrings[10] = "Apagar";
$mainStrings[11] = "Eliminar Lixo";
$mainStrings[12] = "Mover";
$mainStrings[13] = "Procurar";
$mainStrings[14] = "Tamanho";
$mainStrings[15] = "Sem Título";
$mainStrings[16] = "Mostrar";
$mainStrings[17] = "Verificar Correio";
$mainStrings[18] = "Apagar todas";
$mainStrings[19] = "Cancelar";
$mainStrings[20] = "Marcar como %b";
$mainStrings[21] = "Lida";
$mainStrings[22] = "Por ler";


$mainErrors[0] = "Não foram encontradas mensagens nesta pasta";
$mainErrors[1] = "Não há mensagens nesta pasta";
$mainErrors[2] = "Não foi possível mover mensagens para o lixo.";
$mainErrors[3] = "Não foi possível marcar mensagens como apagadas.";
$mainErrors[4] = "Não foi possível mover as mensagens.";
$mainErrors[5] = "Pasta de lixo não especificada.";
$mainErrors[6] = "Não foi possível esvaziar o lixo";
$mainErrors[7] = "Têm a certeza que deseja apagar TODAS as mensagens que estão em %f?";
$mainErrors[8] = "Carregue nas setas por baixo do cabeçalho das colunas para as mover.<br>Quando estiver pronto simplesmente feche a janela.";

?>
