<?php

// TRANSLATORS: Bla Bla :D
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "Identidades";
$piStrings["edit"] = "Editar";
$piStrings["name"] = "Nome";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "Responder para";
$piStrings["sig"] = "Assinatura";
$piStrings["add"] = "Adicionar";
$piStrings["new"] = "Nova Identidade";
$piStrings["edit_ident"] = "Editar Identidade";
$piStrings["delete"] = "Apagar";
$piStrings["setdef"] = "Defenir como principal";
$piStrings["isdef"] = "(Defeito)";

$piError[1] = "Nome e email necessários";

?>
