<?php

// Translators: Bla Bla :D
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/pt/cp.inc
	(C)2003 Darwings <darwings@lisboa.alface.de || asas@netcabo.pt>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "Introduza um código de cor em HTML para cada componente.";
$pcStrings["0.1"] = "Use a ";
$pcStrings["0.2"] = "Tabela de códigos de cor";
$pcStrings["0.3"] = " para achar os códigos de cor certos.";
$pcStrings["0.4"] = "As defenições defenidas no tema não podem ser sobrepostas.";
$pcStrings["1.0"] = "Barra de ferramentas";
$pcStrings["2.0"] = "Lista de Pastas";
$pcStrings["3.0"] = "Príncipal";
$pcStrings["3.1"] = "Heading Back";
$pcStrings["3.2"] = "Texto do Cabeçalho";
$pcStrings["3.3"] = "Fundo escuro: ";
$pcStrings["3.4"] = "Texto claro: ";
$pcStrings["4.0"] = "Pormenores";
$pcStrings["4.1"] = "Transcrições";
$pcStrings["5.0"] = "Letras";
$pcStrings["5.1"] = "Família de letras";
$pcStrings["5.2"] = "Tamanho da letra";
$pcStrings["5.3"] = "Tamanho de letra pequena";
$pcStrings["5.4"] = "Tamanho da letra do Menu";
$pcStrings["5.5"] = "Tamanho da fonte da lista de pastas";

							
$pcPortions = array( "Fundo: ", "Links: ", "Texto: ", "Realçar: ");

?>
