<?php

// TRANSLATORS: Bla Bla :D
include("../lang/eng/quota.inc"); // <-- do not delete
/********************************************************
	lang/pt/quota.inc
	(C)2003 Darwings <darwings@lisboa.alface.de || asas@netcabo.pt>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$quotaStr["label"] = "Utilizaчуo do disco: ";
$quotaStr["full"] = "%utilizadoKB/%totalKB (%livre% livre)";
$quotaStr["unknown"] = "desconhecido";

?>