<?php

// TRANSLATORS: Bla Bla :D
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/pt/read_message.inc
	(C)2003 Darwings <darwings@lisboa.alface.de || asas@netcabo.pt>>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/


$rmStrings[0] = "Indíce";
$rmStrings[1] = "Responder";
$rmStrings[2] = "Reenviar";
$rmStrings[3] = "Anular Apagar";
$rmStrings[4] = "Apagar";
$rmStrings[5] = "Mover";
$rmStrings[6] = "Partes";
$rmStrings[7] = "Isto é uma mensagem em HTML. ";
$rmStrings[8] = "Carregue aqui para a ler.";
$rmStrings[9] = "Código";
$rmStrings[10] = "Tamanho";
$rmStrings[11] = "Não lido";
$rmStrings[12] = "Mostrar Cabeçalho";
$rmStrings[13] = "Denunciar Spam";
$rmStrings[14] = "Responder a Todos";
$rmStrings[15] = "Já respondeu a esta mensagem";
$rmStrings[16] = "Imprimir";

?>
