<?php

// TRANSLATORS: Bla Bla :D
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/pt/search_errors.inc
	(C)2003 Darwings <darwings@lisboa.alface.de || asas@netcabo.pt>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "Critério de procura inválido:  Campo inválido";
$searchErrors["empty"] = "Critério de procura inválido:  Campo de procura vazio";
$searchErrors["date"] = "Critério de procura inválido:  Data não especificada";

?>