<?php

// TRANSLATORS: Bla Bla :D
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/pt/tool.inc
	(C)2003 Darwings <darwings@lisboa.alface.de || asas@netcabo.pt>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "Pastas";
$toolStrings["inbox"] = "Entrada";
$toolStrings["compose"] = "Compor";
$toolStrings["calendar"] = "Calendário";
$toolStrings["contacts"] = "Contactos";
$toolStrings["search"] = "Procurar";
$toolStrings["prefs"] = "Preferências";
$toolStrings["logout"] = "Sair";
$toolStrings["go"] = "Ir";
$toolStrings["bookmarks"] = "Favoritos";

?>
