<?php 	 
//---------------------------------------------------------
// index.php
//---------------------------------------------------------
define('TXT_INDEX_TITLE', 'Your ZPanel account is active!');
define('TXT_INDEX_HOSTING_SPACE', 'Your hosting space is ready...');
define('TXT_INDEX_HOSTING_SPACE2', 'Your web hosting space is now active and ready to be used.');
define('TXT_INDEX_GET_STARTED', 'To get started');
define('TXT_INDEX_LOGIN_ACCOUNT', 'Login to your ZPanel account');
define('TXT_INDEX_FTP_ACCOUNT', 'Create an FTP account');
define('TXT_INDEX_REPLACE_INDEX', 'Replace or delete this file (index.php)');
define('TXT_INDEX_THANK_HOSTING', 'Thank you for using ZPanel to manage your hosting!');
define('TXT_INDEX_INFORMATION_VISIT', 'For more infomation and help using ZPanel please visit');
define('TXT_INDEX_KIND_REGARDS', 'Kind regards');
define('TXT_INDEX_HOSTING_COMPANY', 'Your hosting company');
define('TXT_INDEX_POWERED_BY', 'Powered by');
define('TXT_INDEX_HOSTING_LEVEL', 'Taking hosting to the next level');
//---------------------------------------------------------
// 403.php
//---------------------------------------------------------
define('TXT_403_404_500_510', 'and');
define('TXT_403_TITLE', 'Error 403 - Access Forbidden');
define('TXT_403_AUTHORISED_DIRECTORY', 'You are not authorised to view this page or directory....');
define('TXT_403_FOLLOWING_REASONS', 'This may be due to the following reasons');
define('TXT_403_RETYPE_SERVER_DIRECTORY', 'The web server is setup to disable directory listings.');
define('TXT_403_USER_PASSWORD', 'You supplied an incorrect user/password when attempting to browse this area.');
define('TXT_403_CONTACT_ADMINISTRATOR', 'If you believe you are getting this error message by mistake, please contact the website administrator.');
define('TXT_403_ERROR_GENERATED', 'Error message generated by');
define('TXT_403_HOSTING_PANEL', 'Hosting Panel');
//---------------------------------------------------------
// 404.php
//---------------------------------------------------------
define('TXT_404_TITLE', 'Error 404 - Page not found!');
define('TXT_404_FILE_NOTFOUND', 'The requested file or directory was not found!');
define('TXT_404_RECENTLY_RENAMED', 'The page or directory has recently been moved or renamed.');
define('TXT_404_TEMPORARILY_AVALIABLE', 'The page or directory is temporarily not avaliable.');
define('TXT_404_ADDRESS_AGAIN', 'The address to this content may not be correct, please check the address and try again.');
define('TXT_404_BROWSER', 'Try using the browser\'s <a href="javascript:history.back(1);">back</a> button or try the');
define('TXT_404_HOME', 'home page');
//---------------------------------------------------------
// 500.php
//---------------------------------------------------------
define('TXT_500_TITLE', 'Error 500 - Internal Server Error');
define('TXT_500_UNABLE_REQUEST', 'The server encountered a problem and was unable to fulfill the request.');
define('TXT_505_CONFIGURATION', 'A misconfiguration in the application server\'s configuration.');
define('TXT_CPANELX_LOGIN', 'Log in');
define('TXT_CPANELX_LOGIN', 'Log in');
define('TXT_CPANELX_LOGIN', 'Log in');
//---------------------------------------------------------
// 510.php
//---------------------------------------------------------
define('TXT_510_TITLE', 'Error 510 - Not Extended');
define('TXT_510_USAGE_LIMIT', 'High Usage Limit...');
define('TXT_510_VOLUME_USAGE', 'The site is experiencing  high volume usage');
define('TXT_510_TEMPORARILY_EXCEEDED', 'Connection limit for the site has been temporarily exceeded');
define('TXT_510_BANDWIDTH_LIMIT', 'Bandwidth limit for the site has been temporarily exceeded');
define('TXT_510_MINUTES_AGAIN', 'You may wait a few minutes and try your request again, when site resources are available again');
//---------------------------------------------------------
//---------------------------------------------------------
// END
//---------------------------------------------------------
 	 
?>