<?php
/********************************************************
	lang/se/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Bokmärken";
$bmStrings["identities"] = "Identiteter";
$bmStrings["edit"] = "Redigera";
$bmStrings["name"] = "Namn";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Kategori";
$bmStrings["other"] = "Specificera-&gt;";
$bmStrings["comments"] = "Kommentarer";
$bmStrings["add"] = "Lägg till";
$bmStrings["new"] = "Ny post";
$bmStrings["edit_url"] = "Redigera post";
$bmStrings["delete"] = "Ta bort";

$bmError[1] = "Namn eller URL krävs";
$bmError[2] = "Denna funktion är ej aktiverad.";

?>
