<?php
/********************************************************
	lang/se/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Lägg till schema";
$calStr["edit_schedule"] = "Redigera schema";
$calStr["weekof"] = "Vecka: %d";
$calStr["title"] = "Titel:";
$calStr["color"] = "Färg:";
$calStr["colors"] = array("#990000"=>"Mörkröd", "#FF0000"=>"Röd", "#000099"=>"Mörkblå", 	"#0000FF"=>"Blå", "#006600"=>"Mörkgrön", "#00FF00"=>"Grön", #9900FF"=>"Lila", "#00FFFF"=>"Cyan", "#FF6600"=>"Orange", "#FFFF00"=>"Gul", "#FF00FF"=>"Magenta", ""=>"Ingen färg");
$calStr["starts"] = "Börjar den:";
$calStr["ends"] = "Slutar den:";
$calStr["from"] = "från:";
$calStr["until"] = "till:";
$calStr["repeat_on"] = "Upprepa på";
$calStr["of"] = "av varje";
$calStr["weeks"] = array(1=>"första veckan", 2=>"andra veckan", 3=>"tredje veckan", 4=>"fjärde veckan"); 
$calStr["week_blurb"] = "...varje månad(till slutdatum).<br>Upprepas varje vecka om ingen valts.";
$calStr["monthly"] = "Repetera månatligen";
$calStr["yearly"] = "Repetera årligen";
$calStr["place"] = "Plats:";
$calStr["description"] = "Beskrivning:";
$calStr["add"] = "Lägg till";
$calStr["update"] = "Uppdatera";
$calStr["Delete"] = "Ta bort";
$calStr["go"] = "Gå";
$calStr["disabled"] = "Kalenderfunktionen är ej aktiverad.";

?>