<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/se/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$composeHStrings[0] = "Ämne";
$composeHStrings[1] = "Från";
$composeHStrings[2] = "Till";
$composeHStrings[3] = "Kopia";
$composeHStrings[4] = "Hemlig kopia";
$composeHStrings[5] = "Datum";


$composeStrings[0] = "Skriv Meddelande";
$composeStrings[1] = "Skicka Meddelande";
$composeStrings[2] = "Ladda up";
$composeStrings[3] = "Bifoga Signatur";
$composeStrings[4] = "Bifoga";
$composeStrings[5] = "Visa kontakter";
$composeStrings[6] = "Göm kontakter";
$composeStrings[7] = "Meddelande:";
$composeStrings[8] = "Lägg till";
$composeStrings[9] = "Den %d, skrev %s:\n";
$composeStrings[10] = "--- Ursprungligt meddelande ---\n";
$composeStrings[11] = "Stäng fönster";

$composeStrings[12] = "Kontrollera stavning";
$composeStrings[13] = "Korrigera stavning";
$composeStrings[14] = "Inga ändringar";
$composeStrings[15] = "Möjliga stavfel";
$composeStrings[16] = "Ändringar";
$composeStrings[17] = "ignorera";
$composeStrings[18] = "ta bort";

$composeStrings["title"] = "Skriv meddelande";


$composeErrors[0] = "Ämnesfältet är tomt. Skriv in ett ämne, eller klicka på \"".$composeStrings[1]."\" igen för att skicka.";
$composeErrors[1] = "\"Från\" fältet är tomt.  Skriv in din email adress.";
$composeErrors[2] = "\"Till\" fältet är tomt.  Ange mottagare.";
$composeErrors[3] = "Uppladdningen misslyckades";
$composeErrors[4] = "Inga filer mottagna.";
$composeErrors[5] = "För att motverka spam, kan du bara skicka till %1 mottagare (%2 totalt per session) var %3 sekund.";

$composeErrors[6] = "Inga stavfel hittades.";
$composeErrors[7] = "Stavningskontroll är ej tillgänglig för valt språk.";
$composeErrors[8] = "(%s ordbok används)";

?>