<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/se/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$cStrings[0] = "Kontakter";
$cStrings[1] = "Lägg till kontakt";
$cStrings[2] = " Kontakt";
$cStrings[3] = "Namn";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Grupp";
$cStrings[7] = "Kommentarer";
$cStrings[8] = "Lägg till/Ändra Kontakt";
$cStrings[9] = "Email";
$cStrings[10] = "Skriv";

$cStrings["close"] = "Stäng fönster";
$cStrings["addto"] = "Lägg till kontakter i %s";
$cStrings["showgrp"] = "Visa %s";
$cStrings["all"] = "Alla";
$cStrings["instructions"] = "Klicka på namnen du vill lägga till. Du kan även klicka på en grupp för att lägga till alla i gruppen.";

$cErrors[0] = "Kontaktlistan är tom";


?>