<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
	lang/se/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/
$lang_months[1] = "Januari";
$lang_months[2] = "Februari";
$lang_months[3] = "Mars";
$lang_months[4] = "April";
$lang_months[5] = "Maj";
$lang_months[6] = "Juni";
$lang_months[7] = "Juli";
$lang_months[8] = "Augusti";
$lang_months[9] = "September";
$lang_months[10] = "Oktober";
$lang_months[11] = "November";
$lang_months[12] = "December";

$lang_datetime["short_mon"][1] = "Jan";
$lang_datetime["short_mon"][2] = "Feb";
$lang_datetime["short_mon"][3] = "Mar";
$lang_datetime["short_mon"][4] = "Apr";
$lang_datetime["short_mon"][5] = "Maj";
$lang_datetime["short_mon"][6] = "Jun";
$lang_datetime["short_mon"][7] = "Jul";
$lang_datetime["short_mon"][8] = "Aug";
$lang_datetime["short_mon"][9] = "Sep";
$lang_datetime["short_mon"][10] = "Okt";
$lang_datetime["short_mon"][11] = "Nov";
$lang_datetime["short_mon"][12] = "Dec";

$lang_datetime["dsow"][0] = "Sön";
$lang_datetime["dsow"][1] = "Mån";
$lang_datetime["dsow"][2] = "Tis";
$lang_datetime["dsow"][3] = "Ons";
$lang_datetime["dsow"][4] = "Tor";
$lang_datetime["dsow"][5] = "Fre";
$lang_datetime["dsow"][6] = "Lör";

$lang_datetime["dsowl"][0] = "Söndag";
$lang_datetime["dsowl"][1] = "Måndag";
$lang_datetime["dsowl"][2] = "Tisdag";
$lang_datetime["dsowl"][3] = "Onsdag";
$lang_datetime["dsowl"][4] = "Torsdag";
$lang_datetime["dsowl"][5] = "Fredag";
$lang_datetime["dsowl"][6] = "Lördag";


$lang_datetime["dsow_short"] = array("S", "M", "T", "O", "T", "F", "L");
$lang_datetime["today"] = "Idag %t";		//e.g. "Today 12:02"
$lang_datetime["lastweek"] = "%w %t";		//e.g. "Wed 12:00"
$lang_datetime["thisyear"] = "%m/%d";		//e.g. "2/13"
$lang_datetime["prevyears"] = "%m/%d/%y"; 	//e.g. "1/1/2100"
$lang_datetime["monthyear"] = "%m %y";		//e.g. "January 2002"
$lang_datetime["verbal"] = "%m %d, %y";  	//e.g. "Jan 1, 1900"
$lang_datetime["verbal_short"] = "%m %d";  	//e.g. "Jan 1"
$lang_datetime["hour_system"] = 24;		// 12 or 24
$lang_datetime["ampm"]["am"] = "am";
$lang_datetime["ampm"]["pm"] = "pm";
$lang_datetime["time_format"] = "%h:%m%a";	// %h=hour, %m=minutes, %a="am:pm"
$lang_datetime["hour_format"] = "%h%a";

?>