<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/se/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$efStrings[0] = "Hantera Mappar";
$efStrings[1] = "Skapa ny mapp";
$efStrings[2] = "Skapa mapp: ";
$efStrings[3] = "Skapa";
$efStrings[4] = "Ta bort mapp";
$efStrings[5] = "Ta bort";
$efStrings[6] = "Döpa om mapp";
$efStrings[7] = "Döpa om";
$efStrings[8] = "Prenumererade Mappar";
$efStrings[9] = "Prenumerera";
$efStrings[10] = "Ej Prenumererade Mappar";
$efStrings[11] = "Säg upp prenumeration";


$errors[0] = "Skapa mapp: ";
$errors[1] = "Kunde inte skapa mapp: ";
$errors[2] = "Ta bort mapp: ";
$errors[3] = "Kunde inte ta bort mapp: ";
$errors[4] = "Omdöpt mapp: ";
$errors[5] = "Kunde inte döpa om mapp: ";
$errors[6] = "Mappar är endast tillgängliga för IMAP-konton.";

?>