<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/se/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$ecStrings[0] = "Ändra";
$ecStrings[1] = "Lägg till";
$ecStrings[2] = " Kontakt";
$ecStrings[3] = "Namn";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Grupp";
$ecStrings[7] = "Kommentarer";
$ecStrings[8] = "Hemtelefon";
$ecStrings[9] = "Arbetstelefon";
$ecStrings[10] = "Mobiltelefon";
$ecStrings[11] = "Address";
$ecStrings[12] = "Alt. Email";
$ecStrings[13] = "Ta bort";
$ecStrings[14] = "Andra";


$errors[0] = "Kunde inte lägga till kontakt:  databasfel.";
$errors[1] = "En annan kontakt med samma adress finns redan";
$errors[2] = "Klicka ";
$errors[3] = "här";
$errors[4] = " för att redigera kontakten istället.";
$errors[5] = "Hittades ej, eller åtkomst nekad.";
$errors[6] = "Är du säker på att du vill ta bort posten för \"";
$errors[7] = "\"?";

?>