<?php
include("../lang/eng/folders.inc"); // <-- do not delete
/********************************************************
	lang/se/folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

	$fl_str["folders"] = "Mappar";
	$fl_str["manage"] = "Hantera Mappar";

	$sentbox=$my_prefs["sent_box_name"];
	$trashname=$my_prefs["trash_name"];
	$defaults["INBOX"] = "Inkorg";
	$defaults[$sentbox] = "Skickade";
	$defaults[$trashname] = "Skräp";
	$fstr["reload"] = "ladda om";
	$fstr["expunge"] = "ta bort";

?>