<?php
include("../lang/eng/main.inc"); // <-- do not delete
/********************************************************
	lang/se/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$mainMessages["delete"] = "Ta bort %n meddelande(n)";
$mainMessages["move"] = "Flyttade %n meddelande(n) till %f";

$mainStrings[0] = "Visar %p av %n";
$mainStrings[1] = " meddelande funna";
$mainStrings[2] = "förra";
$mainStrings[3] = " med.";
$mainStrings[4] = "Nästa";
$mainStrings[5] = " med.";
$mainStrings[6] = "Ämne";
$mainStrings[7] = "Till";
$mainStrings[8] = "Från";
$mainStrings[9] = "Datum";
$mainStrings[10] = "Ta bort";
$mainStrings[11] = "Töm Skräp";
$mainStrings[12] = "Fil";
$mainStrings[13] = "Sök";
$mainStrings[14] = "Storlek";
$mainStrings[15] = "namnlös";
$mainStrings[16] = "Visa";
$mainStrings[17] = "Titta efter ny";
$mainStrings[18] = "Ta bort alla";
$mainStrings[19] = "Avbryt";
$mainStrings[20] = "Markera som %b";
$mainStrings[21] = "Läst";
$mainStrings[22] = "Oläst";
$mainStrings[23] = "Välj...";

$mainErrors[0] = "Inga meddelande hittade i denna mapp";
$mainErrors[1] = "Inga meddelande i denna mapp";
$mainErrors[2] = "Kunde inte flytta meddelanden till skräpmappen.";
$mainErrors[3] = "Kunde inte markera meddelanden som raderade.";
$mainErrors[4] = "Kunde inte flytta meddelanden.";
$mainErrors[5] = "Skräp-mapp ej angiven.";
$mainErrors[6] = "Kunde inte tömma skräpmappen";
$mainErrors[7] = "Är du säker på att du vill ta bort ALLA meddelanden i %f?";
$mainErrors[8] = "Klicka på pilarna under kolumntitlarna för att flytta dem.<br>Stäng fönstret när du är färdig.";



?>