<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/se/pref_colors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$pcStrings["0"] = "Ange en HTML färgkod för varje komponent.";
$pcStrings["0.1"] = "Använd ";
$pcStrings["0.2"] = "Färgkodstabell";
$pcStrings["0.3"] = " för att hitta rätt färgkoder.";
$pcStrings["0.4"] = "Inställningar som sätts av temat kan ej modifieras.";
$pcStrings["1.0"] = "Verktygsfält";
$pcStrings["2.0"] = "Mapplista";
$pcStrings["3.0"] = "Huvud";
$pcStrings["3.1"] = "Titel Bakgrund: ";
$pcStrings["3.2"] = "Titel Text: ";
$pcStrings["3.3"] = "Mörk Bakgrund: ";
$pcStrings["3.4"] = "Ljus text: ";
$pcStrings["4.0"] = "Övriga";
$pcStrings["4.1"] = "Citeringar: ";
$pcStrings["5.0"] = "Fonter";
$pcStrings["5.1"] = "Fontfamilj";
$pcStrings["5.2"] = "Fontstorlek: ";
$pcStrings["5.3"] = "Liten Fontstorlek: ";
$pcStrings["5.4"] = "Fontstorlek i menyer: ";
$pcStrings["5.5"] = "Fontstorlek i mapplistan: ";

							
$pcPortions = array( "Bakgrund: ", "Länkar: ", "Text: ", "Markering: ");

?>
