<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/se/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$piStrings["identities"] = "Identiteter";
$piStrings["edit"] = "Redigera";
$piStrings["name"] = "Namn";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "Svara till";
$piStrings["sig"] = "Signatur";
$piStrings["add"] = "Lägg till";
$piStrings["new"] = "Ny Identitet";
$piStrings["edit_ident"] = "Redigera Identitet";
$piStrings["delete"] = "Ta bort";
$piStrings["setdef"] = "Sätt till standard";
$piStrings["isdef"] = "(Standard)";

$piError[1] = "Namn eller email krävs";

?>
