<?php
include("../lang/eng/quota.inc"); // <-- do not delete
/********************************************************
	lang/se/quota.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$quotaStr["label"] = "Diskanvändning: ";
$quotaStr["full"] = "%usedKB/%totalKB (%free% ledigt)";
$quotaStr["unknown"] = "okänd";

?>