<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/se/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$rmStrings[0] = "Tillbaka";
$rmStrings[1] = "Svara";
$rmStrings[2] = "Vidarebefordra";
$rmStrings[3] = "Ångra ta bort";
$rmStrings[4] = "ta bort";
$rmStrings[5] = "Fil";
$rmStrings[6] = "Delar";
$rmStrings[7] = "Detta är ett HTML meddelande. ";
$rmStrings[8] = "Klicka här för att läsa det.";
$rmStrings[9] = "Källa";
$rmStrings[10] = "Storlek";
$rmStrings[11] = "Markera som Oläst";
$rmStrings[12] = "Visa Huvud";
$rmStrings[13] = "Rapportera Spam";
$rmStrings[14] = "Svara till alla";
$rmStrings[15] = "Du har svarat på detta meddelande";
$rmStrings[16] = "Skriv ut";

?>