<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/se/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$searchErrors["field"] = "Ogilitigt sökkriterium:  Ogiltigt fält";
$searchErrors["empty"] = "Ogilitigt sökkriterium:  Tom söksträng";
$searchErrors["date"] = "Ogilitigt sökkriterium:  Datum ej angivet";

?>