<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/se/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Markus Svensson <markus.svensson@linux.nu>

********************************************************/

$toolStrings["folders"] = "Mappar";
$toolStrings["inbox"] = "Inkorg";
$toolStrings["compose"] = "Skriv";
$toolStrings["calendar"] = "Kalender";
$toolStrings["contacts"] = "Kontakter";
$toolStrings["bookmarks"] = "Bokmärken";
$toolStrings["search"] = "Sök";
$toolStrings["prefs"] = "Inställningar";
$toolStrings["logout"] = "Logga ut";
$toolStrings["go"] = "Gå";

?>