<?php
/********************************************************
	lang/eng/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Oblíbené";
$bmStrings["identities"] = "Identity";
$bmStrings["edit"] = "Upravit";
$bmStrings["name"] = "Jméno";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Kategorie";
$bmStrings["other"] = "Uveïte-&gt;";
$bmStrings["comments"] = "Komentáø";
$bmStrings["add"] = "Pøidat";
$bmStrings["new"] = "Nový záznam";
$bmStrings["edit_url"] = "Upravit záznam";
$bmStrings["delete"] = "Smazat";

$bmError[1] = "Vy¾adováno jméno nebo URL";
$bmError[2] = "Toto roz¹íøení bylo zakázáno.";
?>