<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Pøidat plán";
$calStr["edit_schedule"] = "Upravit plán";
$calStr["weekof"] = "Týden: %d";
$calStr["title"] = "Název:";
$calStr["color"] = "Barva:";
$calStr["colors"] = array("#990000"=>"Tmavì èervená", "#FF0000"=>"Èervená", "#000099"=>"Tmavì modrá", "#0000FF"=>"Modrá", 
					"#006600"=>"Tmavì zelená", "#00FF00"=>"Zelená", "#9900FF"=>"Purpurová", "#00FFFF"=>"Azurová",
					"#FF6600"=>"Oran¾ová", "#FFFF00"=>"®lutá", "#FF00FF"=>"Fialová", ""=>"Bez barvy");
$calStr["starts"] = "Zaèíná:";
$calStr["ends"] = "Konèí:";
$calStr["from"] = "od:";
$calStr["until"] = "do:";
$calStr["repeat_on"] = "Opakovat";
$calStr["of"] = "ka¾dý";
$calStr["weeks"] = array(1=>"první týden", 2=>"druhý týden", 3=>"tøetí týden", 4=>"ètvrtý týden"); 
$calStr["week_blurb"] = "...ka¾dý mìsíc (do data ukonèení).<br>Mù¾e se opakovat ka¾dý týden pokud není ¾ádný vybrán.";
$calStr["monthly"] = "Opakovat ka¾dý mìsíc";
$calStr["yearly"] = "Opakovat ka¾dý rok";
$calStr["place"] = "Místo:";
$calStr["description"] = "Popis:";
$calStr["add"] = "Pøidat";
$calStr["update"] = "Aktualizovat";
$calStr["Delete"] = "Smazat";
$calStr["go"] = "Zobraz";
$calStr["disabled"] = "Funkce kalendáøe byla zakázána.";
?>