<?php
/********************************************************
	lang/eng/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/compose.inc");

$composeHStrings[0] = "Pшedmмt";
$composeHStrings[1] = "Od";
$composeHStrings[2] = "Komu";
$composeHStrings[3] = "Kopie";
$composeHStrings[4] = "Skrytб kopie";
$composeHStrings[5] = "Datum";


$composeStrings[0] = "Vytvoшenн zprбvy";
$composeStrings[1] = "Odeslat zprбvu";
$composeStrings[2] = "Pшipojit";
$composeStrings[3] = "Pшipojit podpis";
$composeStrings[4] = "Pшнloha";
$composeStrings[5] = "Kontakty";
$composeStrings[6] = "Skrэt kontakty";
$composeStrings[7] = "Text zprбvy:";
$composeStrings[8] = "Pшidat";
$composeStrings[9] = "Dne %d, napsal %s:\n";
$composeStrings[10] = "--- Pщvodnн zprбva ---\n";
$composeStrings[11] = "Zavшнt okno";

$composeStrings[12] = "Kontrola pravopisu";
$composeStrings[13] = "Opravit pravopis";
$composeStrings[14] = "Beze zmмn";
$composeStrings[15] = "Moѕnй chyby pшi kontrole pravopisu";
$composeStrings[16] = "Zmмny v pravopisu";
$composeStrings[17] = "ignorovat";
$composeStrings[18] = "smazat";

$composeStrings["title"] = "Vytvoшenн zprбvy";

$composeErrors[0] = "Pole Pшedmмt je prбzdnй. Prosнm vloѕte Pшedmмt nebo opмt klepnмte na \"".$composeStrings[1]."\" pro odeslбnн zprбvy.";
$composeErrors[1] = "Pole \"Od\" je prбzdnй. Prosнm vloѕte svou emailovou adresu.";
$composeErrors[2] = "Pole \"Komu\" je prбzdnй. Prosнm vloѕte emailovou adresu pшнjemce.";
$composeErrors[3] = "Upload souboru selhal.";
$composeErrors[4] = "®бdnй soubory .";
$composeErrors[5] = "Kvщli prevenci pшed SPAMem, mщѕete odeslat zprбvu %1 lidem (celkem %2 na jedno pшihlб№enн) kaѕdэch %3 vteшin.";

$composeErrors[6] = "Kontrola pravopisu neshledala ѕбdnэch chyb.";
$composeErrors[7] = "Kontrola pravopisu pro uvedenэ jazyk nenн dostupnб.";
$composeErrors[8] = "(pouѕitэ slovnнk: %s)";
?>