<?php
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/contacts.inc");

$cStrings[0] = "Kontakty";
$cStrings[1] = "Novэ kontakt";
$cStrings[2] = " Kontakt";
$cStrings[3] = "Jmйno";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Skupina";
$cStrings[7] = "Poznбmka";
$cStrings[8] = "Novэ/Uprav Kontakt";
$cStrings[9] = "Email";
$cStrings[10] = "Vytvoшit zprбvu";

$cStrings["close"] = "Zavшнt okno";
$cStrings["addto"] = "Pшidat kontakty do %s";
$cStrings["showgrp"] = "Zobraz %s";
$cStrings["all"] = "V№e";
$cStrings["instructions"] = "Klepnмte na jmйno pro pшidбnн. Takй mщѕete klepnout na nбzev skupiny pro pшidбnн v№ech v tйto skupinм.";

$cErrors[0] = "Vб№ seznam kontaktщ je prбzdnэ";


?>