<?php
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Upravit";
$ecStrings[1] = "Nový";
$ecStrings[2] = " Kontakt";
$ecStrings[3] = "Jméno";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Skupina";
$ecStrings[7] = "Poznámka";
$ecStrings[8] = "Telefon domù";
$ecStrings[9] = "Telefon do práce";
$ecStrings[10] = "Mobilní telefon";
$ecStrings[11] = "Adresa";
$ecStrings[12] = "Druhý email";
$ecStrings[13] = "Smazat";
$ecStrings[14] = "Jiné";


$errors[0] = "Nelze pøidat nový kontakt:  chyba databáze.";
$errors[1] = "Záznam s touto emailovou adresou ji¾ existuje.";
$errors[2] = "Klepnìte ";
$errors[3] = "zde";
$errors[4] = " pro úpravu ji¾ existujícího záznamu.";
$errors[5] = "Kontakt nebyl nalezen, nebo byl pøístup odepøen.";
$errors[6] = "Opravdu chcete smazat záznam \"";
$errors[7] = "\"?";

?>