<?php
/********************************************************
	lang/eng/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_folders.inc");

$efStrings[0] = "Spr&#225;va schr&#225;nek";
$efStrings[1] = "Vyvo&#345;en&#237; nov&#233; schr&#225;nky";
$efStrings[2] = "Vytvo&#345;it schr&#225;nku: ";
$efStrings[3] = "Vytvo&#345;it";
$efStrings[4] = "Smaz&#225;n&#237; schr&#225;nky";
$efStrings[5] = "Smazat";
$efStrings[6] = "P&#345;ejmenov&#225;n&#237; schr&#225;nky";
$efStrings[7] = "P&#345;ejmenovat";
$efStrings[8] = "Aktivovan&#233; schr&#225;nky";
$efStrings[9] = "Aktivace";
$efStrings[10] = "Deaktivovan&#233; schr&#225;nky";
$efStrings[11] = "Deaktivace";


$errors[0] = "Vytvo&#345;en&#237; chr&#225;nky: ";
$errors[1] = "Nelze vytvo&#345;it schr&#225;nku: ";
$errors[2] = "Smaz&#225;n&#237; schr&#225;nky: ";
$errors[3] = "Nelze smazat schr&#225;nku: ";
$errors[4] = "P&#345;ejmenov&#225;n&#237; schr&#225;nky: ";
$errors[5] = "Nelze p&#345;ejmenovat schr&#225;nku: ";
$errors[6] = "Podpora schr&#225;nek je dostupn&#225; pouze u IMAP p&#345;&#237;stupu.";

?>