<?php 
/********************************************************
	lang/en/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="U¾ivatel";
$loginStrings[1]="Heslo";
$loginStrings[2]="Server";
$loginStrings[3]="Typ";
$loginStrings[4]="Koøenový adresáø";
$loginStrings[5]="Jazyk";
$loginStrings[6]="Pøihlásit";

$loginErrors[0]="Neautorizovaný host";
$loginErrors[1]="Chyba: adresáø \"uploads\" nebyl nalezen";
$loginErrors[2]="Chyba: adresáø \"users\" nebyl nalezen";
$loginErrors[3]="Chyba: adresáø \"sessions\" nebyl nalezen";

?>