<?php
/********************************************************
	lang/eng/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainMessages["delete"] = "Smazáno %n zpráv";
$mainMessages["move"] = "Pøesunuto %n zpráv do %f";

$mainStrings[0] = "Zobrazeno %p z %n";
$mainStrings[1] = " zpráv nalezeno";
$mainStrings[2] = "Pøede¹lých";
$mainStrings[3] = "";
$mainStrings[4] = "Dal¹ích";
$mainStrings[5] = "";
$mainStrings[6] = "Pøedmìt";
$mainStrings[7] = "Komu";
$mainStrings[8] = "Od";
$mainStrings[9] = "Datum";
$mainStrings[10] = "Smazat";
$mainStrings[11] = "Smazat ko¹";
$mainStrings[12] = "Pøesunout";
$mainStrings[13] = "Hledání";
$mainStrings[14] = "Velikost";
$mainStrings[15] = "neoznaèené";
$mainStrings[16] = "Zobrazit";
$mainStrings[17] = "Obnovit";
$mainStrings[18] = "Smazat v¹e";
$mainStrings[19] = "Zru¹it";
$mainStrings[20] = "Oznaèit jako %b";
$mainStrings[21] = "Pøeètené";
$mainStrings[22] = "Nepøeètené";
$mainStrings[23] = "Vyber...";


$mainErrors[0] = "V této schránce nejsou ¾ádné zprávy";
$mainErrors[1] = "Tato schránka je prázdná";
$mainErrors[2] = "Nelze pøesunout zprávy do ko¹e.";
$mainErrors[3] = "Nelze oznaèit zprávy jako smazané.";
$mainErrors[4] = "Zprávy nelze pøesunout.";
$mainErrors[5] = "Není specifikována schránka reprezentující Ko¹.";
$mainErrors[6] = "Nemohu vymazat obsah ko¹e";
$mainErrors[7] = "Opravdu si pøejete smazat V©ECHNY zprávy ve schránce %f?";
$mainErrors[8] = "Klepnutím na ¹ipky pod nadpisy sloupcù je mù¾ete pøesouvat.<br>A¾ budete hotovi, jednodu¹e zavøete okno.";



?>