<?php
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "Identity";
$piStrings["edit"] = "Upravit";
$piStrings["name"] = "Jméno";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "Odpovìdìt-na";
$piStrings["sig"] = "Podpis";
$piStrings["add"] = "Nová";
$piStrings["new"] = "Nová identita";
$piStrings["edit_ident"] = "Upravit identitu";
$piStrings["delete"] = "Smazat";
$piStrings["setdef"] = "Nastavit jako výchozí";
$piStrings["isdef"] = "(Výchozí)";

$piError[1] = "Jméno nebo email je vy¾adován";

?>
