<?php
/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "Vlo¾te HTML kód barvy u ka¾dé komponenty.";
$pcStrings["0.1"] = "Pou¾ijte ";
$pcStrings["0.2"] = "Tabulku kódù barev";
$pcStrings["0.3"] = " k vyhledání správného kódu.";
$pcStrings["0.4"] = "Nastavení která jsou pøepsána tématem nelze modifikovat.";
$pcStrings["1.0"] = "Panel nástrojù";
$pcStrings["2.0"] = "Seznam schránek";
$pcStrings["3.0"] = "Hlavní";
$pcStrings["3.1"] = "Pozadí nadpisu: ";
$pcStrings["3.2"] = "Text nadpisu: ";
$pcStrings["3.3"] = "Tmavé pozadí: ";
$pcStrings["3.4"] = "Svìtlý text: ";
$pcStrings["4.0"] = "Rùzné";
$pcStrings["4.1"] = "Odsazení: ";
$pcStrings["5.0"] = "Fonty";
$pcStrings["5.1"] = "Rodina fontù";
$pcStrings["5.2"] = "Velikost fontu: ";
$pcStrings["5.3"] = "Velikost malého fontu: ";
$pcStrings["5.4"] = "Velikost fontu pro menu: ";
$pcStrings["5.5"] = "Velikost fontu v seznamu schránek: ";

							
$pcPortions = array( "Pozadí: ", "Odkazy: ", "Text: ", "Zvýraznìné: ");

?>
