<?php
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/read_message.inc");


$rmStrings[0] = "Index";
$rmStrings[1] = "Odpovìdìt";
$rmStrings[2] = "Pøeposlat";
$rmStrings[3] = "Obnovit vymazané";
$rmStrings[4] = "Smazat";
$rmStrings[5] = "Pøesuò";
$rmStrings[6] = "Èásti";
$rmStrings[7] = "Tato zpráva je v HTML.";
$rmStrings[8] = "Klepnìte sem pro pøeètení";
$rmStrings[9] = "Zdroj";
$rmStrings[10] = "Velikost";
$rmStrings[11] = "Nepøeètené";
$rmStrings[12] = "Zobrazit hlavièku";
$rmStrings[13] = "Report Spam";
$rmStrings[14] = "Odpovìdìt v¹em";
$rmStrings[15] = "Na tuto zprávu jste odpovìdìl";
$rmStrings[16] = "Tisk";

?>