<?php
/********************************************************
	lang/eng/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/search_errors.inc");

$searchErrors["field"] = "Neplatná kritéria hledání:  Neplatné pole";
$searchErrors["empty"] = "Neplatná kritéria hledání:  Prázdný øetìzec hledání";
$searchErrors["date"] = "Neplatná kritéria hledání:  Nebylo zadáno datum";

?>