<?php
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/tool.inc");

$toolStrings["folders"] = "Schránky";
$toolStrings["inbox"] = "Doruèená po¹ta";
$toolStrings["compose"] = "Nová zpráva";
$toolStrings["calendar"] = "Kalendáø";
$toolStrings["contacts"] = "Kontakty";
$toolStrings["bookmarks"] = "Oblíbené";
$toolStrings["search"] = "Hledání";
$toolStrings["prefs"] = "Nastavení";
$toolStrings["logout"] = "Odhlásit";
$toolStrings["go"] = "Jdi";

?>