<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/kr/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "제목";
$composeHStrings[1] = "From";
$composeHStrings[2] = "To";
$composeHStrings[3] = "CC";
$composeHStrings[4] = "BCC";
$composeHStrings[5] = "날짜";


$composeStrings[0] = "편지 쓰기";
$composeStrings[1] = "편지 보내기";
$composeStrings[2] = "선택";
$composeStrings[3] = "서명 붙이기";
$composeStrings[4] = "첨부";
$composeStrings[5] = "연락처 보기";
$composeStrings[6] = "연락처 숨기기";
$composeStrings[7] = "본문:";
$composeStrings[8] = "더하기";
$composeStrings[9] = "%d에, %s 씀:\n";
$composeStrings[10] = "--- 원래 본문 ---\n";
$composeStrings[11] = "창 닫기";


$composeErrors[0] = "제목란이 비어 있습니다. 그냥 보내시려면 \"".$composeStrings[1]."\" 를 누르세요.";
$composeErrors[1] = "보내는 사람 주소가 빠졌습니다.";
$composeErrors[2] = "받는 사람 주소가 빠졌습니다.";
$composeErrors[3] = "첨부 파일을 올리는데 실패했습니다.";
$composeErrors[4] = "받은 파일이 없습니다.";
$composeErrors[5] = "스팸을 보내는 것을 방지하기 위해서, 당신은 %1명에게 (접속시간 동안 %2명에게) 매 %3초마다 편지를 보내실수 있습니다.";

?>