<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/kr/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "연락처";
$cStrings[1] = "연락처 추가";
$cStrings[2] = " 연락처";
$cStrings[3] = "이름";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "그룹";
$cStrings[7] = "부가사항";
$cStrings[8] = "연락처 추가/수정";
$cStrings[9] = "Email";
$cStrings[10] = "작성";


$cErrors[0] = "기록된 연락처가 없습니다.";


?>