<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
	lang/kr/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime["dsow"] = array ("일","월","화","수","목","금","토");
$lang_datetime["today"] = "오늘 %t";
$lang_datetime["lastweek"] = "%w %t";
$lang_datetime["thisyear"] = "%m/%d";
$lang_datetime["prevyears"] = "%m/%d/%y";


?>