<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/kr/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "고치기";
$ecStrings[1] = "더하기";
$ecStrings[2] = " 연락처";
$ecStrings[3] = "이름";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "그룹";
$ecStrings[7] = "기타사항";
$ecStrings[8] = "집 전화";
$ecStrings[9] = "직장 전화";
$ecStrings[10] = "휴대 전화";
$ecStrings[11] = "주소";
$ecStrings[12] = "다른 이메일";
$ecStrings[13] = "삭제";
$ecStrings[14] = "기타";


$errors[0] = "연락처를 추가할수 없습니다. 데이타베이스에 오류가 있습니다.";
$errors[1] = "같은 주소를 가진 연락처가 있습니다.";
$errors[2] = "누름 ";
$errors[3] = "여기";
$errors[4] = " to edit that entry instead.";
$errors[5] = "연락처를 찾을 수 없거나 접근이 거부되었습니다.";
$errors[6] = "연락처를 삭제를 원하십니까 \"";
$errors[7] = "\"?";

?>