<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
 
/********************************************************
	lang/kr/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings= array(
							"0" => "각 부분에 원하는 색상코드를 넣으세요.",
							"0.1" => "색상코드를 모르시면 ",
							"0.2" => "색상표",
							"0.3" => "를 사용하세요.",
							"1.0" => "메뉴 표시줄",
							"2.0" => "편지함 목록",
							"3.0" => "주", 
							"4.0" => "기타",
							"4.1" => "인용: "
							);
							
$pcPortions = array( "배경: ", "연결: ", "글: ", "강조: ");

?>