<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/kr/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "뒤로";
$rmStrings[1] = "회신";
$rmStrings[2] = "전달";
$rmStrings[3] = "복구";
$rmStrings[4] = "삭제";
$rmStrings[5] = "파일";
$rmStrings[6] = "부분";
$rmStrings[7] = "HTML로 작성된 편지입니다. ";
$rmStrings[8] = "편지 읽기.";
$rmStrings[9] = "편지 소스";
$rmStrings[10] = "크기";
$rmStrings[11] = "안읽은 표시하기";
$rmStrings[12] = "헤더 보기";
$rmStrings[13] = "스팸 신고";
$rmStrings[14] = "모두에게 회신하기";

?>