<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/kr/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "검색 범위 오류:  범위가 없습니다.";
$searchErrors["empty"] = "검색 범위 오류:  검색 용어가 없습니다.";
$searchErrors["date"] = "검색 범위 오류:  날짜가 지정되지 않았습니다.";

?>