<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/kr/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "편지함";
$toolStrings["inbox"] = "받은편지함";
$toolStrings["compose"] = "편지쓰기";
$toolStrings["contacts"] = "연락처";
$toolStrings["search"] = "검색";
$toolStrings["prefs"] = "환경설정";
$toolStrings["logout"] = "로그아웃";
$toolStrings["go"] = "가기";

?>