<?php
/********************************************************
	lang/eng/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "д‘«д";
$bmStrings["identities"] = "«Ё—«ѕ";
$bmStrings["edit"] = "жн—«н‘";
$bmStrings["name"] = "д«г";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Р—же";
$bmStrings["other"] = " Џннд-&gt;";
$bmStrings["comments"] = " ж÷нЌ« ";
$bmStrings["add"] = "«÷«Ёе";
$bmStrings["new"] = "д‘«д ћѕнѕ";
$bmStrings["edit_url"] = "жн—«н‘ д‘«д";
$bmStrings["delete"] = "Б«я";

$bmError[1] = ".«”г н« ¬ѕ—” «нд —д н б«“г «” ";
$bmError[2] = "«нд ё«»бн  џн—ЁЏ«б «” .";
?>