<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "«÷«›Â ﬂ—œ‰ »—‰«„Â";
$calStr["edit_schedule"] = "ÊÌ—«Ì‘ »—‰«„Â";
$calStr["weekof"] = "Â› Â : %d";
$calStr["title"] = "⁄‰Ê«‰:";
$calStr["color"] = "—‰ê:";
$calStr["colors"] = array("#990000"=>"ﬁ—„“  Ì—Â", "#FF0000"=>"ﬁ—„“", "#000099"=>"¬»Ì  Ì—Â", "#0000FF"=>"¬»Ì",
					"#006600"=>"”»“  Ì—Â", "#00FF00"=>"”»“", "#9900FF"=>"«—€Ê«‰Ì", "#00FFFF"=>"”»“¬»Ì",
					"#FF6600"=>"‰«—‰ÃÌ", "#FFFF00"=>"“—œ", "#FF00FF"=>"”—Œù¬»Ì", ""=>"»œÊ‰ —‰ê");
$calStr["starts"] = "‘—Ê⁄ «“:";
$calStr["ends"] = "Å«Ì«‰  «:";
$calStr["from"] = "«“:";
$calStr["until"] = " «Êﬁ ÌﬂÂ:";
$calStr["repeat_on"] = "«œ«„Â «“";
$calStr["of"] = "«“ Â—";
$calStr["weeks"] = array(1=>"Â› Â «Ê·", 2=>"Â› Â œÊ„", 3=>"Â› Â ”Ê„", 4=>"Â› Â çÂ«—„");
$calStr["week_blurb"] = "...Â—„«Â ( «Å«Ì«‰  «—ÌŒ)<br>«ê— «‰ Œ«» ‰‘Êœ œ—  „«„ Â› Â Â«  ﬂ—«— ŒÊ«Âœ ‘œ.";
$calStr["monthly"] = "«œ«„Â œ— Â— „«Â";
$calStr["yearly"] = "«œ«„Â œ— Â— ”«·";
$calStr["place"] = "ﬁ—«—œ«œ‰:";
$calStr["description"] = "‘—Õ:";
$calStr["add"] = "«÷«›Â";
$calStr["update"] = "»Â —Ê“ ﬂ—œ‰";
$calStr["Delete"] = "Å«ﬂ";
$calStr["go"] = "—› ‰";
$calStr["disabled"] = " ﬁÊÌ„ €Ì—›⁄«· «” .";
?>