<?php
/********************************************************
	lang/eng/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/compose.inc");

$composeHStrings[0] = "гж÷жЏ";
$composeHStrings[1] = "«“";
$composeHStrings[2] = "»е";
$composeHStrings[3] = "—ждж‘ ";
$composeHStrings[4] = "—ждж‘  Бде«д";
$composeHStrings[5] = " «—нќ";


$composeStrings[0] = "дж‘ д д«ге ћѕнѕ";
$composeStrings[1] = "«—”«б д«ге";
$composeStrings[2] = "»«—я–«—н »е ”—ж—";
$composeStrings[3] = "«б’«ё «г÷«Ѕ";
$composeStrings[4] = "«б’«ё";
$composeStrings[5] = "ѕЁ —  г«”е«";
$composeStrings[6] = "Бде«д я—ѕд  г«”е«";
$composeStrings[7] = "г д д«ге:";
$composeStrings[8] = "«÷«Ёе";
$composeStrings[9] = "ѕ—  «—нќ %d, %s  дж‘ е:\n";
$composeStrings[10] = "--- д«ге «’бн ---\n";
$composeStrings[11] = "»” д Бдћ—е";

$composeStrings[12] = "»——”н «гб«Ѕ";
$composeStrings[13] = " ’ЌнЌ «гб«°";
$composeStrings[14] = "»ѕжд   џнн—« ";
$composeStrings[15] = "«‘я«б«  «гб«нн гжћжѕ";
$composeStrings[16] = " џнн—«  «гб«Ѕ";
$composeStrings[17] = "Н‘г Бж‘н";
$composeStrings[18] = "Б«я";

$composeStrings["title"] = "дж‘ д д«ге ћѕнѕ";

$composeErrors[0] = "—‘ е гж÷жЏ ќ«бн «” . бЎЁ« ня гж÷жЏ —« ж«—ѕ яднѕ ж н« ѕж»«—е »— —жн ѕяге \"".$composeStrings[1]."\" ябня яднѕ  « д«ге «—”«б ‘жѕ.";
$composeErrors[1] = "—‘ е \"«“\" ќ«бн” .  бЎЁ« ня ¬ѕ—” Б” н ’ЌнЌ ж«—ѕ яднѕ.";
$composeErrors[2] = "—‘ е \"»е\" ќ«бн” .  бЎЁ« ня ¬ѕ—” Б” н ’ЌнЌ ж«—ѕ яднѕ";
$composeErrors[3] = "»«—Р–«—н »е ”—ж— д«гжЁё »жѕ.";
$composeErrors[4] = "Ё«нбн ѕ—н«Ё  д‘ѕ.";
$composeErrors[5] = "»—«н ћбжРн—н «“ «—”«б д«ге е«н «бя —жднян д«ќж«” е »—«н ѕнР— я«—»—«д ‘г« гнЭ ж«днѕ е— %3 Ћ«дне »—«н %1 я«—»— д«ге »Ё—” нѕ (гћгжЏ« %2 д«ге)";

$composeErrors[6] = "енН «‘я«б «гб«нн н«Ё  д‘ѕ";
$composeErrors[7] = "»——”н «гб«нн »—«н «нд “»«д гжНжѕ дн” .";
$composeErrors[8] = "(%s бџ д«ге гж—ѕ «” Ё«ѕе)";
?>