<?php
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/contacts.inc");

$cStrings[0] = "ѕЁ —  г«”е«";
$cStrings[1] = "«÷«Ёе я—ѕд  г«”";
$cStrings[2] = "  г«”";
$cStrings[3] = "д«г";
$cStrings[4] = "Б”  «бя —жднян";
$cStrings[5] = "¬ѕ—” «нд —д н";
$cStrings[6] = "Р—же";
$cStrings[7] = " ж÷нЌ";
$cStrings[8] = "«÷«Ёе/жн—«н‘  г«”";
$cStrings[9] = "Б”  «бя —жднян";
$cStrings[10] = "«нћ«ѕ";

$cStrings["close"] = "»” д Бдћ—е";
$cStrings["addto"] = "«÷«Ёе я—ѕд  г«”е« »е %s";
$cStrings["showgrp"] = "дг«н‘ %s";
$cStrings["all"] = "еге";
$cStrings["instructions"] = "»— —жн д«г ябня яднѕ  « «÷«Ёе ‘жѕ. ж н« »— —жн Р—же ябня яднѕ  «  г«г «Ё—«ѕ Р—же «÷«Ёе ‘ждѕ.";

$cErrors[0] = "Ёе—”   г«”е« ќ«бн «” ";


?>