<?php
/********************************************************
	lang/eng/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/dates.inc");

$lang_months[1] = "ַהזםו";
$lang_months[2] = "Ýזׁםו";
$lang_months[3] = "דַׁ׃";
$lang_months[4] = "ֲזׁםב";
$lang_months[5] = "דם";
$lang_months[6] = "זֶה";
$lang_months[7] = "זבַם";
$lang_months[8] = "ַז׃Ê";
$lang_months[9] = "׃Êַדָׁ";
$lang_months[10] = "ַßÊָׁ";
$lang_months[11] = "הזַדָׁ";
$lang_months[12] = "ֿ׃ַדָׁ";

$lang_datetime["short_mon"][1] = "ַהזםו";
$lang_datetime["short_mon"][2] = "Ýזׁםו";
$lang_datetime["short_mon"][3] = "דַׁ׃";
$lang_datetime["short_mon"][4] = "ֲזׁםב";
$lang_datetime["short_mon"][5] = "דם";
$lang_datetime["short_mon"][6] = "זֶה";
$lang_datetime["short_mon"][7] = "זבַם";
$lang_datetime["short_mon"][8] = "ֲז׃Ê";
$lang_datetime["short_mon"][9] = "׃Êַדָׁ";
$lang_datetime["short_mon"][10] = "ַßÊָׁ";
$lang_datetime["short_mon"][11] = "הזַדָׁ";
$lang_datetime["short_mon"][12] = "ֿ׃ַדָׁ";

$lang_datetime["dsow"][0] = "Sun";
$lang_datetime["dsow"][1] = "Mon";
$lang_datetime["dsow"][2] = "Tue";
$lang_datetime["dsow"][3] = "Wed";
$lang_datetime["dsow"][4] = "Thu";
$lang_datetime["dsow"][5] = "Fri";
$lang_datetime["dsow"][6] = "Sat";

$lang_datetime["dsowl"][0] = "םßװהָו";
$lang_datetime["dsowl"][1] = "ֿזװהָו";
$lang_datetime["dsowl"][2] = "׃וװהָו";
$lang_datetime["dsowl"][3] = "וַׁװהָו";
$lang_datetime["dsowl"][4] = "הּװהָו";
$lang_datetime["dsowl"][5] = "ּדÚו";
$lang_datetime["dsowl"][6] = "װהָו";
			
$lang_datetime["dsow_short"] = array("S", "M", "T", "W", "T", "F", "S");
$lang_datetime["today"] = "ַדׁזׂ %t";		//e.g. "Today 12:02"
$lang_datetime["lastweek"] = "%w %t";		//e.g. "Wed 12:00"
$lang_datetime["thisyear"] = "%m/%d";		//e.g. "2/13"
$lang_datetime["prevyears"] = "%m/%d/%y"; 	//e.g. "1/1/2100"
$lang_datetime["monthyear"] = "%m %y";		//e.g. "January 2002"
$lang_datetime["verbal"] = "%m %d, %y";  	//e.g. "Jan 1, 1900"
$lang_datetime["verbal_short"] = "%m %d";  	//e.g. "Jan 1"
$lang_datetime["hour_system"] = 12;			// 12 or 24
$lang_datetime["ampm"]["am"] = "ױָֽ";
$lang_datetime["ampm"]["pm"] = "ָÚֿ ַׂ Ùוׁ";
$lang_datetime["time_format"] = "%h:%m%a";	// %h=hour, %m=minutes, %a="am:pm"
$lang_datetime["hour_format"] = "%h%a";
?>