<?php
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "жн—«н‘";
$ecStrings[1] = "«÷«Ёе";
$ecStrings[2] = "  г«”";
$ecStrings[3] = "д«г";
$ecStrings[4] = "Б”  «бя —жднян";
$ecStrings[5] = "¬ѕ—” «нд —д н";
$ecStrings[6] = "Р—же";
$ecStrings[7] = " ж÷нЌ« ";
$ecStrings[8] = " бЁд ќ«де";
$ecStrings[9] = " бЁд я«—";
$ecStrings[10] = " бЁд ег—«е";
$ecStrings[11] = "ѕ” —”н";
$ecStrings[12] = "Б”  «бя —жднян ѕнР—";
$ecStrings[13] = "Б«я";
$ecStrings[14] = "ѕнР—";


$errors[0] = " г«” —« дгнЭ ж«д «÷«Ёе я—ѕ. ќЎ«н »«дя «Ўб«Џ« н";
$errors[1] = "ня  г«” »« ¬ѕ—” –я— ‘ѕе жћжѕ «” ";
$errors[2] = "ябня ";
$errors[3] = "«ндћ«";
$errors[4] = "»—«н жн—«н‘ ¬д  г«” »е ћ«н ¬д";
$errors[5] = " г«” н«Ё  д‘ѕ. ѕ” —”н  —ѕ ‘ѕ.";
$errors[6] = "¬н« ‘г« гЎг∆днѕ яе гнЭќж«енѕ «нд  г«” —« Б«я яднѕ\"";
$errors[7] = "\"њ";

?>