<?php
/********************************************************
	lang/en/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
//include("../lang/eng/login.inc");

$loginStrings[0]="тДгсЕ";
$loginStrings[1]="яЦр зхФя";
$loginStrings[2]="сяФя";
$loginStrings[3]="ДФз";
$loginStrings[4]="тгнЕ гуАМ";
$loginStrings[5]="рхгД";
$loginStrings[6]="ФяФо";

$loginErrors[0]="сяФя глгрЕ ФяФо яг ДЦМ²оЕо";
$loginErrors[1]="ньг: тгнЕ \"uploads\" Мгщй Дто";
$loginErrors[2]="ньг: тгнЕ\"users\" Мгщй Дто";
$loginErrors[3]="ньг: тгнЕ\"sessions\" Мгщй Дто";

?>