<?php
/********************************************************
	lang/eng/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/main.inc");

$mainMessages["delete"] = "äÇãå %n Çß ÔÏ";
$mainMessages["move"] = "%n äÇãå Èå  %f ãäÊŞá ÔÏ";

$mainStrings[0] = "äãÇíÔ %p ÇÒ %n";
$mainStrings[1] = " äÇãå íÇİÊ ÔÏ";
$mainStrings[2] = "ŞÈáí";
$mainStrings[3] = "";
$mainStrings[4] = "ÈÚÏí";
$mainStrings[5] = "";
$mainStrings[6] = "ãæÖæÚ";
$mainStrings[7] = "Èå";
$mainStrings[8] = "ÇÒ";
$mainStrings[9] = "ÊÇÑíÎ";
$mainStrings[10] = "Çß";
$mainStrings[11] = "ÎÇáí ßÑÏä æÔå äÇãååÇí ÏæÑÑíÎÊå";
$mainStrings[12] = "ÇäÊŞÇá";
$mainStrings[13] = "ÌÓÊÌæ";
$mainStrings[14] = "ÇäÏÇÒå";
$mainStrings[15] = "ÈíäÇã";
$mainStrings[16] = "äÔÇä ÈÏå";
$mainStrings[17] = "ÈÑÑÓí äÇãå ÌÏíÏ";
$mainStrings[18] = "ÇßßÑÏä åãå";
$mainStrings[19] = "ÇäÕÑÇİ";
$mainStrings[20] = "ÚáÇãÊ ÒÏä %b";
$mainStrings[21] = "ÎæÇäÏåÔÏå";
$mainStrings[22] = "ÎæÇäÏåäÔÏå";
$mainStrings[23] = "ÇäÊÎÇÈ...";


$mainErrors[0] = "åí äÇãåÇí ÏÑ Çíä æÔå íÇİÊ äÔÏ.";
$mainErrors[1] = "åí äÇãåÇí ÏÑ Çíä æÔå æÌæÏ äÏÇÑÏ";
$mainErrors[2] = "äÇãååÇ Èå æÔå ÏæÑÑíÎÊå ãäÊŞá äÔÏ.";
$mainErrors[3] = "äÇãååÇ Èå ÚäæÇä Çß ÔÏå ÚáÇãÊ äÎæÑÏ.";
$mainErrors[4] = "äÇãååÇ ãäÊŞá äÔÏ";
$mainErrors[5] = "æÔå äÇãååÇí ÏæÑÑíÎÊå ãÔÎÕ äÔÏå ÇÓÊ.";
$mainErrors[6] = "äãíÊæÇä æÔå äÇãååÇí ÏæÑÑíÎÊå ÑÇ ÎÇáí ßÑÏ.";
$mainErrors[7] = "ÂíÇ ÔãÇ ãØãÆäíÏ ßå ãíÎæÇåíÏ ÊãÇã äÇãååÇí ãæÌÏ ÏÑ Çíä æÔå ÑÇ Çß ßäíÏ %f?";
$mainErrors[8] = "ÈÑ Ñæí İáÔ Çííä ÓÊæä ßáíß ßäíÏ ÊÇ äÇãååÇ ÑÇ ãäÊŞá ßäíÏ<br>æŞÊí ÇäÌÇã ÔÏ ÕİÍå ÑÇ ÈÈäÏíÏ";



?>