<?php
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "«Ё—«ѕ";
$piStrings["edit"] = "жн—«н‘";
$piStrings["name"] = "д«г";
$piStrings["email"] = "Б”  «бя —жднян";
$piStrings["replyto"] = "Б«”ќ »е";
$piStrings["sig"] = "«г÷«Ѕ";
$piStrings["add"] = "«÷«Ёе";
$piStrings["new"] = "Ё—ѕ ћѕнѕ";
$piStrings["edit_ident"] = "жн—«н‘ Ё—ѕ";
$piStrings["delete"] = "Ќ–Ё";
$piStrings["setdef"] = "Бн‘ Ё—÷";
$piStrings["isdef"] = "(Бн‘ Ё—÷)";

$piError[1] = "«”г н« Б”  «бя —жднян б«“г «” .";

?>