<?php
/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "»—«н е— ё”г  яѕ ж» ж«—ѕ яднѕ..";
$pcStrings["0.1"] = "—« «” Ё«ѕе яд ";
$pcStrings["0.2"] = "ћѕжб яѕ —дР";
$pcStrings["0.3"] = " »—«н н«Ё г яѕ —дР гд«”».";
$pcStrings["0.4"] = " дўнг« н яе  ж”Ў  г «дћ«г Р—Ё е —« дгнЭ ж«д  џнн— ѕ«ѕ..";
$pcStrings["1.0"] = "дж«— «»“«—";
$pcStrings["2.0"] = "бн”  Бж‘еЭе«";
$pcStrings["3.0"] = "«’бн";
$pcStrings["3.1"] = "Б” “гнде ”—’ЁЌе: ";
$pcStrings["3.2"] = "г д ”—’ЁЌе: ";
$pcStrings["3.3"] = "Б” “гнде  «—ня: ";
$pcStrings["3.4"] = "г д —ж‘д: ";
$pcStrings["4.0"] = "Ржд«Ржд";
$pcStrings["4.1"] = "дёб ёжб: ";
$pcStrings["5.0"] = "ёбг";
$pcStrings["5.1"] = "ѕ” е ёбг";
$pcStrings["5.2"] = "«дѕ«“е ёбг: ";
$pcStrings["5.3"] = "«дѕ«“е ё«г яжНя: ";
$pcStrings["5.4"] = "бн”  «дѕ«“е ёбг: ";
$pcStrings["5.5"] = "«дѕ«“е ёбг бн”  Бж‘еЭе«: ";

							
$pcPortions = array( "Бн‘ “гнде: ", "Бнждѕе«: ", "дж‘ еЭе«: ", "г д —ж‘д —: ");

?>