<?php
/********************************************************
	lang/eng/prefs.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/prefs.inc");

$prefHeaderStrings[0] = "ÊäÙíãÇÊ";
$prefHeaderStrings[1] = "Úãæãí";
$prefHeaderStrings[3] = "ÇİÑÇÏ";
$prefHeaderStrings[2] = "äãÇ";

											
$prefsStrings["0.0"] = "İÑÏ íÔ İÑÖ";
$prefsStrings["0.1"] = "äÇã: ";
$prefsStrings["0.2"] = "ÓÊ ÇáßÊÑæäíßí: ";
$prefsStrings["0.3"] = " äÛííÑÇÊ ãí ÊæÇä ÏÑ ÕİÍåí  \"%s\" ÇÚãÇá ÔæÏ.";
$prefsStrings["0.4"] = "ãÔÎÕ äÔÏå";
$prefsStrings["1.0"] = "ÌåÇäí";
$prefsStrings["1.1"] = "ÑÇÈØ: ";
$prefsStrings["1.2"] = "ÊäÙíã ÍÑæİ: ";
$prefsStrings["1.3"] = "äÇÍíå ÓÇÚÊ: ";
$prefsStrings["1.4"] = "Òíäå ÓÇÚÊ: ";
$prefsStrings["1.5"] = array(12=>"12 ÓÇÚÊí", 24=>"24 ÓÇÚÊí");
$prefsStrings["2.0"] = "áíÓÊ ÒíäååÇí äãÇ";
$prefsStrings["2.1"] = "Çíä ÊÚÏÇÏ ÑÇ äÔÇä ÈÏå";
$prefsStrings["2.2"] = " ãæÇÑÏ";
$prefsStrings["2.3"] = "ÇäÏÇÒå ÑÇ äÔÇä ÈÏå";
$prefsStrings["2.4"] = "ãÑÊÈ ßÑÏä ÈÑ ÇÓÇÓ: ";
$prefsStrings["2.5"] = "";
$prefsStrings["2.6"] = "ãÑÊÈ ßÑÏä ÓİÇÑÔÇÊ: ";
$prefsStrings["2.7"] = "";
$prefsStrings["2.8"] = "äÔÇä ÏÇÏä İåÑÓÊ æÔååÇ";
$prefsStrings["2.9"] = "ÚÑÖ İåÑÓÊ æÔååÇ";
$prefsStrings["2.10"] = "ÈÑÑÓí ÌåÊ äÇãååÇí ÌÏíÏ åÑ  %n ËÇäíå";
$prefsStrings["2.11"] = "äÔÇä ÏÇÏä äæÇÑ ÇÈÒÇÑ ÏÑ %m";
$prefsStrings["2.12"] = array("b"=>"Çííä", "t"=>"ÈÇáÇ", "bt"=>"Çííä æ ÈÇáÇ");
$prefsStrings["2.13"] = "ÏæÈÇÑå íäí ÓÊæäåÇ: ";
$prefsStrings["2.14"] = "ÇíäÌÇ ÑÇ ßáíß ßä";
$prefsStrings["3.0"] = "Òíäå ÖÈØ ÈÕæÑÊ ÇÊæãÇÊíß";
$prefsStrings["3.1"] = "äÇãååÇí ÇÑÓÇáí äåÏÇÑí ÔæäÏ";
$prefsStrings["3.2"] = "äÇãååÇí ÇÑÓÇáí ÏÑ Çíä æÔå äåÏÇÑí ÔæäÏ: ";
$prefsStrings["3.3"] = "";
$prefsStrings["3.4"] = "ÈÕæÑÊ ÎæÏßÇÑ äÇãååÇí ÏæÑÑíÎÊå ÔÏå Çß ÔæäÏ.";
$prefsStrings["3.5"] = "äÇãååÇí ÏæÑ ÑíÎÊå ÔÏå Èå Çíä æÔå ãäÊŞá ÔæäÏ: ";
$prefsStrings["3.6"] = "";
$prefsStrings["3.7"] = "ÔÇÎå ÇÕáí: ";
$prefsStrings["3.8"] = "ÏíÑ";
$prefsStrings["3.9"] = "æÔååÇí ÊÇííÏ äÔÏå ÑÇ äÔÇä äÏå";
$prefsStrings["3.10"] = "äÔÇä ÏÇÏä ÙÑİíÊ ÇÔÛÇá ÔÏå %m";
$prefsStrings["3.11"] = array(""=>"äÔÇä äÏå", "m"=>"ÏÑ İåÑÓÊ äÇãååÇ", "f"=>"ÏÑ İåÑÓÊ æÔååÇ");
$prefsStrings["4.0"] = "Òíäå åÇí äãÇíÔ äÇãå";
$prefsStrings["4.1"] = "äÔÇä ÏÇÏä ÏÑ İÑíã";
$prefsStrings["4.2"] = "äŞá ŞæáåÇ Èå ÕæÑÊ Ñäí";
$prefsStrings["4.3"] = "İÚÇá ßÑÏä Çíä Òíäå ããßä ÇÓÊ ÓÑÚÊ ÈÑäÇãå ÑÇ ßã ßäÏ.";
$prefsStrings["4.4"] = "ÂÏÑÓåÇí ÇíäÊÑäÊí ÑÇ Èå áíäß ÊÈÏíá ßä";
$prefsStrings["4.5"] = "äÇãååÇí HTML ÑÇ äÔÇä ÈÏå";
$prefsStrings["4.6"] = "ÚßÓåÇ ÑÇ ÏÑæä ÈÑäÇãå äÔÇä ÈÏå";
$prefsStrings["4.7"] = "äÔÇä ÏÇÏä áíäßåÇí ÑÇåÈÑí";
$prefsStrings["4.8"] = "ÏÑ Ííä ÇäÊŞÇá äÇãååÇ ÚáÇãÊĞÇÑí äÔæäÏ.";
$prefsStrings["5.0"] = "ÇãÖÇÁ";
$prefsStrings["5.1"] = "ÇãÖÇÁ ÑÇ äÔÇä ÈÏå";
$prefsStrings["5.2"] = "";
$prefsStrings["6.0"] = "äæÔÊä äÇãå";
$prefsStrings["6.1"] = "äÔÇä ÏÇÏä ÊãÇÓåÇ";
$prefsStrings["6.2"] = "äÔÇä ÏÇÏä ÚÈÇÑÇÊ ÑæäæÔÊ";
$prefsStrings["6.3"] = "ÈÓÊä ÈÚÏ ÇÒ ÇÑÓÇá";
$prefsStrings["6.4"] = "äæÔÊä äÇãå ÏÑæä İÑíã";
$prefsStrings["7.0.0"] = "Disk &amp; ÊäÙíãÇÊ æÔååÇ";
$prefsStrings["7.0.1"] = "ÒíäååÇí ÙÑİíÊ";
$prefsStrings["7.1"] = "äÔÇä ÏÇÏä ÊÚÏÇÏ äÇãååÇí ÎæÇäÏå äÔÏå";
$prefsStrings["7.2"] = "áíÓÊ æÔååÇ ÑÇ åÑ  %n ËÇäíå Èå ÑæÒ ßä";

$pref_col_title = "ÏæÈÇÑå íÏä ÓÊæäåÇ";
$pref_colstr["order"] = "ÓİÇÑÔ";
$pref_colstr["field"] = "ÑÔÊå";
$pref_col_label['c'] = "ãÑÈÚ ÚáÇãÊ";
$pref_col_label['a'] = "äÇãååÇí ÇáÕÇŞí";
$pref_col_label['m'] = "Flags/status";

$sort_fields=array("DATE"=>"ÊÇÑíÎ", "SUBJECT"=>"ãæÖæÚ", "SIZE"=>"ÇäÏÇÒå");
$sort_orders=array("ASC"=>"ÕÚæÏí", "DESC"=>"äÒæáí");

$prefsButtonStrings = array( 0=> "ÈÑæÒ ÑÓÇäí", 1=>"ÇÌÑÇ", 2=> "ÇäÕÑÇİ", 3=> "íÔ İÑÖåÇ");

$prefs_new_user = "Èå äÙÑ ãíÑÓÏ ;å ÏİÚå Çæá ÇÓÊ ßå ÔãÇ æÇÑÏ ÔÏåÇíÏ. ÎæÔ ÂãÏíÏ!<br>";
$prefs_new_user .=  'áØİÇ Ó ÇÒ ÇäÌÇã ÊÛííÑÇ Ïßãå "\ ÇÌÑÇ "\  ÑÇ İÔÇÑ ÏåíÏ. ';
?>