<?php
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/read_message.inc");


$rmStrings[0] = "д«геЭе«н —”нѕе";
$rmStrings[1] = "Б«”ќ";
$rmStrings[2] = "—”«дѕд";
$rmStrings[3] = "»«“н«»н";
$rmStrings[4] = "Б«я";
$rmStrings[5] = "«д ё«б";
$rmStrings[6] = "ё”г е«";
$rmStrings[7] = "«нд ня д«геЭн HTML «”  ";
$rmStrings[8] = "«ндћ« —« ябня яднѕ  « ¬д—« »ќж«днѕ";
$rmStrings[9] = "гд»Џ";
$rmStrings[10] = "«дѕ«“е";
$rmStrings[11] = "ќж«дѕеЭд‘ѕе";
$rmStrings[12] = "”—’ЁЌе —« д‘«д »ѕе";
$rmStrings[13] = "Р“«—‘ я—ѕд ня д«ге д«ќж«” е";
$rmStrings[14] = "Б«”ќ »е еге";
$rmStrings[15] = "‘г« »е д«ге ё»б« Б«”ќ ѕ«ѕеЭ«нѕ";
$rmStrings[16] = "Н«Б";

?>