<?php
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/tool.inc");

$toolStrings["folders"] = "זװווַ";
$toolStrings["inbox"] = "הַדווַם ׁ׃םֿו";
$toolStrings["compose"] = "ַםַּֿ הַדו";
$toolStrings["calendar"] = "ÊÞזםד";
$toolStrings["contacts"] = "ֿÝÊׁ Êדַ׃וַ";
$toolStrings["bookmarks"] = "הװַה";
$toolStrings["search"] = "ּ׃Êּז";
$toolStrings["prefs"] = "ׂםהווַ";
$toolStrings["logout"] = "־ׁזּ";
$toolStrings["go"] = "ָׁז";

?>