<?php
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings=array(
	0=>"כתובת",
	1=>"הוסף כתובת",
	2=>" כתובת",
	3=>"שם",
	4=>"דואר אלקטרוני",
	5=>"לינק",
	6=>"קבוצה",
	7=>"הערות",
	8=>"הוספה/עריכה כתובת",
	9=>"דואר אלקטרוני",
    10=>"הודעה חדשה"
);

$cErrors=array(
	0=>"רשימת כתובות ריקה"
);

?>