<?php
/********************************************************
	lang/eng/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime =  array(
	"dsow" => array (			
			0 => "ראשון",
			1 => "שני",
			2 => "שלישי",
			3 => "רביעי",
			4 => "חמישי",
			5 => "שישי",
			6 => "שבת"
			),
	"today" => "היום %t",
	"lastweek" => "%w %t",
	"thisyear" => "%m/%d",
	"prevyears" => "%m/%d/%y"
);

?>