<?php
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings=array(
	0=>"הקודם",
	1=>"מענה",
	2=>"העברה",
	3=>"שחזר",
	4=>"מחק",
	5=>"תייק",
	6=>"מצורפים",
	7=>"הודעת HTML ",
	8=>"לחץ כאן לצפיה בהודעה.",
	9=>"מקור",
	10=>"גודל",
	11=>"סומן כלא נקרא",
	12=>"הראה כותרת",
	13=>"דווח על דואר זבל",
	14=>"מענה לכולם"
);
?>