<?php
/********************************************************
	lang/eng/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors=array(
	"field"=>"ערך לא תקין",
	"empty"=>"מחרוזת חיפוש ריקה",
	"date"=>"שדה תאריך אינו מוגדר"
);
?>