<?php
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings=array(
	"folders"=>"תיקיות",
	"inbox"=>"דואר נכנס",
	"compose"=>"הודעה חדשה",
	"contacts"=>"ספר כתובות",
	"search"=>"חפש",
	"prefs"=>"מאפיניים",
	"logout"=>"התנתק",
	"go"=>"Go"
);
?>
