<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Új ütemezés";
$calStr["edit_schedule"] = "Ütemezés szerkesztése";
$calStr["weekof"] = "Hét: %d";
$calStr["title"] = "Cím:";
$calStr["color"] = "Szín:";
$calStr["colors"] = array("#990000"=>"Sötét vörös", "#FF0000"=>"Vörös", "#000099"=>"Sötét kék", "#0000FF"=>"Kék", 
					"#006600"=>"Sötét zöld", "#00FF00"=>"Zöld", "#9900FF"=>"Lila", "#00FFFF"=>"Cián",
					"#FF6600"=>"Narancssárga", "#FFFF00"=>"Citromsárga", "#FF00FF"=>"Magenta", ""=>"Nincs szín");
$calStr["starts"] = "Kezdés:";
$calStr["ends"] = "Befejezés:";
$calStr["from"] = "kezdés:";
$calStr["until"] = "befejezés:";
$calStr["repeat_on"] = "Ismétlés";
$calStr["of"] = "minden";
$calStr["weeks"] = array(1=>"elsõ héten", 2=>"második héten", 3=>"harmadik héten", 4=>"negyedik héten"); 
$calStr["week_blurb"] = "...minden hónapban (befejezés dátumáig).<br>Ha nincs hét kiválasztva, akkor minden héten ismétlõdni fog.";
$calStr["monthly"] = "Havonta";
$calStr["yearly"] = "Évente";
$calStr["place"] = "Hely:";
$calStr["description"] = "Leírás:";
$calStr["add"] = "Hozzáad";
$calStr["update"] = "Frissít";
$calStr["Delete"] = "Töröl";
$calStr["go"] = "Ugrás";
$calStr["disabled"] = "A naptár funkció ki lett kapcsolva.";
?>