<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/hu/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "Tйma";
$composeHStrings[1] = "Feladу";
$composeHStrings[2] = "Cнmzett";
$composeHStrings[3] = "Mбsolat";
$composeHStrings[4] = "Vakmбsolat";
$composeHStrings[5] = "Dбtum";


$composeStrings[0] = "Levйlнrбs";
$composeStrings[1] = "Levйl kьldйse";
$composeStrings[2] = "Feltцltйs";
$composeStrings[3] = "Alбнrбs";
$composeStrings[4] = "Mellйklet";
$composeStrings[5] = "Cнmjegyzйk mutatбsa";
$composeStrings[6] = "Cнmjegyzйk takarбsa";
$composeStrings[7] = "Ьzenet:";
$composeStrings[8] = "Hozzбad";
$composeStrings[9] = "%d -n, %s irta:\n";
$composeStrings[10] = "--- Eredeti ьzenet---\n";
$composeStrings[11] = "Ablak zбrбsa";

$composeStrings[12] = "Helyesнrбs ellenхrzйs";
$composeStrings[13] = "Javнtбs";
$composeStrings[14] = "Mellхz";
$composeStrings[15] = "Lehetйsges hibбk";
$composeStrings[16] = "Javнtбsok";
$composeStrings[17] = "mellхz";
$composeStrings[18] = "tцrцl";

$composeStrings["title"] = "Ъj ьzenet szerkesztйse";


$composeErrors[0] = "A Tйma nincs kitцltve. Kйrjьk, irjon be egy tйmбt vagy kattintson ujra a \"".$composeStrings[1]."\" gombra.";
$composeErrors[1] = "A \"Feladу\" nincs kitцltve.  Kйrjьk, irja be az Цn e-mail cнmйt.";
$composeErrors[2] = "A \"Cнmzett\" nincs kitцltve.  Kйrjьk, irja be a Cнmzett e-mail cнmйt.";
$composeErrors[3] = "Sikertelen feltцltйs";
$composeErrors[4] = "Nem jцtt fбjl.";
$composeErrors[5] = "%3 mбsodpercenkйnt csak %1 cimzettnek (цsszesen %2-nek) kьldhet ьzenetet azйrt, hogy a kйretlen levelek (SPAM) kьldйsйt elkerьljьk.";

$composeErrors[6] = "Nincs helyesнrбsi hiba.";
$composeErrors[7] = "Ezen a nyelven nem lehet ellenхrizni a helyesнrбst.";
$composeErrors[8] = "(%s szуtбr)";

?>