<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/hu/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Címjegyzék";
$cStrings[1] = "Új bejegyzés";
$cStrings[2] = " Címjegyzék ";
$cStrings[3] = "Név";
$cStrings[4] = "Email";
$cStrings[5] = "URL (Web-cím";
$cStrings[6] = "Csoport";
$cStrings[7] = "Megjegyzések";
$cStrings[8] = "Címek hozzáadása/törlése";
$cStrings[9] = "Email";
$cStrings[10] = "Üzenetküldés";

$cStrings["close"] = "Bezár";
$cStrings["addto"] = "Bejegyzés hozzáadása: %s";
$cStrings["showgrp"] = "%s mutatása";
$cStrings["all"] = "Mind";
$cStrings["instructions"] = "Kattints a névre a hozzáadáshoz. A csoport nevére kattintva az egész csoportot hozzáadhatod.";


$cErrors[0] = "A címjegyzék üres";


?>