<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/hu/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Ir";
$ecStrings[1] = "Hozz&#225;ad";
$ecStrings[2] = " C&#237;mjegyz&#233;k ";
$ecStrings[3] = "N&#233;v";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL (Web-C&#237;m";
$ecStrings[6] = "Csoport";
$ecStrings[7] = "Megjegyz&#233;sek";
$ecStrings[8] = "Otthoni telefonsz&#225;m";
$ecStrings[9] = "Munkahelyi telefonsz&#225;m";
$ecStrings[10] = "Mobil telefonsz&#225;m";
$ecStrings[11] = "Lakc&#237;m";
$ecStrings[12] = "M&#225;sik Email";
$ecStrings[13] = "T&#246;rl&#233;s";
$ecStrings[14] = "Egy&#233;b";


$errors[0] = "Nem tudtuk a c&#237;met bejegyezni - adatb&#225;zis hiba.";
$errors[1] = "Ez a c&#237;m m&#225;r be van jegyezva.";
$errors[2] = "Kattintson ";
$errors[3] = "ide";
$errors[4] = " a bejegyz&#233;st megirni.";
$errors[5] = "Ismeretlen vagy visszautas&#237;tott c&#237;m.";
$errors[6] = "Biztos abban hogy t&#246;r&#246;lni k&#237;v&#225;nja\"";
$errors[7] = "\"?";

?>