<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/hu/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings[0] = "Mapp&#225;k";
$efStrings[1] = "&#218;j mappa l&#233;trehoz&#225;sa";
$efStrings[2] = "Mappa l&#233;trehoz&#225;sa :";
$efStrings[3] = "L&#233;trehoz&#225;s";
$efStrings[4] = "Mappa t&#246;rl&#233;se";
$efStrings[5] = "T&#246;rl&#233;s";
$efStrings[6] = "Mappa nev&#233;nek m&#243;dos&#237;t&#225;sa";
$efStrings[7] = "N&#233;vm&#243;dos&#237;t&#225;s ";
$efStrings[7] = "&#193;tnevez&#233;s";
$efStrings[8] = "El&#337;fizetett mapp&#225;k";
$efStrings[9] = "El&#337;fizet&#233;s";
$efStrings[10] = "Lemondott mapp&#225;k";
$efStrings[11] = "Lemond&#225;s";


$errors[0] = "Mappa l&#233;trehoz&#225;sa: ";
$errors[1] = "Mappa l&#233;trehoz&#225;sa nem siker&#252;lt: ";
$errors[2] = "T&#246;r&#246;lt mappa: ";
$errors[3] = "Mappa t&#246;rl&#233;se nem siker&#252;lt: ";
$errors[4] = "M&#243;dos&#237;tott mappa : ";
$errors[5] = "Mappa nev&#233;nek m&#243;dos&#237;t&#225;sa nem siker&#252;lt: ";
$errors[6] = "Ez csak IMAP postafi&#243;kok eset&#233;ben lehets&#233;ges.";

?>