<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "Azonosítók";
$piStrings["edit"] = "Szerkeszt";
$piStrings["name"] = "Név";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "Válasz cím";
$piStrings["sig"] = "Aláírás";
$piStrings["add"] = "Hozzáad";
$piStrings["new"] = "Új azonosító";
$piStrings["edit_ident"] = "Azonosító szerkesztése";
$piStrings["delete"] = "Töröl";
$piStrings["setdef"] = "Beállítás alapértelmezettként";
$piStrings["isdef"] = "(alapértelmezett)";

$piError[1] = "Szükséges egy név vagy email cím";

?>
