<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/hu/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "Adja meg a HTML szinkódot mindegyik részhez .";
$pcStrings["0.1"] = "Hasznája";
$pcStrings["0.2"] = "Szinkód-táblázatot";
$pcStrings["0.3"] = " a megfelelö szinkódok megtalálásához.";
$pcStrings["0.4"] = "A téma felülbírálhatja a beállított értékeket.";
$pcStrings["1.0"] = "Eszközlista";
$pcStrings["2.0"] = "Mappalista";
$pcStrings["3.0"] = "Központi";
$pcStrings["3.1"] = "Fejléc háttér: ";
$pcStrings["3.2"] = "Fejléc szöveg: ";
$pcStrings["3.3"] = "Sötét háttér: ";
$pcStrings["3.4"] = "Világos szöveg: ";
$pcStrings["4.0"] = "Vegyes";
$pcStrings["4.1"] = "Idézet: ";
$pcStrings["5.0"] = "Betûtípusok";
$pcStrings["5.1"] = "Betûtípus";
$pcStrings["5.2"] = "Méret: ";
$pcStrings["5.3"] = "Kis méretû betû: ";
$pcStrings["5.4"] = "Menü betû méret: ";
$pcStrings["5.5"] = "Mappalista betû méret: ";

							
$pcPortions = array( "Háttér: ", "Link: ", "Szöveg: ", "Kiemel: ");

?>
