<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Vissza";
$rmStrings[1] = "Válasz";
$rmStrings[2] = "Továbbítás";
$rmStrings[3] = "Mégse töröl";
$rmStrings[4] = "Töröl";
$rmStrings[5] = "Üzenet áthelyezése";
$rmStrings[6] = "Részek";
$rmStrings[7] = "Ez HTML üzenet. ";
$rmStrings[8] = "Az olvasáshoz kattintson ide.";
$rmStrings[9] = "Forrás";
$rmStrings[10] = "Méret";
$rmStrings[11] = "Olvasatlanként kijelölni";
$rmStrings[12] = "Fejlécek bemutatása";
$rmStrings[13] = "Nemkívánt üzenet jelzése";
$rmStrings[14] = "Válasz mindenkinek";
$rmStrings[15] = "Már válaszoltál erre a levélre";
$rmStrings[16] = "Nyomtatás";

?>