<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/hu/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "Érvénytelen keresés:  Érvénytelen mezö";
$searchErrors["empty"] = "Érvénytelen keresés:  Üres keresés";
$searchErrors["date"] = "Érvénytelen keresés:  Hiányos dátum";

?>