<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/hu/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "Mappák";
$toolStrings["inbox"] = "Postaláda";
$toolStrings["compose"] = "Üzenet írása";
$toolStrings["calendar"] = "Naptár";
$toolStrings["contacts"] = "Címjegyzék";
$toolStrings["bookmarks"] = "Könyvjelzõk";
$toolStrings["search"] = "Keresés";
$toolStrings["prefs"] = "Beállítások";
$toolStrings["logout"] = "Kilépés";
$toolStrings["go"] = "Megy";

?>