<?php
/*
FILE: themes/theme_name/info.inc
PURPOSE:
	Various information related to theme
*/

/**
	$THEME_OVERRIDES
		The array contains elements with the
		same keys as $my_colors.  Fields that
		are overrided by the theme (in override.inc)
		should have a value of '1', while 
		settings that aren't overrided should
		have a value of '0'.
**/

$THEME_OVERRIDES["tool_bg"] = 1;
$THEME_OVERRIDES["tool_link"] = 1;
$THEME_OVERRIDES["folder_bg"] = 1;
$THEME_OVERRIDES["folder_link"] = 1;
$THEME_OVERRIDES["main_bg"] = 1;
$THEME_OVERRIDES["main_hilite"] = 1;
$THEME_OVERRIDES["main_text"] = 1;
$THEME_OVERRIDES["main_link"] = 1;
$THEME_OVERRIDES["main_head_bg"] = 1;
$THEME_OVERRIDES["main_head_txt"] = 1;
$THEME_OVERRIDES["main_darkbg"] = 1;
$THEME_OVERRIDES["main_light_txt"] = 1;
$THEME_OVERRIDES["quotes"]=0;
$THEME_OVERRIDES["font_family"]=0;
$THEME_OVERRIDES["font_size"]=0;
$THEME_OVERRIDES["small_font_size"]=0;
$THEME_OVERRIDES["menu_font_size"]=0;
$THEME_OVERRIDES["folderlist_font_size"]=0;

?>