<?php
/*

FILE: themes/theme_name/override.inc
PURPOSE:
	Override certain user preferences.  
	Use with care.
*/

//This is a particularly strict override,
//it overrides all user configurable colors.
//Preferences you would like to allow users
//to change should be commented out.

$my_colors["tool_bg"] = "#222244";
$my_colors["tool_link"] = "#FFFFFF";
$my_colors["folder_bg"] = "#222244";
$my_colors["folder_link"] = "#FFFFFF";
$my_colors["main_bg"] = "#f0f0f0";
$my_colors["main_hilite"] = "#b1b1b9";
$my_colors["main_text"] = "#000000";
$my_colors["main_link"] = "#222222";
$my_colors["main_head_bg"] = "#222244";
$my_colors["main_head_txt"] = "#FFFFFF";
$my_colors["main_darkbg"] = "#444466";
$my_colors["main_light_txt"] = "#FFFFFF";

//dark: 000033, lighter-dark: 333366
//dark: 4B4B69, lighter-drak: 5B5B79

//$my_colors["quotes"]="blue";
//$my_colors["font_family"]="";
//$my_colors["font_size"]="12";
//$my_colors["small_font_size"]="10";
//$my_colors["menu_font_size"]="12";

?>