<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Add Schedule";
$calStr["edit_schedule"] = "Edit Schedule";
$calStr["weekof"] = "Week of: %d";
$calStr["title"] = "Title:";
$calStr["color"] = "Color:";
$calStr["colors"] = array("#990000"=>"Dark Red", "#FF0000"=>"Red", "#000099"=>"Deep Blue", "#0000FF"=>"Blue", 
					"#006600"=>"Dark Green", "#00FF00"=>"Green", "#9900FF"=>"Purple", "#00FFFF"=>"Cyan",
					"#FF6600"=>"Orange", "#FFFF00"=>"Yellow", "#FF00FF"=>"Magenta", ""=>"No color");
$calStr["starts"] = "Starts on:";
$calStr["ends"] = "Ends on:";
$calStr["from"] = "from:";
$calStr["until"] = "until:";
$calStr["repeat_on"] = "Repeat on";
$calStr["of"] = "of every";
$calStr["weeks"] = array(1=>"first week", 2=>"second week", 3=>"third week", 4=>"fourth week"); 
$calStr["week_blurb"] = "...of every month (until end date).<br>Will repeat on all weeks if none are selected.";
$calStr["monthly"] = "Repeat monthly";
$calStr["yearly"] = "Repeat annually";
$calStr["place"] = "Place:";
$calStr["description"] = "Description:";
$calStr["add"] = "Add";
$calStr["update"] = "Update";
$calStr["Delete"] = "Delete";
?>