<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/pl/contacts.inc
	(C) 2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Ksi±¿ka Adresowa";
$cStrings[1] = "Dodaj Osobê";
$cStrings[2] = " Ksi±¿ka Adresowa";
$cStrings[3] = "Imiê";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Grupa";
$cStrings[7] = "Komentarze";
$cStrings[8] = "Dodaj/Edytuj Wpis";
$cStrings[9] = "Email";
$cStrings[10] = "Nowa Wiadomo¶æ";


$cErrors[0] = "Lista kontaktów jest pusta";


?>