<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
	lang/pl/dates.inc
	(C) 2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime["dsow"] = array ("Nd","Pn","Wt","Œr","Czw","Pt",6 => "So");
$lang_datetime["today"] = "Dzisiaj %t";
$lang_datetime["lastweek"] = "%w %t";
$lang_datetime["thisyear"] = "%d/%m";
$lang_datetime["prevyears"] = "%d/%m/%y";


?>