<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/pl/edit_contact.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Edytuj";
$ecStrings[1] = "Dodaj";
$ecStrings[2] = " Ksi±¿ka adresowa";
$ecStrings[3] = "Imiê";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Grupa";
$ecStrings[7] = "Komentarze";
$ecStrings[8] = "Tel. Domowy";
$ecStrings[9] = "Tel. S³u¿bowy";
$ecStrings[10] = "Tel. Komórkowy";
$ecStrings[11] = "Adres";
$ecStrings[12] = "Drugi Email";
$ecStrings[13] = "Usuñ";
$ecStrings[14] = "Inne";


$errors[0] = "Nie mogê dodaæ wpisu:  b³±d bazy danych.";
$errors[1] = "Istnieje ju¿ wpis o podanym adresie.";
$errors[2] = "Naciœnij ";
$errors[3] = "tutaj";
$errors[4] = " by modyfikowaæ wpis.";
$errors[5] = "Osoba nie zosta³a odnaleziona, lub brak dostêpu.";
$errors[6] = "Czy na pewno chcesz usun±æ wpis dla \"";
$errors[7] = "\"?";

?>