<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/pl/edit_folders.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings[0] = "Zarz&#261;dzanie folderami";
$efStrings[1] = "Utw&#243;rz nowy folder";
$efStrings[2] = "Utw&#243;rz folder: ";
$efStrings[3] = "Utw&#243;rz";
$efStrings[4] = "Usu&#324; folder";
$efStrings[5] = "Usu&#324;";
$efStrings[6] = "Zmie&#324; nazw&#281; folderu";
$efStrings[7] = "Rename";


$errors[0] = "Utw&#243;rzono folder: ";
$errors[1] = "Nie mo&#380;na utworzy&#263; folderu: ";
$errors[2] = "Usuni&#281;to folder: ";
$errors[3] = "Nie mo&#380;na usun&#261;&#263; folderu: ";
$errors[4] = "Zmieniono nazw&#281; folderu: ";
$errors[5] = "Nie mo&#380;na zmieni&#263; nazwy folderu: ";
$errors[6] = "Obs&#322;uga folder&#243;w jest dost&#281;pna tylko dla protoko&#322;u IMAP.";

?>