<?php
/********************************************************
	lang/eng/filters.inc
	(C)2001-2004 Ryo Chijiiwa <Ryo@IlohaMail.org>
	(C)2004 Cezary Jackiewicz <cjackiewicz@poczta.onet.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/filters.inc");

$fltr["filter"] = "Filtry";
$fltr["conditions"] = "Warunki";
$fltr["actions"] = "Akcje";
$fltr["auto"] = "Automatycznie przenie¶ do skrzynki odbiorczej";
$fltr["deletemsg"] = "Usuñ wiadomo¶æ";
$fltr["&"] = "i";
$fltr["|"] = "lub";
$fltr["^"] = "zaczyna siê na";
$fltr["<"] = "zawiera";
$fltr["$"] = "koñczy siê na";
$fltr["="] = "równa siê";
$fltr["!"] = "nierówna siê";
$fltr["field"] = "Pole";
$fltr["condition"] = "Warunek";
$fltr["action"] = "Akcja";
$fltr["name"] = "Nazwa";
$fltr["sort_order"] = "Priorytet";
$fltr["edit"] = "edycja";
$fltr["add"] = "Dodaj filtr";
$fltr["edit_filter"] = "Edycja filtru";
$fltr["delete"] = "Usuñ";
$fltr["filters"] = "Filtry";
$fltr["new"] = "Nowy filtr";
$fltr["status"] = "Status";
$fltr["stat_en"] = "w³±czony";
$fltr["stat_dis"] = "wy³±czony";
$fltr["is_active"] = "filtr jest w³±czony";
$fltr["other"] = "Inner";
$fltr["move"] = "Przenie¶ do";
$fltr["copy"] = "Skopiuj do";
$fltr["do_nothing"] = "Bez akcji";
$fltr["add_cond"] = "Dodaj warunek";
$fltr["remove_cond"] = "Usuñ warunek";
$fltr["condition_str"] = "%b %c %t";

$f_hlp["priority"] = "(O wy¿szym priorytecie wykonuj± siê pierwsze.)";

$f_err["no_name"] = "Wprowad¼ nazwê dla regu³y filtru\n";
$f_err["no_act"] = "Wybierz jedn± lub wiêcej akcji dla tej regu³y\n";
$f_err["no_cond"] = "Wybierz jeden lub wiêcej warunków dla tej regu³y\n";
$f_err["inv_param"] = "B³êde parametry dla wybranej akcji\n";
$f_err["inv_sort"] = "Kolejno¶æ sortowania musi byæ liczb±\n";

?>
