<?php
include("../lang/eng/prefs.inc"); // <-- do not delete
/********************************************************
	lang/pl/prefs.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$prefHeaderStrings[0] = "Ustawienia";
$prefHeaderStrings[1] = "Ogólne";
$prefHeaderStrings[2] = "Kolory";

											
$prefsStrings["0.0"] = "To¿samo¶æ";
$prefsStrings["0.1"] = "Imiê: ";
$prefsStrings["0.2"] = "Email: ";
$prefsStrings["1.0"] = "Miedzynarodowe";
$prefsStrings["1.1"] = "Interfejs: ";
$prefsStrings["1.2"] = "Zestaw Znaków: ";
$prefsStrings["1.3"] = "Strefa Czasowa: ";
$prefsStrings["2.0"] = "Opcje Wy¶wietlania Listy";
$prefsStrings["2.1"] = "Pokazuj do ";
$prefsStrings["2.2"] = " obiektów";
$prefsStrings["2.3"] = "Poka¿ rozmiar";
$prefsStrings["2.4"] = "Sortuj wed³ug: ";
$prefsStrings["2.5"] = "";
$prefsStrings["2.6"] = "Porz±dek sortowania: ";
$prefsStrings["2.7"] = "";
$prefsStrings["2.8"] = "Poka¿ listê folderów";
$prefsStrings["3.0"] = "Opcje Autozapisu";
$prefsStrings["3.1"] = "Zachowuj wys³ane wiadomo¶ci.";
$prefsStrings["3.2"] = "Zachowuj wiadomo¶ci wys³ane w folderze: ";
$prefsStrings["3.3"] = "";
$prefsStrings["3.4"] = "Automatycznie opró¿niaj kosz";
$prefsStrings["3.5"] = "Przeno¶ skasowane listy do folderu: ";
$prefsStrings["3.6"] = "";
$prefsStrings["3.7"] = "Glówny Katalog: ";
$prefsStrings["3.8"] = "Inne";
$prefsStrings["4.0"] = "Opcje Wy¶wietlania Wiadomo¶ci";
$prefsStrings["4.1"] = "Ogl±daj w ramce";
$prefsStrings["4.2"] = "Koloruj cytaty";
$prefsStrings["4.3"] = "W³±czenie tej opcji mo¿e spowolnic pracê systemu.";
$prefsStrings["4.4"] = "Zamieniaj adresy URL na odno¶niki";
$prefsStrings["4.5"] = "Pokazuj wiadomo¶ci HTML";
$prefsStrings["4.6"] = "Wklejaj obrazki";
$prefsStrings["5.0"] = "Sygnatura";
$prefsStrings["5.1"] = "Domy¶lne wstawianie sygnatury";
$prefsStrings["5.2"] = "";


$sort_fields=array("DATE"=>"Data", "SUBJECT"=>"Temat", "SIZE"=>"Rozmiar");
$sort_orders=array("ASC"=>"Rosn±co", "DESC"=>"Malej±co");

$prefsButtonStrings = array( 0=> "Aktualizuj", 1=>"Zastosuj", 2=> "Anuluj", 3=> "Domy¶lne");

$prefs_new_user = "Wygl±da na to, ¿e logujesz sie po raz pierwszy...witaj!<br>";
$prefs_new_user .= "Proszê dokonaæ nastêpuj±cych ustawieñ, potem nacisn±æ \"Zastosuj\"";
?>