<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/pl/cp.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "Dla ka¿dego elementu wprowad¼ kod koloru HTML.";
$pcStrings["0.1"] = "U¿yj ";
$pcStrings["0.2"] = "Tabeli Kolorów";
$pcStrings["0.3"] = " by znale¼æ w³a¶ciwe kody kolorów.";
$pcStrings["1.0"] = "Pasek Narzêdziowy";
$pcStrings["2.0"] = "Lista Folderów";
$pcStrings["3.0"] = "G³ówne";
$pcStrings["4.0"] = "Ró¿ne";
$pcStrings["4.1"] = "Cytaty: ";

							
$pcPortions = array( "T³o: ", "Odno¶niki: ", "Tekst: ", "Pod¶wietlenie: ");

?>
