<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/pl/read_message.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Poprzednia";
$rmStrings[1] = "Odpowiedz";
$rmStrings[2] = "Prze¶lij";
$rmStrings[3] = "Przywróc";
$rmStrings[4] = "Usuñ";
$rmStrings[5] = "Plik";
$rmStrings[6] = "Cze¶ci";
$rmStrings[7] = "To jest wiadomo¶æ HTML. ";
$rmStrings[8] = "Naci¶nij tu by j± przeczytaæ.";
$rmStrings[9] = "¬ród³o";
$rmStrings[10] = "Rozmiar";
$rmStrings[11] = "Oznacz Jako Nieczytan±";
$rmStrings[12] = "Poka¿ Nag³ówek";
$rmStrings[13] = "Poinformuj o Spamie";
$rmStrings[14] = "Odpowiedz Wszystkim";

?>