<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/pl/tool.inc
	(C)2002 Marcin Piliszczuk <marti@net26.pl>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "Katalogi";
$toolStrings["inbox"] = "Skrzynka odbiorcza";
$toolStrings["compose"] = "Nowa wiadomo¶æ";
$toolStrings["contacts"] = "Ksi±¿ka adresowa";
$toolStrings["search"] = "Szukaj";
$toolStrings["prefs"] = "Ustawienia";
$toolStrings["logout"] = "Wyloguj";
$toolStrings["go"] = "Id¼";

?>