<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.2 setup script
 * Date: Thu, 02 Aug 2012 14:14:52 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'localhost';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['LogoutURL'] = '../../../?module=phpmyadmin';

/* End of servers configuration */

$cfg['blowfish_secret'] = '501a880e5971f3.79068075';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = 'c:/windows/Temp/';
$cfg['SaveDir'] = 'c:/windows/Temp/';
$cfg['BZipDump'] = false;
$cfg['TitleDefault'] = '@HTTP_HOST@ | zpanel | @PHPMYADMIN@';
$cfg['UserprefsDisallow'] = array('PmaNoRelation_DisableWarning', 'SuhosinDisableWarning', 'McryptDisableWarning');
$cfg['QueryHistoryDB'] = true;
$cfg['RetainQueryBox'] = true;
$cfg['SQLQuery']['Validate'] = true;
$cfg['SQLValidator']['use'] = true;
$cfg['ShowPhpInfo'] = true;
$cfg['SaveCellsAtOnce'] = true;
$cfg['ShowDisplayDirection'] = true;
$cfg['LightTabs'] = true;
$cfg['Import']['ods_col_names'] = true;
$cfg['Export']['sql_dates'] = true;
$cfg['Servers'][$i]['AllowNoPassword'] = false;
$cfg['SuhosinDisableWarning'] = true;
$cfg['servers'][$i]['hide_db'] = 'information_shema';
?>