<?php
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Edit";
$ecStrings[1] = "Add";
$ecStrings[2] = " Contact";
$ecStrings[3] = "Name";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Group";
$ecStrings[7] = "Comments";
$ecStrings[8] = "Home Phone";
$ecStrings[9] = "Work Phone";
$ecStrings[10] = "Cell Phone";
$ecStrings[11] = "Address";
$ecStrings[12] = "Alt. Email";
$ecStrings[13] = "Delete";
$ecStrings[14] = "Other";


$errors[0] = "Couldn't add contact:  database error.";
$errors[1] = "An entry with the address already exists.";
$errors[2] = "Click ";
$errors[3] = "here";
$errors[4] = " to edit that entry instead.";
$errors[5] = "Contact not found, or access denied.";
$errors[6] = "Are you sure you would like to delete entry for \"";
$errors[7] = "\"?";

?>