<?php
/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "Enter an HTML color code for each component.";
$pcStrings["0.1"] = "Use the ";
$pcStrings["0.2"] = "Color Code Chart";
$pcStrings["0.3"] = " to find the right color codes.";
$pcStrings["0.4"] = "Settings that the theme overrides can not be modified.";
$pcStrings["1.0"] = "Tool Bar";
$pcStrings["2.0"] = "Folder List";
$pcStrings["3.0"] = "Main";
$pcStrings["3.1"] = "Heading Back: ";
$pcStrings["3.2"] = "Heading Text: ";
$pcStrings["3.3"] = "Dark Background: ";
$pcStrings["3.4"] = "Light text: ";
$pcStrings["4.0"] = "Miscellaneous";
$pcStrings["4.1"] = "Quotes: ";
$pcStrings["5.0"] = "Fonts";
$pcStrings["5.1"] = "Font Family";
$pcStrings["5.2"] = "Font Size: ";
$pcStrings["5.3"] = "Small Font Size: ";
$pcStrings["5.4"] = "Menu Font Size: ";
$pcStrings["5.5"] = "Folderlist Font Size: ";

							
$pcPortions = array( "Background: ", "Links: ", "Text: ", "Hilight: ");

?>
