<?php
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "Identities";
$piStrings["edit"] = "Edit";
$piStrings["name"] = "Name";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "Reply-To";
$piStrings["sig"] = "Signature";
$piStrings["add"] = "Add";
$piStrings["new"] = "New Identity";
$piStrings["edit_ident"] = "Edit Identity";
$piStrings["delete"] = "Delete";
$piStrings["setdef"] = "Set to default";
$piStrings["isdef"] = "(Default)";

$piError[1] = "Name or email required";

?>
