<?php
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/read_message.inc");


$rmStrings[0] = "Index";
$rmStrings[1] = "Reply";
$rmStrings[2] = "Forward";
$rmStrings[3] = "Undelete";
$rmStrings[4] = "Delete";
$rmStrings[5] = "Move";
$rmStrings[6] = "Parts";
$rmStrings[7] = "This is an HTML message. ";
$rmStrings[8] = "Click here to read it.";
$rmStrings[9] = "Source";
$rmStrings[10] = "Size";
$rmStrings[11] = "Unread";
$rmStrings[12] = "Show Header";
$rmStrings[13] = "Report Spam";
$rmStrings[14] = "Re. To All";
$rmStrings[15] = "You have replied to this message";
$rmStrings[16] = "Print";

?>