<?php
/********************************************************
	lang/eng/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/search_errors.inc");

$searchErrors["field"] = "Invalid search criteria:  Invalid field";
$searchErrors["empty"] = "Invalid search criteria:  Empty search string";
$searchErrors["date"] = "Invalid search criteria:  Date not specified";

?>