<?php
/********************************************************
	lang/eng/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Suosikit";
$bmStrings["identities"] = "Henkil&ouml;llisyydet";
$bmStrings["edit"] = "Tallenna";
$bmStrings["name"] = "Nimi";
$bmStrings["url"] = "Osoite (URL)";
$bmStrings["rss"] = "RSS/RDF";
$bmStrings["category"] = "Ryhm&auml;";
$bmStrings["other"] = "Uusi-&gt;";
$bmStrings["comments"] = "Kuvaus";
$bmStrings["add"] = "Tallenna";
$bmStrings["new"] = "Uusi";
$bmStrings["edit_url"] = "Muokkaus";
$bmStrings["delete"] = "Poista";

$bmError[1] = "Nimi ja osoite pit&auml;&auml; olla.";
$bmError[2] = "T&auml;m&auml; ominaisuus on poistettu k&auml;yt&ouml;st&auml;.";
?>
