<?php
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/contacts.inc");

$cStrings[0] = "Yhteystiedot";
$cStrings[1] = "Lis&auml;&auml; yhteystieto";
$cStrings[2] = " Contact";
$cStrings[3] = "Nimi";
$cStrings[4] = "S&auml;hk&ouml;postiosoite";
$cStrings[5] = "URL";
$cStrings[6] = "Ryhm&auml;";
$cStrings[7] = "Comments";
$cStrings[8] = "Tallenna yhteystieto";
$cStrings[9] = "Email";
$cStrings[10] = "Kirjoita viesti";

$cStrings["close"] = "Sulje ikkuna";
$cStrings["addto"] = "Lis&auml;t&auml;&auml;n kentt&auml;&auml;n  %s";
$cStrings["showgrp"] = "N&auml;yt&auml; ryhm&auml;  %s";
$cStrings["all"] = "Kaikki";
$cStrings["instructions"] = "Lis&auml;&auml; yhteystietoja viestiin klikkaamalla nimist&auml;.  Ryhm&auml;n otsikosta voit lis&auml;t&auml; kaikki ryhm&auml;n j&auml;senet.";
$cStrings["share"] = "N&auml;yt&auml; t&auml;m&auml; yhteystieto kaikille";
$cStrings["add_contact"] = "Uusi yhteystieto";
$cStrings["edit_contact"] = "Muokkaa yhteystietoa";
$cStrings["add"] = "Tallenna"; // add
$cStrings["edit"] = "Tallenna"; // update
$cStrings["export"] = "Tallenna tiedostoon";
$cStrings["import"] = "Lue tiedostosta";
$cStrings["exportall"] = "Kaikki yhteystiedot";
$cStrings["exportgroups"] = "Valitut ryhm&auml;t";
$cStrings["exportentries"] = "Valitut yhteystiedot";
$cStrings["format"] = "Tiedostomuoto";
$cStrings["filename"] = "Tiedoston nimi";

$cErrors[0] = "Yhteystietoluettelo on tyhj&auml;";
$cErrors[1] = "Could not access specified entry.";


?>
