<?php
/********************************************************
	lang/eng/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_folders.inc");

$efStrings[0] = "Kansioiden muokkaus";
$efStrings[1] = "Tee uusi kansio";
$efStrings[2] = "Nimi: ";
$efStrings[3] = "Tee";
$efStrings[4] = "Poista kansio";
$efStrings[5] = "Poista";
$efStrings[6] = "Muuta kansion nimi";
$efStrings[7] = "Muuta";
$efStrings[8] = "Postikansiot";
$efStrings[9] = "N&auml;yt&auml; merkityt postikansioina";
$efStrings[10] = "Tiedostoluettelo";
$efStrings[11] = "Piilota merkityt";


$errors[0] = "Tehtiin kansio: ";
$errors[1] = "Kansion tekeminen ei onnistunut: ";
$errors[2] = "Poistettiin kansio: ";
$errors[3] = "Kansion poistaminen ei onnistunut: ";
$errors[4] = "Muutettiin kansion nimi: ";
$errors[5] = "Nimen muuttaminen ei onnistunut: ";
$errors[6] = "Postikansioita voi k&auml;ytt&auml;&auml; vain IMAP-palvelimella.";

?>
