<?php
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Edit";
$ecStrings[1] = "Add";
$ecStrings[2] = " Contact";
$ecStrings[3] = "Nimi";
$ecStrings[4] = "S&auml;hk&ouml;posti";
$ecStrings[5] = "Kotisivu";
$ecStrings[6] = "Ryhm&auml;";
$ecStrings[7] = "Muuta";
$ecStrings[8] = "Kotipuhelin";
$ecStrings[9] = "Ty&ouml;puhelin";
$ecStrings[10] = "Matkapuhelin";
$ecStrings[11] = "Postiosoite";
$ecStrings[12] = "2. s&auml;hk&ouml;posti";
$ecStrings[13] = "Poista";
$ecStrings[14] = "Uusi (alle)";
$ecStrings[15] = "Etunimi";
$ecStrings[16] = "Sukunimi";
$ecStrings[17] = "Katuosoite";
$ecStrings[18] = "Kaupunki";
$ecStrings[19] = "Alue / osavaltio";
$ecStrings[20] = "Postinumero";
$ecStrings[21] = "Maa";
$ecStrings[22] = "Cancel";


$errors[0] = "Yhteystiedon tallennus ei onnistunut: tietokantavirhe.";
$errors[1] = "T&auml;m&auml; osoite on jo toisessa yhteystiedossa.";
$errors[2] = "Paina ";
$errors[3] = "t&auml;st&auml;";
$errors[4] = " n&auml;hd&auml;ksesi sen yhteystiedon.";
$errors[5] = "Yhteystietoa ei l&ouml;ydy, tai k&auml;ytt&ouml;oikeuksia ei ole.";
$errors[6] = "Haluatko varmasti poistaa yhteystiedon \"";
$errors[7] = "\"?";

?>
