<?php 
/********************************************************
	lang/en/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="K&auml;ytt&auml;j&auml;tunnus";
$loginStrings[1]="Salasana";
$loginStrings[2]="Palvelin";
$loginStrings[3]="Tyyppi";
$loginStrings[4]="Postihakemisto";
$loginStrings[5]="Kieli";
$loginStrings[6]="Kirjaudu";

$loginErrors[0]="Palvelinta ei ole hyv&auml;ksytty";
$loginErrors[1]="Virhe: \"uploads\"-hakemistoa ei ole";
$loginErrors[2]="Virhe: \"users\"-hakemistoa ei ole";
$loginErrors[3]="Virhe: \"sessions\"-hakemistoa ei ole";

?>
