<?php
/********************************************************
	lang/eng/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainMessages["delete"] = "Poistettiin %n viesti(&auml;)";
$mainMessages["move"] = "Siirrettiin %n viesti(&auml;) kansioon %f";

$mainStrings[0] = "N&auml;ytet&auml;&auml;n %p viesti&auml;, yhteens&auml; %n";
$mainStrings[1] = " viesti(&auml;) l&ouml;ydetty";
$mainStrings[2] = "Edelliset";
$mainStrings[3] = "";
$mainStrings[4] = "Seuraavat";
$mainStrings[5] = "";
$mainStrings[6] = "Aihe";
$mainStrings[7] = "Vastaanottaja";
$mainStrings[8] = "L&auml;hett&auml;j&auml;";
$mainStrings[9] = "P&auml;iv&auml;m&auml;&auml;r&auml;";
$mainStrings[10] = "Poista";
$mainStrings[11] = "Tyhjenn&auml; Roskakori";
$mainStrings[12] = "Siirr&auml;";
$mainStrings[13] = "Etsi";
$mainStrings[14] = "Koko";
$mainStrings[15] = "ei otsikkoa";
$mainStrings[16] = "N&auml;yt&auml;";
$mainStrings[17] = "Tarkista uudet";
$mainStrings[18] = "Tyhjenn&auml; kansio";
$mainStrings[19] = "Peruuta";
$mainStrings[20] = "Merkitse %b";
$mainStrings[21] = "luetuksi";
$mainStrings[22] = "lukemattomaksi";
$mainStrings[23] = "Valitse...";
$mainStrings[24] = "Suorita suodattimet";
$mainStrings[25] = "Merkitse";
$mainStrings[26] = "t&auml;rke&auml;ksi";
$mainStrings[27] = "Suodattimet:";
$mainStrings[28] = "kaikki"; // suodattimet
$mainStrings[29] = "Suorita";
$mainStrings[30] = "Pikahaku:";
$mainStrings[31] = "Etsi";
$mainStrings[32] = 'tavalliseksi';


$mainErrors[0] = "No messages found in this folder";
$mainErrors[1] = "T&auml;ss&auml; kansiossa ei ole viestej&auml;.";  // my&ouml;s jos haku ei t&auml;rpp&auml;&auml;
$mainErrors[2] = "Viestien siirto roskakoriin ei onnistunut.";
$mainErrors[3] = "Viestien merkint&auml; poistetuiksi ei onnistunut.";
$mainErrors[4] = "Viestien siirto ei onnistunut.";
$mainErrors[5] = "Trash folder not specified.";
$mainErrors[6] = "Roskakorin tyhjent&auml;minen ei onnistunut.";
$mainErrors[7] = "Haluatko varmasti poistaa KAIKKI VIESTIT kansiosta %f?";
$mainErrors[8] = "Click on the arrows underneath the column headings to move them.<br>When you're done, simply close the window.";



?>
