<?php
/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "Kirjoita v&auml;reihin HTML-v&auml;rikoodit.";
$pcStrings["0.1"] = "Voita katsoa v&auml;rikoodit ";
$pcStrings["0.2"] = "v&auml;rikooditaulukosta";
$pcStrings["0.3"] = ".";
$pcStrings["0.4"] = "Teeman asettamia v&auml;rej&auml; ei voi muuttaa.";
$pcStrings["1.0"] = "Ty&ouml;kalupalkki";
$pcStrings["2.0"] = "Kansioluettelo";
$pcStrings["3.0"] = "P&auml;&auml;kehys";
$pcStrings["3.1"] = "Otsikkotausta: ";
$pcStrings["3.2"] = "Otsikkoteksti: ";
$pcStrings["3.3"] = "Tumma tausta: ";
$pcStrings["3.4"] = "Vaalea teksti: ";
$pcStrings["4.0"] = "Sekalaista";
$pcStrings["4.1"] = "Lainaukset: ";
$pcStrings["5.0"] = "Fontit";
$pcStrings["5.1"] = "Fontti";
$pcStrings["5.2"] = "Tekstin koko: ";
$pcStrings["5.3"] = "Pienen tekstin koko: ";
$pcStrings["5.4"] = "Valikon tekstien koko: ";
$pcStrings["5.5"] = "Kansioluettelon tekstien koko: ";
$pcStrings["5.6"] = "Muu fontti: ";

							
$pcPortions = array( "Tausta: ", "Linkit: ", "Teksti: ", "Korostus: ");

?>
