<?php
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "Henkil&ouml;llisyydet";
$piStrings["edit"] = "Muokkaa";
$piStrings["name"] = "Nimi";
$piStrings["email"] = "S&auml;hk&ouml;postiosoite";
$piStrings["replyto"] = "Vastausosoite";
$piStrings["sig"] = "Allekirjoitus";
$piStrings["add"] = "Lis&auml;&auml;";
$piStrings["new"] = "Uusi henkil&ouml;llisyys";
$piStrings["edit_ident"] = "Henkil&ouml;llisyyden muokkaus";
$piStrings["delete"] = "Poista";
$piStrings["setdef"] = "K&auml;yt&auml; oletuksena";
$piStrings["isdef"] = "(Oletus)";

$piError[1] = "Nimi ja s&auml;hk&ouml;postiosoite pit&auml;&auml; olla";

?>
