<?php
/********************************************************
	lang/eng/prefs.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/prefs.inc");

$prefHeaderStrings[0] = "Asetukset";
$prefHeaderStrings[1] = "Yleiset";
$prefHeaderStrings[3] = "Henkil&ouml;llisyydet";
$prefHeaderStrings[2] = "Ulkon&auml;k&ouml;";
$prefHeaderStrings[4] = "Suodattimet";

											
$prefsStrings["0.0"] = "Oletushenkil&ouml;llisyys";
$prefsStrings["0.1"] = "Nimi: ";
$prefsStrings["0.2"] = "S&auml;hk&ouml;posti: ";
$prefsStrings["0.3"] = "Muutoksia voi tehd&auml; kohdassa \"%s\".";
$prefsStrings["0.4"] = "Ei tietoa";
$prefsStrings["1.0"] = "Maa-asetukset";
$prefsStrings["1.1"] = "Kieli: ";
$prefsStrings["1.2"] = "Merkist&ouml;: ";
$prefsStrings["1.3"] = "Aikavy&ouml;hyke: ";
$prefsStrings["1.4"] = "Ajan n&auml;ytt&ouml;: ";
$prefsStrings["1.5"] = array(12=>"12-tuntinen", 24=>"24-tuntinen");
$prefsStrings["1.6"] = "Viikko alkaa ";
$prefsStrings["1.7"] = array(0=>"Sunnuntaina", 1=>"Maanantaina");
$prefsStrings['1.8'] = 'Kes&auml;aika';
$prefsStrings["2.0"] = "Viestiluettelo";
$prefsStrings["2.1"] = "N&auml;ytet&auml;&auml;n ";
$prefsStrings["2.2"] = " rivi&auml; kerralla";
$prefsStrings["2.3"] = "Show size";
$prefsStrings["2.4"] = "J&auml;rjestys: ";
$prefsStrings["2.5"] = "";
$prefsStrings["2.6"] = "Suunta: ";
$prefsStrings["2.7"] = "";
$prefsStrings["2.8"] = "N&auml;yt&auml; kansioluettelo";
$prefsStrings["2.9"] = "Kansioluettelon leveys ";
$prefsStrings["2.10"] = "Tarkista uudet viestit %n sekunnin v&auml;lein";
$prefsStrings["2.11"] = "N&auml;yt&auml; ty&ouml;kalupalkki %m";
$prefsStrings["2.12"] = array("b"=>"alhaalla", "t"=>"ylh&auml;&auml;ll&auml;", "bt"=>"alhaalla ja ylh&auml;&auml;ll&auml;");
$prefsStrings["2.13"] = "Sarakkeiden j&auml;rjestyst&auml; voi muuttaa ";
$prefsStrings["2.14"] = "t&auml;st&auml;";
$prefsStrings["2.15"] = "N&auml;yt&auml; suodatus/pikahaku-ty&ouml;kalupalkki";
$prefsStrings['2.16'] = 'N&auml;yt&auml; viestiluettelo ryhmiteltyn&auml;';
$prefsStrings["3.0"] = "Tallennusasetukset";
$prefsStrings["3.1"] = "S&auml;&auml;st&auml; kopio l&auml;hetetyist&auml; viesteist&auml;";
$prefsStrings["3.2"] = "L&auml;hetettyjen viestien kansio: ";
$prefsStrings["3.3"] = "";
$prefsStrings["3.4"] = "Tyhjenn&auml; roskakori automaattisesti";
$prefsStrings["3.5"] = "Siirr&auml; poistetut viestit kansioon: ";
$prefsStrings["3.6"] = "";
$prefsStrings["3.7"] = "Postihakemisto palvelimella: ";
$prefsStrings["3.8"] = "Muu";
$prefsStrings["3.9"] = "Piilota muut tiedostot kuin postikansiot";
$prefsStrings["3.10"] = "N&auml;yt&auml; tilank&auml;ytt&ouml; %m";
$prefsStrings["3.11"] = array(""=>"ei n&auml;ytet&auml;", "m"=>"viestiluettelossa", "f"=>"kansioluettelossa");
$prefsStrings['3.12'] = 'Keskener&auml;isten viestien kansio ';
$prefsStrings["4.0"] = "Viesti";
$prefsStrings["4.1"] = "N&auml;yt&auml; kehyksess&auml;";
$prefsStrings["4.2"] = "V&auml;rit&auml; lainaukset";
$prefsStrings["4.3"] = "Saattaa olla v&auml;h&auml;n hitaampi (?).";
$prefsStrings["4.4"] = "N&auml;yt&auml; osoitteet linkkein&auml;";
$prefsStrings["4.5"] = "N&auml;yt&auml; HTML-viestit";
$prefsStrings["4.6"] = "N&auml;yt&auml; kuvat automaattisesti";
$prefsStrings["4.7"] = "N&auml;yt&auml; navigointilinkit";
$prefsStrings["4.8"] = "Don't mark messages when traversing";
$prefsStrings['4.9'] = 'Poiston tai siirt&auml;misen j&auml;lkeen n&auml;ytet&auml;&auml;n %menu';
$prefsStrings['4.10']= array('main'=>"Kansio",'next'=>'Seuraava','prev'=>'Edellinen');
$prefsStrings["5.0"] = "Allekirjoitus";
$prefsStrings["5.1"] = "N&auml;yt&auml; allekirjoitus oletuksena";
$prefsStrings["5.2"] = "";
$prefsStrings["6.0"] = "Viestin kirjoitus";
$prefsStrings["6.1"] = "N&auml;yt&auml; yhteystiedot";
$prefsStrings["6.2"] = "N&auml;yt&auml; CC- ja BCC-kent&auml;t";
$prefsStrings["6.3"] = "Sulje ikkuna l&auml;hetyksen j&auml;lkeen";
$prefsStrings["6.4"] = "Kirjoita kehyksess&auml;";
$prefsStrings["6.5"] = "Tekstilaatikon koko: ";
$prefsStrings['6.6'] = 'L&auml;het&auml; BCC itselle oletuksena';
$prefsStrings["7.0.0"] = "Kansioasetukset";
$prefsStrings["7.0.1"] = "Quota Options";
$prefsStrings["7.1"] = "N&auml;yt&auml; uusien viestien m&auml;&auml;r&auml;";
$prefsStrings["7.2"] = "P&auml;ivit&auml; luettelo %n sekunnin v&auml;lein";
$prefsStrings['8.0'] = 'K&auml;ytt&ouml;liittym&auml;';
$prefsStrings["8.1"] = 'Teema';
$prefsStrings["8.2"] = "JavaScriptin k&auml;ytt&ouml;";
$prefsStrings["8.3"] = "V&auml;h&auml;n";
$prefsStrings["8.4"] = "Paljon";
$prefsStrings['8.5'] = 'Automaattinen';

$pref_col_title = "Sarakkeiden j&auml;rjestys";
$pref_colstr["order"] = "J&auml;rjestys";
$pref_colstr["field"] = "Kentt&auml;";
$pref_col_label['c'] = "Merkint&auml;rasti";
$pref_col_label['a'] = "Liitteet";
$pref_col_label['m'] = "Onko vastattu";

$sort_fields=array("DATE"=>"L&auml;hetysaika", "SUBJECT"=>"Aihe", "SIZE"=>"Koko");
$sort_fields['INTERNALDATE'] = 'Vastaanottoaika';
$sort_orders=array("ASC"=>"Vanhimmat ensin", "DESC"=>"Uusimmat ensin");

$prefsButtonStrings = array( 0=> "Update", 1=>"Tallenna", 2=> "Peruuta", 3=> "Palauta oletukset");

$prefs_new_user = "K&auml;yt&auml;t n&auml;k&ouml;j&auml;&auml;n t&auml;t&auml; IlohaMailia ensimm&auml;ist&auml; kertaa...tervetuloa!<br>";
$prefs_new_user .= "tarkista asetukset ja paina sitten \"Tallenna\"";
?>
