<?php
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/read_message.inc");


$rmStrings[0] = "Index";
$rmStrings[1] = "Vastaa";
$rmStrings[2] = "V&auml;lit&auml;";
$rmStrings[3] = "Palauta";
$rmStrings[4] = "Poista";
$rmStrings[5] = "Siirr&auml;";
$rmStrings[6] = "Viestin osat";
$rmStrings[7] = "T&auml;m&auml; on HTML-viesti. ";
$rmStrings[8] = "Voit lukea sen t&auml;st&auml;.";
$rmStrings[9] = "Sorsa";
$rmStrings[10] = "Koko";
$rmStrings[11] = "Lukemattomaksi";
$rmStrings[12] = "Otsikot";
$rmStrings[13] = "Ilmoita roskapostista";
$rmStrings[14] = "..kaikille"; // vastaa kaikille
$rmStrings[15] = "Olet vastannut t&auml;h&auml;n viestiin.";
$rmStrings[16] = "Tulostussivu";
$rmStrings[17] = 'T&auml;m&auml; viesti on kirjoitettu eri merkist&ouml;ll&auml; kuin mit&auml; itse k&auml;yt&auml;t. Jos viesti n&auml;kyy huonosti, <a href="%url">paina t&auml;st&auml;</a>';
$rmStrings[18] = 'T&auml;m&auml; viesti on kirjoitettu tuntemattomalla merkist&ouml;ll&auml;. Jos viesti n&auml;kyy huonosti, kokeile jotain muuta merkist&ouml;&auml;: %menu';
$rmStrings[19] = "Vaihda";
$rmStrings[20] = 'Read';
$rmStrings[21] = 'N&auml;yt&auml;';
$rmStrings[22] = 'Toiminta';
$rmStrings[23] = 'Ketjun viesti %message';
$rmStrings[24] = 'koko ketju'; // siirr&auml;..

$rmStrings['back'] = 'Takaisin';
$rmStrings['next'] = 'Seuraava';
$rmStrings['previous'] = 'Edellinen';
$rmStrings['newer'] = 'Uudempi';
$rmStrings['older'] = 'Vanhempi';
?>
