<?php
/********************************************************
	lang/eng/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/search_errors.inc");

$searchErrors["field"] = "Hakuehdot eiv&auml;t kelpaa:  Tuntematon kentt&auml;";
$searchErrors["empty"] = "Hakuehdot eiv&auml;t kelpaa:  Tyhj&auml; hakuteksti";
$searchErrors["date"] = "Hakuehdot eiv&auml;t kelpaa:  P&auml;iv&auml;m&auml;&auml;r&auml;&auml; ei annettu";

?>
