<?php
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/tool.inc");

$toolStrings["folders"] = "Kansiot";
$toolStrings["inbox"] = "Saapuneet";
$toolStrings["compose"] = "Uusi viesti";
$toolStrings["calendar"] = "Kalenteri";
$toolStrings["contacts"] = "Yhteystiedot";
$toolStrings["bookmarks"] = "Suosikit";
$toolStrings["search"] = "Etsi";
$toolStrings["prefs"] = "Asetukset";
$toolStrings["logout"] = "Kirjaudu ulos";
$toolStrings["go"] = "Go";

?>
