<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "我的最愛";
$bmStrings["identities"] = "身份設定";
$bmStrings["edit"] = "編輯";
$bmStrings["name"] = "名稱";
$bmStrings["url"] = "網址";
$bmStrings["category"] = "分類";
$bmStrings["other"] = "其他，請在此輸入-&gt;";
$bmStrings["comments"] = "附註說明";
$bmStrings["add"] = "新增";
$bmStrings["new"] = "新增我的最愛";
$bmStrings["edit_url"] = "編輯我的最愛";
$bmStrings["delete"] = "刪除";

$bmError[1] = "您必須輸入名稱或網址。";
$bmError[2] = "不提供這項功能.";
?>
