<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "新增約會";
$calStr["edit_schedule"] = "修改約會";
$calStr["weekof"] = "本週約會: %d";
$calStr["title"] = "主旨:";
$calStr["color"] = "顏色:";
$calStr["colors"] = array("#990000"=>"暗紅色", "#FF0000"=>"紅色", "#000099"=>"深藍色", "#0000FF"=>"藍色", 
					"#006600"=>"深綠色", "#00FF00"=>"綠色", "#9900FF"=>"紫色", "#00FFFF"=>"藍綠色",
					"#FF6600"=>"橘色", "#FFFF00"=>"黃色", "#FF00FF"=>"深紫色", ""=>"無色彩");
$calStr["starts"] = "開始於:";
$calStr["ends"] = "結束於:";
$calStr["from"] = "從:";
$calStr["until"] = "到:";
$calStr["repeat_on"] = "重複提醒";
$calStr["of"] = "在每個月的";
$calStr["weeks"] = array(1=>"第一週", 2=>"第二週", 3=>"第三週", 4=>"第四週"); 
$calStr["week_blurb"] = "(直到約會結束).<br>將會每週重複如果沒有任何選取的約會.";
$calStr["monthly"] = "每月一次";
$calStr["yearly"] = "每年一次";
$calStr["place"] = "地點:";
$calStr["description"] = "內容:";
$calStr["add"] = "新增";
$calStr["update"] = "更新";
$calStr["Delete"] = "刪除";
$calStr["disabled"] = "行事曆功能不開放.";
?>
