<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/tw/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "主旨";
$composeHStrings[1] = "寄件人";
$composeHStrings[2] = "收件人";
$composeHStrings[3] = "副本";
$composeHStrings[4] = "密件副本";
$composeHStrings[5] = "日期";


$composeStrings[0] = "新郵件";
$composeStrings[1] = "傳送";
$composeStrings[2] = "上傳";
$composeStrings[3] = "加上簽名檔";
$composeStrings[4] = "附件";
$composeStrings[5] = "顯示通訊錄";
$composeStrings[6] = "隱藏通訊錄";
$composeStrings[7] = "信件本文：";
$composeStrings[8] = "新增";
$composeStrings[9] = "在 %d 的來信中，%s 提及：\n";
$composeStrings[10] = "--- 原始信件內容 ---\n";
$composeStrings[11] = "關閉本視窗";


$composeErrors[0] = "您忘記填寫信件標題了，請填上主旨，或點按「".$composeStrings[1]."」再傳送一次。";
$composeErrors[1] = "您忘記填寫寄件人欄位了。請指定一個寄件人信箱。";
$composeErrors[2] = "您忘記填寫收件人欄位了。請指定一個收件人信箱。";
$composeErrors[3] = "上傳失敗";
$composeErrors[4] = "系統並未新增任何檔案。";
$composeErrors[5] = "為了防杜惡意散發垃圾信件，你只能每隔 %3 秒鐘對 %1 位收件人（每次 %2 封）遞送一次信件。";

?>
