<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/tw/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "通訊錄";
$cStrings[1] = "新增連絡人";
$cStrings[2] = " 連絡人";
$cStrings[3] = "姓名";
$cStrings[4] = "Email 信箱";
$cStrings[5] = "網站網址";
$cStrings[6] = "所屬群組";
$cStrings[7] = "附加說明";
$cStrings[8] = "新增/編輯連絡人";
$cStrings[9] = "寄信";
$cStrings[10] = "寫信";

$cStrings["close"] = "關閉視窗";
$cStrings["addto"] = "新增連絡人到 %s";
$cStrings["showgrp"] = "顯示 %s";
$cStrings["all"] = "全部";
$cStrings["instructions"] = "點選姓名或群組名稱,來加入到郵件的收件人.";

$cErrors[0] = "您的通訊錄目前沒有任何資料。";


?>
