<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
	lang/tw/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_months[1] = "一月";
$lang_months[2] = "二月";
$lang_months[3] = "三月";
$lang_months[4] = "四月";
$lang_months[5] = "五月";
$lang_months[6] = "六月";
$lang_months[7] = "七月";
$lang_months[8] = "八月";
$lang_months[9] = "九月";
$lang_months[10] = "十月";
$lang_months[11] = "十一月";
$lang_months[12] = "十二月";

$lang_datetime["short_mon"][1] = "1月";
$lang_datetime["short_mon"][2] = "2月";
$lang_datetime["short_mon"][3] = "3月";
$lang_datetime["short_mon"][4] = "4月";
$lang_datetime["short_mon"][5] = "5月";
$lang_datetime["short_mon"][6] = "6月";
$lang_datetime["short_mon"][7] = "7月";
$lang_datetime["short_mon"][8] = "8月";
$lang_datetime["short_mon"][9] = "9月";
$lang_datetime["short_mon"][10] = "10月";
$lang_datetime["short_mon"][11] = "11月";
$lang_datetime["short_mon"][12] = "12月";

$lang_datetime["dsow"][0] = "星期日";
$lang_datetime["dsow"][1] = "星期一";
$lang_datetime["dsow"][2] = "星期二";
$lang_datetime["dsow"][3] = "星期三";
$lang_datetime["dsow"][4] = "星期四";
$lang_datetime["dsow"][5] = "星期五";
$lang_datetime["dsow"][6] = "星期六";

$lang_datetime["dsowl"][0] = "星期日";
$lang_datetime["dsowl"][1] = "星期一";
$lang_datetime["dsowl"][2] = "星期二";
$lang_datetime["dsowl"][3] = "星期三";
$lang_datetime["dsowl"][4] = "星期四";
$lang_datetime["dsowl"][5] = "星期五";
$lang_datetime["dsowl"][6] = "星期六";

$lang_datetime["dsow_short"] = array ("日","一","二","三","四","五","六");
$lang_datetime["today"] = "[今日] %t";
$lang_datetime["lastweek"] = "%w %t";
$lang_datetime["thisyear"] = "%m/%d";
$lang_datetime["prevyears"] = "%y/%m/%d";

$lang_datetime["monthyear"] = "%y %m";          //e.g. "一月 2002"
$lang_datetime["verbal"] = "%y-%m-%d";         //e.g. "一月 1, 1900"
$lang_datetime["verbal_short"] = "%m%d日";       //e.g. "一月 1"
$lang_datetime["hour_system"] = 24;                     // 12 or 24
$lang_datetime["ampm"]["am"] = "上午";
$lang_datetime["ampm"]["pm"] = "下午";
$lang_datetime["time_format"] = "%a %h:%m";      // %h=時, %m=分, %a="上午:下午"
$lang_datetime["hour_format"] = "%a %h";

?>
