<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/tw/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "編輯";
$ecStrings[1] = "新增";
$ecStrings[2] = " 連絡人";
$ecStrings[3] = "姓名";
$ecStrings[4] = "Email 信箱";
$ecStrings[5] = "網站網址";
$ecStrings[6] = "所屬群組";
$ecStrings[7] = "附加說明";
$ecStrings[8] = "電話（家）";
$ecStrings[9] = "電話（公）";
$ecStrings[10] = "行動電話";
$ecStrings[11] = "通訊地址";
$ecStrings[12] = "Email 信箱 2";
$ecStrings[13] = "刪除";
$ecStrings[14] = "其他";


$errors[0] = "無法新增連絡人：資料庫發生錯誤。";
$errors[1] = "通訊錄裡已經有該連絡人的資料了。";
$errors[2] = "點選";
$errors[3] = "這裡";
$errors[4] = "可以編輯該連絡人";
$errors[5] = "找不到該連絡人，或無法存取。";
$errors[6] = "您確定要刪除「";
$errors[7] = "」嗎？";

?>