<?php
include("../lang/eng/folders.inc"); // <-- do not delete
/********************************************************
	lang/tw/folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

	$sentbox=$my_prefs["sent_box_name"];
	$trashname=$my_prefs["trash_name"];
	$defaults["INBOX"] = "收件匣";
	$defaults[$sentbox] = "寄件備份匣";
	$defaults[$trashname] = "資源回收筒";
	$fl_str["folders"] = "信件匣一覽";
        $fl_str["manage"] = "信件匣管理";
        $fstr["reload"] = "重新整理";
        $fstr["expunge"] = "清空";
									
	
?>
