<?php 
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="帳號";
$loginStrings[1]="密碼";
$loginStrings[2]="網域";
$loginStrings[3]="Type";
$loginStrings[4]="Rootdir";
$loginStrings[5]="語言";
$loginStrings[6]="登入";

$loginErrors[0]="Unauthorized host";
$loginErrors[1]="Error: \"uploads\" directory not found";
$loginErrors[2]="Error: \"users\" directory not found";
$loginErrors[3]="Error: \"sessions\" directory not found";

?>
