<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "身份設定";
$piStrings["edit"] = "編輯";
$piStrings["name"] = "顯示名稱";
$piStrings["email"] = "Email 信箱";
$piStrings["replyto"] = "回覆信箱";
$piStrings["sig"] = "簽名檔";
$piStrings["add"] = "新增";
$piStrings["new"] = "新增身份";
$piStrings["edit_ident"] = "編輯身份";
$piStrings["delete"] = "刪除";
$piStrings["setdef"] = "設成預設值";
$piError[1] = "您必須輸入「顯示名稱」或 Email 信箱。";

?>
