<?php
/********************************************************
	lang/tw/pref_colors.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "請填入顏色代碼值來設定各項顏色。";
$pcStrings["0.1"] = "或使用";
$pcStrings["0.2"] = "[顏色代碼表]";
$pcStrings["0.3"] = "來查詢並設定合適的顏色。";
$pcStrings["0.4"] = "如果界面風格檔中已有之設定值將無法修改。";
$pcStrings["1.0"] = "工具列";
$pcStrings["2.0"] = "信件匣列表";
$pcStrings["3.0"] = "主視窗";
$pcStrings["3.1"] = "標題背景： ";
$pcStrings["3.2"] = "標題文字： ";
$pcStrings["3.3"] = "深色背景： ";
$pcStrings["3.4"] = "淺色文字： ";
$pcStrings["4.0"] = "綜合選項";
$pcStrings["4.1"] = "引言：";
$pcStrings["5.0"] = "字形";
$pcStrings["5.1"] = "字形群組";
$pcStrings["5.2"] = "字體大小： ";
$pcStrings["5.3"] = "小字體大小： ";
$pcStrings["5.4"] = "選單字體大小： ";
$pcStrings["5.5"] = "信件匣列表字體大小： ";

							
$pcPortions = array( "背景顏色： ", "連結顏色： ", "一般文字顏色： ", "高亮度顯示顏色： ");

?>
