<?php
include("../lang/eng/quota.inc"); // <-- do not delete
/********************************************************
	lang/eng/quota.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$quotaStr["label"] = "磁碟空間：";
$quotaStr["full"] = "已用空間：%usedKB  可用空間：%totalKB  剩餘空間：%free%";
$quotaStr["unknown"] = "未知";

?>