<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/tw/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "返回";
$rmStrings[1] = "回信";
$rmStrings[2] = "轉信";
$rmStrings[3] = "取消刪除";
$rmStrings[4] = "刪除";
$rmStrings[5] = "移至";
$rmStrings[6] = "附加部分";
$rmStrings[7] = "這是一封 HTML 格式信件。";
$rmStrings[8] = "點選這裡可以立即讀取。";
$rmStrings[9] = "信件原始碼";
$rmStrings[10] = "大小";
$rmStrings[11] = "標記未讀";
$rmStrings[12] = "顯示信件標頭";
$rmStrings[13] = "回報垃圾信件";
$rmStrings[14] = "回信給所有人";
$rmStrings[15] = "<b>已回覆</b>";
$rmStrings[16] = "列印";

?>
