<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/tw/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "搜尋錯誤：不正確的欄位";
$searchErrors["empty"] = "搜尋錯誤：您未輸入任何關鍵字";
$searchErrors["date"] = "搜尋錯誤：您未指定任何日期";

?>