<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/tw/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Traditional Chinese (BIG5), for use in Taiwan, 
	Hong Kong, and Overseas Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "信件匣一覽";
$toolStrings["inbox"] = "收件匣";
$toolStrings["compose"] = "建立郵件";
$toolStrings["contacts"] = "通訊錄";
$toolStrings["search"] = "搜尋信件";
$toolStrings["prefs"] = "偏好設定";
$toolStrings["logout"] = "登出";
$toolStrings["go"] = "Go";
$toolStrings["calendar"] = "行事曆";
$toolStrings["bookmarks"] = "我的最愛";
?>
