<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Bookmarks";
$bmStrings["identities"] = "Identities";
$bmStrings["edit"] = "Edit";
$bmStrings["name"] = "Name";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Category";
$bmStrings["other"] = "Specify-&gt;";
$bmStrings["comments"] = "Comments";
$bmStrings["add"] = "Add";
$bmStrings["new"] = "New Entry";
$bmStrings["edit_url"] = "Edit Entry";
$bmStrings["delete"] = "Delete";

$bmError[1] = "Name or URL required";

?>
