<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/eng/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "Subiect";
$composeHStrings[1] = "De la";
$composeHStrings[2] = "Catre";
$composeHStrings[3] = "CC";
$composeHStrings[4] = "BCC";
$composeHStrings[5] = "Data";


$composeStrings[0] = "Compune Mesaj";
$composeStrings[1] = "Trimite Mesaj";
$composeStrings[2] = "Upload";
$composeStrings[3] = "Semnatura";
$composeStrings[4] = "Ataseaza";
$composeStrings[5] = "Vezi contacte";
$composeStrings[6] = "Ascunde contacte";
$composeStrings[7] = "Mesaj:";
$composeStrings[8] = "Adauga";
$composeStrings[9] = "On %d, %s wrote:\n";
$composeStrings[10] = "--- Mesajul Original ---\n";
$composeStrings[11] = "Inchide fereastra";


$composeErrors[0] = "Campul subiect este necompletat. Completati subiectul sau dati click \"".$composeStrings[1]."\" din nou pentru a-l trimite.";
$composeErrors[1] = "Campul \"from\" nu este completat. Introduce-ti adresa dumnavoastra de email.";
$composeErrors[2] = "Campul \"To\"  nu este completat. Va rugam specificati adresele destinatii.";
$composeErrors[3] = "Upload nereusit";
$composeErrors[4] = "Nici un fisier primit.";
$composeErrors[5] = "Pentru prevenirea spam-ului(emailuri nedorite de destinatar), puteti trimite mailuri la %1 persoane (%2 total pe sesiunu) la fiecare %3 secunde.";

?>