<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Contacte";
$cStrings[1] = "Adauga Contacte";
$cStrings[2] = " Contact";
$cStrings[3] = "Nume";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Grup";
$cStrings[7] = "Comentarii";
$cStrings[8] = "Adauga/Modifica Contact";
$cStrings[9] = "Email";
$cStrings[10] = "Compune";


$cErrors[0] = "Lista de Contacte este goala";


?>