<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Modifica";
$ecStrings[1] = "Adauga";
$ecStrings[2] = "Contacte";
$ecStrings[3] = "Nume";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Grup";
$ecStrings[7] = "Comentarii";
$ecStrings[8] = "Telefon Acasa";
$ecStrings[9] = "Telefon Serviciu";
$ecStrings[10] = "Telefon Mobil";
$ecStrings[11] = "Adresa";
$ecStrings[12] = "Alt Email";
$ecStrings[13] = "Sterge";
$ecStrings[14] = "Altele";


$errors[0] = "Adaugare contact esuata:  eroare baza de date.";
$errors[1] = "Datele introduse pentru aceasta adresa exista deja in baza de date.";
$errors[2] = "Clic ";
$errors[3] = "aici";
$errors[4] = "daca vreti sa modificati aceste date";
$errors[5] = "Nu s-a gasit Contact, sau acces nepermis.";
$errors[6] = "Sunteti sigur ca doriti sa stergeti aceste date \"";
$errors[7] = "\"?";

?>