<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/eng/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings[0] = "Administrare directoare";
$efStrings[1] = "Creare director nou";
$efStrings[2] = "Creare director";
$efStrings[3] = "Creare";
$efStrings[4] = "Sterge director";
$efStrings[5] = "Sterge";
$efStrings[6] = "Redenumire director";
$efStrings[7] = "Redenumire";


$errors[0] = "Creare director: ";
$errors[1] = "Nu se poate crea directorul: ";
$errors[2] = "Director sters: ";
$errors[3] = "Nu se poate sterge directorul: ";
$errors[4] = "Director redenumit: ";
$errors[5] = "Nu poate schimba numele directorului: ";
$errors[6] = "Suport-Directoare este disponibil doar pentru cont-uri IMAP.";

?>