<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "Introduceti codul HTML al culorilor, pentru componentele corespunzatoare.";
$pcStrings["0.1"] = "Folositi ";
$pcStrings["0.2"] = "tabela de Culori (cod HTML)";
$pcStrings["0.3"] = " sa gasiti codul culorii potrivite.";
$pcStrings["1.0"] = "Bara configurari";
$pcStrings["2.0"] = "Lista directoare";
$pcStrings["3.0"] = "Principal";
$pcStrings["4.0"] = "Diverse";
$pcStrings["4.1"] = "Citate: ";

							
$pcPortions = array( "Fundal: ", "Legaturi: ", "Text: ", "Evidentiat: ");

?>
