<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Inapoi";
$rmStrings[1] = "Raspunde";
$rmStrings[2] = "Redirecteaza";
$rmStrings[3] = "Anulare stergere";
$rmStrings[4] = "Sterge";
$rmStrings[5] = "Fisier";
$rmStrings[6] = "Parti";
$rmStrings[7] = "Acesta este un mesaj HTML. ";
$rmStrings[8] = "Clic aici ca sa-l cititi.";
$rmStrings[9] = "Sursa";
$rmStrings[10] = "Marime";
$rmStrings[11] = "Marcare ca necitit";
$rmStrings[12] = "Afisare Header";
$rmStrings[13] = "Raporteaza Spam (email nedorit)";
$rmStrings[14] = "Raspunde tuturor";

?>