<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/eng/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "Criteriu de cautare invalid:  Camp invalid";
$searchErrors["empty"] = "Criteriu de cautare invalid:  Nu ati scris sirul de cautare";
$searchErrors["date"] = "Criteriu de cautare invalid:  Data nu este specificata";

?>