<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "Directoare";
$toolStrings["inbox"] = "Mesaje primite";
$toolStrings["compose"] = "Compune mesaje";
$toolStrings["contacts"] = "Contacte";
$toolStrings["search"] = "Cautare";
$toolStrings["prefs"] = "Preferinte";
$toolStrings["logout"] = "Iesire";
$toolStrings["go"] = "OK";

?>