<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Segnalibri";
$bmStrings["identities"] = "Identitità";
$bmStrings["edit"] = "Modifica";
$bmStrings["name"] = "Nome";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Categoria";
$bmStrings["other"] = "Specifico-&gt;";
$bmStrings["comments"] = "Comment";
$bmStrings["add"] = "Aggiungi";
$bmStrings["new"] = "Nuova voce";
$bmStrings["edit_url"] = "Modifica voce";
$bmStrings["delete"] = "Elimina";

$bmError[1] = "Nome o URL richiesto";

?>
