<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Aggiungi Schedule";
$calStr["edit_schedule"] = "Modifica Schedule";
$calStr["weekof"] = "Settimana di: %d";
$calStr["title"] = "Titolo:";
$calStr["color"] = "Colore:";
$calStr["colors"] = array("#990000"=>"Dark Red", "#FF0000"=>"Red", "#000099"=>"Deep Blue", "#0000FF"=>"Blue",
					"#006600"=>"Dark Green", "#00FF00"=>"Green", "#9900FF"=>"Purple", "#00FFFF"=>"Cyan",
					"#FF6600"=>"Orange", "#FFFF00"=>"Yellow", "#FF00FF"=>"Magenta", ""=>"No color");
$calStr["starts"] = "Inzio alle:";
$calStr["ends"] = "Finisce alle:";
$calStr["from"] = "da:";
$calStr["until"] = "fino al:";
$calStr["repeat_on"] = "Si ripete il";
$calStr["of"] = "di tutti";
$calStr["weeks"] = array(1=>"prima settimana", 2=>"seconda settimana", 3=>"terza settimana", 4=>"quarta settimana");
$calStr["week_blurb"] = "...di tutti i mesi  (Fino alla data finale).<br>Ripete tutta la settimana se non è stata effettuata nessuna selezione.";
$calStr["monthly"] = "Si ripete mensilmente";
$calStr["yearly"] = "Si ripete annualmente";
$calStr["place"] = "Luogo:";
$calStr["description"] = "Descrizione:";
$calStr["add"] = "Inserisci";
$calStr["update"] = "Aggiorna";
$calStr["Delete"] = "Cancella";
?>
