<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/it/compose.inc

	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "Oggetto";
$composeHStrings[1] = "Da";
$composeHStrings[2] = "A";
$composeHStrings[3] = "CC";
$composeHStrings[4] = "BCC";
$composeHStrings[5] = "Data";


$composeStrings[0] = "Nuovo messaggio";
$composeStrings[1] = "Invia messaggio";
$composeStrings[2] = "Invia dati";
$composeStrings[3] = "Inserisci firma";
$composeStrings[4] = "Allega";
$composeStrings[5] = "Mostra contatti";
$composeStrings[6] = "Nascondi contatti";
$composeStrings[7] = "Testo del messaggio:";
$composeStrings[8] = "Aggiungi";
$composeStrings[9] = "In data %d, %s ha scritto:\n";
$composeStrings[10] = "--- Messaggio originale ---\n";
$composeStrings[11] = "Chiudi finestra";

$composeStrings[12] = "Controlla ortografia";
$composeStrings[13] = "Correggi parola";
$composeStrings[14] = "Nessun cambiamento";
$composeStrings[15] = "Possibile errore di scrittura";
$composeStrings[16] = "Cambio parola";
$composeStrings[17] = "Ignora";
$composeStrings[18] = "Cancella";

$composeErrors[0] = "Il campo -Oggetto- &egrave; vuoto. Inserire un -Oggetto- o cliccare ancora su \"".$composeStrings[1]."\" per inviare.";
$composeErrors[1] = "Mittente non specificato.  Inserire il proprio indirizzo e-mail.";
$composeErrors[2] = "Destinatario non specificato.  Inserire l'indirizzo e-mail del destinatario.";
$composeErrors[3] = "Invio fallito";
$composeErrors[4] = "Nessun file ricevuto.";
$composeErrors[5] = "Per prevenire ogni abuso (SPAMMING), &egrave; possibile spedire al massimo a %1 persona (%2 per sessione) ogni %3 secondi.";

$composeErrors[6] = "Nessun errore di ortografia trovato.";
$composeErrors[7] = "Controllo ortografico non disponibile per la lingua selezionata.";
$composeErrors[8] = "(%s dizionario usato)";

?>
