<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/it/contacts.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Contatti";
$cStrings[1] = "Aggiungi contatto";
$cStrings[2] = " Contatto";
$cStrings[3] = "Nome";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Gruppo";
$cStrings[7] = "Commenti";
$cStrings[8] = "Aggiungi/Modifica contatto";
$cStrings[9] = "Email";
$cStrings[10] = "Scrivi";

$cStrings["close"] = "CHIUDI FINESTRA";
$cStrings["addto"] = "Inserisci contatti in %s";
$cStrings["showgrp"] = "Visualizza %s";
$cStrings["all"] = "All";
$cStrings["instructions"] = "Clicare sul nome per inserire.  E' possibile inoltre cliccare sul guppo di etichette per inserirle tutte nel gruppo.";


$cErrors[0] = "La rubrica è vuota";




?>
