<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
	lang/it/dates.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$lang_months[1] = "Gennaio";
$lang_months[2] = "Febbraio";
$lang_months[3] = "Marzo";
$lang_months[4] = "Aprile";
$lang_months[5] = "Maggio";
$lang_months[6] = "Giugno";
$lang_months[7] = "Luglio";
$lang_months[8] = "Agosto";
$lang_months[9] = "Settembre";
$lang_months[10] = "Ottobre";
$lang_months[11] = "Novembre";
$lang_months[12] = "Dicembre";

$lang_datetime["short_mon"][1] = "Gen";
$lang_datetime["short_mon"][2] = "Feb";
$lang_datetime["short_mon"][3] = "Mar";
$lang_datetime["short_mon"][4] = "Apr";
$lang_datetime["short_mon"][5] = "Mag";
$lang_datetime["short_mon"][6] = "Giu";
$lang_datetime["short_mon"][7] = "Lug";
$lang_datetime["short_mon"][8] = "Ago";
$lang_datetime["short_mon"][9] = "Set";
$lang_datetime["short_mon"][10] = "Ott";
$lang_datetime["short_mon"][11] = "Nov";
$lang_datetime["short_mon"][12] = "Dic";

$lang_datetime["dsow"][0] = "Dom";
$lang_datetime["dsow"][1] = "Lun";
$lang_datetime["dsow"][2] = "Mar";
$lang_datetime["dsow"][3] = "Merc";
$lang_datetime["dsow"][4] = "Gio";
$lang_datetime["dsow"][5] = "ven";
$lang_datetime["dsow"][6] = "Sab";

$lang_datetime["dsowl"][0] = "Domenica";
$lang_datetime["dsowl"][1] = "Lunedì";
$lang_datetime["dsowl"][2] = "Martedì";
$lang_datetime["dsowl"][3] = "Mercoledì";
$lang_datetime["dsowl"][4] = "Giovedì";
$lang_datetime["dsowl"][5] = "Venerdì";
$lang_datetime["dsowl"][6] = "Sabato";

$lang_datetime["dsow_short"] = array("S", "L", "Ma", "Me", "G", "V", "S");
$lang_datetime["dsow"] = array ("Dom", "Lun", "Mar", "Mer", "Gio", "Ven", "Sab");
$lang_datetime["today"]= "Oggi, %t";
$lang_datetime["lastweek"] = "%w %t";
$lang_datetime["thisyear"] = "%d/%m";
$lang_datetime["prevyears"] = "%d/%m/%y";
$lang_datetime["monthyear"] = "%m %y";		//e.g. "January 2002"
$lang_datetime["verbal"] = "%m %d, %y";  	//e.g. "Jan 1, 1900"
$lang_datetime["verbal_short"] = "%d %m";  	//e.g. "Jan 1"
$lang_datetime["hour_system"] = 12;			// 12 or 24
$lang_datetime["ampm"]["am"] = "am";
$lang_datetime["ampm"]["pm"] = "pm";
$lang_datetime["time_format"] = "%h:%m%a";	// %h=hour, %m=minutes, %a="am:pm"
$lang_datetime["hour_format"] = "%h%a";


?>
