<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/it/edit_folders.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings[0] = "Gestisci cartelle";
$efStrings[1] = "Crea nuova cartella";
$efStrings[2] = "Crea cartella: ";
$efStrings[3] = "Crea";
$efStrings[4] = "Elimina cartella";
$efStrings[5] = "Elimina";
$efStrings[6] = "Rinomina cartella";
$efStrings[7] = "Rinomina";


$errors[0] = "Crea cartella: ";
$errors[1] = "Impossibile creare cartella: ";
$errors[2] = "Cartella eliminata: ";
$errors[3] = "Impossibile eliminare cartella: ";
$errors[4] = "Cartella rinominata: ";
$errors[5] = "Impossibile rinominare cartella: ";
$errors[6] = "La gestione delle cartelle è disponibile solo per il protocollo IMAP.";

?>
