<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/it/edit_contact.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Modifica";
$ecStrings[1] = "Aggiungi";
$ecStrings[2] = " Contatto";
$ecStrings[3] = "Nome";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Gruppo";
$ecStrings[7] = "Commenti";
$ecStrings[8] = "Tel. privato";
$ecStrings[9] = "Tel. ufficio";
$ecStrings[10] = "Cellulare";
$ecStrings[11] = "Indirizzo";
$ecStrings[12] = "Altra Email";
$ecStrings[13] = "Elimina";
$ecStrings[14] = "Altro";


$errors[0] = "Impossibile aggiungere contatto: errore nel database.";
$errors[1] = "Questo indirizzo esiste gi&agrave; nella rubrica.";
$errors[2] = "Clicca ";
$errors[3] = "qu&iacute;";
$errors[4] = " per modificare questa voce.";
$errors[5] = "Voce non trovata o accesso negato.";
$errors[6] = "Sei sicuro di voler eliminare \"";
$errors[7] = "\"?";

?>
