<?php
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="User ID";
$loginStrings[1]="Password";
$loginStrings[2]="Server";
$loginStrings[3]="Tipo";
$loginStrings[4]="Rootdir";
$loginStrings[5]="Lingua";
$loginStrings[6]="Log In";

$loginErrors[0]="Computer non autorizzato";
$loginErrors[1]="Error: \"uploads\" directory non trovata";
$loginErrors[2]="Error: \"users\" directory non trovata";
$loginErrors[3]="Error: \"sessions\" non trovata";

?>
