<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/it/cp.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "Inserisci un codice HTML per il colore di ogni elemento.";
$pcStrings["0.1"] = "Utilizza la ";
$pcStrings["0.2"] = "Tabella codici colori";
$pcStrings["0.3"] = " per trovare il colore voluto.";
$pcStrings["0.4"] = "Settaggi che i temi non possono sovrascrivere.";
$pcStrings["1.0"] = "Barra strumenti";
$pcStrings["2.0"] = "Lista cartelle";
$pcStrings["3.0"] = "Principale";
$pcStrings["3.1"] = "Background  intestazione: ";
$pcStrings["3.2"] = "Testo di intestazione: ";
$pcStrings["3.3"] = "Background scuro: ";
$pcStrings["3.4"] = "Testo chiaro: ";
$pcStrings["4.0"] = "Diversi";
$pcStrings["4.1"] = "Citazione: ";
$pcStrings["5.0"] = "Caratteri";
$pcStrings["5.1"] = "Famiglia caratteri";
$pcStrings["5.2"] = "Dimensione caratteri: ";
$pcStrings["5.3"] = "Dimensione caratteri piccoli: ";
$pcStrings["5.4"] = "Dimensione caratteri menu: ";
$pcStrings["5.5"] = "Dimensione caratteri  lista cartelle: ";


$pcPortions = array( "Sfondo: ", "Collegamenti: ", "Testo: ", "Evidenziato: ");

?>
