<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/it/read_message.inc

	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Indietro";
$rmStrings[1] = "Rispondi";
$rmStrings[2] = "Inoltra";
$rmStrings[3] = "Recupera";
$rmStrings[4] = "Cancella";
$rmStrings[5] = "Sposta";
$rmStrings[6] = "Parti";
$rmStrings[7] = "Questo è un messaggio HTML. ";
$rmStrings[8] = "Clicca qu&iacute; per leggerlo.";
$rmStrings[9] = "Sorgente";
$rmStrings[10] = "Dimensione";
$rmStrings[11] = "Segna come non letto";
$rmStrings[12] = "Mostra intestazione";
$rmStrings[13] = "Segnala Spam";
$rmStrings[14] = "Rispondi a tutti";
$rmStrings[15] = "Hai già risposto a questo messaggio";
$rmStrings[16] = "Stampa";
?>
