<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/it/search_errors.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "Criterio di ricerca non valido: Campo non valido";
$searchErrors["empty"] = "Criterio di ricerca non valido: Stringa da cercare vuota";
$searchErrors["date"] = "Criterio di ricerca non valido: Data non specificata";

?>
