<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/it/tool.inc
	
	Italian Translation by Amos B. <mriya3@surfeu.ch>
	Original english file (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "Cartelle";
$toolStrings["inbox"] = "Posta in arrivo";
$toolStrings["compose"] = "Scrivi messaggio";
$toolStrings["contacts"] = "Contatti";
$toolStrings["search"] = "Cerca";
$toolStrings["prefs"] = "Preferenze";
$toolStrings["logout"] = "Disconnetti";
$toolStrings["calendar"] = "Attività";
$toolStrings["bookmarks"] = "Segnalibri";
$toolStrings["search"] = "Ricerca";
$toolStrings["go"] = "Vai";

?>
