<?php
/********************************************************
        lang/<lang>/bookmarks.inc
        (C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "ブックマーク";
$bmStrings["identities"] = "Identities";
$bmStrings["edit"] = "編集";
$bmStrings["name"] = "名前";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "カテゴリ";
$bmStrings["other"] = "その他(指定)→";
$bmStrings["comments"] = "コメント";
$bmStrings["add"] = "追加";
$bmStrings["new"] = "新規項目";
$bmStrings["edit_url"] = "編集";
$bmStrings["delete"] = "削除";

$bmError[1] = "名前とURLは必須項目です";

?>