<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "新規スケジュール";
$calStr["edit_schedule"] = "スケジュールを更新";
$calStr["weekof"] = "%dの週";
$calStr["title"] = "タイトル:";
$calStr["color"] = "表示色:";
$calStr["colors"] = array("#990000"=>"濃い赤", "#FF0000"=>"赤", "#000099"=>"紺", "#0000FF"=>"青", 
					"#006600"=>"濃い緑", "#00FF00"=>"緑", "#9900FF"=>"紫", "#00FFFF"=>"シアン",
					"#FF6600"=>"オレンジ", "#FFFF00"=>"黄色", "#FF00FF"=>"マゼンタ", ""=>"特に無し");
$calStr["starts"] = "開始日:";
$calStr["ends"] = "終了日:";
$calStr["from"] = "開始時間:";
$calStr["until"] = "終了時間:";
$calStr["repeat_on"] = "繰り返し";
$calStr["of"] = "毎月：";
$calStr["weeks"] = array(1=>"第一週", 2=>"第二週", 3=>"第三週", 4=>"第四週"); 
$calStr["week_blurb"] = "未指定の場合は終了日まで毎週繰り返します。";
$calStr["monthly"] = "毎月繰り返す";
$calStr["yearly"] = "毎年繰り返す";
$calStr["place"] = "場所:";
$calStr["description"] = "コメント:";
$calStr["add"] = "追加";
$calStr["update"] = "更新";
$calStr["Delete"] = "削除";
$calStr["go"] = "表示";
?>