<?php
include("../lang/eng/contacts.inc"); // <-- do not delete

/********************************************************
	lang/jp/contacts.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings=array(
	0=>"アドレス帳",
	1=>"アドレスを追加",
	2=>" Contact",
	3=>"名前",
	4=>"Email",
	5=>"URL",
	6=>"グループ",
	7=>"コメント",
	8=>"追加",
	9=>"選択項目にメール",
	10=>"メール作成"
);

$cStrings["close"] = "ウインドウを閉じる";
$cStrings["addto"] = "アドレスを%sに追加";
$cStrings["showgrp"] = "%s表示";
$cStrings["all"] = "全て";

$cErrors=array(
	0=>"コンタクトリストに項目は有りません"
);
?>