<?php 
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="ログインID";
$loginStrings[1]="パスワード";
$loginStrings[2]="サーバ";
$loginStrings[3]="タイプ";
$loginStrings[4]="ルートフォルダ";
$loginStrings[5]="言語";
$loginStrings[6]="ログイン";

$loginErrors[0]="指定されたメールサーバーにはログインできません";
$loginErrors[1]="Error: \"uploads\" directory not found";
$loginErrors[2]="Error: \"users\" directory not found";
$loginErrors[3]="Error: \"sessions\" directory not found";

?>