<?php
include("../lang/eng/main.inc"); // <-- do not delete
/********************************************************
	lang/jp/main.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	PURPOSE:
		Provide strings for "source/main.php"

********************************************************/

$mainMessages["delete"] = "メッセージ%n件削除しました";
$mainMessages["move"] = "メッセージ%n件を「%f」フォルダに移動";

$mainStrings[0] = "%n件中%p表示";
$mainStrings[1] = "件見つかりました";
$mainStrings[2] = "前の";
$mainStrings[3] = "件";
$mainStrings[4] = "次の";
$mainStrings[5] = "件";
$mainStrings[6] = "件名";
$mainStrings[7] = "宛先";
$mainStrings[8] = "送信者";
$mainStrings[9] = "日付け";
$mainStrings[10] = "削除";
$mainStrings[11] = "ゴミ箱を空に";
$mainStrings[12] = "移動";
$mainStrings[13] = "検索";
$mainStrings[14] = "容量";
$mainStrings[15] = "件名未指定";
$mainStrings[16] = "表示";
$mainStrings[17] = "新着チェック";
$mainStrings[18] = "全て消去";
$mainStrings[19] = "キャンセル";
$mainStrings[20] = "フラグ： %b";
$mainStrings[21] = "該読";
$mainStrings[22] = "未読";
$mainStrings[23] = "選択...";


$mainErrors[0] = "この該当メッセージはありません";
$mainErrors[1] = "このフォルダーにメッセージはありません";
$mainErrors[2] = "メッセージの削除に失敗しました";
$mainErrors[3] = "メッセージのステータス変更に失敗しました";
$mainErrors[4] = "メッセージの移動に失敗しました";
$mainErrors[5] = "ゴミ箱フォルダーが指定されていません";
$mainErrors[6] = "ゴミ箱を空にする事ができませんでした";
$mainErrors[7] = "「%f」フォルダ内の全てのメッセージを消去してよろしいですか？";
$mainErrors[8] = "コラムを移動するには、矢印にクリックしてください。移動が終わった後はこのウインドウを閉じてください。";

?>