<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "あなたの個人情報";
$piStrings["edit"] = "変更";
$piStrings["name"] = "名前";
$piStrings["email"] = "メールアドレス";
$piStrings["replyto"] = "返信用アドレス";
$piStrings["sig"] = "署名";
$piStrings["add"] = "追加";
$piStrings["new"] = "新しい個人情報";
$piStrings["edit_ident"] = "個人情報を変更";
$piStrings["delete"] = "削除";
$piStrings["setdef"] = "デフォルトに指定";
$piStrings["isdef"] = "（デフォルト）";

$piError[1] = "「名前」か「メールアドレス」が空欄です。";

?>
