<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/eng/cp.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "各々のパネルの表示色(HTMLカラーコード)を指定してください。";
$pcStrings["0.1"] = "好みの色のカラーコードを";
$pcStrings["0.2"] = "カラーコード表";
$pcStrings["0.3"] = "から探す事もできます。";
$pcStrings["0.4"] = "一部の設定を変更できない場合もあります。";
$pcStrings["1.0"] = "ツールバー";
$pcStrings["2.0"] = "フォルダーリスト";
$pcStrings["3.0"] = "メイン";
$pcStrings["3.1"] = "ヘッダ（バック）";
$pcStrings["3.2"] = "ヘッダ（テキスト）";
$pcStrings["3.3"] = "濃いバックグラウンド: ";
$pcStrings["3.4"] = "明るいテキスト色: ";
$pcStrings["4.0"] = "その他";
$pcStrings["4.1"] = "引用文";
$pcStrings["5.0"] = "フォント";
$pcStrings["5.1"] = "タイプ";
$pcStrings["5.2"] = "普通のテキスト";
$pcStrings["5.3"] = "小さいテキスト";
$pcStrings["5.4"] = "メニューのテキスト";
$pcStrings["5.5"] = "フォルダリストのフォントサイズ：";

							
$pcPortions = array( "背景: ", "リンク: ", "テキスト: ", "ハイライト: ");

?>
