<?php
include("../lang/eng/quota.inc"); // <-- do not delete
/********************************************************
	lang/eng/quota.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$quotaStr["label"] = "ディスク使用量: ";
$quotaStr["full"] = "%totalKB中%usedKB使用 (%free% 空き)";
$quotaStr["unknown"] = "--";

?>