<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/jp/search_errors.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	PURPOSE:
		Error strings for search function.

********************************************************/

$searchErrors["field"] = "対象フィールドが指定されていません。";
$searchErrors["empty"] = "検索項目が指定されていません。";
$searchErrors["date"] = "日付けが指定されていません。";

?>