<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/jp/tool.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "フォルダー";
$toolStrings["inbox"] = "受信箱";
$toolStrings["compose"] = "作成";
$toolStrings["calendar"] = "カレンダー";
$toolStrings["contacts"] = "アドレス帳";
$toolStrings["search"] = "検索";
$toolStrings["prefs"] = "設定";
$toolStrings["logout"] = "ログアウト";
$toolStrings["go"] = "表示";
$toolStrings["bookmarks"] = "ブックマーク";
?>