<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Favoriten";
$bmStrings["identities"] = "Identit&auml;ten";
$bmStrings["edit"] = "&Auml;ndern";
$bmStrings["name"] = "Name";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Kategorie";
$bmStrings["other"] = "Angeben-&gt;";
$bmStrings["comments"] = "Kommentar";
$bmStrings["add"] = "Hinzu";
$bmStrings["new"] = "Neuer Eintrag";
$bmStrings["edit_url"] = "Eintrag &auml;ndern";
$bmStrings["delete"] = "L&ouml;schen";

$bmError[1] = "Name oder URL werden ben&ouml;tigt.";
$bmError[2] = "Diese Aktion ist nicht verf&uuml;gbar.";
?>
