<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Neue Wiederholung";
$calStr["edit_schedule"] = "Wiederholung &auml;ndern";
$calStr["weekof"] = "Woche vom: %d";
$calStr["title"] = "Titel:";
$calStr["color"] = "Farbe:";
$calStr["colors"] = array("#990000"=>"dunkelrot", "#FF0000"=>"rot", "#000099"=>"dunkelblau", "#0000FF"=>"blau", 
					"#006600"=>"dunkelgr&uuml;n", "#00FF00"=>"gr&uuml;n", "#9900FF"=>"lila", "#00FFFF"=>"cyan",
					"#FF6600"=>"orange", "#FFFF00"=>"gelb", "#FF00FF"=>"magenta", ""=>"keine Farbe");
$calStr["starts"] = "Beginnt am:";
$calStr["ends"] = "Endet am:";
$calStr["from"] = "von:";
$calStr["until"] = "bis:";
$calStr["repeat_on"] = "Wiederholen am";
$calStr["of"] = "jeder";
$calStr["weeks"] = array(1=>"ersten Woche", 2=>"zweiten Woche", 3=>"dritten Woche", 4=>"vierten Woche"); 
$calStr["week_blurb"] = "... des Monats (bis zum Enddatum).<br>Ohne Auswahl wird jede Woche wiederholt.";
$calStr["monthly"] = "Monatliche Wiederholung";
$calStr["yearly"] = "J&auml;hrliche Wiederholung";
$calStr["place"] = "Ort:";
$calStr["description"] = "Beschreibung:";
$calStr["add"] = "Hinzu";
$calStr["update"] = "Speichern";
$calStr["Delete"] = "L&ouml;schen";
$calStr["go"] = "Ok";
$calStr["disabled"] = "Die Kalender-Funktion ist nicht verf&uuml;gbar.";
?>
