<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Kontakte";
$cStrings[1] = "Neuer Kontakt";
$cStrings[2] = " Kontakt";
$cStrings[3] = "Name";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Gruppe";
$cStrings[7] = "Kommentar";
$cStrings[8] = "Kontakt speichern";
$cStrings[9] = "Email";
$cStrings[10] = "Neue Nachricht";

$cStrings["close"] = "Fenster schlie&szlig;en";
$cStrings["addto"] = "Kontakt in Feld &uuml;bernehmen: %s";
$cStrings["showgrp"] = "Zeige Gruppe %s";
$cStrings["all"] = "Alle";
$cStrings["instructions"] = "Klick auf Namen &uuml;bernimmt die Adresse.<br>Klick auf Gruppennamen &uuml;bernimmt alle Adressen einer Gruppe.";

$cErrors[0] = "Keine Kontakte vorhanden.";


?>
