<?php
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "&Auml;ndern";
$ecStrings[1] = "Hinzu";
$ecStrings[2] = " Kontakt";
$ecStrings[3] = "Name";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Gruppe";
$ecStrings[7] = "Kommentar";
$ecStrings[8] = "Tel. privat";
$ecStrings[9] = "Tel. B&uuml;ro";
$ecStrings[10] = "Tel. mobil";
$ecStrings[11] = "Adresse";
$ecStrings[12] = "Weitere Email";
$ecStrings[13] = "L&ouml;schen";
$ecStrings[14] = "Andere";


$errors[0] = "Konnte Kontakt nicht hinzuf&uuml;gen: Datenbank-Fehler.";
$errors[1] = "Ein Eintrag mit dieser Adresse existiert bereits.";
$errors[2] = "Klicken Sie ";
$errors[3] = "hier";
$errors[4] = " um diesen Eintrag zu &auml;ndern.";
$errors[5] = "Kontakt nicht gefunden oder Zugriff verweigert.";
$errors[6] = "Soll der Eintrag f&uuml;\"";
$errors[7] = "\" wirklich gel&ouml;scht werden??";

?>
