<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/eng/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings[0] = "Ordnerverwaltung";
$efStrings[1] = "Neuer Ordner";
$efStrings[2] = "Neuer Ordner: ";
$efStrings[3] = "Erstellen";
$efStrings[4] = "Ordner l&ouml;schen";
$efStrings[5] = "L&ouml;schen";
$efStrings[6] = "Ordner umbenennen";
$efStrings[7] = "Umbenennen";


$errors[0] = "Neuer Ordner: ";
$errors[1] = "Konnte neuen Ordner nicht anlegen: ";
$errors[2] = "Ordner gel&ouml;scht: ";
$errors[3] = "Konnte Ordner nicht l&ouml;schen: ";
$errors[4] = "Ordner umbenannt: ";
$errors[5] = "Konnte Ordner nicht umbenennen: ";
$errors[6] = "Ordner werden nur f&uuml;r IMAP-Zug&auml;nge unterst&uuml;tzt.";

?>