<?php
/********************************************************
	lang/de/filters.inc
	(C)2001-2004 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/filters.inc");

$fltr["filter"] = "Filter";
$fltr["conditions"] = "Bedingungen";
$fltr["actions"] = "Aktionen";
$fltr["auto"] = "Automatisch auf Ordner Posteingang anwenden";
$fltr["deletemsg"] = "Nachricht l&ouml;schen";
$fltr["&"] = "und";
$fltr["|"] = "oder";
$fltr["^"] = "beginnt mit";
$fltr["<"] = "enth&auml;lt";
$fltr["$"] = "endet mit";
$fltr["="] = "ja";
$fltr["!"] = "nein";
$fltr["field"] = "Feld";
$fltr["condition"] = "Bedingung";
$fltr["action"] = "Aktion";
$fltr["name"] = "Name";
$fltr["sort_order"] = "Priorit&auml;t";
$fltr["edit"] = "Bearbeiten";
$fltr["add"] = "Filter speichern";
$fltr["edit_filter"] = "Filter bearbeiten";
$fltr["delete"] = "L&ouml;schen";
$fltr["filters"] = "Filter";
$fltr["new"] = "Neuer Filter";
$fltr["status"] = "Status";
$fltr["stat_en"] = "aktiv";
$fltr["stat_dis"] = "inaktiv";
$fltr["is_active"] = "Filter ist aktiv";
$fltr["other"] = "Anderes";
$fltr["move"] = "Verschiebe in Ordner";
$fltr["copy"] = "Kopiere in ordner";
$fltr["do_nothing"] = "Keine Aktion";
$fltr["add_cond"] = "Bedingung hinzuf&uuml;gen";
$fltr["remove_cond"] = "Bedingung l&ouml;schen";
$fltr["condition_str"] = "%b %c %t";
$f_hlp["priority"] = "(Zahl eingeben. Filter mit h&ouml;chster Priorit&auml;t wird zuerst angewandt)";
$f_err["no_name"] = "Bitte einen Namen für diesen Filter vergeben. \n";
$f_err["no_act"] = "Bitte eine oder mehrere Aktionen ausw&auml;hlen. \n";
$f_err["no_cond"] = "Bitte eine oder mehrere Bedingungen angeben. \n";
$f_err["inv_param"] = "Ung&uuml;ltige Paramter für ausgew&auml;hlte Aktionen. \n";
$f_err["inv_sort"] = "Priorit&auml;ten m&uuml;ssen ganzzahlig sein. \n";
?>
