<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "Geben Sie bitte die HTML-Farbcodes f&uuml;r alle Elemente ein.";
$pcStrings["0.1"] = "Benutzen Sie die ";
$pcStrings["0.2"] = "Farbcode-Tabelle";
$pcStrings["0.3"] = ", um die richtigen Farbcodes zu finden.";
$pcStrings["0.4"] = "Einstellungen, die vom &quot;Theme&quot; gesetzt werden, k&ouml;nnen nicht ge&auml;ndert werden.";
$pcStrings["1.0"] = "Men&uuml;leiste";
$pcStrings["2.0"] = "Ordnerliste";
$pcStrings["3.0"] = "Hauptfenster";
$pcStrings["3.1"] = "&Uuml;berschriften Hintergrund: ";
$pcStrings["3.2"] = "&Uuml;berschriften Textfarbe: ";
$pcStrings["3.3"] = "Dunkle Hintergrundfarbe: ";
$pcStrings["3.4"] = "Heller Text: ";
$pcStrings["4.0"] = "Sonstige";
$pcStrings["4.1"] = "Zitierter Text: ";
$pcStrings["5.0"] = "Schriften";
$pcStrings["5.1"] = "Schriftfamilie";
$pcStrings["5.2"] = "Schriftgr&ouml;&szlig;e Normal: ";
$pcStrings["5.3"] = "Schriftgr&ouml;&szlig;e Klein: ";
$pcStrings["5.4"] = "Schriftgr&ouml;&szlig;e Men&uuml;: ";
$pcStrings["5.5"] = "Schriftgr&ouml;&szlig;e Ordnerliste: ";

							
$pcPortions = array( "Hintergrund: ", "Links: ", "Text: ", "Hervorgehoben: ");

?>
