<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "Identit&auml;ten";
$piStrings["edit"] = "&Auml;ndern";
$piStrings["name"] = "Name";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "Antwortadresse (Reply-To)";
$piStrings["sig"] = "Signatur";
$piStrings["add"] = "Speichern";
$piStrings["new"] = "Neue Identit&auml;t";
$piStrings["edit_ident"] = "Identit&auml;t &auml;ndern";
$piStrings["delete"] = "L&ouml;schen";
$piStrings["setdef"] = "Als Standardidentit&auml;t festlegen.";
$piStrings["isdef"] = "(Standardadresse)";

$piError[1] = "Name oder Email-Adresse erforderlich.";

?>
