<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Zur&uuml;ck";
$rmStrings[1] = "Antworten";
$rmStrings[2] = "Weiterleiten";
$rmStrings[3] = "Gel&ouml;schte wiederherstellen";
$rmStrings[4] = "L&ouml;schen";
$rmStrings[5] = "Verschieben";
$rmStrings[6] = "Teile";
$rmStrings[7] = "Dies ist eine HTML-Nachricht. ";
$rmStrings[8] = "Klicken Sie hier, um sie zu lesen.";
$rmStrings[9] = "Quelle";
$rmStrings[10] = "Gr&ouml;&szlig;e";
$rmStrings[11] = "Als ungelesen markieren";
$rmStrings[12] = "Mail-Header anzeigen";
$rmStrings[13] = "Spam-Beschwerde";
$rmStrings[14] = "Antwort an alle";
$rmStrings[15] = "Sie haben auf diese Nachricht geantwortet";
$rmStrings[16] = "Druckansicht";

?>