<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/eng/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "Ung&uuml;ltige Suche: Ung&uuml;ltiges Feld";
$searchErrors["empty"] = "Ung&uuml;ltige Suche: Leerer Suchbegriff";
$searchErrors["date"] = "Ung&uuml;ltige Suche: Datum nicht angegeben";

?>