<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "Ordner";
$toolStrings["inbox"] = "Posteingang";
$toolStrings["compose"] = "Neue Nachricht";
$toolStrings["calendar"] = "Kalender";
$toolStrings["contacts"] = "Kontakte";
$toolStrings["bookmarks"] = "Lesezeichen";
$toolStrings["search"] = "Suche";
$toolStrings["prefs"] = "Einstellungen";
$toolStrings["logout"] = "Abmelden";
$toolStrings["go"] = "OK";

?>
