<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Bladwijzers";
$bmStrings["identities"] = "Identiteiten";
$bmStrings["edit"] = "Wijzigen";
$bmStrings["name"] = "Naam";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Categorie";
$bmStrings["other"] = "Anders-&gt;";
$bmStrings["comments"] = "Aantekeningen";
$bmStrings["add"] = "Toevoegen";
$bmStrings["new"] = "Nieuwe bladwijzer";
$bmStrings["edit_url"] = "Bladwijzer wijzigen";
$bmStrings["delete"] = "Verwijderen";

$bmError[1] = "Naam of URL verplicht";

?>
