<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/nl/compose.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "Onderwerp";
$composeHStrings[1] = "Van";
$composeHStrings[2] = "Aan";
$composeHStrings[3] = "CC";
$composeHStrings[4] = "BCC";
$composeHStrings[5] = "Datum";


$composeStrings[0] = "Nieuw bericht";
$composeStrings[1] = "Bericht versturen";
$composeStrings[2] = "Toevoegen";
$composeStrings[3] = "Handtekening toevoegen";
$composeStrings[4] = "Bijvoegen";
$composeStrings[5] = "Adressenlijst tonen";
$composeStrings[6] = "Adressenlijst verbergen";
$composeStrings[7] = "Bericht tekst:";
$composeStrings[8] = "Toevoegen";
$composeStrings[9] = "Op %d schreef %s:\n";
$composeStrings[10] = "--- Oorspronkelijke  boodschap ---\n";
$composeStrings[11] = "Venster sluiten";


$composeStrings[12] = "Spelling controleren";
$composeStrings[13] = "Spelling corrigeren";
$composeStrings[14] = "Geen veranderingen";
$composeStrings[15] = "Mogelijke spelfouten";
$composeStrings[16] = "Spellingsveranderingen";
$composeStrings[17] = "negeren";
$composeStrings[18] = "verwijderen";

$composeErrors[0] = "Het onderwerpveld is leeg. Vul alstublieft een onderwerp in, of klik nogmaals op \"".$composeStrings[1]."\" om toch te zenden.";
$composeErrors[1] = "Het \"Van\" veld is leeg. Vul alstublieft je e-mail adres in.";
$composeErrors[2] = "Het \"Aan\" veld is leeg. Vul alstublieft een e-mail adres in.";
$composeErrors[3] = "Uploaden mislukt.";
$composeErrors[4] = "Geen bestanden ontvangen.";
$composeErrors[5] = "Om \"spam\" tegen te gaan kan je slechts eens in de %3 seconden berichten sturen naar %1 mensen (%2 in totaal per sessie).";

$composeErrors[6] = "Geen spelfouten gevonden.";
$composeErrors[7] = "Spellingscontrole niet beschikbaar in de gekozen taal.";
$composeErrors[8] = "(%s woordenboek gebruikt)";
?>
