<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/nl/contacts.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Adressen";
$cStrings[1] = "Een adres toevoegen";
$cStrings[2] = "Contact";
$cStrings[3] = "Naam";
$cStrings[4] = "E-mail";
$cStrings[5] = "Homepage";
$cStrings[6] = "Groep";
$cStrings[7] = "Extra";
$cStrings[8] = "Gegevens bijwerken";
$cStrings[9] = "E-mail";
$cStrings[10] = "Nieuw bericht";

$cStrings["close"] = "Venster sluiten";
$cStrings["addto"] = "Adressen toevoegen aan %s";
$cStrings["showgrp"] = "%s weergeven";
$cStrings["all"] = "Alle adressen";
$cStrings["instructions"] = "Klik op een naam om het bijbehorende adres toe te voegen. U kunt ook op de groep klikken om iedereen in die groep toe te voegen.";

$cErrors[0] = "Adressenlijst is leeg";
?>
