<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
	lang/nl/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/



$lang_months[1] = "Januari";
$lang_months[2] = "Februari";
$lang_months[3] = "Maart";
$lang_months[4] = "April";
$lang_months[5] = "Mei";
$lang_months[6] = "Juni";
$lang_months[7] = "Juli";
$lang_months[8] = "Augustus";
$lang_months[9] = "September";
$lang_months[10] = "Oktober";
$lang_months[11] = "November";
$lang_months[12] = "December";

$lang_datetime["short_mon"][1]="Jan";
$lang_datetime["short_mon"][2]="Feb";
$lang_datetime["short_mon"][3]="Mrt";
$lang_datetime["short_mon"][4]="Apr";
$lang_datetime["short_mon"][5]="Mei";
$lang_datetime["short_mon"][6]="Jun";
$lang_datetime["short_mon"][7]="Jul";
$lang_datetime["short_mon"][8]="Aug";
$lang_datetime["short_mon"][9]="Sep";
$lang_datetime["short_mon"][10]="Okt";
$lang_datetime["short_mon"][11]="Nov";
$lang_datetime["short_mon"][12]="Dec";

$lang_datetime["dsow"][0] = "Zo";
$lang_datetime["dsow"][1] = "Ma";
$lang_datetime["dsow"][2] = "Di";
$lang_datetime["dsow"][3] = "Wo";
$lang_datetime["dsow"][4] = "Do";
$lang_datetime["dsow"][5] = "Vr";
$lang_datetime["dsow"][6] = "Za";

$lang_datetime["dsowl"][0] = "Zondag";
$lang_datetime["dsowl"][1] = "Maandag";
$lang_datetime["dsowl"][2] = "Dinsdag";
$lang_datetime["dsowl"][3] = "Woensdag";
$lang_datetime["dsowl"][4] = "Donderdag";
$lang_datetime["dsowl"][5] = "Vrijdag";
$lang_datetime["dsowl"][6] = "Zaterdag";

$lang_datetime["dsow_short"] = array("Zo", "Ma", "Di", "Wo", "Do", "Vr", "Za");
$lang_datetime["today"] = "%t";			//e.g. "Today 12:02"
$lang_datetime["lastweek"] = "%w %t";		//e.g. "Wed 12:00"
$lang_datetime["thisyear"] = "%d/%m";		//e.g. "2/13"
$lang_datetime["prevyears"] = "%d/%m/%y"; 	//e.g. "1/12/2100"
$lang_datetime["monthyear"] = "%m %y";		//e.g. "January 2002"
$lang_datetime["verbal"] = "%d %m %y";  	//e.g. "1 Jan 1900"
$lang_datetime["verbal_short"] = "%d %m";  	//e.g. "1 Jan"
$lang_datetime["hour_system"] = 24;		// 12 or 24
$lang_datetime["ampm"]["am"] = "am";
$lang_datetime["ampm"]["pm"] = "pm";
$lang_datetime["time_format"] = "%h:%m%a";	// %h=hour, %m=minutes, %a="am:pm"
$lang_datetime["hour_format"] = "%h";

?>
