<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/nl/edit_contact.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Wijzig";
$ecStrings[1] = "Voeg toe";
$ecStrings[2] = "Adresgegevens";
$ecStrings[3] = "Naam";
$ecStrings[4] = "E-mail";
$ecStrings[5] = "Internet";
$ecStrings[6] = "Groep";
$ecStrings[7] = "Extra's";
$ecStrings[8] = "Telefoon thuis";
$ecStrings[9] = "Telefoon werk";
$ecStrings[10] = "GSM";
$ecStrings[11] = "Adres";
$ecStrings[12] = "2de e-mail";
$ecStrings[13] = "Verwijder";
$ecStrings[14] = "Anders:";


$errors[0] = "Kon de gegevens niet toevoegen vanwege een database fout.";
$errors[1] = "Dat adres zit al in je adresboek.";
$errors[2] = "Klik ";
$errors[3] = "hier";
$errors[4] = " om dat adres aan te passen.";
$errors[5] = "Geen adres gevonden, of ik kon geen toegang krijgen.";
$errors[6] = "Weet je zeker dat je het adres \"";
$errors[7] = "\" wilt verwijderen ?";

?>