<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/nl/edit_folders.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	
	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html
********************************************************/


$efStrings[0] = "Beheer mappen";
$efStrings[1] = "Maak een nieuwe map";
$efStrings[2] = "Nieuwe map: ";
$efStrings[3] = "Maken";
$efStrings[4] = "Verwijder map";
$efStrings[5] = "Verwijderen";
$efStrings[6] = "Hernoem map";
$efStrings[7] = "Hernoemen";
$efStrings[8] = "Aangemelde mappen";
$efStrings[9] = "Aanmelden";
$efStrings[10] = "Beschikbare mappen";
$efStrings[11] = "Afmelden";

$errors[0] = "Nieuwe map aangemaakt: ";
$errors[1] = "De volgende map kon niet worden aangemaakt: ";
$errors[2] = "Map verwijderd: ";
$errors[3] = "De volgende map kon niet worden verwijderd: ";
$errors[4] = "De volgende map is hernoemd: ";
$errors[5] = "De voglende map kon niet worden hernoemd: ";
$errors[6] = "Map-ondersteuning is alleen beschikbaar als je IMAP gebruikt.";

?>