<?php 
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Gebruikersnaam";
$loginStrings[1]="Wachtwoord";
$loginStrings[2]="Server";
$loginStrings[3]="Type";
$loginStrings[4]="Rootdir";
$loginStrings[5]="Taal";
$loginStrings[6]="Inloggen";

$loginErrors[0]="Verboden contact te leggen met die computer";
$loginErrors[1]="Error: \"uploads\" map niet gevonden";
$loginErrors[2]="Error: \"users\" map niet gevonden";
$loginErrors[3]="Error: \"sessions\" map niet gevonden";

?>