<?php
include("../lang/eng/main.inc"); // <-- do not delete
/********************************************************
	lang/nl/main.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$mainMessages["delete"] = "%n bericht(en) verwijderd.";
$mainMessages["move"] = "%n bericht(en) verplaatst naar %f.";

$mainStrings[0] = "%p van %n berichten";
$mainStrings[1] = " berichten gevonden";
$mainStrings[2] = "Vorige";
$mainStrings[3] = "";
$mainStrings[4] = "Volgende";
$mainStrings[5] = "";
$mainStrings[6] = "Onderwerp";
$mainStrings[7] = "Aan";
$mainStrings[8] = "Afzender";
$mainStrings[9] = "Ontvangen";
$mainStrings[10] = "Verwijderen";
$mainStrings[11] = "Prullenbak legen";
$mainStrings[12] = "Verplaatsen";
$mainStrings[13] = "Zoeken";
$mainStrings[14] = "Grootte";
$mainStrings[15] = "(geen onderwerp)";
$mainStrings[16] = "Weergeven";
$mainStrings[17] = "Controleer op nieuwe berichten";
$mainStrings[18] = "Alle berichten verwijderen";
$mainStrings[19] = "Annuleren";
$mainStrings[20] = "Markeren als %b";
$mainStrings[21] = "gelezen";
$mainStrings[22] = "ongelezen";


$mainErrors[0] = "Geen berichten gevonden in deze map.";
$mainErrors[1] = "Geen berichten in deze map.";
$mainErrors[2] = "Kon de berichten niet naar de prullenbak verplaatsen.";
$mainErrors[3] = "Kon de berichten niet markeren als \"verwijderd\".";
$mainErrors[4] = "Kon de berichten niet verplaatsten.";
$mainErrors[5] = "Geen prullenbak opgegeven.";
$mainErrors[6] = "Kon de prullenbak niet legen.";
$mainErrors[7] = "Weet u zeker dat u ALLE berichten in %f wilt verwijderen?";
$mainErrors[8] = "Klik op de pijlen onder de kolomkoppen om ze te verplaatsen.<br>Sluit het venster als u klaar bent.";

?>
