<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "Identiteiten";
$piStrings["edit"] = "Aanpassen";
$piStrings["name"] = "Naam";
$piStrings["email"] = "E-mail";
$piStrings["replyto"] = "Antwoorden naar";
$piStrings["sig"] = "Handtekening";
$piStrings["add"] = "Toevoegen";
$piStrings["new"] = "Nieuwe identiteit";
$piStrings["edit_ident"] = "Identiteit aanpassen";
$piStrings["delete"] = "Verwijderen";

$piError[1] = "Naam of e-mail adres vereist";

?>
