<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	
	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html
	
********************************************************/

$pcStrings["0"] = "Vul een HTML kleurcode in voor elk onderdeel.";
$pcStrings["0.1"] = "Gebruik deze ";
$pcStrings["0.2"] = "kleurcode kaart";
$pcStrings["0.3"] = " om de juiste kleurcodes te vinden.";
$pcStrings["0.4"] = "Instellingen die het thema overschrijven kunnen niet worden veranderd.";
$pcStrings["1.0"] = "Werkbalk";
$pcStrings["2.0"] = "Mappenlijst";
$pcStrings["3.0"] = "Hoofdscherm";
$pcStrings["3.1"] = "Titel-achtergrond: ";
$pcStrings["3.2"] = "Titel-tekst: ";
$pcStrings["3.3"] = "Donkere achtergrond: ";
$pcStrings["3.4"] = "Lichte tekst: ";
$pcStrings["4.0"] = "Overig";
$pcStrings["4.1"] = "Citaten: ";
$pcStrings["5.0"] = "Lettertypen";
$pcStrings["5.1"] = "Soort lettertype";
$pcStrings["5.2"] = "Lettertype grootte: ";
$pcStrings["5.3"] = "Kleine letter grootte: ";
$pcStrings["5.4"] = "Menuletter grootte: ";
$pcStrings["5.5"] = "Mappenlijst-letter grootte: ";

$pcPortions = array( "Achtergrond: ", "Verwijzingen: ", "Tekst: ", "Geaccentueerd: ");
?>
