<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/nl/read_message.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Terug";
$rmStrings[1] = "Beantwoorden";
$rmStrings[2] = "Doorsturen";
$rmStrings[3] = "Herstellen";
$rmStrings[4] = "Verwijderen";
$rmStrings[5] = "Verplaats";
$rmStrings[6] = "Onderdelen";
$rmStrings[7] = "Dit is een HTML bericht. ";
$rmStrings[8] = "Klik hier om het te lezen.";
$rmStrings[9] = "Bron";
$rmStrings[10] = "Omvang";
$rmStrings[11] = "Markeer als ongelezen";
$rmStrings[12] = "Toon header";
$rmStrings[13] = "Rapporteer \"spam\"";
$rmStrings[14] = "Iedereen beantwoorden";
$rmStrings[15] = "Je hebt dit bericht beantwoord.";

?>