<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/nl/search_errors.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "Ongeldige zoekcriteria: ongeldig veld";
$searchErrors["empty"] = "Ongeldige zoekcriteria: lege zoekstring";
$searchErrors["date"] = "Ongeldige zoekcriteria: geen datum opgegeven";

?>