<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/nl/tool.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "Mappen";
$toolStrings["inbox"] = "Inbox";
$toolStrings["compose"] = "Nieuw bericht";
$toolStrings["calendar"] = "Kalender";
$toolStrings["contacts"] = "Adressen";
$toolStrings["bookmarks"] = "Bladwijzers";
$toolStrings["search"] = "Zoeken";
$toolStrings["prefs"] = "Voorkeuren";
$toolStrings["logout"] = "Afmelden";
$toolStrings["go"] = "Ga";

?>