<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "收藏夹";
$bmStrings["identities"] = "身份设置";
$bmStrings["edit"] = "编辑";
$bmStrings["name"] = "名称";
$bmStrings["url"] = "网址";
$bmStrings["category"] = "分类";
$bmStrings["other"] = "其他，请在此输入-&gt;";
$bmStrings["comments"] = "附注说明";
$bmStrings["add"] = "新建";
$bmStrings["new"] = "新建收藏夹";
$bmStrings["edit_url"] = "编辑收藏夹";
$bmStrings["delete"] = "删除";

$bmError[1] = "您必须输入名称或网址。";

?>
