<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/tw/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "主旨";
$composeHStrings[1] = "寄件人";
$composeHStrings[2] = "收件人";
$composeHStrings[3] = "副本";
$composeHStrings[4] = "密件副本";
$composeHStrings[5] = "日期";


$composeStrings[0] = "写信";
$composeStrings[1] = "寄信";
$composeStrings[2] = "上传";
$composeStrings[3] = "加上签名档";
$composeStrings[4] = "附件";
$composeStrings[5] = "显示地址簿";
$composeStrings[6] = "隐藏地址簿";
$composeStrings[7] = "邮件本文：";
$composeStrings[8] = "新建";
$composeStrings[9] = "在 %d 的来信中，%s 提及：\n";
$composeStrings[10] = "--- 原始邮件内容 ---\n";
$composeStrings[11] = "关闭本窗口";


$composeErrors[0] = "您忘记填写信申标题了，请填上主旨，或点按“".$composeStrings[1]."”再发送一次。";
$composeErrors[1] = "您忘记填写寄件人区域了。请指定一个寄件人邮箱。";
$composeErrors[2] = "您忘记填写收件人区域了。请指定一个收件人邮箱。";
$composeErrors[3] = "上传失败";
$composeErrors[4] = "系统并未新建任何文件。";
$composeErrors[5] = "为了防杜恶意散发垃圾邮件，你只能每隔 %3 秒钟对 %1 位收件人（每次 %2 封）递送一次邮件。";

?>
