<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/tw/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "地址簿";
$cStrings[1] = "新建联系人";
$cStrings[2] = " 联系人";
$cStrings[3] = "姓名";
$cStrings[4] = "Email 邮箱";
$cStrings[5] = "网站网址";
$cStrings[6] = "所属群组";
$cStrings[7] = "附加说明";
$cStrings[8] = "新建/编辑联系人";
$cStrings[9] = "寄信";
$cStrings[10] = "写信";


$cErrors[0] = "您的地址簿当前没有任何数据。";


?>
