<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
	lang/tw/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime["dsow"] = array ("日","一","二","三","四","五","六");
$lang_datetime["today"] = "[今日] %t";
$lang_datetime["lastweek"] = "%w %t";
$lang_datetime["thisyear"] = "%m/%d";
$lang_datetime["prevyears"] = "%y/%m/%d";


?>
