<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/tw/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "编辑";
$ecStrings[1] = "新建";
$ecStrings[2] = " 联系人";
$ecStrings[3] = "姓名";
$ecStrings[4] = "Email 邮箱";
$ecStrings[5] = "网站网址";
$ecStrings[6] = "所属群组";
$ecStrings[7] = "附加说明";
$ecStrings[8] = "电话（家）";
$ecStrings[9] = "电话（公）";
$ecStrings[10] = "行动电话";
$ecStrings[11] = "通讯地址";
$ecStrings[12] = "Email 邮箱 2";
$ecStrings[13] = "删除";
$ecStrings[14] = "其他";


$errors[0] = "无法新建联系人：数据库发生错误。";
$errors[1] = "地址簿里已经有该联系人的数据了。";
$errors[2] = "点选";
$errors[3] = "这里";
$errors[4] = "可以编辑该联系人";
$errors[5] = "未找到该联系人，或不能访问。";
$errors[6] = "您确实要删除“";
$errors[7] = "”吗？";

?>
