<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "身份设置";
$piStrings["edit"] = "编辑";
$piStrings["name"] = "显示名称";
$piStrings["email"] = "Email 邮箱";
$piStrings["replyto"] = "回覆邮箱";
$piStrings["sig"] = "签名档";
$piStrings["add"] = "新建";
$piStrings["new"] = "新建身份";
$piStrings["edit_ident"] = "编辑身份";
$piStrings["delete"] = "删除";

$piError[1] = "您必须输入“显示名称”或 Email 邮箱。";

?>
