<?php
/********************************************************
	lang/tw/pref_colors.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "请填入颜色代码值来设置各项颜色。";
$pcStrings["0.1"] = "或使用";
$pcStrings["0.2"] = "[颜色代码表]";
$pcStrings["0.3"] = "来查询并设置合适的颜色。";
$pcStrings["0.4"] = "如果界面风格档中已有之设置数值将无法修改。";
$pcStrings["1.0"] = "工具栏";
$pcStrings["2.0"] = "邮件箱列表";
$pcStrings["3.0"] = "主窗口";
$pcStrings["3.1"] = "标题背景： ";
$pcStrings["3.2"] = "标题文字： ";
$pcStrings["3.3"] = "深色背景： ";
$pcStrings["3.4"] = "浅色文字： ";
$pcStrings["4.0"] = "综合选项";
$pcStrings["4.1"] = "引用：";
$pcStrings["5.0"] = "字形";
$pcStrings["5.1"] = "字形群组";
$pcStrings["5.2"] = "字体大小： ";
$pcStrings["5.3"] = "小字体大小： ";
$pcStrings["5.4"] = "菜单词体大小： ";
$pcStrings["5.5"] = "邮件箱列表字体大小： ";

							
$pcPortions = array( "背景颜色： ", "链接颜色： ", "常规文字颜色： ", "高亮度显示颜色： ");

?>
