<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/tw/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "返回";
$rmStrings[1] = "回信";
$rmStrings[2] = "转发";
$rmStrings[3] = "取消删除";
$rmStrings[4] = "删除";
$rmStrings[5] = "文件";
$rmStrings[6] = "附加部分";
$rmStrings[7] = "这是一封 HTML 格式邮件。";
$rmStrings[8] = "点选这里可以立即读取。";
$rmStrings[9] = "邮件原始码";
$rmStrings[10] = "大小";
$rmStrings[11] = "标记未读";
$rmStrings[12] = "显示邮件标头";
$rmStrings[13] = "回报垃圾邮件";
$rmStrings[14] = "回信给所有人";

?>
