<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/tw/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "查找错误：无效的区域";
$searchErrors["empty"] = "查找错误：您未输入任何关键字";
$searchErrors["date"] = "查找错误：您未指定任何日期";

?>
