<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/tw/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	Simplified Chinese (GB2312), for use in China, 
	Singapore & Malaysia Chinese communities
	Translator: Danny Lin <danny@groopie.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "邮件箱一览";
$toolStrings["inbox"] = "收件匣";
$toolStrings["compose"] = "写信";
$toolStrings["contacts"] = "地址簿管理";
$toolStrings["search"] = "查找邮件";
$toolStrings["prefs"] = "首选";
$toolStrings["logout"] = "注销";
$toolStrings["go"] = "Go";

?>
