<?php
include("../lang/eng/main.inc"); // <-- do not delete
/********************************************************
	lang/ga/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$bmStrings["bookmarks"] = "Favoritos";
$bmStrings["identities"] = "Identidades";
$bmStrings["edit"] = "Editar";
$bmStrings["name"] = "Nome";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Categoría";
$bmStrings["other"] = "Especifica-&gt;";
$bmStrings["comments"] = "Comentarios";
$bmStrings["add"] = "Engadir";
$bmStrings["new"] = "Nova Entrada";
$bmStrings["edit_url"] = "Editar Entrada";
$bmStrings["delete"] = "Borrar";

$bmError[1] = "Tes que escribir un Nome ou URL";
$bmError[2] = "Esta función foi desactivada.";
?>
