<?php
include("../lang/eng/main.inc"); // <-- do not delete
/********************************************************
	lang/ga/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$calStr["add_schedule"] = "Engadir Cita";
$calStr["edit_schedule"] = "Editar Cita";
$calStr["weekof"] = "Semana do: %d";
$calStr["title"] = "Titulo:";
$calStr["color"] = "Cor:";
$calStr["colors"] = array("#990000"=>"Vermello Escuro", "#FF0000"=>"Vermello", "#000099"=>"Azul Escuro", "#0000FF"=>"Azul", 
					"#006600"=>"Verde Escuro", "#00FF00"=>"Verde", "#9900FF"=>"Purpura", "#00FFFF"=>"Cian",
					"#FF6600"=>"Laranxa", "#FFFF00"=>"Amarillo", "#FF00FF"=>"Maxenta", ""=>"Sen cor");
$calStr["starts"] = "Comenza o:";
$calStr["ends"] = "Remata o:";
$calStr["from"] = "desde:";
$calStr["until"] = "ata:";
$calStr["repeat_on"] = "Repetir";
$calStr["of"] = "de cada";
$calStr["weeks"] = array(1=>"primeira semana", 2=>"segunda semana", 3=>"terceira semana", 4=>"carta semana"); 
$calStr["week_blurb"] = "...de cada mes(ata a data final).<br>Repite tódalas semanas se non se selecciona ningunha.";
$calStr["monthly"] = "Repetir mensualmente";
$calStr["yearly"] = "Repetir anualmente";
$calStr["place"] = "Lugar:";
$calStr["description"] = "Descripción:";
$calStr["add"] = "Engadir";
$calStr["update"] = "Actualizar";
$calStr["Delete"] = "Borrar";
$calStr["go"] = "Ir";
$calStr["disabled"] = "A función de calendario está desactivada.";

?>
