<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/ga/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "Asunto";
$composeHStrings[1] = "De";
$composeHStrings[2] = "Para";
$composeHStrings[3] = "CC";
$composeHStrings[4] = "BCC";
$composeHStrings[5] = "Data";


$composeStrings[0] = "Escribir Mensaxe";
$composeStrings[1] = "Enviar Mensaxe";
$composeStrings[2] = "Subir";
$composeStrings[3] = "Adxuntar Sinatura";
$composeStrings[4] = "Adxuntar";
$composeStrings[5] = "Contactos";
$composeStrings[6] = "Ocultar Contactos";
$composeStrings[7] = "Corpo da mensaxe:";
$composeStrings[8] = "Engadir";
$composeStrings[9] = "O %d, %s escribiu:\n";
$composeStrings[10] = "--- Mensaxe Orixinal ---\n";
$composeStrings[11] = "Pechar fiestra";
$composeStrings[12] = "Revisar ortografía";
$composeStrings[13] = "Correxir ortografía";
$composeStrings[14] = "Sen cambios";
$composeStrings[15] = "Posibles erros ortograficos";
$composeStrings[16] = "Combios ortográficos";
$composeStrings[17] = "ignorar";
$composeStrings[18] = "borrar";

$composeStrings["title"] = "Redactar";



$composeErrors[0] = "O campo Asunto está valeiro. Por favor, escriba un asunto ou prema \"".$composeStrings[1]."\" de novo para envialo.";
$composeErrors[1] = "O campo \"De\" está valeiro.  Por favor, escriba o seu enderezo de correo electrónico.";
$composeErrors[2] = "O campo \"Para\" está valeiro.  Por favor, escriba o enderezo de correo electrónico do destinatario.";
$composeErrors[3] = "O arquivo non puido subirse";
$composeErrors[4] = "Non se recibiu arquivo ningún.";
$composeErrors[5] = "Para previr o SPAM, só a %1 persoas (%2 en total por sesión) cada %3 segundos.";
$composeErrors[6] = "Non se atoparon erros ortográficos.";
$composeErrors[7] = "O corrector ortográfico non está activado para este idioma.";
$composeErrors[8] = "(usando diccionario %s)";

?>
