<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/ga/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Contactos";
$cStrings[1] = "Engadir Contacto";
$cStrings[2] = " Contacto";
$cStrings[3] = "Nome";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Grupo";
$cStrings[7] = "Comentarios";
$cStrings[8] = "Engadir/Editar Contacto";
$cStrings[9] = "Email";
$cStrings[10] = "Escribir nova mensaxe";

$cStrings["close"] = "Pechar fiestra";
$cStrings["addto"] = "Engadir contactos a %s";
$cStrings["showgrp"] = "Amosar %s";
$cStrings["all"] = "Todos";
$cStrings["instructions"] = "Prema nos nomes a engadir. Tamén pode premer nas etiquetas de grupo para engadir a tódolos dese grupo.";

$cErrors[0] = "A lista de contactos está valeira";


?>
