<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
	lang/ga/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_months[1] = "Xaneiro";
$lang_months[2] = "Febreiro";
$lang_months[3] = "Marzo";
$lang_months[4] = "Abril";
$lang_months[5] = "Maio";
$lang_months[6] = "Xuño";
$lang_months[7] = "Xullo";
$lang_months[8] = "Agosto";
$lang_months[9] = "Septembro";
$lang_months[10] = "Octubre";
$lang_months[11] = "Novembro";
$lang_months[12] = "Decembro";

$lang_datetime["short_mon"][1] = "Xan";
$lang_datetime["short_mon"][2] = "Feb";
$lang_datetime["short_mon"][3] = "Mar";
$lang_datetime["short_mon"][4] = "Abr";
$lang_datetime["short_mon"][5] = "Mai";
$lang_datetime["short_mon"][6] = "Xuñ";
$lang_datetime["short_mon"][7] = "Xul";
$lang_datetime["short_mon"][8] = "Ago";
$lang_datetime["short_mon"][9] = "Set";
$lang_datetime["short_mon"][10] = "Out";
$lang_datetime["short_mon"][11] = "Nov";
$lang_datetime["short_mon"][12] = "Dec";

$lang_datetime["dsow"][0] = "Dom";
$lang_datetime["dsow"][1] = "Lun";
$lang_datetime["dsow"][2] = "Mar";
$lang_datetime["dsow"][3] = "Mer";
$lang_datetime["dsow"][4] = "Xov";
$lang_datetime["dsow"][5] = "Ven";
$lang_datetime["dsow"][6] = "Sab";

$lang_datetime["dsowl"][0] = "Domingo";
$lang_datetime["dsowl"][1] = "Luns";
$lang_datetime["dsowl"][2] = "Martes";
$lang_datetime["dsowl"][3] = "Mércores";
$lang_datetime["dsowl"][4] = "Xoves";
$lang_datetime["dsowl"][5] = "Venres";
$lang_datetime["dsowl"][6] = "Sábado";

$lang_datetime["dsow_short"] = array("D", "L", "M", "M", "X", "V", "S");
$lang_datetime["today"] = "Hoxe %t";           //e.g. "Today 12:02"
$lang_datetime["lastweek"] = "%w %t";           //e.g. "Wed 12:00"
$lang_datetime["thisyear"] = "%d/%m";           //e.g. "13/2"
$lang_datetime["prevyears"] = "%d/%m/%y";       //e.g. "1/1/2100"
$lang_datetime["monthyear"] = "%m %y";          //e.g. "January 2002"
$lang_datetime["verbal"] = "%d %m, %y";         //e.g. "Jan 1, 1900"
$lang_datetime["verbal_short"] = "%d %m";       //e.g. "Jan 1"
$lang_datetime["hour_system"] = 12;			// 12 or 24
$lang_datetime["ampm"]["am"] = "am";
$lang_datetime["ampm"]["pm"] = "pm";
$lang_datetime["time_format"] = "%h:%m%a";	// %h=hour, %m=minutes, %a="am:pm"
$lang_datetime["hour_format"] = "%h%a";         
?>
