<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/ga/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings[0] = "Administrar Carpetas";
$efStrings[1] = "Crear Nova Carpeta";
$efStrings[2] = "Crear Carpeta: ";
$efStrings[3] = "Crear";
$efStrings[4] = "Borrar Carpeta";
$efStrings[5] = "Borrar";
$efStrings[6] = "Renomear Carpeta";
$efStrings[7] = "Renomear";
$efStrings[8] = "Carpetas Subscritas";
$efStrings[9] = "Subscribir";
$efStrings[10] = "Carpetas Non Subscritas";
$efStrings[11] = "Desubscribir";


$errors[0] = "Carpeta creada: ";
$errors[1] = "Non se puido crear a Carpeta: ";
$errors[2] = "Carpeta borrada: ";
$errors[3] = "Non se puido borrar a Carpeta: ";
$errors[4] = "Carpeta renomeada: ";
$errors[5] = "Non se puido renomear a Carpeta: ";
$errors[6] = "As carpetas só poden usarse con contas IMAP.";

?>
