<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/ga/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Editar";
$ecStrings[1] = "Engadir";
$ecStrings[2] = " Contacto";
$ecStrings[3] = "Nome";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Grupo";
$ecStrings[7] = "Comentarios";
$ecStrings[8] = "Teléfono Casa";
$ecStrings[9] = "Teléfono Traballo";
$ecStrings[10] = "Teléfono Móvil";
$ecStrings[11] = "Enderezo";
$ecStrings[12] = "Email Alt.";
$ecStrings[13] = "Borrar";
$ecStrings[14] = "Outro";


$errors[0] = "Non se puido engadir o contacto:  error de base de datos.";
$errors[1] = "Xa existe unha entrada con ese enderezo.";
$errors[2] = "Prema ";
$errors[3] = "aquí";
$errors[4] = " para editar esa entrada.";
$errors[5] = "Contacto non atopado, ou acceso denegado.";
$errors[6] = "¿Desexa borrar a entrada de \"";
$errors[7] = "\"?";

?>
