<?php
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Usuario";
$loginStrings[1]="Contrasinal";
$loginStrings[2]="Servidor";
$loginStrings[3]="Tipo";
$loginStrings[4]="Directorio Raíz";
$loginStrings[5]="Linguaxe";
$loginStrings[6]="Conectar";

$loginErrors[0]="Host non autorizado";
$loginErrors[1]="Error: Non se atopa o directorio \"uploads\"";
$loginErrors[2]="Error: Non se atopa o directorio \"users\" directory not found";
$loginErrors[3]="Error: Non se atopa o directorio \"sessions\" directory not found";

?>
