<?php
include("../lang/eng/main.inc"); // <-- do not delete
/********************************************************
	lang/ga/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$mainMessages["delete"] = "%n mensaxe(s)borradas";
$mainMessages["move"] = "%n mensaxe(s) movidas a %f";

$mainStrings[0] = "Amosando %p de %n";
$mainStrings[1] = " mensaxes atopadas";
$mainStrings[2] = "Anterior";
$mainStrings[3] = "";
$mainStrings[4] = "Seguinte";
$mainStrings[5] = "";
$mainStrings[6] = "Asunto";
$mainStrings[7] = "Para";
$mainStrings[8] = "De";
$mainStrings[9] = "Data";
$mainStrings[10] = "Borrar";
$mainStrings[11] = "Valeirar Eliminados";
$mainStrings[12] = "Mover";
$mainStrings[13] = "Buscar";
$mainStrings[14] = "Tamaño";
$mainStrings[15] = "sen título";
$mainStrings[16] = "Mostrar";
$mainStrings[17] = "Buscar Novos";
$mainStrings[18] = "Borrar Todos";
$mainStrings[19] = "Cancelar";
$mainStrings[20] = "Marcar coma %b";
$mainStrings[21] = "Lida";
$mainStrings[22] = "Non lida";
$mainStrings[23] = "Escolla...";

$mainErrors[0] = "Non se atoparon mensaxes nesta carpeta";
$mainErrors[1] = "Non hai mensaxes nesta carpeta";
$mainErrors[2] = "Non se puido mover as mensaxes a Eliminados.";
$mainErrors[3] = "Non se puido marcar as mensaxes coma eliminadas.";
$mainErrors[4] = "Non se puido mover as mensaxes.";
$mainErrors[5] = "Non se especificou a carpeta Eliminados.";
$mainErrors[6] = "Non se puido valeirar Eliminados";
$mainErrors[7] = "¿Desexa eliminar TÓDALAS MENSAXES en %f?";
$mainErrors[8] = "Pulse nas frechas baixo os encabezados das columnas para movelas.  Cando remate, pulse na ligazón \"Opcións\" na barra de ferramentas.";
?>
