<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/ga/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "Escriba un código de cor HTML color code para cada sección.";
$pcStrings["0.1"] = "Use a ";
$pcStrings["0.2"] = "Carta de Códigos de Cores";
$pcStrings["0.3"] = " para atopar o código adecuado.";
$pcStrings["0.4"] = "Algunhas cores non poden modificarse, por estaren sobreescritas polo Tema.";
$pcStrings["1.0"] = "Barra de Ferramentas";
$pcStrings["2.0"] = "Lista de Carpetas";
$pcStrings["3.0"] = "Principal";
$pcStrings["3.1"] = "Fondo de Encabezado";
$pcStrings["3.2"] = "Texto de Encabezado";
$pcStrings["3.3"] = "Fondo Claro: ";
$pcStrings["3.4"] = "Fondo Escuro: ";
$pcStrings["4.0"] = "Outros";
$pcStrings["4.1"] = "Citas";
$pcStrings["5.0"] = "Fontes";
$pcStrings["5.1"] = "Familia de Fonte";
$pcStrings["5.2"] = "Tamaño de Fonte";
$pcStrings["5.3"] = "Tamaño de Fonte Pequeno";
$pcStrings["5.4"] = "Tamaño de Fonte o Menú";
$pcStrings["5.5"] = "Tamaño de Fonte da Lista de Carpetas: ";

$pcPortions = array( "Fondo: ", "Ligazóns: ", "Texto: ", "Resaltado: ");

?>
