<?php
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "Identidades";
$piStrings["edit"] = "Editar";
$piStrings["name"] = "Nome";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "Respostar a";
$piStrings["sig"] = "Sinatura";
$piStrings["add"] = "Engadir";
$piStrings["new"] = "Nova Identidade";
$piStrings["edit_ident"] = "Editar Identidade";
$piStrings["delete"] = "Borrar";
$piStrings["setdef"] = "Axustar a valores por defecto";
$piStrings["isdef"] = "(Por defecto)";

$piError[1] = "O Nome ou o email son necesarios";

?>
