<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/ga/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Inicio";
$rmStrings[1] = "Respostar";
$rmStrings[2] = "Reenviar";
$rmStrings[3] = "Recuperar";
$rmStrings[4] = "Borrar";
$rmStrings[5] = "Mover";
$rmStrings[6] = "Partes";
$rmStrings[7] = "Esta é unha mensaxe HTML. ";
$rmStrings[8] = "Prema aquí para leela.";
$rmStrings[9] = "Fonte";
$rmStrings[10] = "Tamaño";
$rmStrings[11] = "Non Leída";
$rmStrings[12] = "Amosar Encabezados";
$rmStrings[13] = "Avisar de SPAM";
$rmStrings[14] = "Resp. a Todos";
$rmStrings[15] = "Vostede respondeu a esta mensaxe";
$rmStrings[16] = "Imprimir";
?>
