<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/eng/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "Criterio de Busca non válido:  campo non válido";
$searchErrors["empty"] = "Criterio de Busca non válido:  non especificou cadea a buscar";
$searchErrors["date"] = "Criterio de Busca non válido:  data non especificada";

?>
