<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/ga/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "Carpetas";
$toolStrings["inbox"] = "Bandexa de Entrada";
$toolStrings["compose"] = "Escribir";
$toolStrings["calendar"] = "Calendario";
$toolStrings["contacts"] = "Contactos";
$toolStrings["bookmarks"] = "Favoritos";
$toolStrings["search"] = "Buscar";
$toolStrings["prefs"] = "Preferencias";
$toolStrings["logout"] = "Saír";
$toolStrings["go"] = "Ir";

?>
