<?php

/*  config.php: Plugin file responsible for defining how the plugin interacts with Hastymail 
    Copyright (C) 2002-2010  Hastymail Development group

    This file is part of Hastymail.

    Hastymail is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Hastymail is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Hastymail; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

* $Id:$
*/

$filters_hooks = array(
    'work_hooks'        => array('mailbox_page_start', 'new_page_start'),
    'display_hooks'     => array('mailbox_options_table', 'new_page_controls', 'mailbox_controls_1', 'mailbox_controls_2', 'menu'),
    'page_hook'         => true,
);
$filters_langs = array(
    'en_US' => array(
        1 => 'Mailbox Filters',
        2 => 'Existing Filters',
        3 => 'No Filters Found',
        4 => 'Pattern',
        5 => 'Target',
        6 => 'Action',
        7 => 'Destination Mailbox',
        8 => 'Up',
        9 => 'Down',
        10 => 'Edit',
        11 => 'New Filter',
        12 => 'Edit Filter',
        13 => 'Pattern Target',
        14 => 'Move To',
        15 => 'Mark as Flagged',
        16 => 'Delete Message',
        17 => 'Add',
        18 => 'Update',
        19 => 'Cancel',
        20 => 'Delete',
        21 => 'Filter Options',
        22 => 'Auto Filter INBOX',
        23 => 'Show Filters options in the main menu',
        24 => 'Manage Filters',
        25 => 'Filters',
        26 => 'Custom header field',
        27 => 'Filter',
        28 => 'Move',
        29 => 'Filter Deleted',
        30 => 'Filter Updated',
        31 => 'Filter Added',
        32 => 'Entire message',
        33 => 'Message body',
        34 => 'To field',
        35 => 'Cc field',
        36 => 'From field',
        37 => 'Subject field',
        38 => 'Date',
        39 => 'Message Age',
        40 => 'Older than',
        41 => 'Newer than',
        42 => 'days',
        43 => 'Any age',
        44 => 'Any',
        45 => 'Source Folders',
        46 => 'Any folder being filtered',
        47 => 'Only the following folders',
        48 => 'No messages matched any filters',
    ),
    'bg_BG' => array(
        1 => 'Филтри за писмата',
        2 => 'Съществуващи филтри',
        3 => 'Няма намерени филтри',
        4 => 'Критерий',
        5 => 'Търси в',
        6 => 'Действие',
        7 => 'Целева папка',
        8 => 'Нагоре',
        9 => 'Надолу',
        10 => 'Редактирай',
        11 => 'Нов филтър',
        12 => 'Редактирай филтър',
        13 => 'Търси в',
        14 => 'Премести в',
        15 => 'Маркирай с флаг',
        16 => 'Изтрий писмото',
        17 => 'Добави',
        18 => 'Запази',
        19 => 'Отказ',
        20 => 'Изтрий',
        21 => 'Настройки на филтрите',
        22 => 'Автоматично филтрирай папка "ВХОДЯЩИ"',
        23 => 'Показвай бутона "Филтри" в основното меню',
        24 => 'Управление на филтри',
        25 => 'Филтри',
        26 => 'Потребителско хедърно поле',
        27 => 'Филтрирай',
        28 => 'Преместване',
        29 => 'Филтърът е изтрит',
        30 => 'Филтърът е обновен',
        31 => 'Филтърът е добавен',
        32 => 'Цялото писмо',
        33 => 'Тялото на писмото',
        34 => 'Поле "До"',
        35 => 'Поле "Копие"',
        36 => 'Поле "От"',
        37 => 'Поле "Заглавие"',
        38 => 'Дата',
    ),
    'gr_GR' => array(
        1 => 'Φίλτρα γραμματοκιβωτίου', //'Mailbox Filters',
        2 => 'Υπάρχοντα φίλτρα', //'Existing Filters',
        3 => 'Δεν βρέθηκαν φίλτρα', //'No Filters Found',
        4 => 'Μορφή', //'Pattern',
        5 => 'Στόχος', //'Target',
        6 => 'Ενέργεια', //'Action',
        7 => 'Γραμματοκιβώτιο προορισμού', //'Destination Mailbox',
        8 => 'Επάνω', //'Up',
        9 => 'Κάτω', //'Down',
        10 => 'Επεξεργασία', //'Edit',
        11 => 'Νέο φίλτρο', //'New Filter',
        12 => 'Επεξεργασία φίλτρου', //'Edit Filter',
        13 => 'Μορφή στόχου', //'Pattern Target',
        14 => 'Μετακίνηση σε', //'Move To',
        15 => 'Προσθήκη σήμανσης', //Mark as Flagged',
        16 => 'Διαγραφή μηνύματος', //'Delete Message',
        17 => 'Προσθήκη' , //'Add',
        18 => 'Ενημέρωση', //'Update',
        19 => 'Ακύρωση', //'Cancel',
        20 => 'Διαγραφή', //'Delete',
        21 => 'Επιλογές φίλτρου', //'Filter Options',
        22 => 'Αυτόματο φιλτράρισμα ΕΙΣΕΡΧΟΜΕΝΩΝ', //'Auto Filter INBOX',
        23 => 'Εμφάνιση επιλογής "Φίλτρα" στο κυρίως μενού', //'Show Filters options in the main menu',
        24 => 'Διαχείριση φίλτρων', //'Manage Filters',
        25 => 'Φίλτρα', //'Filters',
        26 => 'Ιδιωτικό πεδίο κεφαλίδας', //'Custom header field',
        27 => 'Φίλτρο', //'Filter',
        28 => 'Μετακίνηση', //'Move',
        29 => 'Το φίλτρο διαγράφηκε', //'Filter Deleted',
        30 => 'Το φίλτρο ενημερώθηκε', //'Filter Updated',
        31 => 'Το φίλτρο προστέθηκε', //'Filter Added',
        32 => 'Ολόκληρο το μήνυμα', //'Entire message',
        33 => 'Σώμα μηνύματος', //'Message body',
        34 => 'Πεδίο ΠΡΟΣ/ΣΕ', //'To field',
        35 => 'Πεδίο ΚΟΙΝ', //'Cc field',
        36 => 'Πεδίο ΑΠΟ', //'From field',
        37 => 'Πεδίο ΘΕΜΑ', //'Subject field',
        38 => 'Ημερομηνία', //'Date',
        39 => 'Παλαιότητα μηνύματος', //'Message Age',
        40 => 'Παλαιότερο από', //'Older than',
        41 => 'Νεότερο από', //'Newer than',
        42 => 'ημέρες', //'days',
        43 => 'Αδιάφορη', //'Any age',
        44 => 'Any',
        45 => 'Source Folders',
        46 => 'Any folder being filtered',
        47 => 'Only the following folders',
        48 => 'No messages matched any filters',
    ),
    'pl_PL' => array(
        1 => 'Filtry Mailbox',
        2 => 'Istniejące Filtry',
        3 => 'Nie znaleziono żadnych filtrów',
        4 => 'Szablon',
        5 => 'Cel',
        6 => 'Akcja',
        7 => 'Skrzynka docelowa',
        8 => 'W górę',
        9 => 'W dół',
        10 => 'Edycja',
        11 => 'Nowy filtr',
        12 => 'Edytuj filtr',
        13 => 'Docelowy wzór',
        14 => 'Przenieś do',
        15 => 'Oznacz jako oflagowana',
        16 => 'Usuń wiadomość',
        17 => 'Dodaj',
        18 => 'Aktualizuj',
        19 => 'Anuluj',
        20 => 'Usuń',
        21 => 'Opcje filtr',
        22 => 'Auto filtr Skrzynki odbiorczej',
        23 => 'Pokazuj opcje filtrów w menu głównym',
        24 => 'Zarządzaj filtrami',
        25 => 'Filtry',
        26 => 'Niestandardowe pole nagłówka',
        27 => 'Filtr',
        28 => 'Przenieś',
        29 => 'Filtr usunięty',
        30 => 'Filtr zaktualizowany',
        31 => 'Filtr dodany',
        32 => 'Cała wiadomość',
        33 => 'Ciało wiadomości',
        34 => 'Pole Do',
        35 => 'Pole DW',
        36 => 'Pole Od',
        37 => 'Pole tematu',
        38 => 'Data',
        39 => 'Wiek wiadomości',
        40 => 'Starsze niż',
        41 => 'Newer than',
        42 => 'dni',
        43 => 'Any age',
        44 => 'Any',
        45 => 'Source Folders',
        46 => 'Any folder being filtered',
        47 => 'Only the following folders',
        48 => 'No messages matched any filters',
    ),
);
?>
