<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Bogm&aelig;rker";
$bmStrings["identities"] = "Identiteter";
$bmStrings["edit"] = "Rediger";
$bmStrings["name"] = "Navn";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Kategori";
$bmStrings["other"] = "V&aelig;lg eller angiv-&gt;";
$bmStrings["comments"] = "Kommentarer";
$bmStrings["add"] = "Tilf&oslash;j";
$bmStrings["new"] = "Ny indgang";
$bmStrings["edit_url"] = "Rediger indgang";
$bmStrings["delete"] = "Slet";

$bmError[1] = "Navn eller URL skal anf&oslash;res";
$bmError[2] = "Denne funktion er blevet deaktiveret.";
?>
