<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Ny aftale";
$calStr["edit_schedule"] = "Rediger aftale";
$calStr["weekof"] = "Uge: %d";
$calStr["title"] = "Titel:";
$calStr["color"] = "Farve:";
$calStr["colors"] = array("#990000"=>"M&oslash;rker&oslash;d", "#FF0000"=>"R&oslash;d", "#000099"=>"M&oslash;rkebl&aring;", "#0000FF"=>"Bl&aring;", 
					"#006600"=>"M&oslash;rkegr&oslash;n", "#00FF00"=>"Gr&oslash;n", "#9900FF"=>"Lila", "#00FFFF"=>"Cyan",
					"#FF6600"=>"Orange", "#FFFF00"=>"Gul", "#FF00FF"=>"Magenta", ""=>"Ingen farve");
$calStr["starts"] = "Starter:";
$calStr["ends"] = "Slutter:";
$calStr["from"] = "fra:";
$calStr["until"] = "til:";
$calStr["repeat_on"] = "Gentag";
$calStr["of"] = "hver";
$calStr["weeks"] = array(1=>"f&oslash;rste uge", 2=>"anden uge", 3=>"tredje uge", 4=>"fjerde uge"); 
$calStr["week_blurb"] = "... i hver m&aring;ned (ind til slutdatoen).<br>Vil blive gentaget hver uge, hvis ingen er valgt.";
$calStr["monthly"] = "Gentag hver m&aring;ned";
$calStr["yearly"] = "Gentag hvert &aring;r";
$calStr["place"] = "Sted:";
$calStr["description"] = "Beskrivelse:";
$calStr["add"] = "Tilf&oslash;j";
$calStr["update"] = "Rediger";
$calStr["Delete"] = "Slet";
$calStr["go"] = "G&aring; til";
$calStr["disabled"] = "Kalenderfunktionen er deaktiveret.";
?>
