<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
    lang/dk/compose.inc
    (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

    This file is part of IlohaMail, and released under GPL.
    See COPYING, or http://www.fsf.org/copyleft/gpl.html

    Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$composeHStrings[0] = "Emne";
$composeHStrings[1] = "Fra";
$composeHStrings[2] = "Til";
$composeHStrings[3] = "CC";
$composeHStrings[4] = "BCC";
$composeHStrings[5] = "Dato";


$composeStrings[0] = "Ny meddelelse";
$composeStrings[1] = "Send meddelelse";
$composeStrings[2] = "Tilf&oslash;j bilag";
$composeStrings[3] = "Inds&aelig;t signatur";
$composeStrings[4] = "Bilag";
$composeStrings[5] = "Tilf&oslash;j kontaktpersoner";
$composeStrings[6] = "Skjul kontaktpersoner";
$composeStrings[7] = "Meddelelsestekst:";
$composeStrings[8] = "Tilf&oslash;j";
$composeStrings[9] = "Den %d, skrev %s:\n";
$composeStrings[10] = "--- Oprindelig meddelelse ---\n";
$composeStrings[11] = "Luk vindue";

$composeStrings[12] = "Kontroller stavning";
$composeStrings[13] = "Ret stavning";
$composeStrings[14] = "Ingen rettelser";
$composeStrings[15] = "Mulige stavefejl";
$composeStrings[16] = "Staverettelser";
$composeStrings[17] = "ignorer";
$composeStrings[18] = "slet";

$composeStrings["title"] = "Ny meddelelse";

$composeErrors[0] = "Emnefeltet er tomt.  Angiv et emne for meddelelsen eller klik p&aring; \"" . $composeStrings[1] . "\" igen for at sende.";
$composeErrors[1] = "\"Fra\"-feltet er tomt.  Angiv din egen mail-adresse.";
$composeErrors[2] = "\"Til\"-feltet er tomt.  Angiv en eller flere modtagere.";
$composeErrors[3] = "Det lykkedes ikke at hente bilaget.";
$composeErrors[4] = "Bilaget blev ikke tilf&oslash;jet.";
$composeErrors[5] = "For at minimere muligheden for udsendelse af uanmodede meddelelser (spam), er det ikke tilladt at sende til flere end %1 personer (%2 i alt per meddelelse) med %3 sekunders mellemrum.";

$composeErrors[6] = "Ingen stavefejl blev fundet.";
$composeErrors[7] = "Stavekontrol er ikke tilg&aelig;ngelig for det valgte sprog.";
$composeErrors[8] = "(%s -ordbog bruges)";
?>
