<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
        lang/dk/contacts.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$cStrings[0] = "Kontaktpersoner";
$cStrings[1] = "Tilf&oslash;j kontaktperson";
$cStrings[2] = " kontaktperson";
$cStrings[3] = "Navn";
$cStrings[4] = "Mail-adresse";
$cStrings[5] = "URL";
$cStrings[6] = "Gruppe";
$cStrings[7] = "Kommentar";
$cStrings[8] = "Tilf&oslash;j/rediger kontaktperson";
$cStrings[9] = "Mail-adresse";
$cStrings[10] = "Skriv ny meddelelse til de valgte personer";

$cStrings["close"] = "Luk vindue";
$cStrings["addto"] = "Tilf&oslash;j kontaktperson(er) til %s";
$cStrings["showgrp"] = "Vis %s";
$cStrings["all"] = "Alle";
$cStrings["instructions"] = "Klik p&aring; de navne, der skal tilf&oslash;jes.<br>Hvis du klikker p&aring; en gruppelabel, tilf&oslash;jes alle fra denne gruppe.<br>Luk blot vinduet, n&aring;r du er f&aelig;rdig.";

$cErrors[0] = "Listen med kontaktpersoner er tom";

?>
