<?php
include("../lang/eng/cp.inc"); // <-- do not delete
/********************************************************
        lang/dk/cp.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/
?>
<B>Oversigt over farvekoder</B>
