<?php
include("../lang/eng/defaultFolders.inc"); // <-- do not delete
/********************************************************
        lang/dk/defaultFolders.inc
        (C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

        $sentbox=$my_prefs["sent_box_name"];
        $trashname=$my_prefs["trash_name"];
        $defaults["INBOX"] = "Indbakke";
        $defaults[$sentbox] = "Sendte mails";
        $defaults[$trashname] = "Papirkurv";

?>
