<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
        lang/dk/edit_folders.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$efStrings[0] = "Folderh&aring;ndtering";
$efStrings[1] = "Opret ny folder";
$efStrings[2] = "Opret folder: ";
$efStrings[3] = "Opret";
$efStrings[4] = "Slet folder";
$efStrings[5] = "Slet";
$efStrings[6] = "Omd&oslash;b folder";
$efStrings[7] = "Omd&oslash;b";
$efStrings[8] = "Tilmeldte foldere";
$efStrings[9] = "Tilmeld";
$efStrings[10] = "Afmeldte foldere";
$efStrings[11] = "Afmeld";


$errors[0] = "Opret folder: ";
$errors[1] = "Kunne ikke oprette folder: ";
$errors[2] = "Slettet folder: ";
$errors[3] = "Kunne ikke slette folder: ";
$errors[4] = "Omd&oslash;bt folder: ";
$errors[5] = "Kunne ikke omd&oslash;be folder: ";
$errors[6] = "Folderunderst&oslash;ttelse er kun tilg&aelig;ngelig med IMAP-konti.";

?>
