<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
        lang/dk/edit_contact.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$ecStrings[0] = "Rediger";
$ecStrings[1] = "Tilf&oslash;j";
$ecStrings[2] = " kontaktperson";
$ecStrings[3] = "Navn";
$ecStrings[4] = "Mail-adresse";
$ecStrings[5] = "URL";
$ecStrings[6] = "Gruppe";
$ecStrings[7] = "Kommentarer";
$ecStrings[8] = "Hjemmetelefon";
$ecStrings[9] = "Arbejdstelefon";
$ecStrings[10] = "Mobiltelefon";
$ecStrings[11] = "Adresse";
$ecStrings[12] = "Alternativ mail";
$ecStrings[13] = "Slet";
$ecStrings[14] = "V&aelig;lg eller angiv-&gt;";


$errors[0] = "Kunne ikke tilf&oslash;je kontaktperson: databasefejl.";
$errors[1] = "Der findes allerede en indgang med samme adresse.";
$errors[2] = "Klik ";
$errors[3] = "her";
$errors[4] = " for i stedet at redigere den indgang.";
$errors[5] = "Kontaktperson ikke fundet eller adgang n&aelig;gtet.";
$errors[6] = "Er du sikker p&aring;, at du vil slette \"";
$errors[7] = "\"?";

?>
