<?php
/********************************************************
	lang/dk/filters.inc
	(C)2001-2004 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Danish translation: Niels Baggesen <nba@users.sourceforge.net>

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/filters.inc");

$fltr["filter"] = "Filter";
$fltr["conditions"] = "Betingelser";
$fltr["actions"] = "Handlinger";
$fltr["auto"] = "Udf&oslash;res automatisk p&aring; Indbakke";
$fltr["deletemsg"] = "Slet meddelelse";
$fltr["&"] = "og";
$fltr["|"] = "eller";
$fltr["^"] = "begynder med";
$fltr["<"] = "indeholder";
$fltr["$"] = "slutter med";
$fltr["="] = "";
$fltr["!"] = "ikke";
$fltr["field"] = "Felt";
$fltr["condition"] = "Betingelse";
$fltr["action"] = "Handling";
$fltr["name"] = "Navn";
$fltr["sort_order"] = "R&aelig;kkef&oslash;lge";
$fltr["edit"] = "ret";
$fltr["add"] = "Tilf&oslash;j filter";
$fltr["edit_filter"] = "Ret filter";
$fltr["delete"] = "Slet";
$fltr["filters"] = "Filtre";
$fltr["new"] = "Nyt filter";
$fltr["status"] = "Status";
$fltr["stat_en"] = "aktiv";
$fltr["stat_dis"] = "inaktiv";
$fltr["is_active"] = "filter er aktivt";
$fltr["other"] = "Andet";
$fltr["move"] = "Flyt til";
$fltr["copy"] = "Kopier til";
$fltr["do_nothing"] = "G&oslash;r ingenting";
$fltr["add_cond"] = "Tilf&oslash;j betingelse";
$fltr["remove_cond"] = "Slet betingelse";
$fltr["condition_str"] = "%b %c %t";

$f_hlp["priority"] = "(h&oslash;jere prioritet k&oslash;res f&oslash;rst.)";

$f_err["no_name"] = "Giv venligst denne regel et navn\n";
$f_err["no_act"] = "V&aelig;lg en eller flere handlinger til denne regel";
$f_err["no_cond"] = "Angiv en eller flere betingelser for denne regel\n";
$f_err["inv_param"] = "Invalid parameters for selected actions\n";
$f_err["inv_sort"] = "Sorterings r&aelig;kkef&oslash;lge skal v&aelig;re et tal\n";

?>
