<?php
include("../lang/eng/folders.inc"); // <-- do not delete
/********************************************************
        lang/dk/folders.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/


	$fl_str["folders"] = "Foldere";
	$fl_str["manage"] = "Folderh&aring;ndtering";

	$sentbox=$my_prefs["sent_box_name"];
	$trashname=$my_prefs["trash_name"];
	$defaults["INBOX"] = "Indbakke";
	$defaults[$sentbox] = "Sendte mails";
	$defaults[$trashname] = "Papirkurv";
	$fstr["reload"] = "genopfrisk";
	$fstr["expunge"] = "t&oslash;m";

?>
