<?php 
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Brugernavn";
$loginStrings[1]="Password";
$loginStrings[2]="Server";
$loginStrings[3]="Type";
$loginStrings[4]="Hovedfolder";
$loginStrings[5]="Sprog";
$loginStrings[6]="Log ind";

$loginErrors[0]="Uautoriseret v&aelig;rtsmaskine";
$loginErrors[1]="Fejl: \"uploads\"-mappe ikke fundet";
$loginErrors[2]="Fejl: \"users\"-mappe ikke fundet";
$loginErrors[3]="Fejl: \"sessions\"-mappe ikke fundet";

?>
