<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
    lang/dk/cp.inc
    (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

    This file is part of IlohaMail, and released under GPL.
    See COPYING, or http://www.fsf.org/copyleft/gpl.html

    Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$pcStrings["0"] = "Indtast en HTML-farve for hver komponent.";
$pcStrings["0.1"] = "Brug ";
$pcStrings["0.2"] = "oversigten over farvekoder.";
$pcStrings["0.3"] = " for at finde de rigtige farvekoder.";
$pcStrings["0.4"] = "Visse indstillinger kan ikke &aelig;ndres afh&aelig;ngig af det valgte farvetema.";
$pcStrings["1.0"] = "V&aelig;rkt&oslash;jslinje";
$pcStrings["2.0"] = "Folderoversigt";
$pcStrings["3.0"] = "Hovedsk&aelig;rmbilledet";
$pcStrings["3.1"] = "Baggrundsfarve for brevhoved: ";
$pcStrings["3.2"] = "Tekstfarve for brevhoved: ";
$pcStrings["3.3"] = "M&oslash;rk baggrund: ";
$pcStrings["3.4"] = "Lys tekst: ";
$pcStrings["4.0"] = "Diverse";
$pcStrings["4.1"] = "Citater: ";
$pcStrings["5.0"] = "Skrifttyper";
$pcStrings["5.1"] = "Skrifttypefamilie";
$pcStrings["5.2"] = "Skriftst&oslash;rrelse: ";
$pcStrings["5.3"] = "Lille skriftst&oslash;rrelse: ";
$pcStrings["5.4"] = "Skriftst&oslash;rrelse for menuen: ";
$pcStrings["5.5"] = "Skriftst&oslash;rrelse for folderoversigten: ";

                            
$pcPortions = array( "Baggrund: ", "Links: ", "Tekst: ", "Fremh&aelig;v: ");

?>
