<?php
include("../lang/eng/quota.inc"); // <-- do not delete
/********************************************************
	lang/eng/quota.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$quotaStr["label"] = "Diskforbrug: ";
$quotaStr["full"] = "%usedKB/%totalKB (%free% tilg&aelig;ngelig)";
$quotaStr["unknown"] = "ukendt";

?>
