<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
        lang/dk/read_message.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$rmStrings[0] = "Tilbage";
$rmStrings[1] = "Svar";
$rmStrings[2] = "Videresend";
$rmStrings[3] = "Fortryd slet";
$rmStrings[4] = "Slet";
$rmStrings[5] = "Flyt";
$rmStrings[6] = "Dele";
$rmStrings[7] = "Dette er en HTML-meddelelse. ";
$rmStrings[8] = "Klik her for at l&aelig;se den.";
$rmStrings[9] = "Vis den r&aring; meddelelse";
$rmStrings[10] = "St&oslash;rrelse";
$rmStrings[11] = "Marker som ul&aelig;st";
$rmStrings[12] = "Vis brevhoved";
$rmStrings[13] = "Rapporter spam";
$rmStrings[14] = "Svar til alle";
$rmStrings[15] = "Du har besvaret denne meddelelse";
$rmStrings[16] = "Udskriftsvenlig";

?>
