<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
        lang/dk/tool.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

	Translated by Torben Rybner, Ziberex (try@ziberex.dk)

********************************************************/

$toolStrings["folders"] = "Foldere";
$toolStrings["inbox"] = "Indbakke";
$toolStrings["compose"] = "Skriv ny meddelelse";
$toolStrings["calendar"] = "Kalender";
$toolStrings["contacts"] = "Kontaktpersoner";
$toolStrings["bookmarks"] = "Bogm&aelig;rker";
$toolStrings["search"] = "S&oslash;g";
$toolStrings["prefs"] = "Indstillinger";
$toolStrings["logout"] = "Log ud";
$toolStrings["go"] = "G&aring; til";

?>
