<?php
/********************************************************
	lang/eng/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Юymлs";
$bmStrings["identities"] = "Profiliai";
$bmStrings["edit"] = "Atnaujinti";
$bmStrings["name"] = "Vardas";
$bmStrings["url"] = "Adresas";
$bmStrings["rss"] = "RSS/RDF";
$bmStrings["category"] = "Kategorija";
$bmStrings["other"] = "Nurodyti-&gt;";
$bmStrings["comments"] = "Komentarai";
$bmStrings["add"] = "Pridлti";
$bmStrings["new"] = "Naujas бraрas";
$bmStrings["edit_url"] = "Redaguoti бraра";
$bmStrings["delete"] = "Iрtrinti";

$bmError[1] = "Reikia бvesti vardа arba adresа";
$bmError[2] = "Рi funkcija yra panaikinta.";
?>