<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Pridëti tvarkaraðtá";
$calStr["edit_schedule"] = "Redaguoti tvarkaraðtá";
$calStr["weekof"] = "Savaitë: %d";
$calStr["title"] = "Pavadinimas:";
$calStr["color"] = "Spalva:";
$calStr["colors"] = array("#990000"=>"Tamsiai raudona", "#FF0000"=>"Raudona", "#000099"=>"Tamsiai mëlyna", "#0000FF"=>"Þydra", 
					"#006600"=>"Tamsiai þalia", "#00FF00"=>"Þalsva", "#9900FF"=>"Purpurinë", "#00FFFF"=>"Þalsvai mëlyna",
					"#FF6600"=>"Oranþinë", "#FFFF00"=>"Geltona", "#FF00FF"=>"Rausva", ""=>"Be spalvos");
$calStr["starts"] = "Prasideda:";
$calStr["ends"] = "Baigiasi:";
$calStr["from"] = "Nuo:";
$calStr["until"] = "Iki:";
$calStr["repeat_on"] = "Pasikartoja";
$calStr["of"] = "kiekvienà";
$calStr["weeks"] = array(1=>"pirmà savaitæ", 2=>"antrà savaitæ", 3=>"treèià savaitæ", 4=>"ketvirtà savaitæ"); 
$calStr["week_blurb"] = "kiekvieno mënesio (iki datos pabaigos).<br>Kartosis kiekvienà savaitæ, jeigu niekas nepaþymëta.";
$calStr["monthly"] = "Kartoti kas mënesá";
$calStr["yearly"] = "Kartoti kasmet";
$calStr["place"] = "Vieta:";
$calStr["description"] = "Apraðymas:";
$calStr["add"] = "Pridëti";
$calStr["update"] = "Atnaujinti";
$calStr["Delete"] = "Iðtrinti";
$calStr["go"] = "Pirmyn";
$calStr["disabled"] = "Kalendoriaus funkcija yra iðjungta.";
$calStr["public"] = "Daryti áraðà vieðai prieinamà"; 
?>