<?php
/********************************************************
	lang/eng/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/compose.inc");

$composeHStrings[0] = "Tema";
$composeHStrings[1] = "Nuo";
$composeHStrings[2] = "Kam";
$composeHStrings[3] = "Kam kopijа";
$composeHStrings[4] = "Kam nematoma kopijа";
$composeHStrings[5] = "Data";


$composeStrings[0] = "Raрyti laiрkа";
$composeStrings[1] = "Siшsti laiрkа";
$composeStrings[2] = "Patalpinti";
$composeStrings[3] = "Prisegti paraра";
$composeStrings[4] = "Prisegti";
$composeStrings[5] = "Kontaktai";
$composeStrings[6] = "Slлpti kontaktus";
$composeStrings[7] = "Laiрko turinys";
$composeStrings[8] = "Pridлti";
$composeStrings[9] = " %d, %s raрyta:\n";
$composeStrings[10] = "--- Laiрko originalas ---\n";
$composeStrings[11] = "Uюdaryti langа";

$composeStrings[12] = "Tikrinti raрybа";
$composeStrings[13] = "Taisyti raрybа";
$composeStrings[14] = "Be pakeitimш";
$composeStrings[15] = "Galimos raрybos klaidos";
$composeStrings[16] = "Raрybos keitimas";
$composeStrings[17] = "ignoruoti";
$composeStrings[18] = "iрtrinti";

$composeStrings["title"] = "Raрyti laiрkа";

$composeErrors[0] = "Temos laukas yra tuриias. Praрome бraрyti temа arba paspausti \"".$composeStrings[1]."\" vлl, kad iрsiшstumлt.";
$composeErrors[1] = " \"Nuo\" laukas yra tuриias.  Praрome бraрyti savo el. paрto adresа.";
$composeErrors[2] = " \"Kam\" laukas yra tuриias.  Praрome nurodyti gavлjo adresа.";
$composeErrors[3] = "Nusiuntimas nepavyko";
$composeErrors[4] = "Bylш negauta.";
$composeErrors[5] = "Dлl рiыkрlinimo prevencijos, jыs galite iрsiшsti tik %1 юmonлms (%2 iр viso per vienа sesijа) kas %3 sekundes.";

$composeErrors[6] = "Raрybos klaidш nerasta.";
$composeErrors[7] = "Рiai kalbai raрybos klaidш taisymas negalimas.";
$composeErrors[8] = "(%s naudojamas юodynas)";
?>