<?php
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/contacts.inc");

$cStrings[0] = "Kontaktai";
$cStrings[1] = "Pridëti kontaktà";
$cStrings[2] = " Kontaktas";
$cStrings[3] = "Vardas";
$cStrings[4] = "Elektroninis paðtas";
$cStrings[5] = "Adresas";
$cStrings[6] = "Grupë";
$cStrings[7] = "Komentarai";
$cStrings[8] = "Pridëti/Redaguoti Kontaktà";
$cStrings[9] = "Elektroninis paðtas";
$cStrings[10] = "Raðyti";

$cStrings["close"] = "Uþdaryti langà";
$cStrings["addto"] = "Pridëti kontaktus á %s";
$cStrings["showgrp"] = "Rodyti %s";
$cStrings["all"] = "Visi";
$cStrings["instructions"] = "Paspauskite an vardø, kad pridëtumëte.  Jûs taip pat galite paspausti grupës þymës, kad pridëtumëte visus, esanèius grupëje.";
$cStrings["share"] = "Padaryti áraðà prieinamà vieðai";
$cStrings["add_contact"] = "Pridëti kontaktà";
$cStrings["edit_contact"] = "Redaguoti kontaktà";
$cStrings["add"] = "Pridëti";
$cStrings["edit"] = "Atnaujinti";
$cErrors[0] = "Kontaktø sàraðas yra tuðèias";
$cErrors[1] = "Neiðëjo pasiekti nurodyto áraðo.";


?>