<?php
/********************************************************
	lang/eng/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_folders.inc");

$efStrings[0] = "Redaguoti aplankus";
$efStrings[1] = "Sukurti naujà aplankà";
$efStrings[2] = "Sukurti aplankà: ";
$efStrings[3] = "Sukurti";
$efStrings[4] = "Iðtrinti aplankà";
$efStrings[5] = "Iðtrinti";
$efStrings[6] = "Pervadinti aplankà";
$efStrings[7] = "Pervadinti";
$efStrings[8] = "Uþsakyti aplankai";
$efStrings[9] = "Uþsakyti";
$efStrings[10] = "Atsisakyti aplankai";
$efStrings[11] = "Atsisakyti";


$errors[0] = "Sukurti aplankà: ";
$errors[1] = "Neiðëjo sukurti aplanko: ";
$errors[2] = "Iðtrintas aplankas: ";
$errors[3] = "Neiðëjo iðtrinti aplanko: ";
$errors[4] = "Pervadintas aplankas: ";
$errors[5] = "Neiðëjo pervadinti aplanko: ";
$errors[6] = "Aplankø palaikymas yra galimas tik IMAP sàskaitas turintiems vartotojams.";

?>