<?php
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Redaguoti";
$ecStrings[1] = "Pridлti";
$ecStrings[2] = " Kontaktа";
$ecStrings[3] = "Vardas";
$ecStrings[4] = "Elektroninis paрtas";
$ecStrings[5] = "Adresas";
$ecStrings[6] = "Grupл";
$ecStrings[7] = "Komentarai";
$ecStrings[8] = "Namш telefonas";
$ecStrings[9] = "Darbo telefonas";
$ecStrings[10] = "Mobilus telefonas";
$ecStrings[11] = "Adresas";
$ecStrings[12] = "Alt. el. paрtas";
$ecStrings[13] = "Iрtrinti";
$ecStrings[14] = "Kita";
$ecStrings[15] = "Vardas";
$ecStrings[16] = "Pavardл";
$ecStrings[17] = "Gatvл";
$ecStrings[18] = "Miestas";
$ecStrings[19] = "Rajonas / Regionas";
$ecStrings[20] = "Paрto indeksas";
$ecStrings[21] = "Рalis";


$errors[0] = "Neiрлjo pridлti kontakto:  duomenш bazлs klaida.";
$errors[1] = "Бraрas su рiuo adresu jau egzistuoja.";
$errors[2] = "Spausti ";
$errors[3] = "иia";
$errors[4] = " redaguoti бraра iр naujo.";
$errors[5] = "Kontaktas nerastas, arba priлjimas negalimas.";
$errors[6] = "Ar Jыs esate бsitikinжs, kad norite iрtrinti бraра \"";
$errors[7] = "\"?";

?>