<?php 
/********************************************************
	lang/en/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Vartotojo ID";
$loginStrings[1]="Slaptaþodis";
$loginStrings[2]="Serveris";
$loginStrings[3]="Tipas";
$loginStrings[4]="Pagrindinë dir.";
$loginStrings[5]="Kalba";
$loginStrings[6]="Prisijungti";

$loginErrors[0]="Neleistinas adresas";
$loginErrors[1]="Klaida: \"uploads\" direktorija nerasta";
$loginErrors[2]="Klaida: \"users\" direktorija nerasta";
$loginErrors[3]="Klaida: \"sessions\" direktorija nerasta";

?>