<?php
/********************************************************
	lang/eng/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainMessages["delete"] = "Iðtrinti %n laiðkà(us)";
$mainMessages["move"] = "Perkelti %n laiðkà(us) á %f";

$mainStrings[0] = "Rodoma %p ið %n";
$mainStrings[1] = " rasta laiðkø";
$mainStrings[2] = "Ankstesni";
$mainStrings[3] = "";
$mainStrings[4] = "Sekantys";
$mainStrings[5] = "";
$mainStrings[6] = "Tema";
$mainStrings[7] = "Kam";
$mainStrings[8] = "Nuo";
$mainStrings[9] = "Data";
$mainStrings[10] = "Iðtrinti";
$mainStrings[11] = "Iðvalyti ðiûkðliadëþæ";
$mainStrings[12] = "Perkelti";
$mainStrings[13] = "Ieðkoti";
$mainStrings[14] = "Dydis";
$mainStrings[15] = "neávardintas";
$mainStrings[16] = "Rodyti";
$mainStrings[17] = "Tikrinti naujà";
$mainStrings[18] = "Iðtrinti viskà";
$mainStrings[19] = "Atðaukti";
$mainStrings[20] = "Paþymëti kaip %b";
$mainStrings[21] = "Skaitytas";
$mainStrings[22] = "Neskaitytas";
$mainStrings[23] = "Paþymëti...";
$mainStrings[24] = "Ájugti filtrà";
$mainStrings[25] = "Paþymëti";
$mainStrings[26] = "Svarbûs";
$mainStrings[27] = "Filtrai:";
$mainStrings[28] = "Visi filtrai";
$mainStrings[29] = "Taikyti";
$mainStrings[30] = "Greita paieðka:";
$mainStrings[31] = "Iðsirinkti";

$mainErrors[0] = "Ðiame aplanke laiðkø nerasta";
$mainErrors[1] = "Aplanke laiðkø nëra";
$mainErrors[2] = "Nepavyko perkelti laiðkø á ðiûkðliadëþæ.";
$mainErrors[3] = "Nepavyko paþymëti laiðkø kaip iðtrintø.";
$mainErrors[4] = "Nepavyko perkelti laiðkø.";
$mainErrors[5] = "Ðiûkðliadëþë nenurodyta.";
$mainErrors[6] = "Nepavyko iðvalyti ðiûkðliadëþës";
$mainErrors[7] = "Ar Jûs esate ásitikinæ, kad norite iðtrinti VISUS laiðkus %f?";
$mainErrors[8] = "Spauskite ant rodyklëlës po stulpeliø pavadinimais norëdami pajudinti juos.<br>Jeigu jau uþbaigëte, tiesiog uþdarykite langà.";



?>