<?php
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "Profiliai";
$piStrings["edit"] = "Redaguoti";
$piStrings["name"] = "Vardas";
$piStrings["email"] = "Elektroninis paðtas";
$piStrings["replyto"] = "Atsakyti kam";
$piStrings["sig"] = "Paraðas";
$piStrings["add"] = "Pridëti";
$piStrings["new"] = "Naujas profilis";
$piStrings["edit_ident"] = "Redaguoti profilá";
$piStrings["delete"] = "Iðtrinti";
$piStrings["setdef"] = "Padaryti pagrindiná nutylint";
$piStrings["isdef"] = "(Pagrindinis nutylint)";

$piError[1] = "Vardà ar el. paðtà ávesti bûtina ";

?>
