<?php
/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "Áveskite HTML spalvos kodà kiekvienam komponentui.";
$pcStrings["0.1"] = "Naudokite ";
$pcStrings["0.2"] = "Spalvø kodø lentelæ";
$pcStrings["0.3"] = " jeigu norite surasti reikiamus kodus.";
$pcStrings["0.4"] = "Aukðtesnio lygio nustatymai negali bûti keièiami.";
$pcStrings["1.0"] = "Árankiai";
$pcStrings["2.0"] = "Aplankø sàraðas";
$pcStrings["3.0"] = "Pagrindinis";
$pcStrings["3.1"] = "Antraðtës kita pusë: ";
$pcStrings["3.2"] = "Antraðtës tekstas: ";
$pcStrings["3.3"] = "Tamsus fonas: ";
$pcStrings["3.4"] = "Ðviesus tekstas: ";
$pcStrings["4.0"] = "Ávairûs";
$pcStrings["4.1"] = "Kabutës: ";
$pcStrings["5.0"] = "Ðriftai";
$pcStrings["5.1"] = "Ðriftø ðeima";
$pcStrings["5.2"] = "Ðrifto dydis: ";
$pcStrings["5.3"] = "Maþo ðrifto dydis: ";
$pcStrings["5.4"] = "Meniu ðrifto dydis: ";
$pcStrings["5.5"] = "Aplankø sàraðo ðrifto dydis: ";
$pcStrings["5.6"] = "Kita: ";

							
$pcPortions = array( "Fonas: ", "Nuorodos: ", "Tekstas: ", "Paðviesinti: ");

?>
