<?php
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/read_message.inc");


$rmStrings[0] = "Rodiklis";
$rmStrings[1] = "Atsakyti";
$rmStrings[2] = "Persiøsti";
$rmStrings[3] = "Sugràþinti iðtrintus";
$rmStrings[4] = "Iðtrinti";
$rmStrings[5] = "Perkelti";
$rmStrings[6] = "Dalys";
$rmStrings[7] = "Tai yra HTML laiðkas. ";
$rmStrings[8] = "Spauskite èia, jei norite skaityti.";
$rmStrings[9] = "Ðaltinis";
$rmStrings[10] = "Dydis";
$rmStrings[11] = "Neskaityta";
$rmStrings[12] = "Rodyti antraðtæ";
$rmStrings[13] = "Skelbti kaip Spam'à";
$rmStrings[14] = "Atsakyti visiems";
$rmStrings[15] = "Atsakyta";
$rmStrings[16] = "Spausdinti";
$rmStrings[17] = 'Ðis laiðkas yra koduotas kitokiu simboliø rinkiniu, nei jûsø pasirinktas.  Jeigu jums neiðeina perskaityti þemiau esanèio laiðko, <a href="%url">spauskite èia</a>';
$rmStrings[18] = 'Ðis laiðkas yra koduotas nepalaikomu simboliø rinkiniu.  Jeigu jums neiðeina perskaityti laiðko, bandykite alternatyvø simboliø rinkiná: %menu';
$rmStrings[19] = "Rodyti";
?>