<?php
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/tool.inc");

$toolStrings["folders"] = "Aplankai";
$toolStrings["inbox"] = "Gauti laiðkai";
$toolStrings["compose"] = "Raðyti";
$toolStrings["calendar"] = "Kalendorius";
$toolStrings["contacts"] = "Kontaktai";
$toolStrings["bookmarks"] = "Þymës";
$toolStrings["search"] = "Paieðka";
$toolStrings["prefs"] = "Nustatymai";
$toolStrings["logout"] = "Atsijungti";
$toolStrings["go"] = "Pirmyn";

?>