<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Signets";
$bmStrings["identities"] = "Identités";
$bmStrings["edit"] = "Mofifier";
$bmStrings["name"] = "Nom";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Catégorie";
$bmStrings["other"] = "Spécifier -&gt;";
$bmStrings["comments"] = "Commentaires";
$bmStrings["add"] = "Ajouter";
$bmStrings["new"] = "Ajouter un signet";
$bmStrings["edit_url"] = "Modifier un signet";
$bmStrings["delete"] = "Supprimer";

$bmError[1] = "Un nom d'URL est obligatoire";
$bmError[2] = "Les favoris sont désactivés.";

?>
