<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
#include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Ajouter un rendez-vous";
$calStr["edit_schedule"] = "Modifier un rendez-vous";
$calStr["weekof"] = "Semaine du: %d";
$calStr["title"] = "Titre: ";
$calStr["color"] = "Couleur: ";
$calStr["colors"] = array("#990000"=>"Rouge foncé", "#FF0000"=>"Rouge", "#000099"=>"Bleu foncé",
"#0000FF"=>"Bleu","#006600"=>"Vert foncé", "#00FF00"=>"Vert","#9900FF"=>"Mauve", 
"#00FFFF"=>"Cyan","#FF6600"=>"Orange", "#FFFF00"=>"Jaune", "#FF00FF"=>"Magenta", ""=>"Aucune 
couleur");
$calStr["starts"] = "Date de début: ";
$calStr["ends"] = "Date de fin: ";
$calStr["from"] = "Heure de début: ";
$calStr["until"] = "Jusqu'à: ";
$calStr["repeat_on"] = "Répéter chaque: ";
$calStr["of"] = "de chaque: ";
$calStr["weeks"] = array(1=>"première semaine", 2=>"deuxième semaine", 
3=>"troisième semaine", 4=>"quatrième semaine"); 
$calStr["week_blurb"] = "de chaque mois (jusqu'à la date indiquée).<br>L'événement 
sera répété toutes les semaines si rien n'est sélectionné.";
$calStr["monthly"] = "Répétition mensuelle";
$calStr["yearly"] = "Répétition annuelle";
$calStr["place"] = "Endroit: ";
$calStr["description"] = "Description: ";
$calStr["add"] = "Ajouter";
$calStr["update"] = "Mettre à jour";
$calStr["Delete"] = "Supprimer";
$calStr["go"] = "Go";
$calStr["disabled"] = "La fonction calendrier est désactivée.";
?>
