<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/fr/compose.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeHStrings[0] = "Sujet";
$composeHStrings[1] = "De";
$composeHStrings[2] = "À";
$composeHStrings[3] = "CC";
$composeHStrings[4] = "CCi";
$composeHStrings[5] = "Date";


$composeStrings[0] = "Nouveau message";
$composeStrings[1] = "Envoyer";
$composeStrings[2] = "Joindre le fichier";
$composeStrings[3] = "Joindre la signature";
$composeStrings[4] = "Joindre";
$composeStrings[5] = "Carnet d'adresses";
$composeStrings[6] = "Dissimuler les adresses";
$composeStrings[7] = "Corps du texte:";
$composeStrings[8] = "Ajouter";
$composeStrings[9] = "Le %d, %s a écrit:\n";
$composeStrings[10] = "--- Message d'origine ---\n";
$composeStrings[11] = "Fermer la fenêtre";
$composeStrings[12] = "Vérifier l'orthographe";
$composeStrings[13] = "Corriger";
$composeStrings[14] = "Pas de changement";
$composeStrings[15] = "Des erreurs ont été trouvées:";
$composeStrings[16] = "Corrections effectuées";
$composeStrings[17] = "Ignorer";
$composeStrings[18] = "Effacer";
$composeStrings["title"] = "Rédiger un message";

$composeErrors[0] = "Ce message n'a pas de sujet. Pour l'envoyer tel-quel, cliquer à nouveau sur \"Envoyer\". ";
$composeErrors[1] = "Le champ \"de\" est vide.  L'adresse de l'expéditeur est obligatoire.";
$composeErrors[2] = "Le champ \"à\" est vide.  L'adresse du destinataire est obligatoire.";
$composeErrors[3] = "Erreur du téléchargement";
$composeErrors[4] = "Aucun fichier n'a été reçu.";
$composeErrors[5] = "Afin d'éviter l'envoi de courrier non sollicité (spam), vous ne pouvez envoyer qu'à %1 des correspondants (%2 au total par session) toutes les %3 secondes.";

$composeErrors[6] = "Aucune erreur trouvée. <br>";
$composeErrors[7] = "La correction orthographique n'est pas disponible pour cette langue.";
$composeErrors[8] = "--> Dictionnaire de référence: %s ";
?>
