<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/fr/contacts.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Contacts";
$cStrings[1] = "Ajouter/modifier un contact";
$cStrings[2] = "Contact";
$cStrings[3] = "Nom";
$cStrings[4] = "Courriel";
$cStrings[5] = "URL";
$cStrings[6] = "Groupe";
$cStrings[7] = "Commentaires";
$cStrings[8] = "Valider";
$cStrings[9] = "Courriel";
$cStrings[10] = "Rédiger";
$cStrings["close"] = "Fermer la fenêtre.";
$cStrings["addto"] = "Ajouter un contact à %s";
$cStrings["showgrp"] = "Afficher %s";
$cStrings["all"] = "Tout";
$cStrings["instructions"] = "Cliquer sur le nom à ajouter. Il est également possible de cliquer sur un groupe pour ajouter tous les contacts de ce groupe.";

$cErrors[0] = "Le carnet d'adresses est vide";

?>
