<?php
include("../lang/eng/cp.inc"); // <-- do not delete
/********************************************************
lang/fr/cp.inc

(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

Ce fichier fait partie de IlohaMail est est distribué selon les termes du GPL. 
Se référer à  COPYING, où à l'adresse http://www.fsf.org/copyleft/gpl.html

********************************************************/
?>
<B> Codes des couleurs </B>
