<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
	lang/fr/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_months[1] = "janvier";
$lang_months[2] = "février";
$lang_months[3] = "mars";
$lang_months[4] = "avril";
$lang_months[5] = "mai";
$lang_months[6] = "juin";
$lang_months[7] = "juillet";
$lang_months[8] = "août";
$lang_months[9] = "septembre";
$lang_months[10] = "octobre";
$lang_months[11] = "novembre";
$lang_months[12] = "décembre";

$lang_datetime["short_mon"][1] = "jan";
$lang_datetime["short_mon"][2] = "fév";
$lang_datetime["short_mon"][3] = "mar";
$lang_datetime["short_mon"][4] = "avr";
$lang_datetime["short_mon"][5] = "mai";
$lang_datetime["short_mon"][6] = "juin";
$lang_datetime["short_mon"][7] = "juil";
$lang_datetime["short_mon"][8] = "août";
$lang_datetime["short_mon"][9] = "sept";
$lang_datetime["short_mon"][10] = "oct";
$lang_datetime["short_mon"][11] = "nov";
$lang_datetime["short_mon"][12] = "déc";

$lang_datetime["dsow"][0] = "Dim";
$lang_datetime["dsow"][1] = "Lun";
$lang_datetime["dsow"][2] = "Mar";
$lang_datetime["dsow"][3] = "Mer";
$lang_datetime["dsow"][4] = "Jeu";
$lang_datetime["dsow"][5] = "Ven";
$lang_datetime["dsow"][6] = "Sam";

$lang_datetime["dsowl"][0] = "Dimanche";
$lang_datetime["dsowl"][1] = "Lundi";
$lang_datetime["dsowl"][2] = "Mardi";
$lang_datetime["dsowl"][3] = "Mercredi";
$lang_datetime["dsowl"][4] = "Jeudi";
$lang_datetime["dsowl"][5] = "Vendredi";
$lang_datetime["dsowl"][6] = "Samedi";

$lang_datetime["dsow_short"] = array ("D", "L", "M", "M", "J", "V", "S");
$lang_datetime["today"] = "Aujourd'hui %t";  //e.g. "Aujourd'hui 12:02"
$lang_datetime["lastweek"] = "%w %t";        //e.g. "Wed 12:00"
$lang_datetime["thisyear"] = "%d/%m";        //e.g. "13/2"
$lang_datetime["prevyears"] = "%d/%m/%y";    //e.g. "15/1/2100"
$lang_datetime["monthyear"] = "%m %y";       //e.g. "Janvier 2002"
$lang_datetime["verbal"] = "%d %m %y";       //e.g. "2 janvier 1900"
$lang_datetime["verbal_short"] = "%d %m";    //e.g. "2 janvier"
$lang_datetime["hour_system"] = 24;          // 12 or 24
$lang_datetime["ampm"]["am"] = "am";
$lang_datetime["ampm"]["pm"] = "pm";
$lang_datetime["time_format"] = "%h:%m"; 
$lang_datetime["hour_format"] = "%h";           // %h=hour, %m=minutes, %a="am:pm"

?>
