<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/fr/edit_contact.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Modifier ";
$ecStrings[1] = "Ajouter ";
$ecStrings[2] = "Contact ";
$ecStrings[3] = "Nom  ";
$ecStrings[4] = "Courriel-1 ";
$ecStrings[5] = "URL";
$ecStrings[6] = "Groupe ";
$ecStrings[7] = "Commentaires ";
$ecStrings[8] = "Tél. domicile ";
$ecStrings[9] = "Tél. travail ";
$ecStrings[10] = "Tél. mobile ";
$ecStrings[11] = "Adresse ";
$ecStrings[12] = "Courriel-2 ";
$ecStrings[13] = "Supprimer ";
$ecStrings[14] = "Autre groupe ";


$errors[0] = "Le contact n'a pas été ajouté suite à une erreur dans la base de données.";
$errors[1] = "Cette adresse existe déjà dans votre carnet d'adresses.";
$errors[2] = "Cliquer ";
$errors[3] = "ici";
$errors[4] = " pour modifier cette entrée.";
$errors[5] = "Le contact est introuvable ou l'accès est refusé.";
$errors[6] = "Veuillez confirmer la suppression de  \"";
$errors[7] = "\"?";

?>
