<?php 
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="ID utilisateur";
$loginStrings[1]="Mot de passe";
$loginStrings[2]="Serveur";
$loginStrings[3]="Type";
$loginStrings[4]="Racine";
$loginStrings[5]="Langage";
$loginStrings[6]="Connexion";

$loginErrors[0]="Hôte non autorisé";
$loginErrors[1]="Erreur: le répertoire \"uploads\" n'existe pas";
$loginErrors[2]="Erreur: l'utilisateur \"users\" n'existe pas";
$loginErrors[3]="Erreur: la session \"sessions\" n'existe pas";

?>
