<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/fr/cp.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html
********************************************************/

$pcStrings["0"] = "Entrer un code de couleur HTML dans chacune des sections.";
$pcStrings["0.1"] = "Se servir du ";
$pcStrings["0.2"] = "tableau des couleurs";
$pcStrings["0.3"] = " afin de fournir les bons codes de couleurs.";
$pcStrings["0.4"] = "Les réglages prédéfinis ne peuvent être modifiés.";
$pcStrings["1.0"] = "Tableau des couleurs";
$pcStrings["2.0"] = "Liste des dossiers";
$pcStrings["3.0"] = "Autres écrans";
$pcStrings["3.1"] = "Entête arrière";
$pcStrings["3.2"] = "Entête texte";
$pcStrings["3.3"] = "Arrière plan foncé";
$pcStrings["3.4"] = "Texte léger: ";
$pcStrings["4.0"] = "Divers";
$pcStrings["4.1"] = "Citations: ";

$pcStrings["5.0"] = "Typographie";
$pcStrings["5.1"] = "Polices";
$pcStrings["5.2"] = "Taille de la police";
$pcStrings["5.3"] = "Taille des petits caractères";
$pcStrings["5.4"] = "Taille des menus";
$pcStrings["5.5"] = "Taille de la liste des dossiers";

$pcPortions = array( "Arrière plan: ", "Lien: ", "Texte: ", "Surbrillance: ");

?>
