<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "Identités";
$piStrings["edit"] = "Modifier";
$piStrings["name"] = "Nom";
$piStrings["email"] = "Courriel";
$piStrings["replyto"] = "Répondre à";
$piStrings["sig"] = "Signature";
$piStrings["add"] = "Ajouter";
$piStrings["new"] = "Nouvelle identité";
$piStrings["edit_ident"] = "Modifier l'identité";
$piStrings["delete"] = "Supprimer";
$piStrings["setdef"] = "Définir comme identité principale";
$piStrings["isdef"] = "(Identité principale)";

$piError[1] = "Le nom ou l'adresse de courriel sont obligatoires.";

?>
