<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/fr/read_message.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Index";
$rmStrings[1] = "Répondre";
$rmStrings[2] = "Transmettre";
$rmStrings[3] = "Restaurer";
$rmStrings[4] = "Supprimer";
$rmStrings[5] = "Transférer";
$rmStrings[6] = "Pièces jointes";
$rmStrings[7] = "Ceci est un message au format HTML. ";
$rmStrings[8] = "Cliquer ici pour le lire.";
$rmStrings[9] = "Source";
$rmStrings[10] = "Taille";
$rmStrings[11] = "Marquer non lu";
$rmStrings[12] = "Afficher l'entête";
$rmStrings[13] = "Signaler comme Spam";
$rmStrings[14] = "Répondre à tous";
$rmStrings[15] = "Réponse envoyée";
$rmStrings[16] = "Imprimer";

?>
