<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/fr/search_errors.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["field"] = "Critère de recherche non valide:  champ non valide";
$searchErrors["empty"] = "Critère de recherche non valide:  chaîne des critères de recherche vide";
$searchErrors["date"] = "Critère de recherche non valide:   aucune date n'a été entrée";

?>
