<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/fr/tool.inc
	(C) 1999-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["folders"] = "Dossiers";
$toolStrings["inbox"] = "Boite de réception";
$toolStrings["compose"] = "Nouveau message";
$toolStrings["calendar"] = "Calendrier";
$toolStrings["contacts"] = "Contacts";
$toolStrings["bookmarks"] = "Favoris";
$toolStrings["search"] = "Rechercher";
$toolStrings["prefs"] = "Préférences";
$toolStrings["logout"] = "Quitter";
$toolStrings["go"] = "Ouvrir";

?>
