<?php
/********************************************************
	lang/vn/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
/* SnAKes */

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Bookmarks";
$bmStrings["identities"] = "Identities";
$bmStrings["edit"] = "Sửa";
$bmStrings["name"] = "Tên";
$bmStrings["url"] = "Địa chỉ Web";
$bmStrings["category"] = "Lọai";
$bmStrings["other"] = "Tạo lọai mới -->";
$bmStrings["comments"] = "Lời chú thích";
$bmStrings["add"] = "Thêm";
$bmStrings["new"] = "Mục mới";
$bmStrings["edit_url"] = "Sửa mục";
$bmStrings["delete"] = "Xóa";

$bmError[1] = "Xin bạn ghi rõ tên họac địa chỉ Web";
$bmError[2] = "Chưa dùng được";
?>
