<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Ghi một cuộc hẹn mới";
$calStr["edit_schedule"] = "Sửa một cuộc hẹn";
$calStr["weekof"] = "Tuần: %d";
$calStr["title"] = "Chử đề:";
$calStr["color"] = "Màu:";
$calStr["colors"] = array("#990000"=>"Đỏ đậm", "#FF0000"=>"Đỏ", "#000099"=>"Xanh da trời đậm", "#0000FF"=>"Xanh da trời",
                                        "#006600"=>"Xanh lá đậm", "#00FF00"=>"Xanh lá", "#9900FF"=>"Tím", "#00FFFF"=>"Xanh biển",
                                        "#FF6600"=>"Cam", "#FFFF00"=>"Vàng", "#FF00FF"=>"Đỏ Magenta", ""=>"Không màu");
$calStr["starts"] = "Bắt đâù vào:";
$calStr["ends"] = "Kết thúc vào:";
$calStr["from"] = "từ:";
$calStr["until"] = "cho đến:";
$calStr["repeat_on"] = "Lập lại vào";
$calStr["of"] = "của những";
$calStr["weeks"] = array(1=>"tuần đầu", 2=>"tuần thứ hai", 3=>"tuần thứ ba", 4=>"tuần thư tư");
$calStr["week_blurb"] = "...mỗi tháng (cho đến ngày kết thúc).<br>Sẽ được lập lại mỗi tuần nếu không có lựa chọn.";
$calStr["monthly"] = "Mỗi tháng";
$calStr["yearly"] = "Mỗi năm";
$calStr["place"] = "Nơi:";
$calStr["description"] = "Miêu tả:";
$calStr["add"] = "Kèm thêm";
$calStr["update"] = "Lưu lại";
$calStr["Delete"] = "Xóa";
$calStr["go"] = "Chọn";
$calStr["disabled"] = "Chưa thể dùng được cuốn lịch";
?>
