<?
/********************************************************
	lang/vn/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
/*** Vietnamese support added by SnAKes (snx@ifrance.com) ***/

$composeHStrings=array(
	0=>"Chủ đề",
	1=>"Từ",
	2=>"Đến",
	3=>"CC",
	4=>"BCC",
	5=>"Ngày"
);

$composeStrings=array(
	0=>"Viết thư",
	1=>"Gửi thư",
	2=>"Gửi lên",
	3=>"Kèm chữ ký",
	4=>"Gắn tài liệu",
	5=>"Hiện thị địa chỉ",
	6=>"Giấu địa chỉ",
	7=>"Thơ tín",
	8=>"Thêm",
	9=>"On %d, %s wrote:\n",
	10=>"--- Original Message ---\n",
	11=>"Đóng hộp thọai"

);

$composeErrors=array(
	0=>"Xin hãy ghi chủ đề họac bấm lên \"".$composeStrings[1]."\" để gửi thư không chủ đề.",
	1=>"Xin hãy ghi địa chỉ người gửi.",
	2=>"Xin hãy ghi địa chỉ người nhận.",
	3=>"Không thể gửi lên",
	4=>"Không nhận được gì.",
    5=>"Bạn chỉ có thể gửi đến %1 người (tổng cộng là %2 người) cách nhau %3 dây."
);
?>
