<?
/********************************************************
	lang/vn/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
/*** Vietnamese support added by SnAKes (snx@ifrance.com) ***/

$cStrings=array(
	0=>"Sổ lưu địa chỉ",
	1=>"Thêm điạ chỉ",
	2=>"Ðiạ chỉ",
	3=>"Tên",
	4=>"Email",
	5=>"Trang WEB",
	6=>"Nhóm",
	7=>"Chú thích",
	8=>"Thêm/sưả điạ chỉ", 
	9=>"Email",
    10=>"Viết thơ"
);

$cStrings["close"]="Đóng cửa sổ";
$cStrings["addto"]="Kèm thêm địa chỉ";
$cStrings["showgrp"]="Hiện thị %s";
$cStrings["all"]="Tất cả";
$cStrings["instructions"]="Hãy click lên tên để kèm thệm Bạn có thể click lên tên nhóm để kèm tất cả nhóm";

$cErrors=array(
	0=>"Chưa có điạ chỉ trong sổ lưu" 
);

?>
