<?
/********************************************************
	lang/vn/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
/*** Vietnamese support added by SnAKes (snx@ifrance.com) ***/

$lang_months[1] = "Tháng giêng";
$lang_months[2] = "Tháng hai";
$lang_months[3] = "Tháng ba";
$lang_months[4] = "Tháng tư";
$lang_months[5] = "Tháng năm";
$lang_months[6] = "Tháng sáu";
$lang_months[7] = "Tháng bảy";
$lang_months[8] = "Tháng tám";
$lang_months[9] = "Tháng chín";
$lang_months[10] = "Tháng mười";
$lang_months[11] = "Tháng mười một";
$lang_months[12] = "Tháng mười hai";

$lang_datetime["short_mon"][1] = "Th. 01";
$lang_datetime["short_mon"][2] = "Th. 02";
$lang_datetime["short_mon"][3] = "Th. 03";
$lang_datetime["short_mon"][4] = "Th. 04";
$lang_datetime["short_mon"][5] = "Th. 05";
$lang_datetime["short_mon"][6] = "Th. 06";
$lang_datetime["short_mon"][7] = "Th. 07";
$lang_datetime["short_mon"][8] = "Th. 08";
$lang_datetime["short_mon"][9] = "Th. 09";
$lang_datetime["short_mon"][10] = "Th. 10";
$lang_datetime["short_mon"][11] = "Th. 11";
$lang_datetime["short_mon"][12] = "Th. 12";

$lang_datetime["dsow"][0] = "CN";
$lang_datetime["dsow"][1] = "Thứ 2";
$lang_datetime["dsow"][2] = "Thứ 3";
$lang_datetime["dsow"][3] = "Thứ 4";
$lang_datetime["dsow"][4] = "Thứ 5";
$lang_datetime["dsow"][5] = "Thứ 6";
$lang_datetime["dsow"][6] = "Thứ 7";

$lang_datetime["dsowl"][0] = "Chử nhật";
$lang_datetime["dsowl"][1] = "Thứ hai";
$lang_datetime["dsowl"][2] = "Thứ ba";
$lang_datetime["dsowl"][3] = "Thứ tư";
$lang_datetime["dsowl"][4] = "Thứ năm";
$lang_datetime["dsowl"][5] = "Thứ sáu";
$lang_datetime["dsowl"][6] = "Thứ bảy";

$lang_datetime["dsow_short"] = array("S", "M", "T", "W", "T", "F", "S");
$lang_datetime["today"] = "Hôm nay %t";           //e.g. "Today 12:02"
$lang_datetime["lastweek"] = "%w %t";           //e.g. "Wed 12:00"
$lang_datetime["thisyear"] = "%m/%d";           //e.g. "2/13"
$lang_datetime["prevyears"] = "%m/%d/%y";       //e.g. "1/1/2100"
$lang_datetime["monthyear"] = "%m %y";          //e.g. "January 2002"
$lang_datetime["verbal"] = "%m %d, %y";         //e.g. "Jan 1, 1900"
$lang_datetime["verbal_short"] = "%m %d";       //e.g. "Jan 1"
$lang_datetime["hour_system"] = 12;                     // 12 or 24
$lang_datetime["ampm"]["am"] = "am";
$lang_datetime["ampm"]["pm"] = "pm";
$lang_datetime["time_format"] = "%h:%m%a";      // %h=hour, %m=minutes, %a="am:pm"
$lang_datetime["hour_format"] = "%h%a";
?>
