<?
/********************************************************
	lang/vn/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
/*** Vietnamese support added by SnAKes (snx@ifrance.com) ***/

$ecStrings=array(
	0=>"Sửa",
	1=>"Thêm",
	2=>"Ðiạ chỉ",
	3=>"Tên",
	4=>"Email",
	5=>"Trang WEB",
	6=>"Nhóm",
	7=>"Chú thích",
	8=>"ÐT nhà ",
	9=>"ÐT sở",
	10=>"ÐT di động",
	11=>"Ðiạ chỉ",
	12=>"Email2",
	13=>"Xoá",
	14=>"Mới"
);

$errors=array(
	0=>"Không thể thêm địa chỉ: vấn đề \"database\"",
	1=>"Đã có địa chỉ này rồi",
	2=>"Click ",
	3=>"đây",
	4=>" để sửa phần này.",
	5=>"Không có họac không có quyền.",
	6=>"Bạn chắc chắn muốn xóa địa chỉ  \"",
	7=>"\"?"
);
?>
