<?
/********************************************************
	lang/vn/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
/*** Vietnamese support added by SnAKes (snx@ifrance.com) ***/

$efStrings=array(
	0=>"Quản lý hồ sơ",
	1=>"Tạo hồ sơ mới",
	2=>"Tạo hồ sơ",
	3=>"Tạo",
	4=>"Xóa hồ sơ",
	5=>"Xóa",
	6=>"Thay tên",
	7=>"Thay",
	8=>"Hồ sơ đã được đăng ký",
	9=>"Đăng ký",
	10=>"Hồ sơ chưa được đăng ký",
	11=>"Xóa",
);

$errors=array(
	0=>"Tạo hồ sơ: ",
	1=>"Không thể tạo hồ sơ: ",
	2=>"Hồ sơ được xóa: ",
	3=>"Không thể xóa hồ sơ: ",
	4=>"Hồ sơ được thay tên: ",
	5=>"Không thể thay tên hồ sơ: ",
	6=>"Bạn chỉ dùng được hồ sơ với tài khòan trương mục IMAP."
);
?>
    