<?
/********************************************************
	lang/vn/folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
/*** Vietnamese support added by SnAKes (snx@ifrance.com) ***/

        $fl_str["folders"] = "Hồ sơ";
        $fl_str["manage"] = "Quản lý hồ sơ";

	$sentbox=$my_prefs["sent_box_name"];
	$trashname=$my_prefs["trash_name"];
	$defaults=array(
		"INBOX" =>"Hộp thư",
		$sentbox =>"Gửi rồi",
		$trashname =>"Hộp rác",
	);
	$fstr["reload"]="kiểm tra lại";
	$fstr["expunge"]="xóa";
?>
