<?
include("../lang/eng/main.inc");
/********************************************************
	lang/vn/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
/*** Vietnamese support added by SnAKes (snx@ifrance.com) ***/

$mainMessages["delete"] = "Xóa đi %n bức thư";
$mainMessages["move"] = "Chuyển đi %n bức thư qua %f";

$mainStrings=array(
	0=>"%p thư đang hiện ra trong tổng số %n thư",
	1=>" được tìm ra",
	2=>"<-- ",
	3=>" thư sau",
	4=>"",
	5=>" thư trước -->",
	6=>"Chủ đề",
	7=>"Gửi đến",
	8=>"Từ",
	9=>"Ngày",
	10=>"Xóa",
	11=>"Xóa hộp rác",
	12=>"Chuyển",
	13=>"Truy cập",
	14=>"Kích thước",
	15=>"không tên",
	16=>"Hiện thị",
	17=>"Sóat lại hộp thư",
	18=>"Xóa hết",
	19=>"Bỏ",
	20=>"Đánh dấu %b",
	21=>"Đọc rồi",
	22=>"Chưa đọc",
	23=>"Chọn"
);

$mainErrors=array(
	0=>"Không có thư trong hồ sơ này",
	1=>"Không có thư trong hồ sơ này",
	2=>"Không thể chuyển qua hộp rác.",
	3=>"Không thể chọn thư này để xóa đi.",
	4=>"Không thể chuyển những thư này.",
    	5=>"Bạn chưa có chọn hồ sơ để làm hộp rác.",
	6=>"Không thể đổ rác",
	7=>"Bạn có chắc chắn xóa tất cả bức thư trong %f?",
	8=>"Bạn hãy bấm lên cái mũi tên ở dưới cột để thay đổi chỗ<br>Khi xong thì đóng lại cửa sô."
);


?>
