<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "Identities";
$piStrings["edit"] = "Sửa";
$piStrings["name"] = "Tên";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "Reply-To";
$piStrings["sig"] = "Chữ ký";
$piStrings["add"] = "OK";
$piStrings["new"] = "New Identity";
$piStrings["edit_ident"] = "Edit Identity";
$piStrings["delete"] = "Xóa";

$piError[1] = "Xin bạn ghi rõ tên họac địa chỉ email";

?>
