<?php
/********************************************************
	lang/eng/quota.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$quotaStr["label"] = "Kích thước hộp thư: ";
$quotaStr["full"] = "%usedKB/%totalKB (%free% trống)";
$quotaStr["unknown"] = "không biết";

?>
