<?
/********************************************************
	lang/vn/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
/*** Vietnamese support added by SnAKes (snx@ifrance.com) ***/

$rmStrings=array(
        0=>"Trở lại",
        1=>"Trả lời",
        2=>"Chuyển tới",
        3=>"Lấy lại",
        4=>"Xóa",
        5=>"Chuyển",
        6=>"Parts",
        7=>"Đây là thơ bằng HTML. ",
        8=>"Bấm lên đây để đọc.",
        9=>"Thu vào đĩa",
        10=>"Kích thước",
        11=>"Đánh dấu đọc rồi",
        12=>"Hiện thị đề đầu thơ",
        13=>"Báo Spam",
        14=>"Trả lời tất cả",
	15=>"Bạn đã trả lời thư này",
        16=>"In"
);
?>
