<?
/********************************************************
	lang/vn/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
/*** Vietnamese support added by SnAKes (snx@ifrance.com) ***/

$searchErrors=array(
	"field"=>"Invalid search criteria:  Invalid field",
	"empty"=>"Invalid search criteria:  Empty search string",
	"date"=>"Invalid search criteria:  Date not specified"
);
?>
