<?
/********************************************************
	lang/vn/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
/*** Vietnamese support added by SnAKes (snx@ifrance.com) ***/

$toolStrings=array(
	"folders"=>"Hồ sơ",
	"inbox"=>"Hộp thư",
	"compose"=>"Viết thư",
	"contacts"=>"Địa chỉ",
	"search"=>"Truy cập",
	"bookmarks"=>"Bookmarks",
	"prefs"=>"Lựa chọn",
	"logout"=>"Kết thúc",
	"calendar"=>"Lịch",
	"go"=>"Tiếp"
);
?>
