.\" 
.TH "conf.pl" "8" "Jan 14, 2006" "Tomas Kuliavas" "SquirrelMail"
.SH "NAME"
conf.pl \- SquirrelMail configuration utility

.SH "SYNOPSIS"
.B conf.pl
.RI [\-\-install\-plugin\ plugin\-name\ |\ \-\-remove\-plugin\ plugin\-name]
.br 

.SH "DESCRIPTION"
This manual page explains usage of the
.B conf.pl
program.
.PP 
It is normally called without any arguments, and then provides an interactive
menu to configure SquirrelMail.

.SH "OPTIONS"
.B 
.IP \-\-install\-plugin\ plugin\-name
Enable a plugin. Activates the plugin and saves SquirrelMail configuration.

.B 
.IP \-\-remove\-plugin\ plugin\-name
Disable a plugin. Deactivates the plugin and saves SquirrelMail configuration.
.SH "BUGS"
If you find bugs in SquirrelMail configuration utility or this manual, you can 
report them in SquirrelMail bug tracker. See \fBhttp://squirrelmail.org/bugs\fR
.SH "AUTHOR"
Tomas Kuliavas <tokul@users.sourceforge.net>
.SH "COPYRIGHT"
Copyright (c) 2006-2011 The SquirrelMail Project Team
.SH "LICENSE"
This manual is licensed under GNU General Public License. See COPYING file
included in the SquirrelMail package or
\fBhttp://opensource.org/licenses/gpl\-license.php\fR.
