<?php
/////////////////////////////
//	ISO-8859-7.inc
//	(C)2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
//		
//		Description:
//				Encoding library for the ISO-8859-2 charset.
//				Simply includes the ISO-8859-1 charset library,
//				since all functionality are the same.
//
//	This file is part of IlohaMail. IlohaMail is free software released 
//	under the GPL license.  See enclosed file COPYING for details, or 
//	see http://www.fsf.org/copyleft/gpl.html
////////////////////////////

include_once("../lang/ISO-8859-1.inc");

?>
