<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmError[1] = "Necess&aacute;rio informar Nome ou URL";
$bmError[2] = "Este recurso est&aacute; desabilitado.";
$bmStrings["add"] = "Novo";
$bmStrings["bookmarks"] = "Marcadores";
$bmStrings["category"] = "Categoria";
$bmStrings["comments"] = "Coment&aacute;rios";
$bmStrings["delete"] = "Excluir";
$bmStrings["edit"] = "Editar";
$bmStrings["edit_url"] = "Editar Registro";
$bmStrings["identities"] = "Identidades";
$bmStrings["name"] = "Nome";
$bmStrings["new"] = "Novo Registro";
$bmStrings["other"] = "Especificar-&gt;";
$bmStrings["url"] = "URL";

?>
