<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["colors"] = array("#990000"=>"Vermelho Escuro", "#FF0000"=>"Vermelho", "#000099"=>"Azul
Escuro", "#0000FF"=>"Azul","#006600"=>"Verde Escuro", "#00FF00"=>"Verde", "#9900FF"=>"Violeta", "#00FFFF"=>"Ciano", "#FF6600"=>"Laranja", "#FFFF00"=>"Amarelo", "#FF00FF"=>"Magenta", ""=>"Sem cor");
$calStr["add"] = "Novo";
$calStr["add_schedule"] = "Novo Compromisso";
$calStr["color"] = "Cor:";
	$calStr["Delete"] = "Excluir";
$calStr["description"] = "Descri&ccedil;&atilde;o:";
$calStr["disabled"] = "O recurso de Calend&aacute;rio est&aacute; desabilitado.";
$calStr["edit_schedule"] = "Editar Compromisso";
$calStr["ends"] = "Termina em:";
$calStr["from"] = "de:";
$calStr["go"] = "Ir";
$calStr["monthly"] = "Repete mensalmente";
$calStr["of"] = "a cada";
$calStr["place"] = "Local:";
$calStr["repeat_on"] = "Repetindo";
$calStr["starts"] = "Inicia em:";
$calStr["title"] = "T&iacute;tulo:";
$calStr["until"] = "at&eacute;:";
$calStr["update"] = "Atualizar";
$calStr["week_blurb"] = "...de cada m&ecirc;s (at&eacute; a data final).<br>Repetir&aacute; em todas as semanas se nenhuma for selecionada.";
$calStr["weekof"] = "Semana de: %d";
$calStr["weeks"] = array(1=>"primeira semana", 2=>"segunda semana", 3=>"terceira semana", 4=>"quarta semana"); 
$calStr["yearly"] = "Repete anualmente";
?>
