<?php
include("../lang/eng/compose.inc"); // <-- do not delete
/********************************************************
	lang/eng/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$composeErrors[0] = "O campo de assunto est&aacute; vazio. Por favor, entre com um assunto ou clique \"".$composeStrings[1]."\" novamente para enviar.";
$composeErrors[1] = "O campo \"De\" est&aacute; vazio. Por favor, entre com o seu endere&ccedil;o de e-mail.";
$composeErrors[2] = "O campo \"Para\" est&aacute; vazio.  Por favor, especifique o endere&ccedil;o de e-mail do destinat&aacute;rio.";
$composeErrors[3] = "Carga do anexo falhou";
$composeErrors[4] = "Nenhum arquivo foi recebido.";
$composeErrors[5] = "Afim de prevenir a pr&aacute;tica de SPAM, voc&ecirc; deve enviar e-mail para apenas %1 pessoas (%2 no total, por se&ccedil;&atilde;o) a cada %3 segundos.";
$composeErrors[6] = "Nenhum erro de grafia encontrado.";
$composeErrors[7] = "Corretor Gramatical n&atilde;o est&aacute;o dispon&iacute;vel para o idioma especficado.";
$composeErrors[8] = "(dicin&aacute;rio utilizado: %s)";
$composeHStrings[0] = "Assunto";
$composeHStrings[1] = "De";
$composeHStrings[2] = "Para";
$composeHStrings[3] = "CC";
$composeHStrings[4] = "BCC";
$composeHStrings[5] = "Data";
$composeStrings[0] = "Nova Mensagem";
$composeStrings[10] = "--- Mensagem Original ---\n";
$composeStrings[11] = "Fechar Janela";
$composeStrings[12] = "Verificar Grafia";
$composeStrings[13] = "Corrigir Grafia";
$composeStrings[14] = "Sem altera&ccedil;&otilde;es";
$composeStrings[15] = "Poss&iacute;veis Erros de Grafia";
$composeStrings[16] = "Altera&ccedil;&otilde;es de Grafia";
$composeStrings[17] = "ignorar";
$composeStrings[18] = "excluir";
$composeStrings[1] = "Enviar Mensagem";
$composeStrings[2] = "Anexar";
$composeStrings[3] = "Inserir assinatura";
$composeStrings[4] = "Anexar";
$composeStrings[5] = "Mostrar contatos";
$composeStrings[6] = "Esconder contatos";
$composeStrings[7] = "Corpo da mensagem:";
$composeStrings[8] = "Adicionar";
$composeStrings[9] = "Em %d, %s escreveu:\n";
$composeStrings["title"] = "Escrever Mensagem";
?>
