<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cErrors[0] = "A lista de contatos est&aacute; vazia";
$cStrings[0] = "Contatos";
$cStrings[10] = "Escrever";
$cStrings[1] = "Adicionar Contato";
$cStrings[2] = " Contato";
$cStrings[3] = "Nome";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Grupo";
$cStrings[7] = "Coment&aacute;rios";
$cStrings[8] = "Adicionar/Editar Contato";
$cStrings[9] = "Email";
?>
