<?php
include("../lang/eng/dates.inc"); // <-- do not delete
/********************************************************
	lang/eng/dates.inc
	(C) 2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$lang_datetime["ampm"]["am"] = "am";
$lang_datetime["ampm"]["pm"] = "pm";
$lang_datetime["dsow"][0] = "Dom";
$lang_datetime["dsow"][1] = "Seg";
$lang_datetime["dsow"][2] = "Ter";
$lang_datetime["dsow"][3] = "Qua";
$lang_datetime["dsow"][4] = "Qui";
$lang_datetime["dsow"][5] = "Sex";
$lang_datetime["dsow"][6] = "Sab";
$lang_datetime["dsowl"][0] = "Domingo";
$lang_datetime["dsowl"][1] = "Segunda-feira";
$lang_datetime["dsowl"][2] = "Ter&ccedil;a-feira";
$lang_datetime["dsowl"][3] = "Quarta-feira";
$lang_datetime["dsowl"][4] = "Quinta-feira";
$lang_datetime["dsowl"][5] = "Sexta-Feira";
$lang_datetime["dsowl"][6] = "S&aacute;bado";
$lang_datetime["dsow_short"] = array("D", "S", "T", "Q", "Q", "S", "S");
$lang_datetime["hour_format"] = "%h%a";
$lang_datetime["hour_system"] = 24;			// 12 or 24
$lang_datetime["lastweek"] = "%w %t";		//e.g. "Wed 12:00"
$lang_datetime["monthyear"] = "%m, %y";		//e.g. "January 2002"
$lang_datetime["prevyears"] = "%d/%m/%y";
$lang_datetime["short_mon"][10] = "Out";
$lang_datetime["short_mon"][11] = "Nov";
$lang_datetime["short_mon"][12] = "Dez";
$lang_datetime["short_mon"][1] = "Jan";
$lang_datetime["short_mon"][2] = "Fev";
$lang_datetime["short_mon"][3] = "Mar";
$lang_datetime["short_mon"][4] = "Abr";
$lang_datetime["short_mon"][5] = "Mai";
$lang_datetime["short_mon"][6] = "Jun";
$lang_datetime["short_mon"][7] = "Jul";
$lang_datetime["short_mon"][8] = "Ago";
$lang_datetime["short_mon"][9] = "Set";
$lang_datetime["thisyear"] = "%d/%m";
$lang_datetime["time_format"] = "%h:%m%a";	// %h=hour, %m=minutes, %a="am:pm"
$lang_datetime["today"] = "Hoje %t";
$lang_datetime["verbal"] = "%d de %m de %y";  	//e.g. "Jan 1, 1900"
$lang_datetime["verbal_short"] = "%d %m";  	//e.g. "Jan 1"
$lang_months[10] = "Outubro";
$lang_months[11] = "Novembro";
$lang_months[12] = "Dezembro";
$lang_months[1] = "Janeiro";
$lang_months[2] = "Fevereiro";
$lang_months[3] = "Mar&ccedil;o";
$lang_months[4] = "Abril";
$lang_months[5] = "Maio";
$lang_months[6] = "Junho";
$lang_months[7] = "Julho";
$lang_months[8] = "Agosto";
$lang_months[9] = "Setembro";
?>
