<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Editar";
$ecStrings[10] = "Telefone celular";
$ecStrings[11] = "Endere&ccedil;o";
$ecStrings[12] = "Email alternativo";
$ecStrings[13] = "Excluir";
$ecStrings[14] = "Outros";
$ecStrings[1] = "Adicionar";
$ecStrings[2] = " Contato";
$ecStrings[3] = "Nome";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Grupo";
$ecStrings[7] = "Coment&aacute;rios";
$ecStrings[8] = "Telefone casa";
$ecStrings[9] = "Telefone trabalho";
$errors[0] = "Imposs&iacute;vel adicionar contato:  erro no banco de dados.";
$errors[1] = "Um registro com este endere&ccedil;o j&aacute; existe.";
$errors[2] = "Clique ";
$errors[3] = "aqui";
$errors[4] = " para editar esse registro.";
$errors[5] = "Contato n&atilde;o encontrado ou acesso negado.";
$errors[6] = "Tem certeza de que deseja excluir o registro de \"";
$errors[7] = "\"?";
?>
