<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/eng/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
$efStrings[0] = "Gerenciar Pastas";
$efStrings[10] = "Pastas N&atilde;o Inscritas";
$efStrings[11] = "Canc. Inscri&ccedil;&atilde;o";
$efStrings[1] = "Criar nova pasta";
$efStrings[2] = "Criar pasta: ";
$efStrings[3] = "Criar";
$efStrings[4] = "Excluir pasta";
$efStrings[5] = "Excluir";
$efStrings[6] = "Renomear pasta";
$efStrings[7] = "Renomear";
$efStrings[8] = "Pastas Inscritas";
$efStrings[9] = "Inscrever";
$errors[0] = "Criar pasta: ";
$errors[1] = "Imposs&iacute;vel criar pasta: ";
$errors[2] = "Pasta exclu&iacure;da: ";
$errors[3] = "Imposs&iacure;vel excluir pasta: ";
$errors[4] = "Pasta renomeada: ";
$errors[5] = "Imposs&iacute;vel renomear pasta: ";
$errors[6] = "Suporte a pasta est&aacute; dispon&iacute;vel apenas para contas do tipo IMAP.";
?>
