<?php 
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginErrors[0]="Servidor n&atilde;o autorizado";
$loginErrors[1]="Erro: diret&oacute;rio \"uploads\" n&atilde; encontrado";
$loginErrors[2]="Erro: diret&oacute;rio \"users\"  n&atilde; encontrado";
$loginErrors[3]="Erro: diret&oacute;rio \"sessions\"  n&atilde; encontrado";
$loginStrings[0]="Usuário";
$loginStrings[1]="Senha";
$loginStrings[2]="Servidor";
$loginStrings[3]="Tipo";
$loginStrings[4]="Pasta Raiz";
$loginStrings[5]="Idioma";
$loginStrings[6]="Entrar";
?>
