<?php
include("../lang/eng/main.inc"); // <-- do not delete
/********************************************************
	lang/eng/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$mainErrors[0] = "Nenhuma mensagem encontrada nessa pasta";
$mainErrors[1] = "Nenhuma mensagem nessa pasta";
$mainErrors[2] = "Imposs&iacute;vel mover mensagens para a pasta Exclu&iacute;das.";
$mainErrors[3] = "Imposs&iacute;vel marcar mensagens como exclu&iacute;das.";
$mainErrors[4] = "Imposs&iacute;vel mover mensagens.";
$mainErrors[5] = "Pasta Exclu&iacute;das n&atilde;o especificada.";
$mainErrors[6] = "Imposs&iacute;vel esvaziar Exclu&iacute;das";
$mainErrors[7] = "Tem certeza de que quer excluir TODAS as mensagens em %f?";
$mainErrors[8] = "Clique nas setas abaixo dos cabe&ccedil;alhos das colunas para mov&ecirc;-las.<br>Quando terminar, simplesmente feche a janela.";
$mainMessages["delete"] = "%n messagem(ns) exclu&iacute;das";
$mainMessages["move"] = "%n message(ns) movidas para %f";
$mainStrings[0] = "Mostrando %p de %n";
$mainStrings[10] = "Excluir";
$mainStrings[11] = "Esvaziar Exclu&iacute;das";
$mainStrings[12] = "Mover";
$mainStrings[13] = "Procurar";
$mainStrings[14] = "Tamanho";
$mainStrings[15] = "sem t&iacute;tulo";
$mainStrings[16] = "Mostrar";
$mainStrings[17] = "Checar correio";
$mainStrings[18] = "Apagar todas";
$mainStrings[19] = "Cancelar";
$mainStrings[1] = " mensagens encontradas";
$mainStrings[20] = "Marcar como %b";
$mainStrings[21] = "Lida";
$mainStrings[22] = "N&atilde;o Lida";
$mainStrings[2] = "Anterior";
$mainStrings[3] = " mens.";
$mainStrings[4] = "Pr&oacute;xima";
$mainStrings[5] = " mens.";
$mainStrings[6] = "Assunto";
$mainStrings[7] = "Para";
$mainStrings[8] = "De";
$mainStrings[9] = "Data";
?>
