<?php
include("../lang/eng/prefs.inc"); // <-- do not delete
/********************************************************
	lang/eng/prefs.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$prefHeaderStrings[0] = "Op&ccedil;&otilde;es";
$prefHeaderStrings[1] = "Geral";
$prefHeaderStrings[2] = "Apar&ecirc;ncia";
$prefHeaderStrings[3] = "Identidades";
$prefsButtonStrings = array( 0=> "Atualizar", 1=>"Aplicar", 2=> "Cancelar", 3=> "Padr&otilde;es");
$prefs_new_user = "Parece que voc&ecirc; est&acute; se conectando pela primeira vez, seja bem-vindo!<br>";
$prefs_new_user .= "Por favor, preencha as configura&ccedil;&otilde;es a seguir e ent&atilde;o pressione \"Aplicar\"";
$prefsStrings["0.0"] = "Identifica&ccedil;&atilde;o";
$prefsStrings["0.1"] = "Nome: ";
$prefsStrings["0.2"] = "Email: ";
$prefsStrings["1.0"] = "Internacional";
$prefsStrings["1.1"] = "Interface: ";
$prefsStrings["1.2"] = "Conjunto de caracteres: ";
$prefsStrings["1.3"] = "Fuso Hor&aacute;rio: ";
$prefsStrings["1.4"] = "Formato do Rel&oacute;gio: ";
$prefsStrings["1.5"] = array(12=>"12 horas", 24=>"24 horas");
$prefsStrings["2.0"] = "Op&ccedil;&otilde;es de visualiza&ccedil;&atilde;o";
$prefsStrings["2.10"] = "Verificar novas mensagens a cada %n segundos";
$prefsStrings["2.11"] = "Exibar Barra de Ferramentas %m";
$prefsStrings["2.12"] = array("b"=>"abaixo", "t"=>"acima", "bt"=>"abaixo e acima");
$prefsStrings["2.13"] = "Rorganizar colunas: ";
$prefsStrings["2.14"] = "clique aqui";
$prefsStrings["2.1"] = "Mostrar at&eacute; ";
$prefsStrings["2.2"] = " itens";
$prefsStrings["2.3"] = "Mostrar tamanho";
$prefsStrings["2.4"] = "Ordernar por: ";
$prefsStrings["2.5"] = "";
$prefsStrings["2.6"] = "Ordena&ccedil;&atilde;o: ";
$prefsStrings["2.7"] = "";
$prefsStrings["2.8"] = "Mostrar listagem de pastas";
$prefsStrings["2.9"] = "Folder list width";
$prefsStrings["2.9"] = "Largura da listagem de pastas";
$prefsStrings["3.0"] = "Op&ccedil;&otilde;es de Auto-Salvamento";
$prefsStrings["3.10"] = "Exibir cota %m";
$prefsStrings["3.11"] = array(""=>"n&atilde;o exibir", "m"=>"na Listagem de Mensagens", "f"=>"Na Listagem de Pastas");
$prefsStrings["3.1"] = "Salvar itens enviados.";
$prefsStrings["3.2"] = "Salvar itens enviados na pasta: ";
$prefsStrings["3.3"] = "";
$prefsStrings["3.4"] = "Limpar Exclu&iacute;das automaticamente";
$prefsStrings["3.5"] = "Mover itens exclu&iacute;dos para a pasta: ";
$prefsStrings["3.6"] = "";
$prefsStrings["3.7"] = "Diret&oacute;rio Raiz: ";
$prefsStrings["3.8"] = "Outros";
$prefsStrings["3.9"] = "Esconder Pastas que n&atilde;o inscritas";
$prefsStrings["4.0"] = "Op&ccedil;&otilde;es de Visualiza&ccedil;&atilde;o de Mensagens";
$prefsStrings["4.1"] = "Visualizar em frames";
$prefsStrings["4.2"] = "Marcas coloridas";
$prefsStrings["4.3"] = "Esta op&ccedil;&atilde;o pode deixar o sistema lento.";
$prefsStrings["4.4"] = "Converter URLs em links";
$prefsStrings["4.5"] = "Mostrar mensagens HTML";
$prefsStrings["4.6"] = "Mostrar imagens";
$prefsStrings["4.7"] = "Exibir Links de Navega&ccedil;&atilde;o";
$prefsStrings["4.8"] = "N&atilde;o marcar mensagens quando navegando";
$prefsStrings["5.0"] = "Assinatura";
$prefsStrings["5.1"] = "Mostrar assinatura por padr&atilde;o";
$prefsStrings["5.2"] = "";
$prefsStrings["6.0"] = "Compor";
$prefsStrings["6.1"] = "Exibir Contatos";
$prefsStrings["6.2"] = "Exibir Campos CC/BCC";
$prefsStrings["6.3"] = "Fechar ap&oacute;s envio";
$prefsStrings["6.4"] = "Compor dentro da janela";
$prefsStrings["7.0.0"] = "Op&ccedil;&otilde;es de Disco &amp; Pastas";
$prefsStrings["7.0.1"] = "Op&ccedil;&otilde;es de Cota";
$prefsStrings["7.1"] = "Exibir num. de n&atilde;o lidas";
$prefsStrings["7.2"] = "Atualizar listagem de pastas a cada %n segundos";
$sort_fields=array("DATE"=>"Data", "SUBJECT"=>"Assunto", "SIZE"=>"Tam");
$sort_orders=array("ASC"=>"Ascendente", "DESC"=>"Descendente");
?>
