<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piError[1] = "Necess&aacute;rio informar Nome ou email";
$piStrings["add"] = "Novo";
$piStrings["delete"] = "Excluir";
$piStrings["edit"] = "Editar";
$piStrings["edit_ident"] = "Editar Identidade";
$piStrings["email"] = "Email";
$piStrings["identities"] = "Identidades";
$piStrings["name"] = "Nome";
$piStrings["new"] = "Nova Identidade";
$piStrings["replyto"] = "Responder-Para";
$piStrings["sig"] = "Assinatura";
?>
