<?php
/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/
include("../lang/eng/pref_colors.inc"); // <-- do not delete

$pcStrings["0"] = "Informe um C&oacute;digo HTML de cor para cada componente.";
$pcStrings["0.1"] = "Use a ";
$pcStrings["0.2"] = "Tabela de C&oacute;digos de Cores";
$pcStrings["0.3"] = " para encontrar o c&oacute;digo correto da cor.";
$pcStrings["0.4"] = "Configura&ccedil;&otilde;es contidas no tema n&atilde;o podem ser alteradas.";
$pcStrings["1.0"] = "Barra de Ferramentas";
$pcStrings["2.0"] = "Listagem de Pastas";
$pcStrings["3.0"] = "Principal";
$pcStrings["3.1"] = "Fundo do Cabe&ccedil;alho: ";
$pcStrings["3.2"] = "Texto do Cabe&ccedil;alho: ";
$pcStrings["3.3"] = "Fundo Escuro: ";
$pcStrings["3.4"] = "Texto destacado: ";
$pcStrings["4.0"] = "Diversos";
$pcStrings["4.1"] = "Cita&ccedil;&otilde;es: ";
$pcStrings["5.0"] = "Caracteres";
$pcStrings["5.1"] = "Fam&iacute;lia de Caracteres";
$pcStrings["5.2"] = "Tamanho dos Caracteres: ";
$pcStrings["5.3"] = "Tamanho do caractere pequeno: ";
$pcStrings["5.4"] = "Tamanho do caractere do Menu: ";
$pcStrings["5.5"] = "Tamanho do caractere da Listagem de Pastas: ";
$pcPortions = array( "Fundo: ", "Links: ", "Texto: ", "Destaque: ");

?>
