<?php
include("../lang/eng/read_message.inc"); // <-- do not delete
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$rmStrings[0] = "Voltar";
$rmStrings[1] = "Responder";
$rmStrings[2] = "Encaminhar";
$rmStrings[3] = "Reverter exclus&atilde;o";
$rmStrings[4] = "Excluir";
$rmStrings[5] = "Arquivo";
$rmStrings[6] = "Partes";
$rmStrings[7] = "Esta &eacute; uma mensagem HTML. ";
$rmStrings[8] = "Clique aqui para ler.";
$rmStrings[9] = "C&oacute;digo fonte";
$rmStrings[10] = "Tamanho";
$rmStrings[11] = "Marcar como n&atilde;o lida";
$rmStrings[12] = "Mostrar cabe&ccedil;alho";
$rmStrings[13] = "Relatar Spam";
$rmStrings[14] = "Responder a todos";
$rmStrings[15] = "Esta mensagem foi respondida";
$rmStrings[16] = "Imprimir";
?>
