<?php
include("../lang/eng/search_errors.inc"); // <-- do not delete
/********************************************************
	lang/eng/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$searchErrors["date"] = "Crit&eacute;rio de pesquisa inv&aacute;lido:  Data n&atilde;o especificada";
$searchErrors["empty"] = "Crit&eacute;rio de pesquisa inv&aacute;lido: cadeia de pesquisa vazia";
$searchErrors["field"] = "Crit&eacute;rio de pesquisa inv&aacute;lido:  Campo inv&aacute;lido";
?>
