<?php
include("../lang/eng/tool.inc"); // <-- do not delete
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$toolStrings["bookmarks"] = "Marcadores";
$toolStrings["calendar"] = "Calend&aacute;rio";
$toolStrings["compose"] = "Nova mensagem";
$toolStrings["contacts"] = "Contatos";
$toolStrings["folders"] = "Pastas";
$toolStrings["go"] = "Ir";
$toolStrings["inbox"] = "Entrada";
$toolStrings["logout"] ="Sair";
$toolStrings["prefs"] = "Op&ccedil;&otilde;es";
$toolStrings["search"] = "Pesquisar";
?>
