<?php
/********************************************************
	lang/tr/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Favoriler";
$bmStrings["identities"] = "Kimlikler";
$bmStrings["edit"] = "Düzenle";
$bmStrings["name"] = "Ad";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Kategori";
$bmStrings["other"] = "Tanimla-&gt;";
$bmStrings["comments"] = "Yorumlar";
$bmStrings["add"] = "Ekle";
$bmStrings["new"] = "Yeni Kayit";
$bmStrings["edit_url"] = "Kayidi Düzenle";
$bmStrings["delete"] = "Sil";

$bmError[1] = "Isim veya URL gerekmektedir.";
$bmError[2] = "Bu özellik devre disi birakilmistir.";
?>
