<?php
/********************************************************
	lang/tr/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Not Ekle";
$calStr["edit_schedule"] = "Notu düzenle";
$calStr["weekof"] = "Haftasi: %d";
$calStr["title"] = "Baslik:";
$calStr["color"] = "Renk:";
$calStr["colors"] = array("#990000"=>"Koyu Kirmizi", "#FF0000"=>"Kirmizi", "#000099"=>"Derin Mavi", "#0000FF"=>"Mavi", 
					"#006600"=>"Koyu Yesil", "#00FF00"=>"Yesil", "#9900FF"=>"Mor", "#00FFFF"=>"Camgöbegi",
					"#FF6600"=>"Turuncu", "#FFFF00"=>"Sari", "#FF00FF"=>"Koyu Pembe", ""=>"Renksiz");
$calStr["starts"] = "Baslama:";
$calStr["ends"] = "Bitis:";
$calStr["from"] = "Kimden:";
$calStr["until"] = "Tarihine Kadar:";
$calStr["repeat_on"] = "Tekrarla";
$calStr["of"] = "Her ";
$calStr["weeks"] = array(1=>"ilk hafta", 2=>"ikinci hafta", 3=>"ucuncu hafta", 4=>"dorduncu hafta"); 
$calStr["week_blurb"] = "(Bitis tarihine kadar her ayin...).<br>Hicbiri seçilmezse her hafta tekrarlanir.";
$calStr["monthly"] = "Aylik tekrar et";
$calStr["yearly"] = "Yillik tekrar et";
$calStr["place"] = "Yer:";
$calStr["description"] = "Tanimlama:";
$calStr["add"] = "Ekle";
$calStr["update"] = "Güncelle";
$calStr["Delete"] = "Sil";
$calStr["go"] = "Git";
$calStr["disabled"] = "Takvim özelligi devre disi birakilmistir.";
?>
