<?php
/********************************************************
	lang/tr/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/contacts.inc");

$cStrings[0] = "Adres Defteri";
$cStrings[1] = "Kisi Ekle";
$cStrings[2] = " Kisi";
$cStrings[3] = "Ad";
$cStrings[4] = "E-posta";
$cStrings[5] = "URL";
$cStrings[6] = "Grup";
$cStrings[7] = "Yorumlar";
$cStrings[8] = "Ekle/Düzenle";
$cStrings[9] = "E-posta";
$cStrings[10] = "Yeni";

$cStrings["close"] = "Pencereyi Kapat";
$cStrings["addto"] = "%s grubuna ekle";
$cStrings["showgrp"] = "%s i göster.";
$cStrings["all"] = "Hepsi";
$cStrings["instructions"] = "Eklemek için isimlerin üstüne tiklayin. Bir gruptaki herkesi eklemek için grup adinin ustune tiklayabilirsiniz.";

$cErrors[0] = "Adres defteri bos";


?>
