<?php
/********************************************************
	lang/tr/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/edit_folders.inc");

$efStrings[0] = "Klas&#246;rleri D&#252;zenle";
$efStrings[1] = "Yeni klas&#246;r olustur";
$efStrings[2] = "Klas&#246;r olustur: ";
$efStrings[3] = "Olustur";
$efStrings[4] = "Klas&#246;r&#252; sil";
$efStrings[5] = "Sil";
$efStrings[6] = "Klas&#246;r&#252; yeniden adlandir";
$efStrings[7] = "Yeniden adlandir";
$efStrings[8] = "Kayitli Klas&#246;rler";
$efStrings[9] = "Kaydet";
$efStrings[10] = "Kayitsiz Klas&#246;rler";
$efStrings[11] = "Kayidi Sil";


$errors[0] = "Klas&#246;r&#252; Olustur: ";
$errors[1] = "Klas&#246;r olusturulamadi: ";
$errors[2] = "Silinen klas&#246;r: ";
$errors[3] = "Klas&#246;r silinemedi: ";
$errors[4] = "Yeniden adlandirilan klas&#246;r: ";
$errors[5] = "Klas&#246;r yeniden adlandirilamadi: ";
$errors[6] = "Klas&#246;r destegi sadece IMAP hesaplari i&#231;in mevcuttur.";

?>