<?php
/********************************************************
	lang/tr/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Düzenle";
$ecStrings[1] = "Ekle";
$ecStrings[2] = " Kisi";
$ecStrings[3] = "Ad";
$ecStrings[4] = "E-posta";
$ecStrings[5] = "URL";
$ecStrings[6] = "Grup";
$ecStrings[7] = "Yorumlar";
$ecStrings[8] = "Ev Tel.";
$ecStrings[9] = "Is tel.";
$ecStrings[10] = "Cep tel.";
$ecStrings[11] = "Adres";
$ecStrings[12] = "Alt. E-posta";
$ecStrings[13] = "Sil";
$ecStrings[14] = "Diger";


$errors[0] = "Kontak eklenemedi: veritabani hatasi.";
$errors[1] = "Bu adrese sahip bir kayit mevcut.";
$errors[2] = "Tiklayin ";
$errors[3] = "buraya";
$errors[4] = " bu kaydi düzenlemek icin.";
$errors[5] = "Kontak bulunamadi veya erisim izni yok.";
$errors[6] = "Bu kayidi silmek istediginize emin misiniz? \"";
$errors[7] = "\"?";

?>
