<?php 
/********************************************************
	lang/tr/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Kullanici adi";
$loginStrings[1]="Sifre";
$loginStrings[2]="Sunucu";
$loginStrings[3]="Tip";
$loginStrings[4]="Ana dizin";
$loginStrings[5]="Dil";
$loginStrings[6]="Giris";

$loginErrors[0]="Yetkisiz host";
$loginErrors[1]="Hata: \"uploads\" dizini bulunamadi";
$loginErrors[2]="Hata: \"users\" dizini bulunamadi";
$loginErrors[3]="Hata: \"sessions\" dizini bulunamadi";

?>
