<?php
/********************************************************
	lang/tr/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainMessages["delete"] = "%n mesaji sil";
$mainMessages["move"] = "%n mesaj %f klasörüne tasindi";

$mainStrings[0] = "%n mesajdan %p tanesi gösteriliyor";
$mainStrings[1] = " mesaj bulundu";
$mainStrings[2] = "Önceki";
$mainStrings[3] = "";
$mainStrings[4] = "Sonraki";
$mainStrings[5] = "";
$mainStrings[6] = "Konu";
$mainStrings[7] = "Kime";
$mainStrings[8] = "Kimden";
$mainStrings[9] = "Tarih";
$mainStrings[10] = "Sil";
$mainStrings[11] = "Çöp Kutusunu Bosalt";
$mainStrings[12] = "Tasi";
$mainStrings[13] = "Ara";
$mainStrings[14] = "Boyut";
$mainStrings[15] = "konu yok";
$mainStrings[16] = "Göster";
$mainStrings[17] = "Yeni Mesajlari Kontrol Et";
$mainStrings[18] = "Hepsini Sil";
$mainStrings[19] = "Iptal";
$mainStrings[20] = "%b olarak isaretle";
$mainStrings[21] = "Okunan";
$mainStrings[22] = "Okunmayan";
$mainStrings[23] = "Seç...";


$mainErrors[0] = "Bu klasörde mesaj bulunamadi";
$mainErrors[1] = "Bu klasörde mesaj yok";
$mainErrors[2] = "Mesajlar Çöp kutusuna tasinamadi.";
$mainErrors[3] = "Mesajlar 'silindi' olarak isaretlenemedi.";
$mainErrors[4] = "Mesajlar tasinamadi.";
$mainErrors[5] = "Çöp Kutusu klasörü tanimlanmamis.";
$mainErrors[6] = "Çöp Kutusu bosaltilamadi";
$mainErrors[7] = "%f klasöründeki BÜTÜN mesajlari silmek istediginize emin misiniz?";
$mainErrors[8] = "Tasimak icin kolonlarin altindaki oklara tiklayiniz.<br>Bittiginde pencereyi kapatiniz.";



?>
