<?php
/********************************************************
	lang/tr/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
//include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "Her birim icin bir HTML kodu giriniz.";
$pcStrings["0.1"] = "Kullan ";
$pcStrings["0.2"] = "Renk Kod Tablosu";
$pcStrings["0.3"] = " dogru renk kodlarini bulmak icin";
$pcStrings["0.4"] = "Temanin ustune yazdigi ayarlar degistirilemez.";
$pcStrings["1.0"] = "Araç Çubugu";
$pcStrings["2.0"] = "Klasor Listesi";
$pcStrings["3.0"] = "Ana";
$pcStrings["3.1"] = "Heading Back: ";
$pcStrings["3.2"] = "Heading Text: ";
$pcStrings["3.3"] = "Koyu Arka Fon: ";
$pcStrings["3.4"] = "Açik yazi: ";
$pcStrings["4.0"] = "Çesitli";
$pcStrings["4.1"] = "Alintilar: ";
$pcStrings["5.0"] = "Fontlar";
$pcStrings["5.1"] = "Font Ailesi";
$pcStrings["5.2"] = "Font Boyutu: ";
$pcStrings["5.3"] = "Küçük Font Boyutu: ";
$pcStrings["5.4"] = "Menü Font Boyutu: ";
$pcStrings["5.5"] = "Klasör Listesi Font Boyutu: ";

							
$pcPortions = array( "Arka Fon: ", "Linkler: ", "Metin: ", "Öne Çikarma: ");

?>
