<?php
/********************************************************
	lang/tr/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "Kimlikler";
$piStrings["edit"] = "Düzenle";
$piStrings["name"] = "Ad";
$piStrings["email"] = "E-posta";
$piStrings["replyto"] = "Cevap Adresi";
$piStrings["sig"] = "Imza";
$piStrings["add"] = "Ekle";
$piStrings["new"] = "Yeni Kimlik";
$piStrings["edit_ident"] = "Kimligi Düzenle";
$piStrings["delete"] = "Sil";
$piStrings["setdef"] = "Varsayilan Olarak Ata";
$piStrings["isdef"] = "(Varsayilan)";

$piError[1] = "Isim veya e-psota gerekmektedir";

?>
