<?php
/********************************************************
	lang/tr/quota.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/quota.inc");

$quotaStr["label"] = "Disk Kullanimi: ";
$quotaStr["full"] = "%usedKB/%totalKB (%free% bos)";
$quotaStr["unknown"] = "bilinmiyor";

?>
