<?php
/********************************************************
	lang/tr/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/read_message.inc");


$rmStrings[0] = "Gelen Kutusu";
$rmStrings[1] = "Cevapla";
$rmStrings[2] = "Ilet";
$rmStrings[3] = "Silmeyi geri al";
$rmStrings[4] = "Sil";
$rmStrings[5] = "Tasi";
$rmStrings[6] = "Kisimlar";
$rmStrings[7] = "Bu bir HTML mesajidir. ";
$rmStrings[8] = "Okumak icin tiklayin .";
$rmStrings[9] = "Kaynak";
$rmStrings[10] = "Boyut";
$rmStrings[11] = "Okunmamis";
$rmStrings[12] = "Basliklari goster";
$rmStrings[13] = "Spam bildir";
$rmStrings[14] = "Hepsine cevap ver";
$rmStrings[15] = "Bu mesaji okudunuz";
$rmStrings[16] = "Yazdir";

?>
