<?php
/********************************************************
	lang/tr/search_errors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/search_errors.inc");

$searchErrors["field"] = "Geçersiz arama kriteri: Geçersiz alan";
$searchErrors["empty"] = "Geçersiz arama kriteri: Bos arama dizini";
$searchErrors["date"] = "Geçersiz arama kriteri: Belirtilmemis tarih";

?>
