<?php
/********************************************************
	lang/tr/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	Turkish Translation by Ufuk Yuzereroglu <ufuk@yuzereroglu.com>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/tool.inc");

$toolStrings["folders"] = "Klasörler";
$toolStrings["inbox"] = "Gelen Kutusu";
$toolStrings["compose"] = "Yeni";
$toolStrings["calendar"] = "Takvim";
$toolStrings["contacts"] = "Adres Defteri";
$toolStrings["bookmarks"] = "Linkler";
$toolStrings["search"] = "Arama";
$toolStrings["prefs"] = "Seçenekler";
$toolStrings["logout"] = "Sistemden Çik";
$toolStrings["go"] = "Git";

?>
