<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Adreces d'inter&egrave;s";
$bmStrings["identities"] = "Identitats";
$bmStrings["edit"] = "Editar";
$bmStrings["name"] = "Nom";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Categoria";
$bmStrings["other"] = "Especificar-&gt;";
$bmStrings["comments"] = "Comentaris";
$bmStrings["add"] = "Afegir";
$bmStrings["new"] = "Entrada nova";
$bmStrings["edit_url"] = "Editar entrada";
$bmStrings["delete"] = "Esborrar";

$bmError[1] = "Cal un nom o una URL";
$bmError[2] = "Aquesta caracter&iacute;stica est&agrave; inhabilitada.";

?>
