<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Afegir planificaci&oacute;";
$calStr["edit_schedule"] = "Editar planificaci&oacute;";
$calStr["weekof"] = "Setmana de: %d";
$calStr["title"] = "T&iacute;tol:";
$calStr["color"] = "Color:";
$calStr["colors"] = array("#990000"=>"Vermell"
                         ,"#FF0000"=>"Roig"
                         ,"#000099"=>"Blau"
                         ,"#0000FF"=>"Blau cel"
                         ,"#006600"=>"Verd fosc"
                         ,"#00FF00"=>"Verd"
                         ,"#9900FF"=>"Porpra"
                         ,"#00FFFF"=>"Cian"
                         ,"#FF6600"=>"Taronja"
                         ,"#FFFF00"=>"Groc"
                         ,"#FF00FF"=>"Magenta"
                         ,""=>"Sense color");
$calStr["starts"] = "Comen&ccedil;a a:";
$calStr["ends"] = "Acaba a:";
$calStr["from"] = "des de:";
$calStr["until"] = "fins a:";
$calStr["repeat_on"] = "Repetir";
$calStr["of"] = "de cada";
$calStr["weeks"] = array(1=>"primera setmana"
                        ,2=>"segona setmana"
                        ,3=>"tercera setmana"
                        ,4=>"quarta setmana");
$calStr["week_blurb"] = "...de cada mes (fins que acabi).<br>Es repetir&agrave; cada setmana si no se'n selecciona cap.";
$calStr["monthly"] = "Repetir mensualment";
$calStr["yearly"] = "Repetir anyalment";
$calStr["place"] = "Lloc:";
$calStr["description"] = "Descripci&oacute;:";
$calStr["add"] = "Afegir";
$calStr["update"] = "Actualitzar";
$calStr["Delete"] = "Esborrar";
$calStr["go"] = "Anar";
$calStr["disabled"] = "El calendari est&agrave; inhabilitat.";
?>
