<?php
/********************************************************
	lang/cat/compose.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/compose.inc");

$composeHStrings[0] = "Assumpte";
$composeHStrings[1] = "De";
$composeHStrings[2] = "A";
$composeHStrings[3] = "C&ograve;pia";
$composeHStrings[4] = "C&ograve;pia oculta";
$composeHStrings[5] = "Data";


$composeStrings[0] = "Redactar missatge";
$composeStrings[1] = "Enviar missatge";
$composeStrings[2] = "Carregar";
$composeStrings[3] = "Afegir signatura";
$composeStrings[4] = "Adjuntar";
$composeStrings[5] = "Contactes";
$composeStrings[6] = "Amagar contactes";
$composeStrings[7] = "Cos del missatge:";
$composeStrings[8] = "Afegir";
$composeStrings[9] = "A %d, %s va escriure:\n";
$composeStrings[10] = "--- Missatge original ---\n";
$composeStrings[11] = "Tancar finestra";

$composeStrings[12] = "Verificar ortografia";
$composeStrings[13] = "Corregir ortografia";
$composeStrings[14] = "Cap canvi";
$composeStrings[15] = "Possibles error d'ortografia";
$composeStrings[16] = "Canvis d'ortografia";
$composeStrings[17] = "ignorar";
$composeStrings[18] = "esborrar";

$composeStrings["title"] = "Redactar missatge";

$composeErrors[0] = "No hi ha assumpte. Escriviu-ne un o cliqueu un altre cop \"".$composeStrings[1]."\" per enviar-lo.";
$composeErrors[1] = "El camp \"De\" &eacute;s buit. Introdu&iuml;u-hi la vostra adre&ccedil;a.";
$composeErrors[2] = "El camp \"A\" &eacute;s buit. Especifiqueu-hi un destinatari.";
$composeErrors[3] = "C&agrave;rrega fallida";
$composeErrors[4] = "No s'han rebut fitxers.";
$composeErrors[5] = "Per prevenir el correu no desitjat, nom&eacute;s podeu enviar a %1 persones (%2 en total per sessi&oacute;) cada %3 segons.";

$composeErrors[6] = "No s'han trobat errors ortogr&agrave;fics.";
$composeErrors[7] = "La verificaci&oacute; ortogr&agrave;fica no est&agrave; disponible per l'idioma especificat.";
$composeErrors[8] = "(usat diccionari %s)";
?>
