<?php
/********************************************************
	lang/cat/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/contacts.inc");

$cStrings[0] = "Contactes";
$cStrings[1] = "Afegir contacte";
$cStrings[2] = " Contacte";
$cStrings[3] = "Nom";
$cStrings[4] = "Correu";
$cStrings[5] = "URL";
$cStrings[6] = "Grup";
$cStrings[7] = "Comentaris";
$cStrings[8] = "Afegir/editar contacte";
$cStrings[9] = "Correu";
$cStrings[10] = "Redactar";

$cStrings["close"] = "Tancar finestra";
$cStrings["addto"] = "Afegir contactes a %s";
$cStrings["showgrp"] = "Mostrar %s";
$cStrings["all"] = "Tot";
$cStrings["instructions"] = "Cliqueu als noms per afegir-los. Tamb&eacute; podeu clicara les etiquetes de grup per afegir-hi tothom del grup.";

$cErrors[0] = "La llista de contactes &eacute;s buida";

?>
