<?php
include("../lang/eng/cp.inc"); // <-- do not delete
/********************************************************
	lang/cat/cp.inc	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>
	This file is part of IlohaMail, and released under GPL.	See COPYING,
	or http://www.fsf.org/copyleft/gpl.html
        Translated: David Gimeno i Ayuso info@sima-pc.com
********************************************************/?>
<B>Diagrama de codis de color</B>
