<?php
/********************************************************
	lang/cat/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/
//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Editar";
$ecStrings[1] = "Afegir";
$ecStrings[2] = " Contacte";
$ecStrings[3] = "Nom";
$ecStrings[4] = "Correu";
$ecStrings[5] = "URL";
$ecStrings[6] = "Grup";
$ecStrings[7] = "Comentaris";
$ecStrings[8] = "Tel&egrave;fon de casa";
$ecStrings[9] = "Tel&egrave;fon de la feina";
$ecStrings[10] = "Tel&egrave;fon m&ograve;bil";
$ecStrings[11] = "Adre&ccedil;a";
$ecStrings[12] = "Correu alternatiu";
$ecStrings[13] = "Esborrar";
$ecStrings[14] = "Altres";


$errors[0] = "No s'ha pogut afegir el contacte: error a la base de dades.";
$errors[1] = "Ja existeix un contacte amb aquesta adre&ccedil;a.";
$errors[2] = "Cliqueu ";
$errors[3] = "aqu&iacute;";
$errors[4] = " per editar aquest registre.";
$errors[5] = "No s'ha trobat el contacte o s'ha denegat l'acc&eacute;s";
$errors[6] = "Esteu segur que voleu esborrar el registre \"";
$errors[7] = "\"?";

?>
