<?php
/********************************************************
	lang/cat/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/
//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_folders.inc");

$efStrings[0] = "Gestionar carpetes";
$efStrings[1] = "Crear carpeta nova";
$efStrings[2] = "Crear carpeta: ";
$efStrings[3] = "Crear";
$efStrings[4] = "Esborrar carpeta";
$efStrings[5] = "Esborrar";
$efStrings[6] = "Redenominar carpeta";
$efStrings[7] = "Redenominar";


$errors[0] = "Crear carpeta: ";
$errors[1] = "No s'ha pogut crear la carpeta: ";
$errors[2] = "Carpeta esborrada: ";
$errors[3] = "No s'ha pogut esborrar la carpeta: ";
$errors[4] = "Carpeta redenominada: ";
$errors[5] = "No s'ha pogut redenominar la carpeta: ";
$errors[6] = "El suport per a carpetes nom&eacute;s &eacute;s disponible per comptes IMAP.";

?>
