<?php 
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Identificador d'usuari";
$loginStrings[1]="Contrasenya";
$loginStrings[2]="Servidor";
$loginStrings[3]="Tipus";
$loginStrings[4]="Directori arrel";
$loginStrings[5]="Idioma";
$loginStrings[6]="Entrada";

$loginErrors[0]="Ordinador no autoritzat";
$loginErrors[1]="Error: no s'ha trobat el directori \"uploads\"";
$loginErrors[2]="Error: no s'ha trobat el directori \"users\"";
$loginErrors[3]="Error: no s'ha trobat el directori \"sessions\"";

?>
