<?php
/********************************************************
        lang/eng/main.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainMessages["delete"] = "Esborrats %n missatges";
$mainMessages["move"] = "Moguts %n missatges a %f";

$mainStrings[0] = "Mostrant %p de %n";
$mainStrings[1] = " missatges trobats";
$mainStrings[2] = "Anterior";
$mainStrings[3] = "";
$mainStrings[4] = "Seg&uuml;ent";
$mainStrings[5] = "";
$mainStrings[6] = "Tema";
$mainStrings[7] = "A";
$mainStrings[8] = "De";
$mainStrings[9] = "Data";
$mainStrings[10] = "Esborrar";
$mainStrings[11] = "Buidar paperera";
$mainStrings[12] = "Moure";
$mainStrings[13] = "Cercar";
$mainStrings[14] = "Tamany";
$mainStrings[15] = "sense t&iacute;tol";
$mainStrings[16] = "Mostrar";
$mainStrings[17] = "Comprovar nous";
$mainStrings[18] = "Delete All";
$mainStrings[19] = "Cancel&middot;lar";
$mainStrings[20] = "Marcar com %b";
$mainStrings[21] = "Llegir";
$mainStrings[22] = "Per llegir";
$mainStrings[23] = "Seleccionar...";


$mainErrors[0] = "No s'han trobat missatges a aquesta carpeta";
$mainErrors[1] = "No hi ha missatges a aquesta carpeta";
$mainErrors[2] = "No s'ha pogut enviar els missatges a la paperera";
$mainErrors[3] = "No s'ha pogut senyalar els missatges com a esborrats";
$mainErrors[4] = "No s'ha pogut moure els missatges.";
$mainErrors[5] = "No s'ha especificat la carpeta paperera.";
$mainErrors[6] = "No s'ha pogut buidar la paperera";
$mainErrors[7] = "Esteu segur que voleu esborrar TOTS els missatges a %f?";
$mainErrors[8] = "Cliqueu a les fletxes de sota dels encap&ccedil;alaments de les columnes per moure-les.<br>En acabat, tanqueu la finestra.";

?>
