<?php
/********************************************************
        lang/eng/cp.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "Introdu&iuml;u un codi de color HTML per a cada component.";
$pcStrings["0.1"] = "Usar el ";
$pcStrings["0.2"] = "Diagrama de codis de color";
$pcStrings["0.3"] = " per trobar els codis de color correctes.";
$pcStrings["0.4"] = "Par&agrave;metres que no poden ser modificats per la substituci&oacute; d'aspecte.";
$pcStrings["1.0"] = "Barra d'eines";
$pcStrings["2.0"] = "Llista de carpetes";
$pcStrings["3.0"] = "Principal";
$pcStrings["3.1"] = "Fons d'encap&ccedil;alament: ";
$pcStrings["3.2"] = "Text d'encap&ccedil;alament: ";
$pcStrings["3.3"] = "Fons fosc: ";
$pcStrings["3.4"] = "Text clar: ";
$pcStrings["4.0"] = "Miscel&middot;lani";
$pcStrings["4.1"] = "Cometes: ";
$pcStrings["5.0"] = "Lletres";
$pcStrings["5.1"] = "Familia de tipus";
$pcStrings["5.2"] = "Tamany de lletra: ";
$pcStrings["5.3"] = "Tamany de lletra petit: ";
$pcStrings["5.4"] = "Tamany de lletra men&uacute;s: ";
$pcStrings["5.5"] = "Tamany de lletra llista de carpetes: ";

$pcPortions = array( "Fons: ", "Enlla&ccedil;os: ", "Text: ", "Ressalt: ");

?>

