<?php
/********************************************************
        lang/eng/pref_identities.inc
        (C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "Identitats";
$piStrings["edit"] = "Editar";
$piStrings["name"] = "Nom";
$piStrings["email"] = "Correu";
$piStrings["replyto"] = "Respon a";
$piStrings["sig"] = "Signatura";
$piStrings["add"] = "Afegir";
$piStrings["new"] = "Identitat nova";
$piStrings["edit_ident"] = "Editar identitat";
$piStrings["delete"] = "Esborrar";
$piStrings["setdef"] = "Restituir valors predeterminats";
$piStrings["isdef"] = "(Predeterminat)";

$piError[1] = "Cal un nom o un correu";

?>

