<?php
/********************************************************
        lang/eng/quota.inc
        (C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/quota.inc");

$quotaStr["label"] = "&Uacute;s de disc: ";
$quotaStr["full"] = "%usedKB/%totalKB (%free% disponible)";
$quotaStr["unknown"] = "desconegut";

?>
