<?php
/********************************************************
        lang/eng/read_message.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/read_message.inc");

$rmStrings[0] = "&Iacute;ndex";
$rmStrings[1] = "Respondre";
$rmStrings[2] = "Endavant";
$rmStrings[3] = "Recuperar";
$rmStrings[4] = "Esborrar";
$rmStrings[5] = "Moure";
$rmStrings[6] = "Peces";
$rmStrings[7] = "Aix&ograve; &eacute;s un missatge HTML. ";
$rmStrings[8] = "Cliqueu aqu&iacute; per llegir-lo.";
$rmStrings[9] = "Or&iacute;gen";
$rmStrings[10] = "Tamany";
$rmStrings[11] = "Per llegir";
$rmStrings[12] = "Mostrar cap&ccedil;alera";
$rmStrings[13] = "Informar d'spam";
$rmStrings[14] = "Re. tothom";
$rmStrings[15] = "Heu respost aquest missatge";
$rmStrings[16] = "Imprimir";

?>
