<?php
/********************************************************
        lang/eng/search_errors.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/search_errors.inc");

$searchErrors["field"] = "Criteri erroni de cerca:  Camp erroni";
$searchErrors["empty"] = "Criteri erroni de cerca:  Cadena de cerca buida";
$searchErrors["date"] = "Criteri erroni de cerca:  No s'ha especificat data";

?>
