<?php
/********************************************************
        lang/eng/tool.inc
        (C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

        This file is part of IlohaMail, and released under GPL.
        See COPYING, or http://www.fsf.org/copyleft/gpl.html

        Translated: David Gimeno i Ayuso info@sima-pc.com

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/tool.inc");

$toolStrings["folders"] = "Carpetes";
$toolStrings["inbox"] = "Entrades";
$toolStrings["compose"] = "Redactar";
$toolStrings["calendar"] = "Calendari";
$toolStrings["contacts"] = "Contactes";
$toolStrings["bookmarks"] = "Adreces d'inter&egrave;s";
$toolStrings["search"] = "Cercar";
$toolStrings["prefs"] = "Opcions";
$toolStrings["logout"] = "Sortir";
$toolStrings["go"] = "Anar";

?>
