<?php
/********************************************************
	lang/eng/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Отметки";
$bmStrings["identities"] = "Самоличности";
$bmStrings["edit"] = "Редактирай";
$bmStrings["name"] = "Име";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Категория";
$bmStrings["other"] = "Определи-&gt;";
$bmStrings["comments"] = "Коментар";
$bmStrings["add"] = "Добави";
$bmStrings["new"] = "Нов запис";
$bmStrings["edit_url"] = "Редактирай записа";
$bmStrings["delete"] = "Изтрий";

$bmError[1] = "Изисква се име или URL";
$bmError[2] = "Тази възможност е изключена.";
?>
