<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Добави Разписание";
$calStr["edit_schedule"] = "Редактирай Разписание";
$calStr["weekof"] = "Седмица: %d";
$calStr["title"] = "Заглавие:";
$calStr["color"] = "Цвят:";
$calStr["colors"] = array("#990000"=>"Dark Red", "#FF0000"=>"Red", "#000099"=>"Deep Blue", "#0000FF"=>"Blue", 
					"#006600"=>"Dark Green", "#00FF00"=>"Green", "#9900FF"=>"Purple", "#00FFFF"=>"Cyan",
					"#FF6600"=>"Orange", "#FFFF00"=>"Yellow", "#FF00FF"=>"Magenta", ""=>"No color");
$calStr["starts"] = "Започва на:";
$calStr["ends"] = "Свършва на:";
$calStr["from"] = "от:";
$calStr["until"] = "докато:";
$calStr["repeat_on"] = "Повтаряй на";
$calStr["of"] = "на всеки";
$calStr["weeks"] = array(1=>"първа седмица", 2=>"втора седмица", 3=>"трета седмица", 4=>"четвърта седмица"); 
$calStr["week_blurb"] = "...of every month (until end date).<br>Ще се повтаря всички седмици, ако нищо не е избрано.";
$calStr["monthly"] = "Повтаряй месечно";
$calStr["yearly"] = "Повтаряй ежегодно";
$calStr["place"] = "Място:";
$calStr["description"] = "Описание:";
$calStr["add"] = "Добави";
$calStr["update"] = "Обнови";
$calStr["Delete"] = "Изтрий";
$calStr["go"] = "Давай";
$calStr["disabled"] = "Използването на календара е изключено.";
?>
