<?php
/********************************************************
	lang/eng/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/contacts.inc");

$cStrings[0] = "Контакти";
$cStrings[1] = "Добави контакт";
$cStrings[2] = " контакт";
$cStrings[3] = "Име";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Група";
$cStrings[7] = "Коментар";
$cStrings[8] = "Добави/Редактирай контакта";
$cStrings[9] = "Email";
$cStrings[10] = "Състави";

$cStrings["close"] = "Затвори прозореца";
$cStrings["addto"] = "Добави контактите до %s";
$cStrings["showgrp"] = "Покажи %s";
$cStrings["all"] = "Всички";
$cStrings["instructions"] = "Натиснете върху имената за да ги добавите.  Също можете да натиснете върху името на групата за да добавите всички от тази група.";

$cErrors[0] = "Списъка с контакти е празен";


?>
