<?php
/********************************************************
	lang/eng/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/edit_contact.inc");

$ecStrings[0] = "Редактирай";
$ecStrings[1] = "Добави";
$ecStrings[2] = " контакт";
$ecStrings[3] = "Име";
$ecStrings[4] = "Email";
$ecStrings[5] = "URL";
$ecStrings[6] = "Група";
$ecStrings[7] = "Коментар";
$ecStrings[8] = "Домашен телефон";
$ecStrings[9] = "Служебен телефон";
$ecStrings[10] = "Мобилен телефон";
$ecStrings[11] = "Адрес";
$ecStrings[12] = "Друг Email";
$ecStrings[13] = "Изтрий";
$ecStrings[14] = "Други";


$errors[0] = "Не мога да добавя контакта:  database error.";
$errors[1] = "Запис с този адрес вече съществува.";
$errors[2] = "Натисни ";
$errors[3] = "тук";
$errors[4] = " за да редактирате този запис.";
$errors[5] = "Контакта не е намерен или достъпа е отказан.";
$errors[6] = "Сигурни ли сте че искате да изтриете този запис \"";
$errors[7] = "\"?";

?>
