<?php 
/********************************************************
	lang/en/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Потребител";
$loginStrings[1]="Парола";
$loginStrings[2]="Сървър";
$loginStrings[3]="Тип";
$loginStrings[4]="Главна директория";
$loginStrings[5]="Език";
$loginStrings[6]="Влез";

$loginErrors[0]="Неоторизиран хост";
$loginErrors[1]="Грешка: \"uploads\" директорията не е намерена";
$loginErrors[2]="Грешка: \"users\" директорията не е намерена";
$loginErrors[3]="Грешка: \"sessions\" директорията не е намерена";

?>
