<?php
/********************************************************
	lang/eng/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/main.inc");

$mainMessages["delete"] = "Изтрий %n съобщение(я)";
$mainMessages["move"] = "Преместени са %n съобщения в %f";

$mainStrings[0] = "Показани са %p от %n";
$mainStrings[1] = " съобщения намерени";
$mainStrings[2] = "Предишни";
$mainStrings[3] = "";
$mainStrings[4] = "Следващи";
$mainStrings[5] = "";
$mainStrings[6] = "Тема";
$mainStrings[7] = "До";
$mainStrings[8] = "От";
$mainStrings[9] = "Дата";
$mainStrings[10] = "Изтрий";
$mainStrings[11] = "Изпразни кошчето";
$mainStrings[12] = "Премести";
$mainStrings[13] = "Търсене";
$mainStrings[14] = "Размер";
$mainStrings[15] = "неименовано";
$mainStrings[16] = "Покажи";
$mainStrings[17] = "Провери за нови";
$mainStrings[18] = "Изтрий всички";
$mainStrings[19] = "Откажи";
$mainStrings[20] = "Маркирай като %b";
$mainStrings[21] = "Прочетено";
$mainStrings[22] = "Непрочетено";
$mainStrings[23] = "Избери...";


$mainErrors[0] = "Не са намерени съобщения в тази папка";
$mainErrors[1] = "Няма съобщения в тази папка";
$mainErrors[2] = "Не мога да преместя съобщенията в кошчето.";
$mainErrors[3] = "Не мога да маркирам съобщението като изтрито.";
$mainErrors[4] = "Не мога да преместя съобщенията.";
$mainErrors[5] = "Папката Кошче не е посочена.";
$mainErrors[6] = "Не мога да изпразня кошчето";
$mainErrors[7] = "Сигурни ли сте че искате да изтриете ВСИЧКИ съобщения в %f?";
$mainErrors[8] = "Натиснете върху стрелките под заглавията на колоните за да ги преместите.<br>Когато сте готови, просто затворете прозореца.";



?>
