<?php
/********************************************************
	lang/eng/cp.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_colors.inc");

$pcStrings["0"] = "Въведете HTML код на цвета за всеки компонент.";
$pcStrings["0.1"] = "Използвай ";
$pcStrings["0.2"] = "Таблица с кодове на цветовете";
$pcStrings["0.3"] = " за да намерите точния код на цвят.";
$pcStrings["0.4"] = "Настройки които темата презаписва, не могат да бъдат променяни.";
$pcStrings["1.0"] = "Лента с Инструменти";
$pcStrings["2.0"] = "Списък на папките";
$pcStrings["3.0"] = "Основни";
$pcStrings["3.1"] = "Фон на заглавната част: ";
$pcStrings["3.2"] = "Текст на заглавната част: ";
$pcStrings["3.3"] = "Тъмен фон: ";
$pcStrings["3.4"] = "Светъл текст: ";
$pcStrings["4.0"] = "Разни";
$pcStrings["4.1"] = "Цитати: ";
$pcStrings["5.0"] = "Шрифтове";
$pcStrings["5.1"] = "Тип на шрифта";
$pcStrings["5.2"] = "Размер на шрифта: ";
$pcStrings["5.3"] = "Размер на малък шрифт: ";
$pcStrings["5.4"] = "Размер на шрифта за менюто: ";
$pcStrings["5.5"] = "Размер на шрифта за списъка с папки: ";

							
$pcPortions = array( "Background: ", "Links: ", "Text: ", "Hilight: ");

?>
