<?php
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/pref_identities.inc");

$piStrings["identities"] = "Самоличности";
$piStrings["edit"] = "Редактирай";
$piStrings["name"] = "Име";
$piStrings["email"] = "Email";
$piStrings["replyto"] = "Reply-To";
$piStrings["sig"] = "Подпис";
$piStrings["add"] = "Добави";
$piStrings["new"] = "Нова самоличност";
$piStrings["edit_ident"] = "Редактирай самоличността";
$piStrings["delete"] = "Изтрий";
$piStrings["setdef"] = "Настрой като подразбираща се";
$piStrings["isdef"] = "(Подразбираща се)";

$piError[1] = "Задължително е име или email";

?>
