<?php
/********************************************************
	lang/eng/read_message.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/read_message.inc");


$rmStrings[0] = "Индекс";
$rmStrings[1] = "Отговори";
$rmStrings[2] = "Препрати";
$rmStrings[3] = "Неизтрито";
$rmStrings[4] = "Изтрий";
$rmStrings[5] = "Премести";
$rmStrings[6] = "Части";
$rmStrings[7] = "Това е HTML съобщение. ";
$rmStrings[8] = "Натиснете тук за да го прочетете.";
$rmStrings[9] = "Изходен код";
$rmStrings[10] = "Размер";
$rmStrings[11] = "Непрочетено";
$rmStrings[12] = "Покажи заглавната част";
$rmStrings[13] = "Докладвай спам";
$rmStrings[14] = "Отговори на всички";
$rmStrings[15] = "Вие отговорихте на това съобщение";
$rmStrings[16] = "Отпечатай";

?>
