<?php
/********************************************************
	lang/eng/tool.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/tool.inc");

$toolStrings["folders"] = "Папки";
$toolStrings["inbox"] = "Входящи";
$toolStrings["compose"] = "Съставяне";
$toolStrings["calendar"] = "Календар";
$toolStrings["contacts"] = "Контакти";
$toolStrings["bookmarks"] = "Отметки";
$toolStrings["search"] = "Търсене";
$toolStrings["prefs"] = "Натройки";
$toolStrings["logout"] = "Изход";
$toolStrings["go"] = "Давай";

?>
