<?php
/********************************************************
	lang/<lang>/bookmarks.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/bookmarks.inc");

$bmStrings["bookmarks"] = "Marcadores";
$bmStrings["identities"] = "Identidades";
$bmStrings["edit"] = "Editar";
$bmStrings["name"] = "Nombre";
$bmStrings["url"] = "URL";
$bmStrings["category"] = "Categoría";
$bmStrings["other"] = "Indicar-&gt;";
$bmStrings["comments"] = "Comentarios";
$bmStrings["add"] = "Agregar";
$bmStrings["new"] = "Nueva Entrada";
$bmStrings["edit_url"] = "Editar Entrada";
$bmStrings["delete"] = "Borrar";

$bmError[1] = "Se requiere el Nombre o la URL";
$bmError[2] = "Esta opción ha sido deshabilitada.";
?>