<?php
/********************************************************
	lang/<lang>/calendar.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//TRANSLATORS:  Uncomment next line for all non-English languages!!
include("../lang/eng/calendar.inc");

$calStr["add_schedule"] = "Agregar Apunte";
$calStr["edit_schedule"] = "Editar Apunte";
$calStr["weekof"] = "Semana del: %d";
$calStr["title"] = "Título:";
$calStr["color"] = "Color:";
$calStr["colors"] = array("#990000"=>"Rojo Oscuro", "#FF0000"=>"Rojo", "#000099"=>"Azul Profundo", "#0000FF"=>"Azul", 
					"#006600"=>"Verde Oscuro", "#00FF00"=>"Verde", "#9900FF"=>"Rosado", "#00FFFF"=>"Cyan",
					"#FF6600"=>"Naranja", "#FFFF00"=>"Amarillo", "#FF00FF"=>"Magenta", ""=>"Sin color");
$calStr["starts"] = "Comienza a:";
$calStr["ends"] = "Finaliza a:";
$calStr["from"] = "desde:";
$calStr["until"] = "hasta:";
$calStr["repeat_on"] = "Repetir en";
$calStr["of"] = "de cada";
$calStr["weeks"] = array(1=>"primer semana", 2=>"segunda semana", 3=>"tercer semana", 4=>"cuarta semana"); 
$calStr["week_blurb"] = "...de cada mes (hasta la fecha de finalizacion).<br>Se repetirá todas las semanas si no indica nada.";
$calStr["monthly"] = "Repetir mensualmente";
$calStr["yearly"] = "Repetir anualmente";
$calStr["place"] = "Lugar:";
$calStr["description"] = "Descripción:";
$calStr["add"] = "Agregar";
$calStr["update"] = "Actualizar";
$calStr["Delete"] = "Borrar";
$calStr["go"] = "&nbsp;Ir&nbsp;";
$calStr["disabled"] = "El calendario está deshabilitado.";
?>
