<?php
include("../lang/eng/contacts.inc"); // <-- do not delete
/********************************************************
	lang/es/contacts.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$cStrings[0] = "Contactos";
$cStrings[1] = "Agregar Contacto";
$cStrings[2] = " Contacto";
$cStrings[3] = "Nombre";
$cStrings[4] = "Email";
$cStrings[5] = "URL";
$cStrings[6] = "Grupo";
$cStrings[7] = "Comentarios";
$cStrings[8] = "Agregar/Editar Contacto";
$cStrings[9] = "Correo";
$cStrings[10] = "Redactar";

$cStrings["close"] = "Cerrar ventana";
$cStrings["addto"] = "Agregar contaco a %s";
$cStrings["showgrp"] = "Ver %s";
$cStrings["all"] = "Todos";
$cStrings["instructions"] = "Click en los nombres para agregarlo.  También pude dar click en el nombres de un grupo para agregar a todos los del grupo.";

$cErrors[0] = "La lista de contactos está vacía";

?>
