<?php
include("../lang/eng/edit_contact.inc"); // <-- do not delete
/********************************************************
	lang/es/edit_contact.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$ecStrings[0] = "Editar";
$ecStrings[1] = "Agregar";
$ecStrings[2] = " Contacto";
$ecStrings[3] = "Nombre";
$ecStrings[4] = "Correo";
$ecStrings[5] = "URL";
$ecStrings[6] = "Grupo";
$ecStrings[7] = "Comentarios";
$ecStrings[8] = "Teléfono de casa";
$ecStrings[9] = "Teléfono del trabajo";
$ecStrings[10] = "Teléfono celular";
$ecStrings[11] = "Dirección";
$ecStrings[12] = "Correo alterno";
$ecStrings[13] = "Eliminar";
$ecStrings[14] = "Otro";


$errors[0] = "No se pudo agregar el contacto: error en la base de datos.";
$errors[1] = "Ya existe un contacto con esa dirección.";
$errors[2] = "Clic ";
$errors[3] = "aquí";
$errors[4] = " para editar ese registro.";
$errors[5] = "No se encontró al contacto, o se negó el acceso.";
$errors[6] = "¿Estás seguro de que quieres eliminar el registro de \"";
$errors[7] = "\"?";

?>
