<?php
include("../lang/eng/edit_folders.inc"); // <-- do not delete
/********************************************************
	lang/es/edit_folders.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$efStrings[0] = "Administrar Carpetas";
$efStrings[1] = "Crear nueva Carpeta";
$efStrings[2] = "Crear Carpeta: ";
$efStrings[3] = "Crear";
$efStrings[4] = "Eliminar Carpeta";
$efStrings[5] = "Eliminar";
$efStrings[6] = "Renombrar Carpeta";
$efStrings[7] = "Renombrar";
$efStrings[8] = "Carpetas Suscriptas";
$efStrings[9] = "Suscribir";
$efStrings[10] = "Carpetas no Suscriptas";
$efStrings[11] = "Desuscribir";


$errors[0] = "Crear Carpeta: ";
$errors[1] = "No se pudo crear la carpeta: ";
$errors[2] = "Carpeta Eliminada: ";
$errors[3] = "No se pudo eliminar la carpeta: ";
$errors[4] = "Carpeta renombrada: ";
$errors[5] = "No se pudo renombrar carpeta: ";
$errors[6] = "El soporte para carpetas sólo está disponible para cuentas IMAP.";

?>