<?php
/********************************************************
	lang/<lang>/login.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

//translators: leave following include
include("../lang/eng/login.inc");

$loginStrings[0]="Usuario";
$loginStrings[1]="Clave";
$loginStrings[2]="Servidor";
$loginStrings[3]="Tipo";
$loginStrings[4]="Dir Raiz";
$loginStrings[5]="Lenguaje";
$loginStrings[6]="Log In";

$loginErrors[0]="Host no autorizado";
$loginErrors[1]="Error: directorio \"uploads\" no encontrado";
$loginErrors[2]="Error: directorio \"users\" no encontrado";
$loginErrors[3]="Error: directorio \"sessions\" no encontrado";

?>