<?php
include("../lang/eng/main.inc"); // <-- do not delete
/********************************************************
	lang/es/main.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$mainMessages["delete"] = "Borrar %n mensaje(s)";
$mainMessages["move"] = "Mover %n mensaje(s) para %f";

$mainStrings[0] = "Se muestran %p de %n";
$mainStrings[1] = " mensajes encontrados";
$mainStrings[2] = "Previo";
$mainStrings[3] = " mensajes";
$mainStrings[4] = "Siguiente";
$mainStrings[5] = " mensajes";
$mainStrings[6] = "Asunto";
$mainStrings[7] = "Para";
$mainStrings[8] = "De";
$mainStrings[9] = "Fecha";
$mainStrings[10] = "Eliminar";
$mainStrings[11] = "Vaciar Basura";
$mainStrings[12] = "Archivo";
$mainStrings[13] = "Buscar";
$mainStrings[14] = "Tamaño";
$mainStrings[15] = "Sin Título";
$mainStrings[16] = "Mostrar";
$mainStrings[17] = "Verificar correos";
$mainStrings[18] = "Borrar todo";
$mainStrings[19] = "Cancelar";
$mainStrings[20] = "Marcar como %b";
$mainStrings[21] = "Leído";
$mainStrings[22] = "No Leído";
$mainStrings[23] = "Seleccionar...";


$mainErrors[0] = "No se encontraron mensajes en esta carpeta";
$mainErrors[1] = "No hay mensajes en esta carpeta";
$mainErrors[2] = "No se pudieron mover los mensajes a la basura.";
$mainErrors[3] = "No se pudieron marcar los mensajes como borrados.";
$mainErrors[4] = "No se pudieron mover los mensajes.";
$mainErrors[5] = "Carpeta de Basura no especificada.";
$mainErrors[6] = "No se pudo tirar la basura";
$mainErrors[7] = "¿Estás seguro de que deseas borrar TODOS los mensajes de %f?";
$mainErrors[8] = "Click en las flechas arriba de cada columna para moverla.<br>Cuando termine, simplemente cierre la ventana.";



?>