<?php
include("../lang/eng/pref_colors.inc"); // <-- do not delete
/********************************************************
	lang/es/pref_colors.inc
	(C)2001-2002 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$pcStrings["0"] = "Ingresar el código de color HTML para cada componente.";
$pcStrings["0.1"] = "En la ";
$pcStrings["0.2"] = "Gráfica de códigos de color";
$pcStrings["0.3"] = " puede revisar los códigos de colores.";
$pcStrings["0.4"] = "La configuración que está determinada por el tema utilizado no puede ser modificada.";
$pcStrings["1.0"] = "Barra de Herramientas";
$pcStrings["2.0"] = "Lista de Carpetas";
$pcStrings["3.0"] = "Principal";
$pcStrings["3.1"] = "Fondo Cabezal: ";
$pcStrings["3.2"] = "Texto Cabezal: ";
$pcStrings["3.3"] = "Fondo Oscuro: ";
$pcStrings["3.4"] = "Texto Claro: ";
$pcStrings["4.0"] = "Misceláneo";
$pcStrings["4.1"] = "Citas: ";
$pcStrings["5.0"] = "Tipografía";
$pcStrings["5.1"] = "Familia Tipográfica";
$pcStrings["5.2"] = "Tamaño Tipográfico: ";
$pcStrings["5.3"] = "Tamaño Tipográfico Pequeño: ";
$pcStrings["5.4"] = "Tamaño Tipográfico del Menú: ";
$pcStrings["5.5"] = "Tamaño Tipográfico de la Lista de Carpetas: ";


$pcPortions = array( "Fondo: ", "Enlaces: ", "Texto: ", "Destacado: ");

?>