<?php
include("../lang/eng/pref_identities.inc"); // <-- do not delete
/********************************************************
	lang/eng/pref_identities.inc
	(C)2003 Ryo Chijiiwa <Ryo@IlohaMail.org>

	This file is part of IlohaMail, and released under GPL.
	See COPYING, or http://www.fsf.org/copyleft/gpl.html

********************************************************/

$piStrings["identities"] = "Identidades";
$piStrings["edit"] = "Editar";
$piStrings["name"] = "Nombre";
$piStrings["email"] = "E-mail";
$piStrings["replyto"] = "Responder-A";
$piStrings["sig"] = "Firma";
$piStrings["add"] = "Agregar";
$piStrings["new"] = "Nueva Identidad";
$piStrings["edit_ident"] = "Editar Identidad";
$piStrings["delete"] = "Borrar";
$piStrings["setdef"] = "Usar como predeterminada";
$piStrings["isdef"] = "(Predeterminada)";

$piError[1] = "Se require el nombre o el e-mail";

?>
